return { 
--  "plotter",
  "dataset",
  "matrix",
  "random",
  "util",
  "cmdOpt",
--   "profiler",
  "math",
  "trainable",
  -- "function_interface",
  "ann_base",
  "loss_functions",
  "trainable",
  "sdae",
  "fnnlm",
  "gzio",
  "image",
  "image_io",
  "libpng",
-- --  "median_filter",
   "image_metrics",
   "binarization_filter",
   "image_cleaning",
   "interest_points",
--   --"libtiff",
 }
