/*
 * This file is part of APRIL-ANN toolkit (A
 * Pattern Recognizer In Lua with Artificial Neural Networks).
 *
 * Copyright 2014, Francisco Zamora-Martinez
 *
 * The APRIL-ANN toolkit is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this library; if not, write to the Free Software Foundation,
 * Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 */
#ifndef LUA_STRING_H
#define LUA_STRING_H

extern "C" {
#include "lauxlib.h"
#include "lualib.h"
#include "lua.h"
}
#include "stream_memory.h"

namespace AprilIO {
  
  /**
   * @brief A class which generates a Lua string on-the-fly using small
   * intermediate C strings.
   *
   * @note The string is generated by adding data to a @c luaL_Buffer.
   *
   * @note Never instantiate this in Lua, it needs a Lua stack in C to work and
   * it is not safe to reuse the same object between different C calls from Lua.
   */
  class OutputLuaStringStream : public StreamMemory {
    lua_State *L;            ///< @c lua_State where the string is allocated.
    const size_t block_size; ///< Default size of the written block.
    size_t total_size;       ///< Total size written until the moment.
    luaL_Buffer lua_buffer;  ///< A Lua string buffer allocated at @c L.
    char *out_buffer;        ///< A string buffer where data is written.
    bool closed;             ///< Closed indicator flag.

  public:
    /// Constructor from a @c lua_State and a @c block_size.
    OutputLuaStringStream(lua_State *L,
                          size_t block_size=StreamMemory::BLOCK_SIZE);
    /// Destructor
    virtual ~OutputLuaStringStream();
    
    WRITE_ONLY_STREAM(OutputLuaStringStream);
    WRITE_ONLY_STREAM_MEMORY(OutputLuaStringStream);

    virtual bool empty() const;
    virtual size_t size() const;
    virtual char &operator[](size_t pos);
    virtual void clear();
    virtual int push(lua_State *L);

    virtual bool isOpened() const;
    virtual void close();
    virtual off_t seek(int whence = SEEK_CUR, int offset = 0);
    virtual void flush();
    virtual int setvbuf(int mode, size_t size);
    virtual bool hasError() const;
    virtual const char *getErrorMsg() const;
    
  protected:
    virtual const char *nextInBuffer(size_t &buf_len);
    virtual char *nextOutBuffer(size_t &buf_len);
    virtual bool eofStream() const;

    void moveOutBuffer(size_t len);
  };

  /**
   * @brief A class which reads from a Lua string.
   *
   * @note A reference to the string is allocated at the registry in order to
   * avoid garbage collection.
   *
   * @note This class uses a hook in the binding to retrieve the Lua string
   * from the registry every time a C call is produced. This behavior is
   * implemented by the lua_toInputLuaStringStream() function.
   *
   * @note This class can modify the stack by adding a reference to the string
   * allocated at the registry.
   */
  class InputLuaStringStream : public StreamMemory {
    lua_State *L;       ///< The @c lua_State where the string is allocated.
    int ref;            ///< A Lua reference to the registry.
    const char *data;   ///< The string pointer in C.
    size_t total_size,  ///< Length of the string.
      data_pos;         ///< Current position for read.
    
  public:
    /// Constructor from @c lua_State and the stack @c pos of the string.
    InputLuaStringStream(lua_State *L, int pos);
    /// Destructor
    virtual ~InputLuaStringStream();
    
    READ_ONLY_STREAM(InputLuaStringStream);
    READ_ONLY_STREAM_MEMORY(InputLuaStringStream);
    virtual bool empty() const;
    virtual size_t size() const;
    virtual char operator[](size_t pos) const;
    virtual int push(lua_State *L);
    
    virtual bool isOpened() const;
    virtual void close();
    virtual off_t seek(int whence = SEEK_CUR, int offset = 0);
    virtual int setvbuf(int mode, size_t size);
    virtual bool hasError() const;
    virtual const char *getErrorMsg() const;
    
    void retrieveStringFromRegistry(lua_State *L);
    
  protected:
    virtual const char *nextInBuffer(size_t &buf_len);
    virtual char *nextOutBuffer(size_t &buf_len);
    virtual bool eofStream() const;
  };

} // namespace AprilIO

#endif // LUA_STRING_H
