april-ann
DataSet< T > Class Template Reference
Dataset
A pure abstract templatized class that serves as interface.
Public Member Functions
virtual ~DataSet ()
virtual int numPatterns ()=0
Number of patterns in the set.
virtual int patternSize ()=0
Size of each pattern.
virtual int getPattern (int index, T *pat)=0
virtual int putPattern (int index, T *pat)=0
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Detailed Description
template<typename T>
class DataSet< T >
A pure abstract templatized class that serves as interface.
A DataSet is a class interface which define the concept of set of pattern vectors. The template argument is the type of the data stored. Methods for get the size of the set, or size of each pattern vector, are defined. Also methods to put a new pattern or to get a pattern. Patterns are indexed from 0 to N-1, being N the numPatterns of the DataSet.
Constructor & Destructor Documentation
template<typename T> virtual DataSet< T >::~DataSet () inline virtual
Member Function Documentation
template<typename T> virtual int DataSet< T >::getPattern (int index, T * pat) pure virtual
Get the pattern index to the vector pat. The function call returns the patternSize().
Implemented in DerivDataSet< T >, CacheDataSet< T >, SaltNoiseDataSet< T >, PerturbationDataSet< T >, IndexFilterDataSet< T >, ShortListDataSet< T >, SparseDataset< T >, BitDataSet< T >, ByteDataSet< T >, AccumulateDataSet< T >, ContextualizerDataSet< T >, LinearCombDataSet< T >, IndexDataSet< T >, JoinDataSet< T >, SplitDataSet< T >, SubDataSet< T >, IdentityDataSet< T >, UnionDataSet< T >, and MatrixDataSet< T >.
Referenced by Fmeasure(), Functions::DataSetFloatProducer::get(), Trainable::TrainableSupervised::trainDataset(), Trainable::TrainableSupervised::trainDatasetWithDistribution(), Trainable::TrainableSupervised::trainDatasetWithReplacement(), Trainable::TrainableSupervised::validateDataset(), and Trainable::TrainableSupervised::validateDatasetWithReplacement().
template<typename T> virtual int DataSet< T >::numPatterns () pure virtual
Number of patterns in the set.
Implemented in DerivDataSet< T >, CacheDataSet< T >, SaltNoiseDataSet< T >, PerturbationDataSet< T >, IndexFilterDataSet< T >, ShortListDataSet< T >, SparseDataset< T >, BitDataSet< T >, ByteDataSet< T >, AccumulateDataSet< T >, ContextualizerDataSet< T >, LinearCombDataSet< T >, IndexDataSet< T >, JoinDataSet< T >, SplitDataSet< T >, SubDataSet< T >, IdentityDataSet< T >, UnionDataSet< T >, and MatrixDataSet< T >.
Referenced by ContextualizerDataSet< T >::ContextualizerDataSet(), DerivDataSet< T >::DerivDataSet(), Fmeasure(), Functions::DataSetFloatProducer::get(), JoinDataSet< T >::JoinDataSet(), Functions::DataSetFloatConsumer::put(), Trainable::TrainableSupervised::trainDataset(), Trainable::TrainableSupervised::trainDatasetWithDistribution(), Trainable::TrainableSupervised::trainDatasetWithReplacement(), UnionDataSet< T >::UnionDataSet(), Trainable::TrainableSupervised::validateDataset(), and Trainable::TrainableSupervised::validateDatasetWithReplacement().
template<typename T> virtual int DataSet< T >::patternSize () pure virtual
Size of each pattern.
Implemented in DerivDataSet< T >, CacheDataSet< T >, SaltNoiseDataSet< T >, PerturbationDataSet< T >, IndexFilterDataSet< T >, ShortListDataSet< T >, SparseDataset< T >, BitDataSet< T >, ByteDataSet< T >, AccumulateDataSet< T >, ContextualizerDataSet< T >, LinearCombDataSet< T >, IndexDataSet< T >, JoinDataSet< T >, SplitDataSet< T >, SubDataSet< T >, IdentityDataSet< T >, UnionDataSet< T >, and MatrixDataSet< T >.
Referenced by CacheDataSet< T >::CacheDataSet(), ContextualizerDataSet< T >::ContextualizerDataSet(), DerivDataSet< T >::DerivDataSet(), Trainable::TrainableSupervised::exitOnDatasetSizeError(), Fmeasure(), Functions::DataSetFloatProducer::get(), JoinDataSet< T >::JoinDataSet(), LinearCombDataSet< T >::LinearCombDataSet(), SaltNoiseDataSet< T >::SaltNoiseDataSet(), ShortListDataSet< T >::ShortListDataSet(), SplitDataSet< T >::SplitDataSet(), and UnionDataSet< T >::UnionDataSet().
template<typename T> virtual int DataSet< T >::putPattern (int index, T * pat) pure virtual
Put the given vector pat at pattern index. The function returns the patternSize().
Implemented in DerivDataSet< T >, CacheDataSet< T >, SaltNoiseDataSet< T >, PerturbationDataSet< T >, IndexFilterDataSet< T >, ShortListDataSet< T >, SparseDataset< T >, BitDataSet< T >, ByteDataSet< T >, AccumulateDataSet< T >, ContextualizerDataSet< T >, LinearCombDataSet< T >, IndexDataSet< T >, JoinDataSet< T >, SplitDataSet< T >, SubDataSet< T >, IdentityDataSet< T >, UnionDataSet< T >, and MatrixDataSet< T >.
Referenced by Functions::DataSetFloatConsumer::put().