april-ann
Trainable::TrainableSupervised Class Reference
Public Member Functions
virtual ~TrainableSupervised ()
virtual void setOption (const char *name, double value)=0
virtual bool hasOption (const char *name)=0
virtual double getOption (const char *name)=0
virtual void loadModel (const char *filename)=0
virtual void saveModel (const char *filename)=0
Functions::NS_function_io::type getInputType () const
It returns the data type of the input (or domain).
Functions::NS_function_io::type getOutputType () const
It returns the data type of the output (or range).
virtual float trainOnePattern (float *input, float *target_output)
virtual float validateOnePattern (float *input, float *target_output)
virtual float trainDataset (DataSetFloat *input_dataset, DataSetFloat *target_output_dataset, MTRand *shuffle=0)
virtual float trainDatasetWithReplacement (DataSetFloat *input_dataset, DataSetFloat *target_output_dataset, MTRand *shuffle, int replacement)
virtual float trainDatasetWithDistribution (int num_classes, DataSetFloat **input_datasets, DataSetFloat **target_output_datasets, double *aprioris, MTRand *shuffle, int replacement)
virtual float validateDataset (DataSetFloat *input_dataset, DataSetFloat *target_output_dataset)
virtual float validateDatasetWithReplacement (DataSetFloat *input_dataset, DataSetFloat *target_output_dataset, MTRand *shuffle, int replacement)
virtual void useDataset (DataSetFloat *input_dataset, DataSetFloat *output_dataset)
Public Member Functions inherited from Functions::FunctionInterface< I, O >
virtual ~FunctionInterface ()
virtual bool calculate (const I *input_vector, unsigned int input_size, O *output_vector, unsigned int output_size)=0
A new abstract method that computes output vector given input vector.
virtual void calculateInPipeline (DataProducer< I > *producer, unsigned int input_size, DataConsumer< O > *consumer, unsigned int output_size)
Method for flow computation of outputs in a pipeline system.
Public Member Functions inherited from Functions::FunctionBase
FunctionBase ()
virtual ~FunctionBase ()
virtual unsigned int getInputSize () const =0
It returns the input (or domain) size of the function.
virtual unsigned int getOutputSize () const =0
It returns the output (or range) size of the function.
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Protected Member Functions
virtual void beginTrainingBatch ()=0
Entre begin y end va el conjunto de patrones de una epoca.
virtual void trainPattern (float *input, float *target_output)=0
virtual float endTrainingBatch ()=0
virtual void beginValidateBatch ()=0
virtual void validatePattern (float *input, float *target_output)=0
virtual float endValidateBatch ()=0
Private Member Functions
void exitOnDatasetSizeError (DataSetFloat *input_dataset, DataSetFloat *output_dataset)
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Constructor & Destructor Documentation
virtual Trainable::TrainableSupervised::~TrainableSupervised () inline virtual
Member Function Documentation
virtual void Trainable::TrainableSupervised::beginTrainingBatch () protected pure virtual
Entre begin y end va el conjunto de patrones de una epoca.
Implemented in ANN::MLP.
Referenced by trainDataset(), trainDatasetWithDistribution(), trainDatasetWithReplacement(), and trainOnePattern().
virtual void Trainable::TrainableSupervised::beginValidateBatch () protected pure virtual
Implemented in ANN::MLP.
Referenced by validateDataset(), validateDatasetWithReplacement(), and validateOnePattern().
virtual float Trainable::TrainableSupervised::endTrainingBatch () protected pure virtual
Implemented in ANN::MLP.
Referenced by trainDataset(), trainDatasetWithDistribution(), trainDatasetWithReplacement(), and trainOnePattern().
virtual float Trainable::TrainableSupervised::endValidateBatch () protected pure virtual
Implemented in ANN::MLP.
Referenced by validateDataset(), validateDatasetWithReplacement(), and validateOnePattern().
void Trainable::TrainableSupervised::exitOnDatasetSizeError (DataSetFloat * input_dataset, DataSetFloat * output_dataset) private
References ERROR_EXIT2, Functions::FunctionBase::getInputSize(), Functions::FunctionBase::getOutputSize(), and DataSet< T >::patternSize().
Referenced by trainDataset(), trainDatasetWithDistribution(), trainDatasetWithReplacement(), useDataset(), validateDataset(), and validateDatasetWithReplacement().
Functions::NS_function_io::type Trainable::TrainableSupervised::getInputType () const inline virtual
It returns the data type of the input (or domain).
Implements Functions::FunctionBase.
References Functions::NS_function_io::FLOAT.
virtual double Trainable::TrainableSupervised::getOption (const char * name) pure virtual
Implemented in ANN::MLP.
Functions::NS_function_io::type Trainable::TrainableSupervised::getOutputType () const inline virtual
It returns the data type of the output (or range).
Implements Functions::FunctionBase.
References Functions::NS_function_io::FLOAT.
virtual bool Trainable::TrainableSupervised::hasOption (const char * name) pure virtual
Implemented in ANN::MLP.
virtual void Trainable::TrainableSupervised::loadModel (const char * filename) pure virtual
Implemented in ANN::MLP, and ANN::AllAllMLP.
virtual void Trainable::TrainableSupervised::saveModel (const char * filename) pure virtual
Implemented in ANN::MLP, and ANN::AllAllMLP.
virtual void Trainable::TrainableSupervised::setOption (const char * name, double value) pure virtual
Implemented in ANN::MLP.
float Trainable::TrainableSupervised::trainDataset (DataSetFloat * input_dataset, DataSetFloat * target_output_dataset, MTRand * shuffle = 0) virtual
Entrena con un dataset de entrada y otro de salida, admite ademas el parametro shuffle, que en caso de existir implica que el entrenamiento es aleatorio
References beginTrainingBatch(), endTrainingBatch(), exitOnDatasetSizeError(), Functions::FunctionBase::getInputSize(), Functions::FunctionBase::getOutputSize(), DataSet< T >::getPattern(), DataSet< T >::numPatterns(), MTRand::shuffle(), and trainPattern().
float Trainable::TrainableSupervised::trainDatasetWithDistribution (int num_classes, DataSetFloat ** input_datasets, DataSetFloat ** target_output_datasets, double * aprioris, MTRand * shuffle, int replacement) virtual
References beginTrainingBatch(), endTrainingBatch(), exitOnDatasetSizeError(), Functions::FunctionBase::getInputSize(), Functions::FunctionBase::getOutputSize(), DataSet< T >::getPattern(), DataSet< T >::numPatterns(), MTRand::randInt(), dice::thrown(), and trainPattern().
float Trainable::TrainableSupervised::trainDatasetWithReplacement (DataSetFloat * input_dataset, DataSetFloat * target_output_dataset, MTRand * shuffle, int replacement) virtual
References beginTrainingBatch(), endTrainingBatch(), exitOnDatasetSizeError(), Functions::FunctionBase::getInputSize(), Functions::FunctionBase::getOutputSize(), DataSet< T >::getPattern(), DataSet< T >::numPatterns(), MTRand::randInt(), and trainPattern().
float Trainable::TrainableSupervised::trainOnePattern (float * input, float * target_output) virtual
References beginTrainingBatch(), endTrainingBatch(), and trainPattern().
virtual void Trainable::TrainableSupervised::trainPattern (float * input, float * target_output) protected pure virtual
Implemented in ANN::MLP.
Referenced by trainDataset(), trainDatasetWithDistribution(), trainDatasetWithReplacement(), and trainOnePattern().
void Trainable::TrainableSupervised::useDataset (DataSetFloat * input_dataset, DataSetFloat * output_dataset) virtual
References Functions::FunctionInterface< I, O >::calculateInPipeline(), exitOnDatasetSizeError(), Functions::FunctionBase::getInputSize(), and Functions::FunctionBase::getOutputSize().
float Trainable::TrainableSupervised::validateDataset (DataSetFloat * input_dataset, DataSetFloat * target_output_dataset) virtual
References beginValidateBatch(), endValidateBatch(), exitOnDatasetSizeError(), Functions::FunctionBase::getInputSize(), Functions::FunctionBase::getOutputSize(), DataSet< T >::getPattern(), DataSet< T >::numPatterns(), and validatePattern().
float Trainable::TrainableSupervised::validateDatasetWithReplacement (DataSetFloat * input_dataset, DataSetFloat * target_output_dataset, MTRand * shuffle, int replacement) virtual
References beginValidateBatch(), endValidateBatch(), exitOnDatasetSizeError(), Functions::FunctionBase::getInputSize(), Functions::FunctionBase::getOutputSize(), DataSet< T >::getPattern(), DataSet< T >::numPatterns(), MTRand::randInt(), and validatePattern().
float Trainable::TrainableSupervised::validateOnePattern (float * input, float * target_output) virtual
References beginValidateBatch(), endValidateBatch(), and validatePattern().
virtual void Trainable::TrainableSupervised::validatePattern (float * input, float * target_output) protected pure virtual
Implemented in ANN::MLP.
Referenced by validateDataset(), validateDatasetWithReplacement(), and validateOnePattern().