april-ann
Functions::DataSetFloatProducer Class Reference
A specialization of FloatDataProducer which gets data from a dataset.
Public Member Functions
DataSetFloatProducer (DataSetFloat *ds)
~DataSetFloatProducer ()
float * get ()
Returns a pointer and its property. A 0 inidicates data sequence ending.
void reset ()
Reinitialize the sequence iterator if it is possible.
void destroy ()
It destroys the object content and forces to return a 0 on next get().
Private Attributes
DataSetFloat * ds
The internal DataSetFloat source.
unsigned int ipat
An auxiliar counter which indicates the number of vectros produced.
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Detailed Description
A specialization of FloatDataProducer which gets data from a dataset.
A specialization of FloatDataProducer class which works as a source of data vectors. Data vectros are stored at the internal DataSetFloat attribute.
Constructor & Destructor Documentation
Functions::DataSetFloatProducer::DataSetFloatProducer (DataSetFloat * ds)
References IncRef, and ipat.
Functions::DataSetFloatProducer::~DataSetFloatProducer ()
References DecRef, and ds.
Member Function Documentation
void Functions::DataSetFloatProducer::destroy () virtual
It destroys the object content and forces to return a 0 on next get().
Reimplemented from Functions::DataProducer< float >.
References ipat.
float * Functions::DataSetFloatProducer::get () virtual
Returns a pointer and its property. A 0 inidicates data sequence ending.
Implements Functions::DataProducer< float >.
References ds, DataSet< T >::getPattern(), ipat, DataSet< T >::numPatterns(), and DataSet< T >::patternSize().
void Functions::DataSetFloatProducer::reset () virtual
Reinitialize the sequence iterator if it is possible.
Implements Functions::DataProducer< float >.
References ipat.
Member Data Documentation
DataSetFloat* Functions::DataSetFloatProducer::ds private
The internal DataSetFloat source.
Referenced by get(), and ~DataSetFloatProducer().
unsigned int Functions::DataSetFloatProducer::ipat private
An auxiliar counter which indicates the number of vectros produced.
Referenced by DataSetFloatProducer(), destroy(), get(), and reset().