april-ann
DataSetFloat2TokenWrapper Class Reference
Dataset
Public Member Functions
DataSetFloat2TokenWrapper (DataSetFloat *ds)
virtual ~DataSetFloat2TokenWrapper ()
int numPatterns ()
Number of patterns in the set.
int patternSize ()
Size of each pattern.
Token * getPattern (int index)
Get the pattern index to the vector pat.
Token * getPatternBunch (const int *indexes, unsigned int bunch_size)
Get the pattern index to the vector pat.
void putPattern (int index, Token *pat)
Put the given vector pat at pattern index.
void putPatternBunch (const int *indexes, unsigned int bunch_size, Token *pat)
Put the pattern bunch.
Public Member Functions inherited from DataSetToken
virtual ~DataSetToken ()
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Attributes
MatrixFloat * aux_mat
DataSetFloat * ds
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Constructor & Destructor Documentation
DataSetFloat2TokenWrapper::DataSetFloat2TokenWrapper (DataSetFloat * ds) inline
References aux_mat, IncRef, and DataSet< T >::patternSize().
virtual DataSetFloat2TokenWrapper::~DataSetFloat2TokenWrapper () inline virtual
References aux_mat, DecRef, and ds.
Member Function Documentation
Token* DataSetFloat2TokenWrapper::getPattern (int index) inline virtual
Get the pattern index to the vector pat.
Implements DataSetToken.
References ds, DataSet< T >::getPattern(), GPUMirroredMemoryBlock< T >::getPPALForWrite(), Matrix< T >::getRawDataAccess(), and patternSize().
Token* DataSetFloat2TokenWrapper::getPatternBunch (const int * indexes, unsigned int bunch_size) inline virtual
Get the pattern index to the vector pat.
Reimplemented from DataSetToken.
References aux_mat, Matrix< T >::copy(), ds, DataSet< T >::getPattern(), GPUMirroredMemoryBlock< T >::getPPALForWrite(), Matrix< T >::getRawDataAccess(), numPatterns(), and patternSize().
int DataSetFloat2TokenWrapper::numPatterns () inline virtual
Number of patterns in the set.
Implements DataSetToken.
References ds, and DataSet< T >::numPatterns().
Referenced by getPatternBunch().
int DataSetFloat2TokenWrapper::patternSize () inline virtual
Size of each pattern.
Implements DataSetToken.
References ds, and DataSet< T >::patternSize().
Referenced by getPattern(), getPatternBunch(), and putPatternBunch().
void DataSetFloat2TokenWrapper::putPattern (int index, Token * pat) inline virtual
Put the given vector pat at pattern index.
Implements DataSetToken.
References Token::convertTo(), ds, ERROR_EXIT, TokenMatrix< T >::getMatrix(), GPUMirroredMemoryBlock< T >::getPPALForRead(), Token::getTokenCode(), DataSet< T >::putPattern(), and table_of_token_codes::token_matrix.
void DataSetFloat2TokenWrapper::putPatternBunch (const int * indexes, unsigned int bunch_size, Token * pat) inline virtual
Put the pattern bunch.
Implements DataSetToken.
References aux_mat, Token::convertTo(), Matrix< T >::copy(), ds, ERROR_EXIT, TokenMatrix< T >::getMatrix(), GPUMirroredMemoryBlock< T >::getPPALForWrite(), Matrix< T >::getRawDataAccess(), Token::getTokenCode(), patternSize(), DataSet< T >::putPattern(), and table_of_token_codes::token_matrix.
Member Data Documentation
MatrixFloat* DataSetFloat2TokenWrapper::aux_mat private
Referenced by DataSetFloat2TokenWrapper(), getPatternBunch(), putPatternBunch(), and ~DataSetFloat2TokenWrapper().
DataSetFloat* DataSetFloat2TokenWrapper::ds private
Referenced by getPattern(), getPatternBunch(), numPatterns(), patternSize(), putPattern(), putPatternBunch(), and ~DataSetFloat2TokenWrapper().