april-ann
ANN::StackANNComponent Class Reference
Public Member Functions
StackANNComponent (const char *name=0)
virtual ~StackANNComponent ()
void pushComponent (ANNComponent *component)
ANNComponent * topComponent ()
void popComponent ()
virtual Token * getInput ()
virtual Token * getOutput ()
virtual Token * getErrorInput ()
virtual Token * getErrorOutput ()
virtual Token * doForward (Token *input, bool during_training)
virtual Token * doBackprop (Token *input_error)
virtual void doUpdate ()
virtual void reset ()
virtual ANNComponent * clone ()
virtual void setUseCuda (bool v)
virtual void setOption (const char *name, double value)
Virtual method for setting the value of a training parameter.
virtual bool hasOption (const char *name)
virtual double getOption (const char *name)
virtual void build (unsigned int input_size, unsigned int output_size, hash< string, Connections * > &weights_dict, hash< string, ANNComponent * > &components_dict)
virtual void copyWeights (hash< string, Connections * > &weights_dict)
Abstract method to retrieve Connections objects from ANNComponents.
virtual void copyComponents (hash< string, ANNComponent * > &components_dict)
virtual ANNComponent * getComponent (string &name)
virtual void resetConnections ()
virtual void computeAllGradients (hash< string, MatrixFloat * > &weight_grads_dict)
virtual void debugInfo ()
virtual char * toLuaString ()
unsigned int size ()
Public Member Functions inherited from ANN::ANNComponent
ANNComponent (const char *name=0, const char *weights_name=0, unsigned int input_size=0, unsigned int output_size=0)
virtual ~ANNComponent ()
const string & getName () const
const string & getWeightsName () const
bool hasWeightsName () const
bool getIsBuilt () const
void generateDefaultWeightsName (string &dest, const char *prefix=0)
unsigned int getInputSize () const
unsigned int getOutputSize () const
bool getUseCuda () const
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Attributes
april_utils::vector
< ANNComponent * > components
Additional Inherited Members
Protected Member Functions inherited from ANN::ANNComponent
virtual void computeGradients (MatrixFloat *&weight_grads)
Protected Attributes inherited from ANN::ANNComponent
string name
string weights_name
unsigned int input_size
unsigned int output_size
bool use_cuda
Static Protected Attributes inherited from ANN::ANNComponent
static unsigned int next_name_id = 1
static unsigned int next_weights_id = 1
Constructor & Destructor Documentation
ANN::StackANNComponent::StackANNComponent (const char * name = 0)
Referenced by clone().
ANN::StackANNComponent::~StackANNComponent () virtual
References components, and DecRef.
Member Function Documentation
void ANN::StackANNComponent::build (unsigned int _input_size, unsigned int _output_size, hash< string, Connections * > & weights_dict, hash< string, ANNComponent * > & components_dict) virtual
Abstract method to finish building of component hierarchy and set weights objects pointers. All childs which rewrite this method must call parent method before do anything.
Reimplemented from ANN::ANNComponent.
References ANN::ANNComponent::build(), april_utils::string::c_str(), components, ERROR_EXIT1, ERROR_EXIT3, ANN::ANNComponent::getInputSize(), ANN::ANNComponent::input_size, ANN::ANNComponent::name, and ANN::ANNComponent::output_size.
ANNComponent * ANN::StackANNComponent::clone () virtual
Reimplemented from ANN::ANNComponent.
References april_utils::string::c_str(), components, ANN::ANNComponent::input_size, ANN::ANNComponent::name, ANN::ANNComponent::output_size, pushComponent(), and StackANNComponent().
void ANN::StackANNComponent::computeAllGradients (hash< string, MatrixFloat * > & weight_grads_dict) virtual
Method which receives a hash table with matrices where compute the gradients.
Reimplemented from ANN::ANNComponent.
References components.
void ANN::StackANNComponent::copyComponents (hash< string, ANNComponent * > & components_dict) virtual
Abstract method to retrieve ANNComponents objects. All childs which rewrite this method must call parent method before do anything.
Reimplemented from ANN::ANNComponent.
References components, and ANN::ANNComponent::copyComponents().
void ANN::StackANNComponent::copyWeights (hash< string, Connections * > & weights_dict) virtual
Abstract method to retrieve Connections objects from ANNComponents.
Reimplemented from ANN::ANNComponent.
References components.
virtual void ANN::StackANNComponent::debugInfo () inline virtual
Reimplemented from ANN::ANNComponent.
References components, and ANN::ANNComponent::debugInfo().
Token * ANN::StackANNComponent::doBackprop (Token * input_error) virtual
Virtual method that back-propagates error derivatives and computes other useful stuff. Receives input error gradients, and returns its output error gradients Token.
Reimplemented from ANN::ANNComponent.
References components.
Token * ANN::StackANNComponent::doForward (Token * input, bool during_training) virtual
Virtual method that executes the set of operations required for each block of connections when performing the forward step of the Backpropagation algorithm, and returns its output Token
Reimplemented from ANN::ANNComponent.
References components.
void ANN::StackANNComponent::doUpdate () virtual
Virtual method that update weights given gradients and input/output data
Reimplemented from ANN::ANNComponent.
References components.
ANNComponent * ANN::StackANNComponent::getComponent (string & name) virtual
Virtual method which returns the component with the given name if exists, otherwise it returns 0. By default, base components only contains itself. Component composition will need to look to itself and all contained components. All childs which rewrite this method must call parent method before do anything.
Reimplemented from ANN::ANNComponent.
References components, and ANN::ANNComponent::getComponent().
Token * ANN::StackANNComponent::getErrorInput () virtual
Reimplemented from ANN::ANNComponent.
References components.
Token * ANN::StackANNComponent::getErrorOutput () virtual
Reimplemented from ANN::ANNComponent.
References components.
Token * ANN::StackANNComponent::getInput () virtual
Reimplemented from ANN::ANNComponent.
References components.
double ANN::StackANNComponent::getOption (const char * name) virtual
Virtual method for getting the value of a training parameter. All childs which rewrite this method must call parent method after their process, if the looked option is not found to show the error message.
Reimplemented from ANN::ANNComponent.
References components, ANN::ANNComponent::getOption(), and hasOption().
Token * ANN::StackANNComponent::getOutput () virtual
Reimplemented from ANN::ANNComponent.
References components.
bool ANN::StackANNComponent::hasOption (const char * name) virtual
Virtual method for determining if a training parameter is being used or can be used within the network.
Reimplemented from ANN::ANNComponent.
References components.
Referenced by getOption().
void ANN::StackANNComponent::popComponent ()
References components, DecRef, and ANN::ANNComponent::output_size.
void ANN::StackANNComponent::pushComponent (ANNComponent * component)
References components, and IncRef.
Referenced by clone().
void ANN::StackANNComponent::reset () virtual
Virtual method to reset to zero gradients and outputs (inputs are not reseted)
Reimplemented from ANN::ANNComponent.
References components.
virtual void ANN::StackANNComponent::resetConnections () inline virtual
Reimplemented from ANN::ANNComponent.
References components.
void ANN::StackANNComponent::setOption (const char * name, double value) virtual
Virtual method for setting the value of a training parameter.
Reimplemented from ANN::ANNComponent.
References components.
void ANN::StackANNComponent::setUseCuda (bool v) virtual
Virtual method to set use_cuda option. All childs which rewrite this method must call parent method before do anything.
Reimplemented from ANN::ANNComponent.
References components, and ANN::ANNComponent::setUseCuda().
unsigned int ANN::StackANNComponent::size () inline
References components.
char * ANN::StackANNComponent::toLuaString () virtual
Reimplemented from ANN::ANNComponent.
References april_utils::string::c_str(), components, ANN::ANNComponent::name, buffer_list::NULL_TERMINATED, buffer_list::printf(), and buffer_list::to_string().
ANNComponent * ANN::StackANNComponent::topComponent ()
References components.
Member Data Documentation
april_utils::vector<ANNComponent*> ANN::StackANNComponent::components private
Referenced by build(), clone(), computeAllGradients(), copyComponents(), copyWeights(), debugInfo(), doBackprop(), doForward(), doUpdate(), getComponent(), getErrorInput(), getErrorOutput(), getInput(), getOption(), getOutput(), hasOption(), popComponent(), pushComponent(), reset(), resetConnections(), setOption(), setUseCuda(), size(), toLuaString(), topComponent(), and ~StackANNComponent().