april-ann
Token Class Reference abstract
Tokens
Public Member Functions
Token ()
virtual ~Token ()
virtual Token * clone () const =0
This method implements a deep copy.
virtual buffer_list * debugString (const char *prefix, int debugLevel)=0
FOR DEBUG PURPOSES.
virtual TokenCode getTokenCode () const =0
Abstract method which indicates the TokenCode of child Token classes.
virtual buffer_list * toString ()=0
Abstract method for serialization purposes.
template<typename T >
bool isA () const
template<typename T >
T convertTo ()
template<typename T >
const T convertTo () const
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Detailed Description
A pure abstract class with interface of Token. A Token represents the concept of a datatype throught Dataflow architectures (even Artificial Neural Network components).
Member Function Documentation
virtual Token* Token::clone () const pure virtual
This method implements a deep copy.
Implemented in TokenVector< T >, and TokenMemoryBlock.
template<typename T > T Token::convertTo () inline
Templatized method which converts the given Token pointer to a Token child class
Referenced by ANN::MSELossFunction::addLoss(), ANN::MultiClassCrossEntropyLossFunction::addLoss(), ANN::CrossEntropyLossFunction::addLoss(), ANN::LocalFMeasureLossFunction::addLoss(), ANN::JoinANNComponent::buildErrorInputBunchVector(), ANN::JoinANNComponent::buildInputBunchVector(), ANN::JoinANNComponent::buildMemoryBlockToken(), ANN::DotProductANNComponent::computeBPUpdateOnPrevVectors(), ANN::MSELossFunction::computeGradient(), ANN::MultiClassCrossEntropyLossFunction::computeGradient(), ANN::CrossEntropyLossFunction::computeGradient(), ANN::LocalFMeasureLossFunction::computeGradient(), ANN::BiasANNComponent::doBackprop(), ANN::CopyANNComponent::doBackprop(), ANN::ActivationFunctionANNComponent::doBackprop(), ANN::DotProductANNComponent::doBackprop(), ANN::JoinANNComponent::doBackprop(), ANN::BiasANNComponent::doForward(), ANN::ActivationFunctionANNComponent::doForward(), ANN::DotProductANNComponent::doForward(), DataSetTokenVector::getPatternBunch(), UnionDataSetToken::getPatternBunch(), DataSetFloat2TokenWrapper::putPattern(), and DataSetFloat2TokenWrapper::putPatternBunch().
template<typename T > const T Token::convertTo () const inline
Templatized method which converts the given const Token pointer to a const Token child class
virtual buffer_list* Token::debugString (const char * prefix, int debugLevel) pure virtual
FOR DEBUG PURPOSES.
Implemented in TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, and TokenMemoryBlock.
virtual TokenCode Token::getTokenCode () const pure virtual
Abstract method which indicates the TokenCode of child Token classes.
Implemented in TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, and TokenMemoryBlock.
Referenced by ANN::MSELossFunction::addLoss(), ANN::MultiClassCrossEntropyLossFunction::addLoss(), ANN::CrossEntropyLossFunction::addLoss(), ANN::LocalFMeasureLossFunction::addLoss(), ANN::JoinANNComponent::buildErrorInputBunchVector(), ANN::JoinANNComponent::buildInputBunchVector(), ANN::JoinANNComponent::buildMemoryBlockToken(), ANN::MSELossFunction::computeGradient(), ANN::MultiClassCrossEntropyLossFunction::computeGradient(), ANN::CrossEntropyLossFunction::computeGradient(), ANN::LocalFMeasureLossFunction::computeGradient(), ANN::BiasANNComponent::doBackprop(), ANN::CopyANNComponent::doBackprop(), ANN::ActivationFunctionANNComponent::doBackprop(), ANN::DotProductANNComponent::doBackprop(), ANN::JoinANNComponent::doBackprop(), ANN::BiasANNComponent::doForward(), ANN::ActivationFunctionANNComponent::doForward(), ANN::DotProductANNComponent::doForward(), DataSetTokenVector::getPatternBunch(), UnionDataSetToken::getPatternBunch(), DataSetFloat2TokenWrapper::putPattern(), and DataSetFloat2TokenWrapper::putPatternBunch().
template<typename T > bool Token::isA () const inline
Templatized method which returns true if a Token pointer could be transformed to a given Token child class
virtual buffer_list* Token::toString () pure virtual
Abstract method for serialization purposes.
Implemented in TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, TokenVector< T >, and TokenMemoryBlock.