april-ann
april_utils::vector< T > Class Template Reference
Public Types
typedef T value_type
typedef T * pointer
typedef T & reference
typedef const T & const_reference
typedef size_t size_type
typedef ptrdiff_t difference_type
typedef T * iterator
typedef const T * const_iterator
Public Member Functions
size_type size () const
size_type capacity () const
size_type max_size () const
bool empty () const
vector (size_type n=0)
vector (size_type n, const_reference t)
vector (const vector &l)
vector (const_iterator first, const_iterator last)
vector & operator= (const vector &l)
~vector ()
reference operator[] (size_type n)
const_reference operator[] (size_type n) const
void reserve (size_type n)
void push_back (const_reference t)
void pop_back ()
reference back ()
const_reference back () const
void resize (size_type n)
void clear ()
void swap (vector &other)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
Protected Attributes
T * vec
size_t used_size
size_t vector_size
Member Typedef Documentation
template<typename T> typedef const T* april_utils::vector< T >::const_iterator
template<typename T> typedef const T& april_utils::vector< T >::const_reference
template<typename T> typedef ptrdiff_t april_utils::vector< T >::difference_type
template<typename T> typedef T* april_utils::vector< T >::iterator
template<typename T> typedef T* april_utils::vector< T >::pointer
template<typename T> typedef T& april_utils::vector< T >::reference
template<typename T> typedef size_t april_utils::vector< T >::size_type
template<typename T> typedef T april_utils::vector< T >::value_type
Constructor & Destructor Documentation
template<typename T> april_utils::vector< T >::vector (size_type n = 0) inline
template<typename T> april_utils::vector< T >::vector (size_type n, const_reference t) inline
template<typename T> april_utils::vector< T >::vector (const vector< T > & l) inline
template<typename T> april_utils::vector< T >::vector (const_iterator first, const_iterator last) inline
template<typename T> april_utils::vector< T >::~vector () inline
Member Function Documentation
template<typename T> reference april_utils::vector< T >::back () inline
Referenced by april_utils::string::back(), april_utils::maxiphobic_minheap< T >::foreach(), UnionDataSetToken::numPatterns(), and UnionDataSetToken::push_back().
template<typename T> const_reference april_utils::vector< T >::back () const inline
template<typename T> iterator april_utils::vector< T >::begin () inline
Referenced by april_utils::string::begin(), april_utils::string::c_str(), april_utils::string::data(), and april_utils::MFSet::toString().
template<typename T> const_iterator april_utils::vector< T >::begin () const inline
template<typename T> size_type april_utils::vector< T >::capacity () const inline
Referenced by april_utils::string::capacity().
template<typename T> void april_utils::vector< T >::clear () inline
Referenced by april_utils::string::clear(), april_utils::MFSet::clear(), and april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::get_hash_nodes().
template<typename T> bool april_utils::vector< T >::empty () const inline
Referenced by april_utils::maxiphobic_minheap< T >::foreach().
template<typename T> iterator april_utils::vector< T >::end () inline
Referenced by april_utils::string::end().
template<typename T> const_iterator april_utils::vector< T >::end () const inline
template<typename T> size_type april_utils::vector< T >::max_size () const inline
Referenced by april_utils::string::max_size().
template<typename T> vector& april_utils::vector< T >::operator= (const vector< T > & l) inline
template<typename T> reference april_utils::vector< T >::operator[] (size_type n) inline
template<typename T> const_reference april_utils::vector< T >::operator[] (size_type n) const inline
template<typename T> void april_utils::vector< T >::pop_back () inline
Referenced by april_utils::maxiphobic_minheap< T >::foreach(), and april_utils::string::pop_back().
template<typename T> void april_utils::vector< T >::push_back (const_reference t) inline
Referenced by april_utils::string::append(), april_utils::maxiphobic_minheap< T >::foreach(), april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::get_hash_nodes(), april_utils::WordsTable::insertWords(), april_utils::string::push_back(), DataSetTokenVector::push_back(), UnionDataSetToken::push_back(), UnionDataSetToken::UnionDataSetToken(), and april_utils::WordsTable::WordsTable().
template<typename T> void april_utils::vector< T >::reserve (size_type n) inline
Referenced by april_utils::MFSet::clear(), april_utils::maxiphobic_minheap< T >::foreach(), april_utils::MFSet::MFSet(), april_utils::string::reserve(), april_utils::vector< Token * >::resize(), and april_utils::WordsTable::WordsTable().
template<typename T> void april_utils::vector< T >::resize (size_type n) inline
Referenced by april_utils::MFSet::fromString(), april_utils::MFSet::merge(), april_utils::string::resize(), and april_utils::MFSet::setSize().
template<typename T> size_type april_utils::vector< T >::size () const inline
Referenced by april_utils::string::empty(), UnionDataSetToken::getPattern(), april_utils::WordsTable::insertWords(), DataSetTokenVector::numPatterns(), april_utils::string::size(), april_utils::WordsTable::size(), TokenVector< T >::TokenVector(), april_utils::WordsTable::WordsTable(), DataSetTokenVector::~DataSetTokenVector(), and UnionDataSetToken::~UnionDataSetToken().
template<typename T> void april_utils::vector< T >::swap (vector< T > & other) inline
Referenced by april_utils::string::swap().
Member Data Documentation
template<typename T> size_t april_utils::vector< T >::used_size protected
Referenced by april_utils::vector< Token * >::back(), april_utils::vector< Token * >::clear(), april_utils::vector< Token * >::empty(), april_utils::vector< Token * >::end(), april_utils::vector< Token * >::operator=(), april_utils::vector< Token * >::pop_back(), april_utils::vector< Token * >::push_back(), april_utils::ReferencedVector< T >::release_internal_vector(), april_utils::vector< Token * >::reserve(), april_utils::vector< Token * >::resize(), april_utils::vector< Token * >::size(), april_utils::vector< Token * >::swap(), and april_utils::vector< Token * >::vector().
template<typename T> T* april_utils::vector< T >::vec protected
Referenced by april_utils::vector< Token * >::back(), april_utils::vector< Token * >::begin(), april_utils::vector< Token * >::end(), april_utils::vector< Token * >::operator=(), april_utils::vector< Token * >::operator[](), april_utils::vector< Token * >::push_back(), april_utils::ReferencedVector< T >::release_internal_vector(), april_utils::vector< Token * >::reserve(), april_utils::vector< Token * >::swap(), april_utils::vector< Token * >::vector(), and april_utils::vector< Token * >::~vector().
template<typename T> size_t april_utils::vector< T >::vector_size protected
Referenced by april_utils::vector< Token * >::capacity(), april_utils::vector< Token * >::operator=(), april_utils::vector< Token * >::push_back(), april_utils::ReferencedVector< T >::release_internal_vector(), april_utils::vector< Token * >::reserve(), april_utils::vector< Token * >::swap(), and april_utils::vector< Token * >::vector().