april-ann
ANN::ForwardBiasAction Class Reference
Public Member Functions
ForwardBiasAction (const ANNConfiguration &conf, ActivationUnits *outputs, Connections *bias_vector)
virtual ~ForwardBiasAction ()
virtual void doForward ()
virtual void doBackward ()
virtual Action * clone (hash< void *, void * > &clone_dict, const ANNConfiguration &conf)
virtual void setOption (const char *name, double value)
virtual bool hasOption (const char *name)
virtual double getOption (const char *name)
Public Member Functions inherited from ANN::Action
Action (const ANNConfiguration &conf)
virtual ~Action ()
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Attributes
ActivationUnits * outputs
Connections * bias_vector
float learning_rate
float momentum
Additional Inherited Members
Protected Attributes inherited from ANN::Action
const ANNConfiguration & conf
Constructor & Destructor Documentation
ANN::ForwardBiasAction::ForwardBiasAction (const ANNConfiguration & conf, ActivationUnits * outputs, Connections * bias_vector)
References ANN::Connections::checkInputOutputSizes(), ANN::Connections::countReference(), ERROR_EXIT, and IncRef.
Referenced by clone().
ANN::ForwardBiasAction::~ForwardBiasAction () virtual
References bias_vector, DecRef, and outputs.
Member Function Documentation
Action * ANN::ForwardBiasAction::clone (hash< void *, void * > & clone_dict, const ANNConfiguration & conf) virtual
Implements ANN::Action.
References bias_vector, ForwardBiasAction(), learning_rate, momentum, and outputs.
void ANN::ForwardBiasAction::doBackward () virtual
Implements ANN::Action.
References ANN::Connections::beginUpdate(), bias_vector, ANN::Connections::computeMomentumOnPrevVector(), ANN::Connections::computeWeightDecayOnPrevVector(), ANN::Action::conf, ANN::Connections::copyToPrevVector(), ANNConfiguration::cur_bunch_size, doSaxpyLoop(), ANN::Connections::endUpdate(), ANN::ActivationUnits::getErrorVectorPtr(), ANN::Connections::getNumReferences(), ANN::Connections::getPrevPtr(), ANN::Connections::getPtr(), ANN::Connections::isFirstUpdateCall(), learning_rate, ANNConfiguration::max_bunch_size, momentum, ANN::ActivationUnits::numNeurons(), outputs, and ANNConfiguration::use_cuda_flag.
void ANN::ForwardBiasAction::doForward () virtual
Implements ANN::Action.
References bias_vector, ANN::Action::conf, ANNConfiguration::cur_bunch_size, doScopyLoop(), ANN::ActivationUnits::getPtr(), ANN::Connections::getPtr(), ANNConfiguration::max_bunch_size, ANN::ActivationUnits::numNeurons(), outputs, and ANNConfiguration::use_cuda_flag.
double ANN::ForwardBiasAction::getOption (const char * name) virtual
Reimplemented from ANN::Action.
References ERROR_EXIT, learning_rate, mGetOption, and momentum.
bool ANN::ForwardBiasAction::hasOption (const char * name) virtual
Reimplemented from ANN::Action.
References mHasOption.
void ANN::ForwardBiasAction::setOption (const char * name, double value) virtual
Reimplemented from ANN::Action.
References ERROR_EXIT, learning_rate, momentum, and mSetOption.
Member Data Documentation
Connections* ANN::ForwardBiasAction::bias_vector private
Referenced by clone(), doBackward(), doForward(), and ~ForwardBiasAction().
float ANN::ForwardBiasAction::learning_rate private
Referenced by clone(), doBackward(), getOption(), and setOption().
float ANN::ForwardBiasAction::momentum private
Referenced by clone(), doBackward(), getOption(), and setOption().
ActivationUnits* ANN::ForwardBiasAction::outputs private
Referenced by clone(), doBackward(), doForward(), and ~ForwardBiasAction().