april-ann
constString Class Reference
Util
Public Member Functions
constString ()
constString (const char *s)
constString (const char *s, size_t n)
operator bool ()
bool empty ()
bool operator! ()
size_t len () const
operator const char * () const
char operator[] (int i) const
char operator[] (unsigned int i) const
char * newString () const
bool operator== (const constString &otro) const
bool operator!= (const constString &otro) const
bool operator< (const constString &otro) const
bool operator<= (const constString &otro) const
bool operator> (const constString &otro) const
bool operator>= (const constString &otro) const
bool operator== (const char *otro) const
bool operator!= (const char *otro) const
bool operator< (const char *otro) const
bool operator<= (const char *otro) const
bool operator> (const char *otro) const
bool operator>= (const char *otro) const
void skip (size_t n)
void ltrim (const char *acepta=" \t")
bool is_prefix (const constString &theprefix)
bool is_prefix (const char *theprefix)
bool skip (const char *theprefix)
bool skip (const constString &theprefix)
constString extract_prefix (size_t prefix_len)
constString extract_token (const char *separadores=" \t,;\r\n")
constString extract_line ()
constString extract_u_line ()
bool extract_char (char *resul)
bool extract_int (int *resul, int base=10, const char *separadores=" \t,;\r\n")
bool extract_unsigned_int (unsigned int *resul, int base=10, const char *separadores=" \t,;\r\n")
bool extract_long (long int *resul, int base=10, const char *separadores=" \t,;\r\n")
bool extract_long_long (long long int *resul, int base=10, const char *separadores=" \t,;\r\n")
bool extract_float (float *resul, const char *separadores=" \t,;\r\n")
bool extract_double (double *resul, const char *separadores=" \t,;\r\n")
bool extract_float_binary (float *resul)
bool extract_double_binary (double *resul)
bool extract_log_float_binary (log_float *resul)
bool extract_log_double_binary (log_double *resul)
bool extract_uint32_binary (uint32_t *resul)
bool extract_int32_binary (int32_t *resul)
void print (FILE *F=stdout)
Private Attributes
const char * buffer
size_t length
Constructor & Destructor Documentation
constString::constString () inline
References buffer, and length.
Referenced by extract_prefix(), extract_token(), is_prefix(), operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), and skip().
Member Function Documentation
bool constString::empty () inline
References buffer, and length.
Referenced by extract_char(), extract_double_binary(), extract_float(), extract_float_binary(), extract_int32_binary(), extract_long(), extract_long_long(), extract_prefix(), extract_token(), and extract_uint32_binary().
size_t constString::len () const inline
References length.
Referenced by buffer_list::add_constString_left(), buffer_list::add_constString_right(), ReadFileStream::extract_u_line(), TokenVector< T >::fromString(), april_utils::default_hash_function< constString >::operator()(), and readMatrixFloatPNM().
constString::operator bool () inline
References buffer, and length.
constString::operator const char * () const inline
References buffer.
bool constString::operator! () inline
References buffer, and length.
bool constString::operator!= (const char * otro) const inline
References constString(), and operator!=().
Referenced by operator!=().
bool constString::operator< (const char * otro) const inline
References constString(), and operator<().
Referenced by operator<().
bool constString::operator<= (const char * otro) const inline
References constString(), and operator<=().
Referenced by operator<=().
bool constString::operator== (const char * otro) const inline
References constString(), and operator==().
Referenced by operator==().
bool constString::operator> (const char * otro) const inline
References constString(), and operator>().
Referenced by operator>().
bool constString::operator>= (const char * otro) const inline
References constString(), and operator>=().
Referenced by operator>=().
char constString::operator[] (int i) const inline
References buffer.
char constString::operator[] (unsigned int i) const inline
References buffer.
Member Data Documentation
const char* constString::buffer private
Referenced by constString(), empty(), extract_char(), extract_double(), extract_double_binary(), extract_float(), extract_float_binary(), extract_int32_binary(), extract_long(), extract_long_long(), extract_prefix(), extract_token(), extract_u_line(), extract_uint32_binary(), is_prefix(), ltrim(), newString(), operator bool(), operator const char *(), operator!(), operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), operator[](), print(), and skip().
size_t constString::length private
Referenced by constString(), empty(), extract_double(), extract_double_binary(), extract_float(), extract_float_binary(), extract_int32_binary(), extract_long(), extract_long_long(), extract_prefix(), extract_token(), extract_u_line(), extract_uint32_binary(), is_prefix(), len(), ltrim(), newString(), operator bool(), operator!(), operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), print(), and skip().