april-ann
TokenVector< T > Class Template Reference
Tokens
Public Member Functions
TokenVector ()
TokenVector (unsigned int vlength)
TokenVector (const T *vec, unsigned int vlength)
TokenVector (const april_utils::vector< T > &vec)
~TokenVector ()
T & operator[] (unsigned int i)
const T & operator[] (unsigned int i) const
april_utils::vector< T > & getContainer ()
const april_utils::vector< T > & getContainer () const
void push_back (T &data)
T * data ()
const T * data () const
Token * clone () const
This method implements a deep copy.
buffer_list * toString ()
Abstract method for serialization purposes.
buffer_list * debugString (const char *prefix, int debugLevel)
FOR DEBUG PURPOSES.
TokenCode getTokenCode () const
Abstract method which indicates the TokenCode of child Token classes.
virtual unsigned int size () const
virtual void clear ()
template<>
buffer_list * toString ()
Abstract method for serialization purposes.
template<>
buffer_list * debugString (const char *prefix, int debugLevel)
FOR DEBUG PURPOSES.
template<>
TokenCode getTokenCode () const
Abstract method which indicates the TokenCode of child Token classes.
template<>
Token * fromString (constString &cs)
template<>
buffer_list * toString ()
Abstract method for serialization purposes.
template<>
buffer_list * debugString (const char *prefix, int debugLevel)
FOR DEBUG PURPOSES.
template<>
TokenCode getTokenCode () const
Abstract method which indicates the TokenCode of child Token classes.
template<>
Token * fromString (constString &cs)
template<>
buffer_list * toString ()
Abstract method for serialization purposes.
template<>
buffer_list * debugString (const char *prefix, int debugLevel)
FOR DEBUG PURPOSES.
template<>
TokenCode getTokenCode () const
Abstract method which indicates the TokenCode of child Token classes.
template<>
Token * fromString (constString &cs)
template<>
buffer_list * toString ()
Abstract method for serialization purposes.
template<>
buffer_list * debugString (const char *prefix, int debugLevel)
FOR DEBUG PURPOSES.
template<>
TokenCode getTokenCode () const
Abstract method which indicates the TokenCode of child Token classes.
template<>
Token * fromString (constString &cs)
template<>
buffer_list * toString ()
Abstract method for serialization purposes.
template<>
buffer_list * debugString (const char *prefix, int debugLevel)
FOR DEBUG PURPOSES.
template<>
TokenCode getTokenCode () const
Abstract method which indicates the TokenCode of child Token classes.
template<>
Token * fromString (constString &cs)
template<>
TokenVector (Token *const *vec, unsigned int vlength)
template<>
TokenVector (const vector< Token * > &vec)
template<>
void clear ()
template<>
void push_back (Token *&data)
template<>
~TokenVector ()
template<>
buffer_list * toString ()
Abstract method for serialization purposes.
template<>
buffer_list * debugString (const char *prefix, int debugLevel)
FOR DEBUG PURPOSES.
template<>
TokenCode getTokenCode () const
Abstract method which indicates the TokenCode of child Token classes.
template<>
Token * fromString (constString &cs)
template<>
buffer_list * toString ()
Abstract method for serialization purposes.
template<>
buffer_list * debugString (const char *prefix, int debugLevel)
FOR DEBUG PURPOSES.
template<>
TokenCode getTokenCode () const
Abstract method which indicates the TokenCode of child Token classes.
template<>
Token * fromString (constString &cs)
template<>
buffer_list * toString ()
Abstract method for serialization purposes.
template<>
buffer_list * debugString (const char *prefix, int debugLevel)
FOR DEBUG PURPOSES.
template<>
TokenCode getTokenCode () const
Abstract method which indicates the TokenCode of child Token classes.
template<>
Token * fromString (constString &cs)
template<>
buffer_list * toString ()
Abstract method for serialization purposes.
template<>
buffer_list * debugString (const char *prefix, int debugLevel)
FOR DEBUG PURPOSES.
template<>
TokenCode getTokenCode () const
Abstract method which indicates the TokenCode of child Token classes.
template<>
Token * fromString (constString &cs)
template<>
buffer_list * toString ()
Abstract method for serialization purposes.
template<>
buffer_list * debugString (const char *prefix, int debugLevel)
FOR DEBUG PURPOSES.
template<>
TokenCode getTokenCode () const
Abstract method which indicates the TokenCode of child Token classes.
template<>
Token * fromString (constString &cs)
template<>
buffer_list * toString ()
Abstract method for serialization purposes.
template<>
buffer_list * debugString (const char *prefix, int debugLevel)
FOR DEBUG PURPOSES.
template<>
TokenCode getTokenCode () const
Abstract method which indicates the TokenCode of child Token classes.
template<>
Token * fromString (constString &cs)
template<>
buffer_list * toString ()
Abstract method for serialization purposes.
template<>
buffer_list * debugString (const char *prefix, int debugLevel)
FOR DEBUG PURPOSES.
template<>
TokenCode getTokenCode () const
Abstract method which indicates the TokenCode of child Token classes.
template<>
Token * fromString (constString &cs)
template<>
TokenVector (Token *const *vec, unsigned int vlength)
template<>
TokenVector (const vector< Token * > &vec)
template<>
void clear ()
template<>
void push_back (Token *&data)
template<>
~TokenVector ()
template<>
buffer_list * toString ()
Abstract method for serialization purposes.
template<>
buffer_list * debugString (const char *prefix, int debugLevel)
FOR DEBUG PURPOSES.
template<>
TokenCode getTokenCode () const
Abstract method which indicates the TokenCode of child Token classes.
template<>
Token * fromString (constString &cs)
template<>
buffer_list * toString ()
Abstract method for serialization purposes.
template<>
buffer_list * debugString (const char *prefix, int debugLevel)
FOR DEBUG PURPOSES.
template<>
TokenCode getTokenCode () const
Abstract method which indicates the TokenCode of child Token classes.
template<>
Token * fromString (constString &cs)
Static Public Member Functions
static Token * fromString (constString &cs)
Private Attributes
april_utils::vector< T > vec
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Constructor & Destructor Documentation
template<> TokenVector< Token * >::TokenVector (Token *const * vec, unsigned int vlength)
References IncRef.
template<> TokenVector< Token * >::TokenVector (const vector< Token * > & vec)
References IncRef, and april_utils::vector< T >::size().
template<> TokenVector< Token * >::~TokenVector ()
References DecRef.
template<> TokenVector< Token * >::TokenVector (Token *const * vec, unsigned int vlength)
template<> TokenVector< Token * >::TokenVector (const vector< Token * > & vec)
template<> TokenVector< Token * >::~TokenVector ()
Member Function Documentation
template<typename T> virtual void TokenVector< T >::clear () inline virtual
Implements TokenVectorGeneric.
References TokenVector< T >::vec.
template<> void TokenVector< Token * >::clear () virtual
Implements TokenVectorGeneric.
template<> void TokenVector< Token * >::clear () virtual
Implements TokenVectorGeneric.
References DecRef.
template<typename T> T* TokenVector< T >::data () inline
References TokenVector< T >::vec.
template<typename T> const T* TokenVector< T >::data () const inline
References TokenVector< T >::vec.
template<> buffer_list * TokenVector< float >::debugString (const char * prefix, int debugLevel) virtual
FOR DEBUG PURPOSES.
Implements Token.
template<> buffer_list * TokenVector< float >::debugString (const char * prefix, int debugLevel) virtual
FOR DEBUG PURPOSES.
Implements Token.
References buffer_list::add_formatted_string_right().
template<> buffer_list * TokenVector< double >::debugString (const char * prefix, int debugLevel) virtual
FOR DEBUG PURPOSES.
Implements Token.
template<> buffer_list * TokenVector< int32_t >::debugString (const char * prefix, int debugLevel) virtual
FOR DEBUG PURPOSES.
Implements Token.
template<> buffer_list * TokenVector< uint32_t >::debugString (const char * prefix, int debugLevel) virtual
FOR DEBUG PURPOSES.
Implements Token.
template<> buffer_list * TokenVector< double >::debugString (const char * prefix, int debugLevel) virtual
FOR DEBUG PURPOSES.
Implements Token.
References buffer_list::add_formatted_string_right().
template<> buffer_list * TokenVector< char >::debugString (const char * prefix, int debugLevel) virtual
FOR DEBUG PURPOSES.
Implements Token.
template<> buffer_list * TokenVector< Token * >::debugString (const char * prefix, int debugLevel) virtual
FOR DEBUG PURPOSES.
Implements Token.
template<> buffer_list * TokenVector< int32_t >::debugString (const char * prefix, int debugLevel) virtual
FOR DEBUG PURPOSES.
Implements Token.
References buffer_list::add_formatted_string_right().
template<> buffer_list * TokenVector< april_utils::pair< unsigned int, float > >::debugString (const char * prefix, int debugLevel) virtual
FOR DEBUG PURPOSES.
Implements Token.
template<> buffer_list * TokenVector< uint32_t >::debugString (const char * prefix, int debugLevel) virtual
FOR DEBUG PURPOSES.
Implements Token.
References buffer_list::add_formatted_string_right().
template<> buffer_list * TokenVector< char >::debugString (const char * prefix, int debugLevel) virtual
FOR DEBUG PURPOSES.
Implements Token.
References buffer_list::add_formatted_string_right().
template<> buffer_list * TokenVector< Token * >::debugString (const char * prefix, int debugLevel) virtual
FOR DEBUG PURPOSES.
Implements Token.
References buffer_list::add_formatted_string_right().
template<> buffer_list * TokenVector< pair< unsigned int, float > >::debugString (const char * prefix, int debugLevel) virtual
FOR DEBUG PURPOSES.
Implements Token.
References buffer_list::add_formatted_string_right().
template<> Token * TokenVector< float >::fromString (constString & cs)
template<> Token * TokenVector< double >::fromString (constString & cs)
template<> Token * TokenVector< float >::fromString (constString & cs)
References constString::extract_float_binary(), constString::len(), and TokenVector< T >::vec.
template<> Token * TokenVector< int32_t >::fromString (constString & cs)
template<> Token * TokenVector< uint32_t >::fromString (constString & cs)
template<> Token * TokenVector< char >::fromString (constString & cs)
template<> Token * TokenVector< double >::fromString (constString & cs)
References constString::extract_double_binary(), constString::len(), and TokenVector< T >::vec.
template<> Token * TokenVector< Token * >::fromString (constString & cs)
template<> Token * TokenVector< int32_t >::fromString (constString & cs)
References constString::extract_int32_binary(), constString::len(), and TokenVector< T >::vec.
template<> Token * TokenVector< april_utils::pair< unsigned int, float > >::fromString (constString & cs)
template<> Token * TokenVector< uint32_t >::fromString (constString & cs)
References constString::extract_uint32_binary(), constString::len(), and TokenVector< T >::vec.
template<> Token * TokenVector< char >::fromString (constString & cs)
template<> Token * TokenVector< Token * >::fromString (constString & cs)
template<> Token * TokenVector< pair< unsigned int, float > >::fromString (constString & cs)
template<typename T> april_utils::vector<T>& TokenVector< T >::getContainer () inline
References TokenVector< T >::vec.
template<typename T> const april_utils::vector<T>& TokenVector< T >::getContainer () const inline
References TokenVector< T >::vec.
template<> TokenCode TokenVector< float >::getTokenCode () const virtual
Abstract method which indicates the TokenCode of child Token classes.
Implements Token.
template<> TokenCode TokenVector< double >::getTokenCode () const virtual
Abstract method which indicates the TokenCode of child Token classes.
Implements Token.
template<> TokenCode TokenVector< float >::getTokenCode () const virtual
Abstract method which indicates the TokenCode of child Token classes.
Implements Token.
References table_of_token_codes::vector_float.
template<> TokenCode TokenVector< int32_t >::getTokenCode () const virtual
Abstract method which indicates the TokenCode of child Token classes.
Implements Token.
template<> TokenCode TokenVector< uint32_t >::getTokenCode () const virtual
Abstract method which indicates the TokenCode of child Token classes.
Implements Token.
template<> TokenCode TokenVector< double >::getTokenCode () const virtual
Abstract method which indicates the TokenCode of child Token classes.
Implements Token.
References table_of_token_codes::vector_double.
template<> TokenCode TokenVector< char >::getTokenCode () const virtual
Abstract method which indicates the TokenCode of child Token classes.
Implements Token.
template<> TokenCode TokenVector< Token * >::getTokenCode () const virtual
Abstract method which indicates the TokenCode of child Token classes.
Implements Token.
template<> TokenCode TokenVector< int32_t >::getTokenCode () const virtual
Abstract method which indicates the TokenCode of child Token classes.
Implements Token.
References table_of_token_codes::vector_int32.
template<> TokenCode TokenVector< april_utils::pair< unsigned int, float > >::getTokenCode () const virtual
Abstract method which indicates the TokenCode of child Token classes.
Implements Token.
template<> TokenCode TokenVector< uint32_t >::getTokenCode () const virtual
Abstract method which indicates the TokenCode of child Token classes.
Implements Token.
References table_of_token_codes::vector_uint32.
template<> TokenCode TokenVector< char >::getTokenCode () const virtual
Abstract method which indicates the TokenCode of child Token classes.
Implements Token.
References table_of_token_codes::vector_char.
template<> TokenCode TokenVector< Token * >::getTokenCode () const virtual
Abstract method which indicates the TokenCode of child Token classes.
Implements Token.
References table_of_token_codes::vector_Tokens.
template<> TokenCode TokenVector< pair< unsigned int, float > >::getTokenCode () const virtual
Abstract method which indicates the TokenCode of child Token classes.
Implements Token.
References table_of_token_codes::vector_float_sparse.
template<typename T> T& TokenVector< T >::operator[] (unsigned int i) inline
References TokenVector< T >::vec.
template<typename T> const T& TokenVector< T >::operator[] (unsigned int i) const inline
References TokenVector< T >::vec.
template<typename T> void TokenVector< T >::push_back (T & data) inline
References TokenVector< T >::vec.
Referenced by ANN::JoinANNComponent::build(), and ANN::DotProductANNComponent::doForward().
template<> void TokenVector< Token * >::push_back (Token *& data)
template<> void TokenVector< Token * >::push_back (Token *& data)
References IncRef.
template<typename T> virtual unsigned int TokenVector< T >::size () const inline virtual
Implements TokenVectorGeneric.
References TokenVector< T >::vec.
Referenced by ANN::JoinANNComponent::buildErrorInputBunchVector(), ANN::JoinANNComponent::buildInputBunchVector(), ANN::JoinANNComponent::buildMemoryBlockToken(), ANN::DotProductANNComponent::computeBPUpdateOnPrevVectors(), ANN::CopyANNComponent::doBackprop(), and ANN::DotProductANNComponent::doForward().
template<> buffer_list * TokenVector< float >::toString () virtual
Abstract method for serialization purposes.
Implements Token.
template<> buffer_list * TokenVector< float >::toString () virtual
Abstract method for serialization purposes.
Implements Token.
References buffer_list::add_binarized_float_left().
template<> buffer_list * TokenVector< double >::toString () virtual
Abstract method for serialization purposes.
Implements Token.
template<> buffer_list * TokenVector< int32_t >::toString () virtual
Abstract method for serialization purposes.
Implements Token.
template<> buffer_list * TokenVector< uint32_t >::toString () virtual
Abstract method for serialization purposes.
Implements Token.
template<> buffer_list * TokenVector< double >::toString () virtual
Abstract method for serialization purposes.
Implements Token.
References buffer_list::add_binarized_double_left().
template<> buffer_list * TokenVector< char >::toString () virtual
Abstract method for serialization purposes.
Implements Token.
template<> buffer_list * TokenVector< Token * >::toString () virtual
Abstract method for serialization purposes.
Implements Token.
template<> buffer_list * TokenVector< int32_t >::toString () virtual
Abstract method for serialization purposes.
Implements Token.
References buffer_list::add_binarized_int32_left().
template<> buffer_list * TokenVector< april_utils::pair< unsigned int, float > >::toString () virtual
Abstract method for serialization purposes.
Implements Token.
template<> buffer_list * TokenVector< uint32_t >::toString () virtual
Abstract method for serialization purposes.
Implements Token.
References buffer_list::add_binarized_uint32_left().
template<> buffer_list * TokenVector< char >::toString () virtual
Abstract method for serialization purposes.
Implements Token.
References buffer_list::add_constString_left().
template<> buffer_list * TokenVector< Token * >::toString () virtual
Abstract method for serialization purposes.
Implements Token.
template<> buffer_list * TokenVector< pair< unsigned int, float > >::toString () virtual
Abstract method for serialization purposes.
Implements Token.
Member Data Documentation
template<typename T> april_utils::vector<T> TokenVector< T >::vec private
Referenced by TokenVector< T >::clear(), TokenVector< T >::data(), TokenVector< T >::fromString(), TokenVector< T >::getContainer(), TokenVector< T >::operator[](), TokenVector< T >::push_back(), and TokenVector< T >::size().