april-ann
Functions::FunctionBase Class Reference
A pure abstract class that serves as high level interface.
Public Member Functions
FunctionBase ()
virtual ~FunctionBase ()
virtual NS_function_io::type getInputType () const =0
It returns the data type of the input (or domain).
virtual NS_function_io::type getOutputType () const =0
It returns the data type of the output (or range).
virtual unsigned int getInputSize () const =0
It returns the input (or domain) size of the function.
virtual unsigned int getOutputSize () const =0
It returns the output (or range) size of the function.
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Detailed Description
A pure abstract class that serves as high level interface.
A FunctionBase is an abstraction of an object which represents a mathematical function. It has an input/output type and an input/output size. This abstract class is used to store high level methods, which are independent from the input/output types. Every function is feeded with an input vector and produces an output vector.
This class needs to be extended as a template (FunctionInterface class) in order to fix the input/output data types.
Constructor & Destructor Documentation
Functions::FunctionBase::FunctionBase () inline
virtual Functions::FunctionBase::~FunctionBase () inline virtual
Member Function Documentation
virtual unsigned int Functions::FunctionBase::getInputSize () const pure virtual
It returns the input (or domain) size of the function.
Implemented in ANN::ANNBase.
Referenced by Functions::FunctionInterface< I, O >::calculateInPipeline(), Trainable::TrainableSupervised::exitOnDatasetSizeError(), Trainable::TrainableSupervised::trainDataset(), Trainable::TrainableSupervised::trainDatasetWithDistribution(), Trainable::TrainableSupervised::trainDatasetWithReplacement(), Trainable::TrainableSupervised::useDataset(), Trainable::TrainableSupervised::validateDataset(), and Trainable::TrainableSupervised::validateDatasetWithReplacement().
virtual NS_function_io::type Functions::FunctionBase::getInputType () const pure virtual
It returns the data type of the input (or domain).
Implemented in Trainable::TrainableSupervised.
virtual unsigned int Functions::FunctionBase::getOutputSize () const pure virtual
It returns the output (or range) size of the function.
Implemented in ANN::ANNBase.
Referenced by Functions::FunctionInterface< I, O >::calculateInPipeline(), Trainable::TrainableSupervised::exitOnDatasetSizeError(), Trainable::TrainableSupervised::trainDataset(), Trainable::TrainableSupervised::trainDatasetWithDistribution(), Trainable::TrainableSupervised::trainDatasetWithReplacement(), Trainable::TrainableSupervised::useDataset(), Trainable::TrainableSupervised::validateDataset(), and Trainable::TrainableSupervised::validateDatasetWithReplacement().
virtual NS_function_io::type Functions::FunctionBase::getOutputType () const pure virtual
It returns the data type of the output (or range).
Implemented in Trainable::TrainableSupervised.