april-ann
april_utils::TrieVector Class Reference
Classes
struct TrieNode
Public Member Functions
TrieVector (int logSize=20)
~TrieVector ()
unsigned int getSize () const
uint32_t getParent (uint32_t node) const
uint32_t getWord (uint32_t node) const
bool hasChild (uint32_t node, uint32_t word, uint32_t &destnode)
uint32_t getChild (uint32_t node, uint32_t word)
uint32_t getPersistentChild (uint32_t node, uint32_t word)
bool hasSequence (const uint32_t *sequence, int length, uint32_t &destnode)
uint32_t searchSequence (const uint32_t *sequence, int length)
uint32_t searchPersistentSequence (const uint32_t *sequence, int length)
int getSequence (uint32_t node, uint32_t *sequence, int maxLength)
devuelve la longitud, -2 si no existe, -1 si no cabe
uint32_t rootNode () const
void clear ()
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Attributes
unsigned int max_allowed_size
unsigned int vectorSize
unsigned int mask
unsigned int size
unsigned int stamp
TrieNode * data
Static Private Attributes
static const uint32_t NoWord = (1<<24)-1
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Constructor & Destructor Documentation
april_utils::TrieVector::TrieVector (int logSize = 20)
References data, mask, max_allowed_size, NoWord, size, stamp, vectorSize, and april_utils::TrieVector::TrieNode::wordStamp.
april_utils::TrieVector::~TrieVector ()
References data.
Member Function Documentation
void april_utils::TrieVector::clear ()
References data, size, stamp, vectorSize, and april_utils::TrieVector::TrieNode::wordStamp.
uint32_t april_utils::TrieVector::getChild (uint32_t node, uint32_t word)
References data, ERROR_EXIT1, mask, max_allowed_size, size, stamp, and april_utils::TrieVector::TrieNode::wordStamp.
Referenced by searchSequence().
uint32_t april_utils::TrieVector::getParent (uint32_t node) const inline
References data, and april_utils::TrieVector::TrieNode::parent.
uint32_t april_utils::TrieVector::getPersistentChild (uint32_t node, uint32_t word)
References data, ERROR_EXIT1, mask, max_allowed_size, and size.
Referenced by searchPersistentSequence().
int april_utils::TrieVector::getSequence (uint32_t node, uint32_t * sequence, int maxLength)
devuelve la longitud, -2 si no existe, -1 si no cabe
References data, april_utils::TrieVector::TrieNode::parent, stamp, april_utils::swap(), and april_utils::TrieVector::TrieNode::wordStamp.
unsigned int april_utils::TrieVector::getSize () const inline
References size.
uint32_t april_utils::TrieVector::getWord (uint32_t node) const inline
References data, and april_utils::TrieVector::TrieNode::wordStamp.
bool april_utils::TrieVector::hasChild (uint32_t node, uint32_t word, uint32_t & destnode)
References data, mask, stamp, and april_utils::TrieVector::TrieNode::wordStamp.
Referenced by hasSequence().
bool april_utils::TrieVector::hasSequence (const uint32_t * sequence, int length, uint32_t & destnode)
References hasChild(), and rootNode().
uint32_t april_utils::TrieVector::rootNode () const inline
Referenced by hasSequence(), searchPersistentSequence(), and searchSequence().
uint32_t april_utils::TrieVector::searchPersistentSequence (const uint32_t * sequence, int length)
References getPersistentChild(), and rootNode().
uint32_t april_utils::TrieVector::searchSequence (const uint32_t * sequence, int length)
References getChild(), and rootNode().
Member Data Documentation
TrieNode* april_utils::TrieVector::data private
Referenced by clear(), getChild(), getParent(), getPersistentChild(), getSequence(), getWord(), hasChild(), TrieVector(), and ~TrieVector().
unsigned int april_utils::TrieVector::mask private
Referenced by getChild(), getPersistentChild(), hasChild(), and TrieVector().
unsigned int april_utils::TrieVector::max_allowed_size private
Referenced by getChild(), getPersistentChild(), and TrieVector().
const uint32_t april_utils::TrieVector::NoWord = (1<<24)-1 static private
Referenced by TrieVector().
unsigned int april_utils::TrieVector::size private
Referenced by clear(), getChild(), getPersistentChild(), getSize(), and TrieVector().
unsigned int april_utils::TrieVector::stamp private
Referenced by clear(), getChild(), getSequence(), hasChild(), and TrieVector().
unsigned int april_utils::TrieVector::vectorSize private
Referenced by clear(), and TrieVector().