april-ann
ANN::ConvolutionANNComponent Class Reference
Public Member Functions
ConvolutionANNComponent (int input_num_dims, const int *_kernel_dims, const int *_kernel_step, int num_output_planes, const char *name=0, const char *weights_name=0)
virtual ~ConvolutionANNComponent ()
virtual Token * getInput ()
virtual Token * getOutput ()
virtual Token * getErrorInput ()
virtual Token * getErrorOutput ()
virtual Token * doForward (Token *input, bool during_training)
virtual Token * doBackprop (Token *input_error)
virtual void doUpdate ()
virtual void reset ()
virtual ANNComponent * clone ()
virtual void setOption (const char *name, double value)
Virtual method for setting the value of a training parameter.
virtual bool hasOption (const char *name)
virtual double getOption (const char *name)
virtual void build (unsigned int input_size, unsigned int output_size, hash< string, Connections * > &weights_dict, hash< string, ANNComponent * > &components_dict)
virtual void copyWeights (hash< string, Connections * > &weights_dict)
Abstract method to retrieve Connections objects from ANNComponents.
virtual void resetConnections ()
virtual char * toLuaString ()
Public Member Functions inherited from ANN::ANNComponent
ANNComponent (const char *name=0, const char *weights_name=0, unsigned int input_size=0, unsigned int output_size=0)
virtual ~ANNComponent ()
const string & getName () const
const string & getWeightsName () const
bool hasWeightsName () const
bool getIsBuilt () const
void generateDefaultWeightsName (string &dest, const char *prefix=0)
unsigned int getInputSize () const
unsigned int getOutputSize () const
virtual void computeAllGradients (hash< string, MatrixFloat * > &weight_grads_dict)
virtual void setUseCuda (bool v)
bool getUseCuda () const
virtual void copyComponents (hash< string, ANNComponent * > &components_dict)
virtual void debugInfo ()
virtual ANNComponent * getComponent (string &name)
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Protected Member Functions
virtual void computeGradients (MatrixFloat *&weight_grads)
Private Member Functions
MatrixFloat * getRewrappedMatrix (MatrixFloat *w, const int *rewrap_size, const int N, bool copy) const
void initializeArrays (const int *input_dims)
void computeBP (MatrixFloat *weights_mat, MatrixFloat *input_mat, MatrixFloat *error_input_mat, const float alpha, float beta)
Private Attributes
TokenMatrixFloat * input
TokenMatrixFloat * error_input
TokenMatrixFloat * output
TokenMatrixFloat * error_output
Connections * weights_matrix
MatrixFloat * bias_matrix
unsigned int num_updates_from_last_prune
int number_input_windows
The number of convolutions computed during last forward.
unsigned int kernel_size
The size of one kernel (number of inputs of one hidden neuron)
const unsigned int hidden_size
The number of neurons (number of output planes)
const int input_num_dims
The number of expected input dimensions without count BUNCH dim (first)
int * kernel_dims
Size at each dim of the kernel, input_num_dims + 1.
int * kernel_step
Step at each dim of the input, input_num_dims + 1.
int * output_dims
Size at each dim of the output, input_num_dims + 1.
int * input_window_size
Size of the convolution window, input_num_dims + 1.
int * input_window_num_steps
Number of steps of the convolution window, input_num_dims + 1.
int * input_window_order_step
Order for traversing the input data, prepared for col-major order.
int * input_window_rewrap
Translates the input window into a bi-dimensional matrix.
int * output_window_size
Size of the convolution window, input_num_dims + 1.
int * output_window_step
Step between convolution windows, input_num_dims + 1.
int * output_window_num_steps
Number of steps of the convolution window, input_num_dims + 1.
int * output_window_order_step
Order for traversing the input data, prepared for col-major order.
int * output_window_rewrap
Translates the output window into a bi-dimensional matrix.
float learning_rate
learning parameters
float momentum
float weight_decay
float c_weight_decay
float max_norm_penalty
Additional Inherited Members
Protected Attributes inherited from ANN::ANNComponent
string name
string weights_name
unsigned int input_size
unsigned int output_size
bool use_cuda
Static Protected Attributes inherited from ANN::ANNComponent
static unsigned int next_name_id = 1
static unsigned int next_weights_id = 1
Constructor & Destructor Documentation
ANN::ConvolutionANNComponent::ConvolutionANNComponent (int input_num_dims, const int * _kernel_dims, const int * _kernel_step, int num_output_planes, const char * name = 0, const char * weights_name = 0)
References ANN::ANNComponent::generateDefaultWeightsName(), hidden_size, input_num_dims, input_window_order_step, input_window_rewrap, kernel_dims, kernel_size, kernel_step, output_window_order_step, output_window_rewrap, output_window_size, and output_window_step.
Referenced by clone().
ANN::ConvolutionANNComponent::~ConvolutionANNComponent () virtual
References DecRef, error_input, error_output, input, input_window_num_steps, input_window_order_step, input_window_rewrap, input_window_size, kernel_dims, kernel_step, output, output_dims, output_window_num_steps, output_window_order_step, output_window_rewrap, output_window_size, output_window_step, and weights_matrix.
Member Function Documentation
void ANN::ConvolutionANNComponent::build (unsigned int _input_size, unsigned int _output_size, hash< string, Connections * > & weights_dict, hash< string, ANNComponent * > & components_dict) virtual
Abstract method to finish building of component hierarchy and set weights objects pointers. All childs which rewrite this method must call parent method before do anything.
Reimplemented from ANN::ANNComponent.
References AssignRef, ANN::ANNComponent::build(), april_utils::string::c_str(), ANN::Connections::checkInputOutputSizes(), ANN::Connections::countReference(), ERROR_EXIT3, hidden_size, IncRef, kernel_size, ANN::ANNComponent::name, weights_matrix, and ANN::ANNComponent::weights_name.
ANNComponent * ANN::ConvolutionANNComponent::clone () virtual
Reimplemented from ANN::ANNComponent.
References april_utils::string::c_str(), c_weight_decay, ConvolutionANNComponent(), hidden_size, input_num_dims, ANN::ANNComponent::input_size, kernel_dims, kernel_step, learning_rate, max_norm_penalty, momentum, ANN::ANNComponent::name, ANN::ANNComponent::output_size, weight_decay, and ANN::ANNComponent::weights_name.
void ANN::ConvolutionANNComponent::computeBP (MatrixFloat * weights_mat, MatrixFloat * input_mat, MatrixFloat * error_input_mat, const float alpha, float beta) private
References DecRef, Matrix< T >::gemm(), Matrix< T >::getDimSize(), getRewrappedMatrix(), IncRef, input_window_num_steps, input_window_order_step, input_window_rewrap, input_window_size, kernel_step, output_window_num_steps, output_window_order_step, output_window_rewrap, output_window_size, and output_window_step.
Referenced by computeGradients(), and doUpdate().
void ANN::ConvolutionANNComponent::computeGradients (MatrixFloat *& weight_grads) protected virtual
Method which computes the gradient of the weights on the given MatrixFloat object
Reimplemented from ANN::ANNComponent.
References Matrix< T >::cloneOnlyDims(), computeBP(), error_input, TokenMatrix< T >::getMatrix(), ANN::Connections::getPtr(), input, weights_matrix, and Matrix< T >::zeros().
void ANN::ConvolutionANNComponent::copyWeights (hash< string, Connections * > & weights_dict) virtual
Abstract method to retrieve Connections objects from ANNComponents.
Reimplemented from ANN::ANNComponent.
References april_utils::string::c_str(), ERROR_EXIT1, ERROR_EXIT2, ANN::ANNComponent::name, weights_matrix, and ANN::ANNComponent::weights_name.
Token * ANN::ConvolutionANNComponent::doBackprop (Token * input_error) virtual
Virtual method that back-propagates error derivatives and computes other useful stuff. Receives input error gradients, and returns its output error gradients Token.
Reimplemented from ANN::ANNComponent.
References AssignRef, april_utils::string::c_str(), Token::convertTo(), Matrix< T >::copy(), DecRef, ERROR_EXIT1, error_input, error_output, Matrix< T >::gemm(), Matrix< T >::getDimPtr(), TokenMatrix< T >::getMatrix(), Matrix< T >::getNumDim(), ANN::Connections::getPtr(), Matrix< T >::getRawDataAccess(), getRewrappedMatrix(), Token::getTokenCode(), IncRef, input, input_window_num_steps, input_window_order_step, input_window_rewrap, input_window_size, kernel_step, ANN::ANNComponent::name, number_input_windows, output, output_window_num_steps, output_window_order_step, output_window_rewrap, output_window_size, output_window_step, Matrix< T >::rewrap(), Matrix< T >::setUseCuda(), table_of_token_codes::token_matrix, ANN::ANNComponent::use_cuda, weights_matrix, and Matrix< T >::zeros().
Token * ANN::ConvolutionANNComponent::doForward (Token * input, bool during_training) virtual
Virtual method that executes the set of operations required for each block of connections when performing the forward step of the Backpropagation algorithm, and returns its output Token
Reimplemented from ANN::ANNComponent.
References AssignRef, april_utils::string::c_str(), Token::convertTo(), Matrix< T >::copy(), DecRef, ERROR_EXIT1, ERROR_EXIT3, Matrix< T >::gemm(), Matrix< T >::getDimPtr(), TokenMatrix< T >::getMatrix(), Matrix< T >::getNumDim(), ANN::Connections::getPtr(), Matrix< T >::getRawDataAccess(), getRewrappedMatrix(), Token::getTokenCode(), IncRef, initializeArrays(), input, input_num_dims, input_window_num_steps, input_window_order_step, input_window_rewrap, input_window_size, kernel_step, ANN::ANNComponent::name, number_input_windows, output, output_dims, output_window_num_steps, output_window_order_step, output_window_rewrap, output_window_size, output_window_step, Matrix< T >::rewrap(), Matrix< T >::setUseCuda(), table_of_token_codes::token_matrix, ANN::ANNComponent::use_cuda, and weights_matrix.
void ANN::ConvolutionANNComponent::doUpdate () virtual
Virtual method that update weights given gradients and input/output data
Reimplemented from ANN::ANNComponent.
References ANN::Connections::applyMaxNormPenalty(), ANN::Connections::beginUpdate(), c_weight_decay, computeBP(), ANN::Connections::computeMomentumOnPrevVector(), ANN::Connections::computeWeightDecayOnPrevVector(), ANN::Connections::copyToPrevVector(), ANN::Connections::endUpdate(), error_input, Matrix< T >::getDimSize(), TokenMatrix< T >::getMatrix(), ANN::Connections::getNumReferences(), ANN::Connections::getPrevPtr(), input, ANN::Connections::isFirstUpdateCall(), learning_rate, max_norm_penalty, MAX_UPDATES_WITHOUT_PRUNE, momentum, num_updates_from_last_prune, number_input_windows, ANN::Connections::pruneSubnormalAndCheckNormal(), ANN::ANNComponent::use_cuda, and weights_matrix.
virtual Token* ANN::ConvolutionANNComponent::getErrorInput () inline virtual
Reimplemented from ANN::ANNComponent.
References error_input.
virtual Token* ANN::ConvolutionANNComponent::getErrorOutput () inline virtual
Reimplemented from ANN::ANNComponent.
References error_output.
virtual Token* ANN::ConvolutionANNComponent::getInput () inline virtual
Reimplemented from ANN::ANNComponent.
References input.
double ANN::ConvolutionANNComponent::getOption (const char * name) virtual
Virtual method for getting the value of a training parameter. All childs which rewrite this method must call parent method after their process, if the looked option is not found to show the error message.
Reimplemented from ANN::ANNComponent.
References ANN::ANNComponent::getOption(), learning_rate, LEARNING_RATE_STRING, max_norm_penalty, MAX_NORM_PENALTY_STRING, mGetOption, momentum, MOMENTUM_STRING, weight_decay, and WEIGHT_DECAY_STRING.
virtual Token* ANN::ConvolutionANNComponent::getOutput () inline virtual
Reimplemented from ANN::ANNComponent.
References output.
MatrixFloat* ANN::ConvolutionANNComponent::getRewrappedMatrix (MatrixFloat * w, const int * rewrap_size, const int N, bool copy) const inline private
References Matrix< T >::clone(), Matrix< T >::cloneOnlyDims(), DecRef, Matrix< T >::getIsContiguous(), IncRef, and Matrix< T >::rewrap().
Referenced by computeBP(), doBackprop(), and doForward().
bool ANN::ConvolutionANNComponent::hasOption (const char * name) virtual
Virtual method for determining if a training parameter is being used or can be used within the network.
Reimplemented from ANN::ANNComponent.
References LEARNING_RATE_STRING, MAX_NORM_PENALTY_STRING, mHasOption, MOMENTUM_STRING, and WEIGHT_DECAY_STRING.
void ANN::ConvolutionANNComponent::initializeArrays (const int * input_dims) private
References april_utils::string::c_str(), ERROR_EXIT3, hidden_size, input_num_dims, input_window_num_steps, input_window_rewrap, input_window_size, kernel_dims, kernel_step, ANN::ANNComponent::name, output_dims, output_window_num_steps, output_window_rewrap, and output_window_size.
Referenced by doForward().
void ANN::ConvolutionANNComponent::reset () virtual
Virtual method to reset to zero gradients and outputs (inputs are not reseted)
Reimplemented from ANN::ANNComponent.
References DecRef, error_input, error_output, input, and output.
virtual void ANN::ConvolutionANNComponent::resetConnections () inline virtual
Reimplemented from ANN::ANNComponent.
References ANN::Connections::reset(), and weights_matrix.
void ANN::ConvolutionANNComponent::setOption (const char * name, double value) virtual
Virtual method for setting the value of a training parameter.
Reimplemented from ANN::ANNComponent.
References c_weight_decay, learning_rate, LEARNING_RATE_STRING, max_norm_penalty, MAX_NORM_PENALTY_STRING, momentum, MOMENTUM_STRING, mSetOption, ANN::ANNComponent::setOption(), weight_decay, and WEIGHT_DECAY_STRING.
char * ANN::ConvolutionANNComponent::toLuaString () virtual
Reimplemented from ANN::ANNComponent.
References april_utils::string::c_str(), hidden_size, input_num_dims, kernel_dims, kernel_step, ANN::ANNComponent::name, buffer_list::NULL_TERMINATED, buffer_list::printf(), buffer_list::to_string(), and ANN::ANNComponent::weights_name.
Member Data Documentation
MatrixFloat* ANN::ConvolutionANNComponent::bias_matrix private
float ANN::ConvolutionANNComponent::c_weight_decay private
Referenced by clone(), doUpdate(), and setOption().
TokenMatrixFloat * ANN::ConvolutionANNComponent::error_input private
Referenced by computeGradients(), doBackprop(), doUpdate(), getErrorInput(), reset(), and ~ConvolutionANNComponent().
TokenMatrixFloat * ANN::ConvolutionANNComponent::error_output private
Referenced by doBackprop(), getErrorOutput(), reset(), and ~ConvolutionANNComponent().
const unsigned int ANN::ConvolutionANNComponent::hidden_size private
The number of neurons (number of output planes)
Referenced by build(), clone(), ConvolutionANNComponent(), initializeArrays(), and toLuaString().
TokenMatrixFloat* ANN::ConvolutionANNComponent::input private
Referenced by computeGradients(), doBackprop(), doForward(), doUpdate(), getInput(), reset(), and ~ConvolutionANNComponent().
const int ANN::ConvolutionANNComponent::input_num_dims private
The number of expected input dimensions without count BUNCH dim (first)
Referenced by clone(), ConvolutionANNComponent(), doForward(), initializeArrays(), and toLuaString().
int* ANN::ConvolutionANNComponent::input_window_num_steps private
Number of steps of the convolution window, input_num_dims + 1.
Referenced by computeBP(), doBackprop(), doForward(), initializeArrays(), and ~ConvolutionANNComponent().
int* ANN::ConvolutionANNComponent::input_window_order_step private
Order for traversing the input data, prepared for col-major order.
Referenced by computeBP(), ConvolutionANNComponent(), doBackprop(), doForward(), and ~ConvolutionANNComponent().
int* ANN::ConvolutionANNComponent::input_window_rewrap private
Translates the input window into a bi-dimensional matrix.
Referenced by computeBP(), ConvolutionANNComponent(), doBackprop(), doForward(), initializeArrays(), and ~ConvolutionANNComponent().
int* ANN::ConvolutionANNComponent::input_window_size private
Size of the convolution window, input_num_dims + 1.
Referenced by computeBP(), doBackprop(), doForward(), initializeArrays(), and ~ConvolutionANNComponent().
int* ANN::ConvolutionANNComponent::kernel_dims private
Size at each dim of the kernel, input_num_dims + 1.
Referenced by clone(), ConvolutionANNComponent(), initializeArrays(), toLuaString(), and ~ConvolutionANNComponent().
unsigned int ANN::ConvolutionANNComponent::kernel_size private
The size of one kernel (number of inputs of one hidden neuron)
Referenced by build(), and ConvolutionANNComponent().
int* ANN::ConvolutionANNComponent::kernel_step private
Step at each dim of the input, input_num_dims + 1.
Referenced by clone(), computeBP(), ConvolutionANNComponent(), doBackprop(), doForward(), initializeArrays(), toLuaString(), and ~ConvolutionANNComponent().
float ANN::ConvolutionANNComponent::learning_rate private
learning parameters
Referenced by clone(), doUpdate(), getOption(), and setOption().
float ANN::ConvolutionANNComponent::max_norm_penalty private
Referenced by clone(), doUpdate(), getOption(), and setOption().
float ANN::ConvolutionANNComponent::momentum private
Referenced by clone(), doUpdate(), getOption(), and setOption().
unsigned int ANN::ConvolutionANNComponent::num_updates_from_last_prune private
Referenced by doUpdate().
int ANN::ConvolutionANNComponent::number_input_windows private
The number of convolutions computed during last forward.
Referenced by doBackprop(), doForward(), and doUpdate().
TokenMatrixFloat * ANN::ConvolutionANNComponent::output private
Referenced by doBackprop(), doForward(), getOutput(), reset(), and ~ConvolutionANNComponent().
int* ANN::ConvolutionANNComponent::output_dims private
Size at each dim of the output, input_num_dims + 1.
Referenced by doForward(), initializeArrays(), and ~ConvolutionANNComponent().
int* ANN::ConvolutionANNComponent::output_window_num_steps private
Number of steps of the convolution window, input_num_dims + 1.
Referenced by computeBP(), doBackprop(), doForward(), initializeArrays(), and ~ConvolutionANNComponent().
int* ANN::ConvolutionANNComponent::output_window_order_step private
Order for traversing the input data, prepared for col-major order.
Referenced by computeBP(), ConvolutionANNComponent(), doBackprop(), doForward(), and ~ConvolutionANNComponent().
int* ANN::ConvolutionANNComponent::output_window_rewrap private
Translates the output window into a bi-dimensional matrix.
Referenced by computeBP(), ConvolutionANNComponent(), doBackprop(), doForward(), initializeArrays(), and ~ConvolutionANNComponent().
int* ANN::ConvolutionANNComponent::output_window_size private
Size of the convolution window, input_num_dims + 1.
Referenced by computeBP(), ConvolutionANNComponent(), doBackprop(), doForward(), initializeArrays(), and ~ConvolutionANNComponent().
int* ANN::ConvolutionANNComponent::output_window_step private
Step between convolution windows, input_num_dims + 1.
Referenced by computeBP(), ConvolutionANNComponent(), doBackprop(), doForward(), and ~ConvolutionANNComponent().
float ANN::ConvolutionANNComponent::weight_decay private
Referenced by clone(), getOption(), and setOption().
Connections* ANN::ConvolutionANNComponent::weights_matrix private
Referenced by build(), computeGradients(), copyWeights(), doBackprop(), doForward(), doUpdate(), resetConnections(), and ~ConvolutionANNComponent().