april-ann
ANN::DotProductAction Class Reference
Public Member Functions
DotProductAction (const ANNConfiguration &conf, ActivationUnits *inputs, ActivationUnits *outputs, Connections *weights_matrix)
virtual ~DotProductAction ()
virtual void doForward ()
virtual void doBackward ()
virtual Action * clone (hash< void *, void * > &clone_dict, const ANNConfiguration &conf)
virtual void setOption (const char *name, double value)
virtual bool hasOption (const char *name)
virtual double getOption (const char *name)
Public Member Functions inherited from ANN::Action
Action (const ANNConfiguration &conf)
virtual ~Action ()
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Member Functions
void backpropagateErrors (FloatGPUMirroredMemoryBlock *weights_mat_ptr, FloatGPUMirroredMemoryBlock *output_error, const unsigned int output_error_shift, FloatGPUMirroredMemoryBlock *input_error, const unsigned int input_error_shift)
void computeBPUpdateOnPrevVectors (FloatGPUMirroredMemoryBlock *prev_weights_mat_ptr, FloatGPUMirroredMemoryBlock *input, const unsigned int input_shift, FloatGPUMirroredMemoryBlock *input_error, const unsigned int input_error_shift, float beta)
Private Attributes
ActivationUnits * inputs
ActivationUnits * outputs
Connections * weights_matrix
const unsigned int num_inputs
const unsigned int num_outputs
const ANNConfiguration & conf
float learning_rate
float momentum
float weight_decay
float c_weight_decay
Additional Inherited Members
Protected Attributes inherited from ANN::Action
const ANNConfiguration & conf
Constructor & Destructor Documentation
ANN::DotProductAction::DotProductAction (const ANNConfiguration & conf, ActivationUnits * inputs, ActivationUnits * outputs, Connections * weights_matrix)
References ANN::Connections::checkInputOutputSizes(), ANN::Connections::countReference(), ERROR_EXIT, and IncRef.
Referenced by clone().
ANN::DotProductAction::~DotProductAction () virtual
References DecRef, inputs, outputs, and weights_matrix.
Member Function Documentation
void ANN::DotProductAction::backpropagateErrors (FloatGPUMirroredMemoryBlock * weights_mat_ptr, FloatGPUMirroredMemoryBlock * output_error, const unsigned int output_error_shift, FloatGPUMirroredMemoryBlock * input_error, const unsigned int input_error_shift) private
References conf, ANNConfiguration::cur_bunch_size, doSgemm(), doSgemv(), ANNConfiguration::max_bunch_size, num_inputs, num_outputs, and ANNConfiguration::use_cuda_flag.
Referenced by doBackward().
Action * ANN::DotProductAction::clone (hash< void *, void * > & clone_dict, const ANNConfiguration & conf) virtual
Implements ANN::Action.
References c_weight_decay, DotProductAction(), inputs, learning_rate, momentum, outputs, weight_decay, and weights_matrix.
void ANN::DotProductAction::computeBPUpdateOnPrevVectors (FloatGPUMirroredMemoryBlock * prev_weights_mat_ptr, FloatGPUMirroredMemoryBlock * input, const unsigned int input_shift, FloatGPUMirroredMemoryBlock * input_error, const unsigned int input_error_shift, float beta) private
References conf, ANNConfiguration::cur_bunch_size, doSgemm(), doSger(), doSscal(), ANN::Connections::getNumReferences(), learning_rate, ANNConfiguration::max_bunch_size, num_inputs, num_outputs, ANNConfiguration::use_cuda_flag, and weights_matrix.
Referenced by doBackward().
void ANN::DotProductAction::doBackward () virtual
Implements ANN::Action.
References backpropagateErrors(), ANN::Connections::beginUpdate(), c_weight_decay, computeBPUpdateOnPrevVectors(), ANN::Connections::computeMomentumOnPrevVector(), ANN::Connections::computeWeightDecayOnPrevVector(), conf, ANN::Connections::copyToPrevVector(), ANN::Connections::endUpdate(), ANN::ActivationUnits::getErrorVectorPtr(), ANN::ActivationUnits::getOffset(), ANN::Connections::getPrevPtr(), ANN::ActivationUnits::getPtr(), ANN::Connections::getPtr(), inputs, ANN::Connections::isFirstUpdateCall(), learning_rate, momentum, outputs, ANNConfiguration::use_cuda_flag, and weights_matrix.
void ANN::DotProductAction::doForward () virtual
Implements ANN::Action.
References conf, ANNConfiguration::cur_bunch_size, doSgemm(), doSgemv(), ANN::ActivationUnits::getOffset(), ANN::ActivationUnits::getPtr(), ANN::Connections::getPtr(), inputs, ANNConfiguration::max_bunch_size, num_inputs, num_outputs, outputs, ANNConfiguration::use_cuda_flag, and weights_matrix.
double ANN::DotProductAction::getOption (const char * name) virtual
Reimplemented from ANN::Action.
References ERROR_EXIT, learning_rate, mGetOption, momentum, and weight_decay.
bool ANN::DotProductAction::hasOption (const char * name) virtual
Reimplemented from ANN::Action.
References mHasOption.
void ANN::DotProductAction::setOption (const char * name, double value) virtual
Reimplemented from ANN::Action.
References c_weight_decay, ERROR_EXIT1, learning_rate, momentum, mSetOption, and weight_decay.
Member Data Documentation
float ANN::DotProductAction::c_weight_decay private
Referenced by clone(), doBackward(), and setOption().
const ANNConfiguration& ANN::DotProductAction::conf private
Referenced by backpropagateErrors(), computeBPUpdateOnPrevVectors(), doBackward(), and doForward().
ActivationUnits* ANN::DotProductAction::inputs private
Referenced by clone(), doBackward(), doForward(), and ~DotProductAction().
float ANN::DotProductAction::learning_rate private
Referenced by clone(), computeBPUpdateOnPrevVectors(), doBackward(), getOption(), and setOption().
float ANN::DotProductAction::momentum private
Referenced by clone(), doBackward(), getOption(), and setOption().
const unsigned int ANN::DotProductAction::num_inputs private
Referenced by backpropagateErrors(), computeBPUpdateOnPrevVectors(), and doForward().
const unsigned int ANN::DotProductAction::num_outputs private
Referenced by backpropagateErrors(), computeBPUpdateOnPrevVectors(), and doForward().
ActivationUnits* ANN::DotProductAction::outputs private
Referenced by clone(), doBackward(), doForward(), and ~DotProductAction().
float ANN::DotProductAction::weight_decay private
Referenced by clone(), getOption(), and setOption().
Connections* ANN::DotProductAction::weights_matrix private
Referenced by clone(), computeBPUpdateOnPrevVectors(), doBackward(), doForward(), and ~DotProductAction().