april-ann
ANN::SoftmaxActivationFunction Class Reference
A softmax activation function.
Public Member Functions
SoftmaxActivationFunction ()
virtual ~SoftmaxActivationFunction ()
void applyActivation (FloatGPUMirroredMemoryBlock *units, unsigned int units_size, const ANNConfiguration &conf, bool use_cuda)
Abstract method that activates a "bunch" of units (or neurons).
void multiplyDerivatives (FloatGPUMirroredMemoryBlock *units, FloatGPUMirroredMemoryBlock *input_errors, unsigned int size, const ANNConfiguration &conf, bool use_cuda, bool is_output)
Abstract method that computes derivatives.
ActivationFunction * clone ()
Returns a deep copy of the object.
Public Member Functions inherited from ANN::ActivationFunction
virtual ~ActivationFunction ()
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Attributes
unsigned int size
If use_cuda=true, this is the size of the ActivationUnits.
FloatGPUMirroredMemoryBlock * minimums
Only with use_cuda=true, for map-reduce process.
FloatGPUMirroredMemoryBlock * maximums
Only with use_cuda=true, for map-reduce process.
FloatGPUMirroredMemoryBlock * sums
Only with use_cuda=true, for map-reduce process.
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Detailed Description
A softmax activation function.
Implements ActivationFunction interface and, given a bunch_size number of neuron layers, follows the equation:
If use_cuda flag is true, the object reserves memory for the map-reduce process executed at the GPU. Therefore, with use_cuda=true the object is unable to be shared between different ActivationUnits.
Constructor & Destructor Documentation
ANN::SoftmaxActivationFunction::SoftmaxActivationFunction ()
Referenced by clone().
ANN::SoftmaxActivationFunction::~SoftmaxActivationFunction () virtual
References maximums, minimums, and sums.
Member Function Documentation
void ANN::SoftmaxActivationFunction::applyActivation (FloatGPUMirroredMemoryBlock * units, unsigned int units_size, const ANNConfiguration & conf, bool use_cuda) virtual
Abstract method that activates a "bunch" of units (or neurons).
Abstract method that takes the input neuron potentials and computes the activation:
being the activation of neuron , depending on its potential and the other neurons potentials.
Parameters
units an input matrix of size (size X conf.cur_bunch_size). It is stored at an FloatGPUMirroredMemoryBlock object, Each component is a neuron activation.
units_size the number of neurons.
conf a reference to an ANNConfiguration struct which contains global parameters as: current bunch size, maximum bunch size, use_cuda global flag,
use_cuda a boolean parameter that indicates the use of CPU computation or GPU computation (using CUDA). Overrides the configuration stored at conf parameter.
Implements ANN::ActivationFunction.
References april_utils::ceilingPowerOfTwo(), doApplySoftmaxActivation(), ERROR_EXIT, ANNConfiguration::max_bunch_size, maximums, minimums, size, and sums.
ActivationFunction * ANN::SoftmaxActivationFunction::clone () virtual
Returns a deep copy of the object.
Implements ANN::ActivationFunction.
References SoftmaxActivationFunction().
void ANN::SoftmaxActivationFunction::multiplyDerivatives (FloatGPUMirroredMemoryBlock * units, FloatGPUMirroredMemoryBlock * input_errors, unsigned int size, const ANNConfiguration & conf, bool use_cuda, bool is_output) virtual
Abstract method that computes derivatives.
Abstract method that computes the derivative of a "bunch" of units (or neurons) and stores it on input_errors vector. Basically, it computes the following equation:
Parameters
units an input matrix of size (size X conf.cur_bunch_size). It is stored at an FloatGPUMirroredMemoryBlock object, Each component is a neuron activation.
input_errors an input matrix of size (size X conf.cur_bunch_size). It is stored at an FloatGPUMirroredMemoryBlock object. Each component is a sum of error derivatives that comes from the output layer neurons to the current neuron.
size an unsigned int parameter indicating the number of neurons.
conf an ANNConfiguration reference which stores some global parameters as: current bunch size, maximum bunch size, use_cuda global flag, ...
use_cuda a boolean flag indicating the use of CPU computation or GPU computation (using CUDA). Overrides the configuration stored at conf parameter.
Implements ANN::ActivationFunction.
References doMultiplyLogisticDerivatives(), and ANNConfiguration::error_function_logistic_mandatory.
Member Data Documentation
FloatGPUMirroredMemoryBlock * ANN::SoftmaxActivationFunction::maximums private
Only with use_cuda=true, for map-reduce process.
Referenced by applyActivation(), and ~SoftmaxActivationFunction().
FloatGPUMirroredMemoryBlock* ANN::SoftmaxActivationFunction::minimums private
Only with use_cuda=true, for map-reduce process.
Referenced by applyActivation(), and ~SoftmaxActivationFunction().
unsigned int ANN::SoftmaxActivationFunction::size private
If use_cuda=true, this is the size of the ActivationUnits.
Referenced by applyActivation().
FloatGPUMirroredMemoryBlock * ANN::SoftmaxActivationFunction::sums private
Only with use_cuda=true, for map-reduce process.
Referenced by applyActivation(), and ~SoftmaxActivationFunction().