april-ann
Image< T > Class Template Reference
Image
Public Member Functions
Image (Matrix< T > *mat)
Image (Matrix< T > *mat, int width, int height, int offset_w, int offset_h)
Image (int width, int height, T value=T())
Image (Image &other)
virtual ~Image ()
T & operator() (int x, int y)
T operator() (int x, int y) const
T getpixel (int x, int y, T default_value) const
T getpixel_bilinear (float x, float y, T default_value) const
int matrix_width () const
int matrix_height () const
int offset_width () const
int offset_height () const
Image< T > * clone () const
Image< T > * crop (int width, int height, int offset_w, int offset_h) const
Image< T > * clone_subimage (int width, int height, int offset_w, int offset_h, T default_color) const
Image< T > * crop_with_padding (int width, int height, int offset_w, int offset_h, T default_color) const
void projection_v (T *v) const
void projection_v (Matrix< T > **m) const
void projection_h (T *v) const
void projection_h (Matrix< T > **m) const
Image< T > * shear_h (double radians, T default_color) const
void shear_h_inplace (double radians, T default_color)
void min_bounding_box (float threshold, int *w, int *h, int *x, int *y) const
void copy (const Image< T > *src, int dst_x, int dst_y)
Image< T > * rotate90_cw () const
Image< T > * rotate90_ccw () const
Image< T > * resize (int dst_width, int dst_height) const
Image< T > * invert_colors () const
Image< T > * convolution5x5 (float *k, T default_color=T()) const
Image< T > * affine_transform (AffineTransform2D *trans, T default_value, int *offset_x=0, int *offset_y=0) const
Image< T > * remove_blank_columns () const
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Public Attributes
Matrix< T > * matrix
int offset
int width
int height
Private Member Functions
void invert_affine_matrix (float c[6], float dest[6]) const
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Member Function Documentation
template<typename T> T Image< T >::getpixel (int x, int y, T default_value) const inline
Referenced by Image< T >::getpixel_bilinear().
template<typename T> T Image< T >::getpixel_bilinear (float x, float y, T default_value) const inline
References Image< T >::getpixel().
template<typename T> int Image< T >::matrix_height () const inline
References Image< T >::matrix.
template<typename T> int Image< T >::matrix_width () const inline
References Image< T >::matrix.
Referenced by Image< T >::offset_height(), Image< T >::offset_width(), and Image< T >::operator()().
template<typename T> int Image< T >::offset_height () const inline
References Image< T >::matrix_width(), and Image< T >::offset.
template<typename T> int Image< T >::offset_width () const inline
References Image< T >::matrix_width(), and Image< T >::offset.
template<typename T> T& Image< T >::operator() (int x, int y) inline
References Image< T >::matrix, Image< T >::matrix_width(), and Image< T >::offset.
template<typename T> T Image< T >::operator() (int x, int y) const inline
References Image< T >::matrix, Image< T >::matrix_width(), and Image< T >::offset.
Member Data Documentation
template<typename T> int Image< T >::height
Referenced by Image< T >::copy(), grayscale_to_RGB(), Image< T >::Image(), RGB_to_grayscale(), and LibPNG::writePNG().
template<typename T> Matrix<T>* Image< T >::matrix
Referenced by Image< T >::Image(), Image< T >::matrix_height(), Image< T >::matrix_width(), and Image< T >::operator()().
template<typename T> int Image< T >::offset
Referenced by Image< T >::Image(), Image< T >::offset_height(), Image< T >::offset_width(), and Image< T >::operator()().
template<typename T> int Image< T >::width
Referenced by Image< T >::copy(), grayscale_to_RGB(), Image< T >::Image(), RGB_to_grayscale(), and LibPNG::writePNG().