april-ann
ANN::ErrorFunction Class Reference
Public Member Functions
virtual ~ErrorFunction ()
virtual void computePatternErrorFunction (FloatGPUMirroredMemoryBlock *output, FloatGPUMirroredMemoryBlock *target_output, FloatGPUMirroredMemoryBlock *output_error, FloatGPUMirroredMemoryBlock *pattern_errors, unsigned int output_size, const ANNConfiguration &conf)=0
virtual float computeBatchErrorFunction (float error_sums, unsigned int num_patterns)=0
virtual ErrorFunction * clone ()=0
virtual bool logisticMandatory () const =0
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Constructor & Destructor Documentation
virtual ANN::ErrorFunction::~ErrorFunction () inline virtual
Member Function Documentation
virtual ErrorFunction* ANN::ErrorFunction::clone () pure virtual
Implemented in ANN::FullLogisticCrossEntropy, ANN::FullCrossEntropy, ANN::LocalFMeasure, ANN::LogisticCrossEntropy, ANN::CrossEntropy, ANN::Tanh, and ANN::MSE.
Referenced by ANN::AllAllMLP::clone(), and ANN::MLP::clone().
virtual float ANN::ErrorFunction::computeBatchErrorFunction (float error_sums, unsigned int num_patterns) pure virtual
Implemented in ANN::FullLogisticCrossEntropy, ANN::FullCrossEntropy, ANN::LocalFMeasure, ANN::LogisticCrossEntropy, ANN::CrossEntropy, ANN::Tanh, and ANN::MSE.
Referenced by ANN::MLP::endTrainingBatch(), and ANN::MLP::endValidateBatch().
virtual void ANN::ErrorFunction::computePatternErrorFunction (FloatGPUMirroredMemoryBlock * output, FloatGPUMirroredMemoryBlock * target_output, FloatGPUMirroredMemoryBlock * output_error, FloatGPUMirroredMemoryBlock * pattern_errors, unsigned int output_size, const ANNConfiguration & conf) pure virtual
Implemented in ANN::FullLogisticCrossEntropy, ANN::FullCrossEntropy, ANN::LocalFMeasure, ANN::LogisticCrossEntropy, ANN::CrossEntropy, ANN::Tanh, and ANN::MSE.
Referenced by ANN::MLP::doTraining(), ANN::MLP::endValidateBatch(), and ANN::MLP::validatePattern().
virtual bool ANN::ErrorFunction::logisticMandatory () const pure virtual
Implemented in ANN::FullLogisticCrossEntropy, ANN::FullCrossEntropy, ANN::LocalFMeasure, ANN::LogisticCrossEntropy, ANN::CrossEntropy, ANN::Tanh, and ANN::MSE.
Referenced by ANN::MLP::setErrorFunction().