april-ann
ANN::ActivationFunctionANNComponent Class Reference abstract
Public Member Functions
ActivationFunctionANNComponent (const char *name=0)
virtual ~ActivationFunctionANNComponent ()
virtual Token * getInput ()
virtual Token * getOutput ()
virtual Token * getErrorInput ()
virtual Token * getErrorOutput ()
virtual Token * doForward (Token *input, bool during_training)
virtual Token * doBackprop (Token *input_error)
virtual void reset ()
virtual void setOption (const char *name, double value)
Virtual method for setting the value of a training parameter.
virtual bool hasOption (const char *name)
virtual double getOption (const char *name)
virtual void build (unsigned int _input_size, unsigned int _output_size, hash< string, Connections * > &weights_dict, hash< string, ANNComponent * > &components_dict)
Public Member Functions inherited from ANN::ANNComponent
ANNComponent (const char *name=0, const char *weights_name=0, unsigned int input_size=0, unsigned int output_size=0)
virtual ~ANNComponent ()
const string & getName () const
const string & getWeightsName () const
bool hasWeightsName () const
bool getIsBuilt () const
void generateDefaultWeightsName (string &dest, const char *prefix=0)
unsigned int getInputSize () const
unsigned int getOutputSize () const
virtual void doUpdate ()
virtual void computeAllGradients (hash< string, MatrixFloat * > &weight_grads_dict)
virtual ANNComponent * clone ()
virtual void setUseCuda (bool v)
bool getUseCuda () const
virtual void copyWeights (hash< string, Connections * > &weights_dict)
Abstract method to retrieve Connections objects from ANNComponents.
virtual void copyComponents (hash< string, ANNComponent * > &components_dict)
virtual void resetConnections ()
virtual void debugInfo ()
virtual ANNComponent * getComponent (string &name)
virtual char * toLuaString ()
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Protected Member Functions
virtual void applyActivation (FloatGPUMirroredMemoryBlock *input_units, FloatGPUMirroredMemoryBlock *output_units, unsigned int size, unsigned int bunch_size)=0
virtual void multiplyDerivatives (FloatGPUMirroredMemoryBlock *input_units, FloatGPUMirroredMemoryBlock *output_units, FloatGPUMirroredMemoryBlock *input_errors, FloatGPUMirroredMemoryBlock *output_errors, unsigned int size, unsigned int bunch_size)=0
Protected Member Functions inherited from ANN::ANNComponent
virtual void computeGradients (MatrixFloat *&weight_grads)
Private Attributes
TokenMatrixFloat * input
TokenMatrixFloat * output
TokenMatrixFloat * error_input
TokenMatrixFloat * error_output
float dropout_factor
FloatGPUMirroredMemoryBlock * dropout_mask
int * units_order_permutation
Static Private Attributes
static MTRand dropout_random = MTRand()
static int dropout_seed = -1
Additional Inherited Members
Protected Attributes inherited from ANN::ANNComponent
string name
string weights_name
unsigned int input_size
unsigned int output_size
bool use_cuda
Static Protected Attributes inherited from ANN::ANNComponent
static unsigned int next_name_id = 1
static unsigned int next_weights_id = 1
Detailed Description
An abstract class that defines the basic interface that the anncomponents must fulfill.
Constructor & Destructor Documentation
ANN::ActivationFunctionANNComponent::ActivationFunctionANNComponent (const char * name = 0)
ANN::ActivationFunctionANNComponent::~ActivationFunctionANNComponent () virtual
References DecRef, dropout_mask, error_input, error_output, input, and output.
Member Function Documentation
virtual void ANN::ActivationFunctionANNComponent::applyActivation (FloatGPUMirroredMemoryBlock * input_units, FloatGPUMirroredMemoryBlock * output_units, unsigned int size, unsigned int bunch_size) protected pure virtual
Implemented in ANN::LogLogisticActfANNComponent, ANN::LogSoftmaxActfANNComponent, ANN::LogisticActfANNComponent, ANN::SoftmaxActfANNComponent, ANN::SoftplusActfANNComponent, ANN::SoftsignActfANNComponent, ANN::TanhActfANNComponent, ANN::HardtanhActfANNComponent, ANN::LinearActfANNComponent, and ANN::SinActfANNComponent.
Referenced by doForward().
void ANN::ActivationFunctionANNComponent::build (unsigned int _input_size, unsigned int _output_size, hash< string, Connections * > & weights_dict, hash< string, ANNComponent * > & components_dict) virtual
Abstract method to finish building of component hierarchy and set weights objects pointers. All childs which rewrite this method must call parent method before do anything.
Reimplemented from ANN::ANNComponent.
References ANN::ANNComponent::build(), april_utils::string::c_str(), ERROR_EXIT3, ANN::ANNComponent::input_size, ANN::ANNComponent::name, and ANN::ANNComponent::output_size.
Token * ANN::ActivationFunctionANNComponent::doBackprop (Token * input_error) virtual
Virtual method that back-propagates error derivatives and computes other useful stuff. Receives input error gradients, and returns its output error gradients Token.
Reimplemented from ANN::ANNComponent.
References applyMask(), AssignRef, april_utils::string::c_str(), Matrix< T >::clone(), Matrix< T >::cloneOnlyDims(), Token::convertTo(), dropout_factor, dropout_mask, ERROR_EXIT1, error_input, error_output, Matrix< T >::getDimSize(), Matrix< T >::getIsContiguous(), Matrix< T >::getMajorOrder(), TokenMatrix< T >::getMatrix(), Matrix< T >::getNumDim(), Matrix< T >::getRawDataAccess(), Token::getTokenCode(), input, multiplyDerivatives(), ANN::ANNComponent::name, output, Matrix< T >::rewrap(), Matrix< T >::sameDim(), Matrix< T >::setUseCuda(), Matrix< T >::size(), table_of_token_codes::token_matrix, and ANN::ANNComponent::use_cuda.
Token * ANN::ActivationFunctionANNComponent::doForward (Token * input, bool during_training) virtual
Virtual method that executes the set of operations required for each block of connections when performing the forward step of the Backpropagation algorithm, and returns its output Token
Reimplemented from ANN::ANNComponent.
References applyActivation(), applyMask(), AssignRef, april_utils::string::c_str(), Matrix< T >::clone(), Matrix< T >::cloneOnlyDims(), Token::convertTo(), dropout_factor, dropout_mask, dropout_random, ERROR_EXIT1, Matrix< T >::getDimSize(), Matrix< T >::getIsContiguous(), Matrix< T >::getMajorOrder(), TokenMatrix< T >::getMatrix(), Matrix< T >::getNumDim(), GPUMirroredMemoryBlock< T >::getPPALForWrite(), Matrix< T >::getRawDataAccess(), GPUMirroredMemoryBlock< T >::getSize(), Token::getTokenCode(), input, ANN::ANNComponent::name, output, MTRand::rand(), Matrix< T >::rewrap(), Matrix< T >::scal(), Matrix< T >::setUseCuda(), Matrix< T >::size(), table_of_token_codes::token_matrix, and ANN::ANNComponent::use_cuda.
virtual Token* ANN::ActivationFunctionANNComponent::getErrorInput () inline virtual
Reimplemented from ANN::ANNComponent.
References error_input.
virtual Token* ANN::ActivationFunctionANNComponent::getErrorOutput () inline virtual
Reimplemented from ANN::ANNComponent.
References error_output.
virtual Token* ANN::ActivationFunctionANNComponent::getInput () inline virtual
Reimplemented from ANN::ANNComponent.
References input.
double ANN::ActivationFunctionANNComponent::getOption (const char * name) virtual
Virtual method for getting the value of a training parameter. All childs which rewrite this method must call parent method after their process, if the looked option is not found to show the error message.
Reimplemented from ANN::ANNComponent.
References dropout_factor, DROPOUT_FACTOR_STRING, dropout_seed, DROPOUT_SEED_STRING, ANN::ANNComponent::getOption(), and mGetOption.
Referenced by ANN::HardtanhActfANNComponent::clone(), ANN::LinearActfANNComponent::clone(), ANN::SinActfANNComponent::clone(), ANN::SoftplusActfANNComponent::clone(), ANN::SoftmaxActfANNComponent::clone(), ANN::LogLogisticActfANNComponent::clone(), ANN::LogisticActfANNComponent::clone(), ANN::LogSoftmaxActfANNComponent::clone(), ANN::SoftsignActfANNComponent::clone(), and ANN::TanhActfANNComponent::clone().
virtual Token* ANN::ActivationFunctionANNComponent::getOutput () inline virtual
Reimplemented from ANN::ANNComponent.
References output.
bool ANN::ActivationFunctionANNComponent::hasOption (const char * name) virtual
Virtual method for determining if a training parameter is being used or can be used within the network.
Reimplemented from ANN::ANNComponent.
References DROPOUT_FACTOR_STRING, DROPOUT_SEED_STRING, and mHasOption.
virtual void ANN::ActivationFunctionANNComponent::multiplyDerivatives (FloatGPUMirroredMemoryBlock * input_units, FloatGPUMirroredMemoryBlock * output_units, FloatGPUMirroredMemoryBlock * input_errors, FloatGPUMirroredMemoryBlock * output_errors, unsigned int size, unsigned int bunch_size) protected pure virtual
Implemented in ANN::LogLogisticActfANNComponent, ANN::LogSoftmaxActfANNComponent, ANN::LogisticActfANNComponent, ANN::SoftmaxActfANNComponent, ANN::SoftplusActfANNComponent, ANN::SoftsignActfANNComponent, ANN::TanhActfANNComponent, ANN::HardtanhActfANNComponent, ANN::LinearActfANNComponent, and ANN::SinActfANNComponent.
Referenced by doBackprop().
void ANN::ActivationFunctionANNComponent::reset () virtual
Virtual method to reset to zero gradients and outputs (inputs are not reseted)
Reimplemented from ANN::ANNComponent.
References DecRef, dropout_mask, error_input, error_output, input, and output.
void ANN::ActivationFunctionANNComponent::setOption (const char * name, double value) virtual
Virtual method for setting the value of a training parameter.
Reimplemented from ANN::ANNComponent.
References dropout_factor, DROPOUT_FACTOR_STRING, dropout_random, dropout_seed, DROPOUT_SEED_STRING, mSetOption, and ANN::ANNComponent::setOption().
Referenced by ANN::HardtanhActfANNComponent::clone(), ANN::LinearActfANNComponent::clone(), ANN::SinActfANNComponent::clone(), ANN::SoftplusActfANNComponent::clone(), ANN::SoftmaxActfANNComponent::clone(), ANN::LogLogisticActfANNComponent::clone(), ANN::LogisticActfANNComponent::clone(), ANN::LogSoftmaxActfANNComponent::clone(), ANN::SoftsignActfANNComponent::clone(), and ANN::TanhActfANNComponent::clone().
Member Data Documentation
float ANN::ActivationFunctionANNComponent::dropout_factor private
Referenced by doBackprop(), doForward(), getOption(), and setOption().
FloatGPUMirroredMemoryBlock* ANN::ActivationFunctionANNComponent::dropout_mask private
Referenced by doBackprop(), doForward(), reset(), and ~ActivationFunctionANNComponent().
MTRand ANN::ActivationFunctionANNComponent::dropout_random = MTRand() static private
Referenced by doForward(), and setOption().
int ANN::ActivationFunctionANNComponent::dropout_seed = -1 static private
Referenced by getOption(), and setOption().
TokenMatrixFloat * ANN::ActivationFunctionANNComponent::error_input private
Referenced by doBackprop(), getErrorInput(), reset(), and ~ActivationFunctionANNComponent().
TokenMatrixFloat * ANN::ActivationFunctionANNComponent::error_output private
Referenced by doBackprop(), getErrorOutput(), reset(), and ~ActivationFunctionANNComponent().
TokenMatrixFloat* ANN::ActivationFunctionANNComponent::input private
Referenced by doBackprop(), doForward(), getInput(), reset(), and ~ActivationFunctionANNComponent().
TokenMatrixFloat * ANN::ActivationFunctionANNComponent::output private
Referenced by doBackprop(), doForward(), getOutput(), reset(), and ~ActivationFunctionANNComponent().
int* ANN::ActivationFunctionANNComponent::units_order_permutation private