april-ann
TokenMemoryBlock Class Reference
Tokens
Public Member Functions
TokenMemoryBlock ()
TokenMemoryBlock (unsigned int size)
~TokenMemoryBlock ()
void setData (float *data, unsigned int size)
FloatGPUMirroredMemoryBlock * getMemBlock ()
unsigned int getUsedSize () const
unsigned int getMaxSize () const
void resize (unsigned int size)
Token * clone () const
This method implements a deep copy.
buffer_list * toString ()
Abstract method for serialization purposes.
buffer_list * debugString (const char *prefix, int debugLevel)
FOR DEBUG PURPOSES.
TokenCode getTokenCode () const
Abstract method which indicates the TokenCode of child Token classes.
void clear ()
bool getCudaFlag ()
void printDebug ()
void setToZero (bool use_cuda)
Public Member Functions inherited from Token
Token ()
virtual ~Token ()
template<typename T >
bool isA () const
template<typename T >
T convertTo ()
template<typename T >
const T convertTo () const
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Static Public Member Functions
static Token * fromString (constString &cs)
Private Attributes
FloatGPUMirroredMemoryBlock * mem_block
unsigned int used_size
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Member Function Documentation
void TokenMemoryBlock::clear () inline
References used_size.
static Token* TokenMemoryBlock::fromString (constString & cs) inline static
bool TokenMemoryBlock::getCudaFlag () inline
References GPUMirroredMemoryBlock< T >::getCudaFlag(), and mem_block.
Referenced by ANN::MSELossFunction::addLoss(), ANN::MultiClassCrossEntropyLossFunction::addLoss(), ANN::CrossEntropyLossFunction::addLoss(), ANN::LocalFMeasureLossFunction::addLoss(), ANN::MSELossFunction::computeGradient(), ANN::MultiClassCrossEntropyLossFunction::computeGradient(), ANN::CrossEntropyLossFunction::computeGradient(), ANN::LocalFMeasureLossFunction::computeGradient(), DataSetTokenVector::getPatternBunch(), and UnionDataSetToken::getPatternBunch().
unsigned int TokenMemoryBlock::getMaxSize () const inline
References GPUMirroredMemoryBlock< T >::getSize(), and mem_block.
FloatGPUMirroredMemoryBlock* TokenMemoryBlock::getMemBlock () inline
References mem_block.
Referenced by ANN::MSELossFunction::addLoss(), ANN::MultiClassCrossEntropyLossFunction::addLoss(), ANN::CrossEntropyLossFunction::addLoss(), ANN::LocalFMeasureLossFunction::addLoss(), ANN::JoinANNComponent::buildErrorInputBunchVector(), ANN::JoinANNComponent::buildInputBunchVector(), ANN::JoinANNComponent::buildMemoryBlockToken(), ANN::DotProductANNComponent::computeBPUpdateOnPrevVectors(), ANN::MSELossFunction::computeGradient(), ANN::MultiClassCrossEntropyLossFunction::computeGradient(), ANN::CrossEntropyLossFunction::computeGradient(), ANN::LocalFMeasureLossFunction::computeGradient(), ANN::CopyANNComponent::doBackprop(), ANN::ActivationFunctionANNComponent::doBackprop(), ANN::DotProductANNComponent::doBackprop(), ANN::BiasANNComponent::doForward(), ANN::ActivationFunctionANNComponent::doForward(), ANN::DotProductANNComponent::doForward(), ANN::BiasANNComponent::doUpdate(), ANN::DotProductANNComponent::doUpdate(), DataSetFloat2TokenWrapper::getPattern(), DataSetTokenVector::getPatternBunch(), UnionDataSetToken::getPatternBunch(), DataSetFloat2TokenWrapper::getPatternBunch(), DataSetFloat2TokenWrapper::putPattern(), and DataSetFloat2TokenWrapper::putPatternBunch().
unsigned int TokenMemoryBlock::getUsedSize () const inline
References used_size.
Referenced by ANN::MSELossFunction::addLoss(), ANN::MultiClassCrossEntropyLossFunction::addLoss(), ANN::CrossEntropyLossFunction::addLoss(), ANN::LocalFMeasureLossFunction::addLoss(), ANN::JoinANNComponent::buildErrorInputBunchVector(), ANN::JoinANNComponent::buildInputBunchVector(), ANN::JoinANNComponent::buildMemoryBlockToken(), ANN::MSELossFunction::computeGradient(), ANN::MultiClassCrossEntropyLossFunction::computeGradient(), ANN::CrossEntropyLossFunction::computeGradient(), ANN::LocalFMeasureLossFunction::computeGradient(), ANN::CopyANNComponent::doBackprop(), ANN::ActivationFunctionANNComponent::doBackprop(), ANN::DotProductANNComponent::doBackprop(), ANN::BiasANNComponent::doForward(), ANN::ActivationFunctionANNComponent::doForward(), and ANN::DotProductANNComponent::doForward().
void TokenMemoryBlock::printDebug () inline
References GPUMirroredMemoryBlock< T >::getPPALForRead(), mem_block, and used_size.
Member Data Documentation
FloatGPUMirroredMemoryBlock* TokenMemoryBlock::mem_block private
Referenced by clone(), getCudaFlag(), getMaxSize(), getMemBlock(), printDebug(), resize(), setData(), setToZero(), and ~TokenMemoryBlock().
unsigned int TokenMemoryBlock::used_size private
Referenced by clear(), clone(), getUsedSize(), printDebug(), and resize().