april-ann
ANN::BinarySamplingActivationFunction Class Reference
Public Member Functions
BinarySamplingActivationFunction (MTRand *the_rand)
virtual ~BinarySamplingActivationFunction ()
void applyActivation (FloatGPUMirroredMemoryBlock *units, unsigned int units_size, const ANNConfiguration &conf, bool use_cuda)
Abstract method that activates a "bunch" of units (or neurons).
ActivationFunction * clone ()
Returns a deep copy of the object.
void randomize (FloatGPUMirroredMemoryBlock *units, unsigned int size, const ANNConfiguration &conf, bool use_cuda)
An abstract method for apply the stochastic process over all neurons.
Public Member Functions inherited from ANN::StochasticActivationFunction
StochasticActivationFunction (MTRand *the_rand)
A constructor.
virtual ~StochasticActivationFunction ()
void multiplyDerivatives (FloatGPUMirroredMemoryBlock *units, FloatGPUMirroredMemoryBlock *input_errors, unsigned int size, const ANNConfiguration &conf, bool use_cuda, bool is_output)
An abstract method for compute derivatives of stochastic activation functions.
Public Member Functions inherited from ANN::ActivationFunction
virtual ~ActivationFunction ()
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Additional Inherited Members
Protected Member Functions inherited from ANN::StochasticActivationFunction
float sampleOne (float v)
A method that samples 1.0 or 0.0 with probability v.
Protected Attributes inherited from ANN::StochasticActivationFunction
MTRand * the_rand
A pseudo-random generator object for the stochastic process.
Detailed Description
A binary sampling activation function. Implements ActivationFunction interface. This is an special activation function that works on stochastic graphical models as Restricted Boltzmann Machines.
Constructor & Destructor Documentation
ANN::BinarySamplingActivationFunction::BinarySamplingActivationFunction (MTRand * the_rand)
Referenced by clone().
ANN::BinarySamplingActivationFunction::~BinarySamplingActivationFunction () virtual
Member Function Documentation
void ANN::BinarySamplingActivationFunction::applyActivation (FloatGPUMirroredMemoryBlock * units, unsigned int units_size, const ANNConfiguration & conf, bool use_cuda) virtual
Abstract method that activates a "bunch" of units (or neurons).
Abstract method that takes the input neuron potentials and computes the activation:
being the activation of neuron , depending on its potential and the other neurons potentials.
Parameters
units an input matrix of size (size X conf.cur_bunch_size). It is stored at an FloatGPUMirroredMemoryBlock object, Each component is a neuron activation.
units_size the number of neurons.
conf a reference to an ANNConfiguration struct which contains global parameters as: current bunch size, maximum bunch size, use_cuda global flag,
use_cuda a boolean parameter that indicates the use of CPU computation or GPU computation (using CUDA). Overrides the configuration stored at conf parameter.
Implements ANN::ActivationFunction.
References ANNConfiguration::cur_bunch_size, ERROR_PRINT, GPUMirroredMemoryBlock< T >::getPPALForReadAndWrite(), ANNConfiguration::max_bunch_size, ANN::StochasticActivationFunction::sampleOne(), and sigmoid.
ActivationFunction * ANN::BinarySamplingActivationFunction::clone () virtual
Returns a deep copy of the object.
Implements ANN::ActivationFunction.
References BinarySamplingActivationFunction(), IncRef, and ANN::StochasticActivationFunction::the_rand.
void ANN::BinarySamplingActivationFunction::randomize (FloatGPUMirroredMemoryBlock * units, unsigned int size, const ANNConfiguration & conf, bool use_cuda) virtual
An abstract method for apply the stochastic process over all neurons.
Parameters
units a memory matrix of size (size X bunch_size), represented in a FloatGPUMirroredMemoryBlock object. Its values are the neuron probabilities of being 1.0.
size an unsigned int parameter indicating the number of neurons on the corresponding layer.
bunch_size an unsigned int parameter indicating the number of layers. Each layer is composed by size neurons, and each layer comes from the computation of the forward of a different input pattern.
use_cuda a boolean parameter to switch between CPU computation or GPU computation (using CUDA).
Implements ANN::StochasticActivationFunction.
References ANNConfiguration::cur_bunch_size, GPUMirroredMemoryBlock< T >::getPPALForReadAndWrite(), ANNConfiguration::max_bunch_size, MTRand::rand(), and ANN::StochasticActivationFunction::the_rand.