april-ann
ANN::LocalFMeasureLossFunction Class Reference
Public Member Functions
LocalFMeasureLossFunction (unsigned int size, float beta=1.0f, bool complement_output=false)
virtual ~LocalFMeasureLossFunction ()
virtual float addLoss (Token *input, Token *target)
virtual Token * computeGradient (Token *input, Token *target)
virtual float getAccumLoss ()
virtual void reset ()
virtual LossFunction * clone ()
Public Member Functions inherited from ANN::LossFunction
LossFunction (unsigned int size)
virtual ~LossFunction ()
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Member Functions
LocalFMeasureLossFunction (unsigned int size, float beta, float Gab, float Hab, bool complement_output, float accumulated_loss, unsigned int N)
Private Attributes
float beta
float Gab
float Hab
bool complement_output
float accumulated_loss
unsigned int N
Additional Inherited Members
Protected Member Functions inherited from ANN::LossFunction
void throwErrorAndGetMatrixFromTokens (Token *input, Token *target, MatrixFloat *&input_mat, MatrixFloat *&target_mat) const
Protected Attributes inherited from ANN::LossFunction
Token * error_output
unsigned int size
Constructor & Destructor Documentation
ANN::LocalFMeasureLossFunction::LocalFMeasureLossFunction (unsigned int size, float beta, float Gab, float Hab, bool complement_output, float accumulated_loss, unsigned int N) inline private
Referenced by clone().
ANN::LocalFMeasureLossFunction::LocalFMeasureLossFunction (unsigned int size, float beta = 1.0f, bool complement_output = false)
ANN::LocalFMeasureLossFunction::~LocalFMeasureLossFunction () virtual
Member Function Documentation
float ANN::LocalFMeasureLossFunction::addLoss (Token * input, Token * target) virtual
Implements ANN::LossFunction.
References accumulated_loss, beta, complement_output, doLocalFMeasureLossFunction(), Gab, Matrix< T >::getCudaFlag(), Matrix< T >::getDimSize(), Matrix< T >::getRawDataAccess(), Hab, N, and ANN::LossFunction::throwErrorAndGetMatrixFromTokens().
virtual LossFunction* ANN::LocalFMeasureLossFunction::clone () inline virtual
Implements ANN::LossFunction.
References accumulated_loss, beta, complement_output, Gab, Hab, LocalFMeasureLossFunction(), N, and ANN::LossFunction::size.
Token * ANN::LocalFMeasureLossFunction::computeGradient (Token * input, Token * target) virtual
Implements ANN::LossFunction.
References AssignRef, beta, Matrix< T >::cloneOnlyDims(), complement_output, doComputeLocalFMeasureGradient(), ANN::LossFunction::error_output, Gab, Matrix< T >::getCudaFlag(), Matrix< T >::getDimSize(), Matrix< T >::getRawDataAccess(), Hab, and ANN::LossFunction::throwErrorAndGetMatrixFromTokens().
float ANN::LocalFMeasureLossFunction::getAccumLoss () virtual
Implements ANN::LossFunction.
References accumulated_loss, and N.
void ANN::LocalFMeasureLossFunction::reset () virtual
Reimplemented from ANN::LossFunction.
References accumulated_loss, N, and ANN::LossFunction::reset().
Member Data Documentation
float ANN::LocalFMeasureLossFunction::accumulated_loss private
Referenced by addLoss(), clone(), getAccumLoss(), and reset().
float ANN::LocalFMeasureLossFunction::beta private
Referenced by addLoss(), clone(), and computeGradient().
bool ANN::LocalFMeasureLossFunction::complement_output private
Referenced by addLoss(), clone(), and computeGradient().
float ANN::LocalFMeasureLossFunction::Gab private
Referenced by addLoss(), clone(), and computeGradient().
float ANN::LocalFMeasureLossFunction::Hab private
Referenced by addLoss(), clone(), and computeGradient().
unsigned int ANN::LocalFMeasureLossFunction::N private
Referenced by addLoss(), clone(), getAccumLoss(), and reset().