april-ann
ANN::FullLogisticCrossEntropy Class Reference
Public Member Functions
FullLogisticCrossEntropy ()
virtual ~FullLogisticCrossEntropy ()
void computePatternErrorFunction (FloatGPUMirroredMemoryBlock *output, FloatGPUMirroredMemoryBlock *target_output, FloatGPUMirroredMemoryBlock *output_error, FloatGPUMirroredMemoryBlock *pattern_errors, unsigned int output_size, const ANNConfiguration &conf)
float computeBatchErrorFunction (float error_sums, unsigned int num_patterns)
ErrorFunction * clone ()
bool logisticMandatory () const
Public Member Functions inherited from ANN::ErrorFunction
virtual ~ErrorFunction ()
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Attributes
const float EPSILON
const float INF
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Constructor & Destructor Documentation
ANN::FullLogisticCrossEntropy::FullLogisticCrossEntropy ()
Referenced by clone().
virtual ANN::FullLogisticCrossEntropy::~FullLogisticCrossEntropy () inline virtual
Member Function Documentation
ErrorFunction* ANN::FullLogisticCrossEntropy::clone () inline virtual
Implements ANN::ErrorFunction.
References FullLogisticCrossEntropy().
float ANN::FullLogisticCrossEntropy::computeBatchErrorFunction (float error_sums, unsigned int num_patterns) virtual
Implements ANN::ErrorFunction.
void ANN::FullLogisticCrossEntropy::computePatternErrorFunction (FloatGPUMirroredMemoryBlock * output, FloatGPUMirroredMemoryBlock * target_output, FloatGPUMirroredMemoryBlock * output_error, FloatGPUMirroredMemoryBlock * pattern_errors, unsigned int output_size, const ANNConfiguration & conf) virtual
Implements ANN::ErrorFunction.
References ANNConfiguration::cur_bunch_size, doCalculateFullLogisticCrossEntropyErrorFunction(), EPSILON, INF, and ANNConfiguration::use_cuda_flag.
bool ANN::FullLogisticCrossEntropy::logisticMandatory () const inline virtual
Implements ANN::ErrorFunction.
Member Data Documentation
const float ANN::FullLogisticCrossEntropy::EPSILON private
Referenced by computePatternErrorFunction().
const float ANN::FullLogisticCrossEntropy::INF private
Referenced by computePatternErrorFunction().