april-ann
ANN::MLP Class Reference
Public Member Functions
MLP (ANNConfiguration conf)
~MLP ()
void setErrorFunction (ErrorFunction *error_func)
void setOption (const char *name, double value)
bool hasOption (const char *name)
double getOption (const char *name)
virtual void loadModel (const char *filename)
virtual void saveModel (const char *filename)
void showNetworkAtts ()
void doForward ()
void doBackward ()
void showActivations ()
void showWeights ()
MLP * clone ()
virtual void randomizeWeights (MTRand *rnd, float low, float high, bool use_fanin)
void pushBackAllAllLayer (ActivationUnits *inputs, ActivationUnits *outputs, ActivationFunction *actf, Connections **weights, bool transpose_weights, bool has_bias, Connections **bias)
Public Member Functions inherited from ANN::ANNBase
virtual ~ANNBase ()
void registerActivationUnits (ActivationUnits *actu)
void registerConnections (Connections *conn)
void registerAction (Action *action)
void registerInput (ActivationUnits *actu)
void registerOutput (ActivationUnits *actu)
void releaseOutput ()
This method converts output neurons into hidden neurons, and it sets output to zero.
unsigned int getInputSize () const
It returns the input (or domain) size of the function.
unsigned int getOutputSize () const
It returns the output (or range) size of the function.
unsigned int getLayerConnectionsSize () const
unsigned int getLayerActivationsSize () const
Connections * getLayerConnections (unsigned int layer)
ActivationUnits * getLayerActivations (unsigned int layer)
Action * getAction (unsigned int idx)
virtual void setInput (const float *input, unsigned int bunch_pos)
virtual void copyOutput (float *output, unsigned int bunch_pos)
virtual void setDesiredOutput (float *target_output, unsigned int bunch_pos)
void resetErrorVectors ()
void resetPatternErrorsAuxiliarVector ()
bool calculate (const float *input_vector, unsigned int input_size, float *output_vector, unsigned int output_size)
void calculateInPipeline (Functions::FloatDataProducer *producer, unsigned int input_size, Functions::FloatDataConsumer *consumer, unsigned int output_size)
const ANNConfiguration & getConfReference () const
ANNConfiguration getConf () const
void cloneTopologyTo (ANNBase *other)
void pruneSubnormalAndCheckNormal ()
virtual void setUseCuda (bool use_cuda, bool pinned)
virtual bool getUseCuda ()
float getMaxWeights () const
unsigned int getNumWeights () const
virtual unsigned int copyWeightsTo (MatrixFloat **data, MatrixFloat **old_data) const
Public Member Functions inherited from Trainable::TrainableSupervised
virtual ~TrainableSupervised ()
Functions::NS_function_io::type getInputType () const
It returns the data type of the input (or domain).
Functions::NS_function_io::type getOutputType () const
It returns the data type of the output (or range).
virtual float trainOnePattern (float *input, float *target_output)
virtual float validateOnePattern (float *input, float *target_output)
virtual float trainDataset (DataSetFloat *input_dataset, DataSetFloat *target_output_dataset, MTRand *shuffle=0)
virtual float trainDatasetWithReplacement (DataSetFloat *input_dataset, DataSetFloat *target_output_dataset, MTRand *shuffle, int replacement)
virtual float trainDatasetWithDistribution (int num_classes, DataSetFloat **input_datasets, DataSetFloat **target_output_datasets, double *aprioris, MTRand *shuffle, int replacement)
virtual float validateDataset (DataSetFloat *input_dataset, DataSetFloat *target_output_dataset)
virtual float validateDatasetWithReplacement (DataSetFloat *input_dataset, DataSetFloat *target_output_dataset, MTRand *shuffle, int replacement)
virtual void useDataset (DataSetFloat *input_dataset, DataSetFloat *output_dataset)
Public Member Functions inherited from Functions::FunctionInterface< I, O >
virtual ~FunctionInterface ()
virtual bool calculate (const I *input_vector, unsigned int input_size, O *output_vector, unsigned int output_size)=0
A new abstract method that computes output vector given input vector.
virtual void calculateInPipeline (DataProducer< I > *producer, unsigned int input_size, DataConsumer< O > *consumer, unsigned int output_size)
Method for flow computation of outputs in a pipeline system.
Public Member Functions inherited from Functions::FunctionBase
FunctionBase ()
virtual ~FunctionBase ()
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Protected Member Functions
void beginTrainingBatch ()
Entre begin y end va el conjunto de patrones de una epoca.
void trainPattern (float *input, float *target_output)
void doTraining ()
float endTrainingBatch ()
void beginValidateBatch ()
void validatePattern (float *input, float *target_output)
float endValidateBatch ()
Protected Member Functions inherited from ANN::ANNBase
ANNBase (ANNConfiguration configuration)
virtual void setNumBunch (unsigned int num_bunch)
virtual unsigned int getNumBunch ()
void clearTopology ()
float patternErrorsSum ()
Protected Attributes
unsigned int num_patterns_processed
unsigned int cur_bunch_pos
float learning_rate
float momentum
float weight_decay
float c_weight_decay
ErrorFunction * error_func
Protected Attributes inherited from ANN::ANNBase
ANNConfiguration conf
FloatGPUMirroredMemoryBlock * output_neurons
FloatGPUMirroredMemoryBlock * desired_output
FloatGPUMirroredMemoryBlock * output_errors
FloatGPUMirroredMemoryBlock * pattern_errors
unsigned int total_num_inputs
unsigned int total_num_outputs
vector< ActivationUnits * > inputs
vector< ActivationUnits * > activations
vector< Connections * > connections
vector< Action * > actions
Constructor & Destructor Documentation
ANN::MLP::MLP (ANNConfiguration conf)
References setErrorFunction().
Referenced by clone().
ANN::MLP::~MLP ()
References DecRef, and error_func.
Member Function Documentation
void ANN::MLP::beginTrainingBatch () protected virtual
Entre begin y end va el conjunto de patrones de una epoca.
Implements Trainable::TrainableSupervised.
References cur_bunch_pos, num_patterns_processed, and ANN::ANNBase::resetPatternErrorsAuxiliarVector().
void ANN::MLP::beginValidateBatch () protected virtual
Implements Trainable::TrainableSupervised.
References cur_bunch_pos, num_patterns_processed, and ANN::ANNBase::resetPatternErrorsAuxiliarVector().
MLP * ANN::MLP::clone ()
Reimplemented in ANN::AllAllMLP.
References c_weight_decay, ANN::ErrorFunction::clone(), ANN::ANNBase::cloneTopologyTo(), error_func, ANN::ANNBase::getConfReference(), learning_rate, MLP(), momentum, setErrorFunction(), and weight_decay.
void ANN::MLP::doBackward () virtual
Implements ANN::ANNBase.
References ANN::ANNBase::actions.
Referenced by doTraining().
void ANN::MLP::doForward () virtual
Implements ANN::ANNBase.
References ANN::ANNBase::actions.
Referenced by doTraining(), endValidateBatch(), and validatePattern().
void ANN::MLP::doTraining () protected
References ANN::ErrorFunction::computePatternErrorFunction(), ANN::ANNBase::conf, ANN::ANNBase::desired_output, doBackward(), doForward(), error_func, ANN::ANNBase::output_errors, ANN::ANNBase::output_neurons, ANN::ANNBase::pattern_errors, ANN::ANNBase::resetErrorVectors(), and ANN::ANNBase::total_num_outputs.
Referenced by endTrainingBatch(), and trainPattern().
float ANN::MLP::endTrainingBatch () protected virtual
Implements Trainable::TrainableSupervised.
References ANN::ErrorFunction::computeBatchErrorFunction(), ANN::ANNBase::conf, cur_bunch_pos, ANNConfiguration::cur_bunch_size, doTraining(), error_func, num_patterns_processed, ANN::ANNBase::patternErrorsSum(), and ANN::ANNBase::pruneSubnormalAndCheckNormal().
float ANN::MLP::endValidateBatch () protected virtual
Implements Trainable::TrainableSupervised.
References ANN::ErrorFunction::computeBatchErrorFunction(), ANN::ErrorFunction::computePatternErrorFunction(), ANN::ANNBase::conf, cur_bunch_pos, ANNConfiguration::cur_bunch_size, ANN::ANNBase::desired_output, doForward(), error_func, num_patterns_processed, ANN::ANNBase::output_errors, ANN::ANNBase::output_neurons, ANN::ANNBase::pattern_errors, ANN::ANNBase::patternErrorsSum(), and ANN::ANNBase::total_num_outputs.
double ANN::MLP::getOption (const char * name) virtual
Implements Trainable::TrainableSupervised.
References ERROR_EXIT, learning_rate, mGetOption, momentum, and weight_decay.
bool ANN::MLP::hasOption (const char * name) virtual
Implements Trainable::TrainableSupervised.
References mHasOption.
void ANN::MLP::loadModel (const char * filename) virtual
Implements Trainable::TrainableSupervised.
Reimplemented in ANN::AllAllMLP.
void ANN::MLP::pushBackAllAllLayer (ActivationUnits * inputs, ActivationUnits * outputs, ActivationFunction * actf, Connections ** weights, bool transpose_weights, bool has_bias, Connections ** bias)
References ANN::ANNBase::getConfReference(), ANN::ActivationUnits::numNeurons(), ANN::ANNBase::registerAction(), and ANN::ANNBase::registerConnections().
void ANN::MLP::randomizeWeights (MTRand * rnd, float low, float high, bool use_fanin) virtual
Reimplemented in ANN::AllAllMLP.
References ANN::ANNBase::actions, and ANN::ANNBase::connections.
void ANN::MLP::saveModel (const char * filename) virtual
Implements Trainable::TrainableSupervised.
Reimplemented in ANN::AllAllMLP.
void ANN::MLP::setErrorFunction (ErrorFunction * error_func)
References ANN::ANNBase::conf, DecRef, error_func, ANNConfiguration::error_function_logistic_mandatory, IncRef, and ANN::ErrorFunction::logisticMandatory().
Referenced by ANN::AllAllMLP::clone(), clone(), and MLP().
void ANN::MLP::setOption (const char * name, double value) virtual
Implements Trainable::TrainableSupervised.
References ANN::ANNBase::actions, c_weight_decay, ERROR_EXIT, learning_rate, momentum, mSetOption, and weight_decay.
void ANN::MLP::showActivations ()
References ANN::ANNBase::activations, ANN::ANNBase::conf, and ANNConfiguration::max_bunch_size.
void ANN::MLP::showNetworkAtts ()
void ANN::MLP::showWeights ()
References ANN::ANNBase::connections.
void ANN::MLP::trainPattern (float * input, float * target_output) protected virtual
Implements Trainable::TrainableSupervised.
References ANN::ANNBase::conf, cur_bunch_pos, ANNConfiguration::cur_bunch_size, doTraining(), num_patterns_processed, ANN::ANNBase::pruneSubnormalAndCheckNormal(), ANN::ANNBase::setDesiredOutput(), and ANN::ANNBase::setInput().
void ANN::MLP::validatePattern (float * input, float * target_output) protected virtual
Implements Trainable::TrainableSupervised.
References ANN::ErrorFunction::computePatternErrorFunction(), ANN::ANNBase::conf, cur_bunch_pos, ANNConfiguration::cur_bunch_size, ANN::ANNBase::desired_output, doForward(), error_func, num_patterns_processed, ANN::ANNBase::output_errors, ANN::ANNBase::output_neurons, ANN::ANNBase::pattern_errors, ANN::ANNBase::setDesiredOutput(), ANN::ANNBase::setInput(), and ANN::ANNBase::total_num_outputs.
Member Data Documentation
float ANN::MLP::c_weight_decay protected
Referenced by ANN::AllAllMLP::clone(), clone(), and setOption().
unsigned int ANN::MLP::cur_bunch_pos protected
Referenced by beginTrainingBatch(), beginValidateBatch(), endTrainingBatch(), endValidateBatch(), trainPattern(), and validatePattern().
ErrorFunction* ANN::MLP::error_func protected
Referenced by ANN::AllAllMLP::clone(), clone(), doTraining(), endTrainingBatch(), endValidateBatch(), setErrorFunction(), validatePattern(), and ~MLP().
float ANN::MLP::learning_rate protected
Referenced by ANN::AllAllMLP::clone(), clone(), getOption(), and setOption().
float ANN::MLP::momentum protected
Referenced by ANN::AllAllMLP::clone(), clone(), getOption(), and setOption().
unsigned int ANN::MLP::num_patterns_processed protected
Referenced by beginTrainingBatch(), beginValidateBatch(), endTrainingBatch(), endValidateBatch(), trainPattern(), and validatePattern().
float ANN::MLP::weight_decay protected
Referenced by ANN::AllAllMLP::clone(), clone(), getOption(), and setOption().