april-ann
ANN::JoinANNComponent Class Reference
Public Member Functions
JoinANNComponent (const char *name=0)
virtual ~JoinANNComponent ()
void addComponent (ANNComponent *component)
virtual Token * getInput ()
virtual Token * getOutput ()
virtual Token * getErrorInput ()
virtual Token * getErrorOutput ()
virtual Token * doForward (Token *input, bool during_training)
virtual Token * doBackprop (Token *input_error)
virtual void doUpdate ()
virtual void reset ()
virtual ANNComponent * clone ()
virtual void setUseCuda (bool v)
virtual void setOption (const char *name, double value)
Virtual method for setting the value of a training parameter.
virtual bool hasOption (const char *name)
virtual double getOption (const char *name)
virtual void build (unsigned int input_size, unsigned int output_size, hash< string, Connections * > &weights_dict, hash< string, ANNComponent * > &components_dict)
virtual void copyWeights (hash< string, Connections * > &weights_dict)
Abstract method to retrieve Connections objects from ANNComponents.
virtual void copyComponents (hash< string, ANNComponent * > &components_dict)
virtual ANNComponent * getComponent (string &name)
virtual void resetConnections ()
virtual void computeAllGradients (hash< string, MatrixFloat * > &weight_grads_dict)
virtual void debugInfo ()
virtual char * toLuaString ()
Public Member Functions inherited from ANN::ANNComponent
ANNComponent (const char *name=0, const char *weights_name=0, unsigned int input_size=0, unsigned int output_size=0)
virtual ~ANNComponent ()
const string & getName () const
const string & getWeightsName () const
bool hasWeightsName () const
bool getIsBuilt () const
void generateDefaultWeightsName (string &dest, const char *prefix=0)
unsigned int getInputSize () const
unsigned int getOutputSize () const
bool getUseCuda () const
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Member Functions
void buildInputBunchVector (TokenBunchVector *&vector_token, Token *token)
void buildErrorInputBunchVector (TokenBunchVector *&vector_token, Token *token)
TokenMatrixFloat * buildMatrixFloatToken (TokenBunchVector *token, bool is_output)
TokenMatrixFloat * buildMatrixFloatToken (Token *token, bool is_output)
Private Attributes
vector< ANNComponent * > components
Token * input
Token * error_output
TokenMatrixFloat * output
TokenMatrixFloat * error_input
TokenBunchVector * input_vector
TokenBunchVector * error_input_vector
TokenBunchVector * output_vector
TokenBunchVector * error_output_vector
bool segmented_input
Additional Inherited Members
Protected Member Functions inherited from ANN::ANNComponent
virtual void computeGradients (MatrixFloat *&weight_grads)
Protected Attributes inherited from ANN::ANNComponent
string name
string weights_name
unsigned int input_size
unsigned int output_size
bool use_cuda
Static Protected Attributes inherited from ANN::ANNComponent
static unsigned int next_name_id = 1
static unsigned int next_weights_id = 1
Constructor & Destructor Documentation
ANN::JoinANNComponent::JoinANNComponent (const char * name = 0)
Referenced by clone().
ANN::JoinANNComponent::~JoinANNComponent () virtual
References components, DecRef, error_input, error_input_vector, error_output, error_output_vector, input, input_vector, output, and output_vector.
Member Function Documentation
void ANN::JoinANNComponent::addComponent (ANNComponent * component)
References components, and IncRef.
Referenced by clone().
void ANN::JoinANNComponent::build (unsigned int _input_size, unsigned int _output_size, hash< string, Connections * > & weights_dict, hash< string, ANNComponent * > & components_dict) virtual
Abstract method to finish building of component hierarchy and set weights objects pointers. All childs which rewrite this method must call parent method before do anything.
Reimplemented from ANN::ANNComponent.
References AssignRef, ANN::ANNComponent::build(), april_utils::string::c_str(), components, ERROR_EXIT1, ERROR_EXIT3, error_input_vector, error_output_vector, ANN::ANNComponent::input_size, input_vector, ANN::ANNComponent::name, ANN::ANNComponent::output_size, and output_vector.
void ANN::JoinANNComponent::buildErrorInputBunchVector (TokenBunchVector *& vector_token, Token * token) private
References ASSERT_MATRIX, AssignRef, april_utils::string::c_str(), components, Token::convertTo(), ERROR_EXIT1, TokenMatrix< T >::getMatrix(), Token::getTokenCode(), ANN::ANNComponent::name, ANN::ANNComponent::output_size, TokenVector< T >::size(), table_of_token_codes::token_matrix, and ANN::ANNComponent::use_cuda.
Referenced by doBackprop().
void ANN::JoinANNComponent::buildInputBunchVector (TokenBunchVector *& vector_token, Token * token) private
References ASSERT_MATRIX, AssignRef, april_utils::string::c_str(), components, Token::convertTo(), ERROR_EXIT1, ERROR_EXIT2, ERROR_EXIT3, TokenMatrix< T >::getMatrix(), Token::getTokenCode(), TokenVector< T >::getTokenCode(), IncRef, ANN::ANNComponent::input_size, ANN::ANNComponent::name, segmented_input, Matrix< T >::setUseCuda(), TokenVector< T >::size(), table_of_token_codes::token_matrix, ANN::ANNComponent::use_cuda, and table_of_token_codes::vector_Tokens.
Referenced by doForward().
TokenMatrixFloat * ANN::JoinANNComponent::buildMatrixFloatToken (TokenBunchVector * token, bool is_output) private
References ASSERT_MATRIX, april_utils::string::c_str(), components, Matrix< T >::copy(), ERROR_EXIT1, ERROR_EXIT2, ANN::ANNComponent::getOutputSize(), ANN::ANNComponent::input_size, ANN::ANNComponent::name, ANN::ANNComponent::output_size, Matrix< T >::setUseCuda(), TokenVector< T >::size(), table_of_token_codes::token_matrix, and ANN::ANNComponent::use_cuda.
Referenced by buildMatrixFloatToken(), doBackprop(), and doForward().
TokenMatrixFloat * ANN::JoinANNComponent::buildMatrixFloatToken (Token * token, bool is_output) private
References buildMatrixFloatToken(), april_utils::string::c_str(), Token::convertTo(), ERROR_EXIT1, Token::getTokenCode(), ANN::ANNComponent::name, and table_of_token_codes::vector_Tokens.
ANNComponent * ANN::JoinANNComponent::clone () virtual
Reimplemented from ANN::ANNComponent.
References addComponent(), april_utils::string::c_str(), components, ANN::ANNComponent::input_size, JoinANNComponent(), ANN::ANNComponent::name, and ANN::ANNComponent::output_size.
void ANN::JoinANNComponent::computeAllGradients (hash< string, MatrixFloat * > & weight_grads_dict) virtual
Method which receives a hash table with matrices where compute the gradients.
Reimplemented from ANN::ANNComponent.
References components.
void ANN::JoinANNComponent::copyComponents (hash< string, ANNComponent * > & components_dict) virtual
Abstract method to retrieve ANNComponents objects. All childs which rewrite this method must call parent method before do anything.
Reimplemented from ANN::ANNComponent.
References components, and ANN::ANNComponent::copyComponents().
void ANN::JoinANNComponent::copyWeights (hash< string, Connections * > & weights_dict) virtual
Abstract method to retrieve Connections objects from ANNComponents.
Reimplemented from ANN::ANNComponent.
References components.
virtual void ANN::JoinANNComponent::debugInfo () inline virtual
Reimplemented from ANN::ANNComponent.
References components, and ANN::ANNComponent::debugInfo().
Token * ANN::JoinANNComponent::doBackprop (Token * input_error) virtual
Virtual method that back-propagates error derivatives and computes other useful stuff. Receives input error gradients, and returns its output error gradients Token.
Reimplemented from ANN::ANNComponent.
References AssignRef, buildErrorInputBunchVector(), buildMatrixFloatToken(), april_utils::string::c_str(), components, Token::convertTo(), DecRef, ERROR_EXIT1, error_input, error_input_vector, error_output, error_output_vector, Token::getTokenCode(), ANN::ANNComponent::name, segmented_input, and table_of_token_codes::token_matrix.
Token * ANN::JoinANNComponent::doForward (Token * input, bool during_training) virtual
Virtual method that executes the set of operations required for each block of connections when performing the forward step of the Backpropagation algorithm, and returns its output Token
Reimplemented from ANN::ANNComponent.
References AssignRef, buildInputBunchVector(), buildMatrixFloatToken(), components, input, input_vector, output, and output_vector.
void ANN::JoinANNComponent::doUpdate () virtual
Virtual method that update weights given gradients and input/output data
Reimplemented from ANN::ANNComponent.
References components.
ANNComponent * ANN::JoinANNComponent::getComponent (string & name) virtual
Virtual method which returns the component with the given name if exists, otherwise it returns 0. By default, base components only contains itself. Component composition will need to look to itself and all contained components. All childs which rewrite this method must call parent method before do anything.
Reimplemented from ANN::ANNComponent.
References components, and ANN::ANNComponent::getComponent().
virtual Token* ANN::JoinANNComponent::getErrorInput () inline virtual
Reimplemented from ANN::ANNComponent.
References error_input.
virtual Token* ANN::JoinANNComponent::getErrorOutput () inline virtual
Reimplemented from ANN::ANNComponent.
References error_output.
virtual Token* ANN::JoinANNComponent::getInput () inline virtual
Reimplemented from ANN::ANNComponent.
References input.
double ANN::JoinANNComponent::getOption (const char * name) virtual
Virtual method for getting the value of a training parameter. All childs which rewrite this method must call parent method after their process, if the looked option is not found to show the error message.
Reimplemented from ANN::ANNComponent.
References components, ANN::ANNComponent::getOption(), and hasOption().
virtual Token* ANN::JoinANNComponent::getOutput () inline virtual
Reimplemented from ANN::ANNComponent.
References output.
bool ANN::JoinANNComponent::hasOption (const char * name) virtual
Virtual method for determining if a training parameter is being used or can be used within the network.
Reimplemented from ANN::ANNComponent.
References components.
Referenced by getOption().
void ANN::JoinANNComponent::reset () virtual
Virtual method to reset to zero gradients and outputs (inputs are not reseted)
Reimplemented from ANN::ANNComponent.
References components, DecRef, error_input, error_output, input, and output.
virtual void ANN::JoinANNComponent::resetConnections () inline virtual
Reimplemented from ANN::ANNComponent.
References components.
void ANN::JoinANNComponent::setOption (const char * name, double value) virtual
Virtual method for setting the value of a training parameter.
Reimplemented from ANN::ANNComponent.
References components.
void ANN::JoinANNComponent::setUseCuda (bool v) virtual
Virtual method to set use_cuda option. All childs which rewrite this method must call parent method before do anything.
Reimplemented from ANN::ANNComponent.
References components, and ANN::ANNComponent::setUseCuda().
char * ANN::JoinANNComponent::toLuaString () virtual
Reimplemented from ANN::ANNComponent.
References april_utils::string::c_str(), components, ANN::ANNComponent::name, buffer_list::NULL_TERMINATED, buffer_list::printf(), and buffer_list::to_string().
Member Data Documentation
vector<ANNComponent*> ANN::JoinANNComponent::components private
Referenced by addComponent(), build(), buildErrorInputBunchVector(), buildInputBunchVector(), buildMatrixFloatToken(), clone(), computeAllGradients(), copyComponents(), copyWeights(), debugInfo(), doBackprop(), doForward(), doUpdate(), getComponent(), getOption(), hasOption(), reset(), resetConnections(), setOption(), setUseCuda(), toLuaString(), and ~JoinANNComponent().
TokenMatrixFloat * ANN::JoinANNComponent::error_input private
Referenced by doBackprop(), getErrorInput(), reset(), and ~JoinANNComponent().
TokenBunchVector * ANN::JoinANNComponent::error_input_vector private
Referenced by build(), doBackprop(), and ~JoinANNComponent().
Token * ANN::JoinANNComponent::error_output private
Referenced by doBackprop(), getErrorOutput(), reset(), and ~JoinANNComponent().
TokenBunchVector * ANN::JoinANNComponent::error_output_vector private
Referenced by build(), doBackprop(), and ~JoinANNComponent().
Token* ANN::JoinANNComponent::input private
Referenced by doForward(), getInput(), reset(), and ~JoinANNComponent().
TokenBunchVector* ANN::JoinANNComponent::input_vector private
Referenced by build(), doForward(), and ~JoinANNComponent().
TokenMatrixFloat* ANN::JoinANNComponent::output private
Referenced by doForward(), getOutput(), reset(), and ~JoinANNComponent().
TokenBunchVector* ANN::JoinANNComponent::output_vector private
Referenced by build(), doForward(), and ~JoinANNComponent().
bool ANN::JoinANNComponent::segmented_input private
Referenced by buildInputBunchVector(), and doBackprop().