april-ann
ANN::LogLogisticActfANNComponent Class Reference
Public Member Functions
LogLogisticActfANNComponent (const char *name)
virtual ~LogLogisticActfANNComponent ()
virtual ANNComponent * clone ()
Public Member Functions inherited from ANN::ActivationFunctionANNComponent
ActivationFunctionANNComponent (const char *name=0)
virtual ~ActivationFunctionANNComponent ()
virtual Token * getInput ()
virtual Token * getOutput ()
virtual Token * getErrorInput ()
virtual Token * getErrorOutput ()
virtual Token * doForward (Token *input, bool during_training)
virtual Token * doBackprop (Token *input_error)
virtual void reset ()
virtual void setOption (const char *name, double value)
Virtual method for setting the value of a training parameter.
virtual bool hasOption (const char *name)
virtual double getOption (const char *name)
virtual void build (unsigned int _input_size, unsigned int _output_size, hash< string, Connections * > &weights_dict, hash< string, ANNComponent * > &components_dict)
Public Member Functions inherited from ANN::ANNComponent
ANNComponent (const char *name=0, const char *weights_name=0, unsigned int input_size=0, unsigned int output_size=0)
virtual ~ANNComponent ()
const string & getName () const
const string & getWeightsName () const
bool hasWeightsName () const
bool getIsBuilt () const
void generateDefaultWeightsName ()
unsigned int getInputSize () const
unsigned int getOutputSize () const
virtual void doUpdate ()
virtual void setUseCuda (bool v)
virtual void copyWeights (hash< string, Connections * > &weights_dict)
Abstract method to retrieve Connections objects from ANNComponents.
virtual void copyComponents (hash< string, ANNComponent * > &components_dict)
virtual void resetConnections ()
virtual void debugInfo ()
virtual ANNComponent * getComponent (string &name)
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Protected Member Functions
virtual void applyActivation (FloatGPUMirroredMemoryBlock *input_units, FloatGPUMirroredMemoryBlock *output_units, unsigned int size, unsigned int bunch_size)
virtual void multiplyDerivatives (FloatGPUMirroredMemoryBlock *input_units, FloatGPUMirroredMemoryBlock *output_units, FloatGPUMirroredMemoryBlock *input_errors, FloatGPUMirroredMemoryBlock *output_errors, unsigned int size, unsigned int bunch_size)
Additional Inherited Members
Protected Attributes inherited from ANN::ANNComponent
string name
string weights_name
unsigned int input_size
unsigned int output_size
bool use_cuda
Static Protected Attributes inherited from ANN::ANNComponent
static unsigned int next_name_id = 1
static unsigned int next_weights_id = 1
Detailed Description
An abstract class that defines the basic interface that the anncomponents must fulfill.
Constructor & Destructor Documentation
ANN::LogLogisticActfANNComponent::LogLogisticActfANNComponent (const char * name)
Referenced by clone().
ANN::LogLogisticActfANNComponent::~LogLogisticActfANNComponent () virtual
Member Function Documentation
void ANN::LogLogisticActfANNComponent::applyActivation (FloatGPUMirroredMemoryBlock * input_units, FloatGPUMirroredMemoryBlock * output_units, unsigned int size, unsigned int bunch_size) protected virtual
Implements ANN::ActivationFunctionANNComponent.
References doApplyLogLogisticActivation(), and ANN::ANNComponent::use_cuda.
ANNComponent * ANN::LogLogisticActfANNComponent::clone () virtual
Reimplemented from ANN::ANNComponent.
References april_utils::string::c_str(), LogLogisticActfANNComponent(), and ANN::ANNComponent::name.
void ANN::LogLogisticActfANNComponent::multiplyDerivatives (FloatGPUMirroredMemoryBlock * input_units, FloatGPUMirroredMemoryBlock * output_units, FloatGPUMirroredMemoryBlock * input_errors, FloatGPUMirroredMemoryBlock * output_errors, unsigned int size, unsigned int bunch_size) protected virtual
Implements ANN::ActivationFunctionANNComponent.
References doScopy(), GPUMirroredMemoryBlock< T >::getSize(), and ANN::ANNComponent::use_cuda.