april-ann
ANN::MAELossFunction Class Reference
Public Member Functions
MAELossFunction (unsigned int size)
virtual ~MAELossFunction ()
virtual float addLoss (Token *input, Token *target)
virtual Token * computeGradient (Token *input, Token *target)
virtual float getAccumLoss ()
virtual void reset ()
virtual LossFunction * clone ()
Public Member Functions inherited from ANN::LossFunction
LossFunction (unsigned int size)
virtual ~LossFunction ()
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Member Functions
MAELossFunction (unsigned int size, float accumulated_loss, unsigned int N)
Private Attributes
float accumulated_loss
unsigned int N
Additional Inherited Members
Protected Member Functions inherited from ANN::LossFunction
void throwErrorAndGetMatrixFromTokens (Token *input, Token *target, MatrixFloat *&input_mat, MatrixFloat *&target_mat) const
Protected Attributes inherited from ANN::LossFunction
Token * error_output
unsigned int size
Constructor & Destructor Documentation
ANN::MAELossFunction::MAELossFunction (unsigned int size, float accumulated_loss, unsigned int N) inline private
Referenced by clone().
ANN::MAELossFunction::MAELossFunction (unsigned int size)
ANN::MAELossFunction::~MAELossFunction () virtual
Member Function Documentation
float ANN::MAELossFunction::addLoss (Token * input, Token * target) virtual
Implements ANN::LossFunction.
References accumulated_loss, doMAELossFunction(), Matrix< T >::getCudaFlag(), Matrix< T >::getDimSize(), Matrix< T >::getRawDataAccess(), N, and ANN::LossFunction::throwErrorAndGetMatrixFromTokens().
virtual LossFunction* ANN::MAELossFunction::clone () inline virtual
Implements ANN::LossFunction.
References accumulated_loss, MAELossFunction(), N, and ANN::LossFunction::size.
Token * ANN::MAELossFunction::computeGradient (Token * input, Token * target) virtual
Implements ANN::LossFunction.
References AssignRef, Matrix< T >::cloneOnlyDims(), doComputeMAEGradient(), ANN::LossFunction::error_output, Matrix< T >::getCudaFlag(), Matrix< T >::getDimSize(), Matrix< T >::getRawDataAccess(), NEAR_ZERO, and ANN::LossFunction::throwErrorAndGetMatrixFromTokens().
float ANN::MAELossFunction::getAccumLoss () virtual
Implements ANN::LossFunction.
References accumulated_loss, and N.
void ANN::MAELossFunction::reset () virtual
Reimplemented from ANN::LossFunction.
References accumulated_loss, N, and ANN::LossFunction::reset().
Member Data Documentation
float ANN::MAELossFunction::accumulated_loss private
Referenced by addLoss(), clone(), getAccumLoss(), and reset().
unsigned int ANN::MAELossFunction::N private
Referenced by addLoss(), clone(), getAccumLoss(), and reset().