april-ann
ANN::AllAllMLP Class Reference
Class that represents a neural network with all-all connections.
Public Member Functions
AllAllMLP (ANNConfiguration configuration)
~AllAllMLP ()
void generateAllAll (const char *str, MTRand *rnd, float low, float high, bool use_fanin)
void generateAllAll (const char *str, MatrixFloat *weights_mat, MatrixFloat *old_weights_mat)
unsigned int copyWeightsTo (MatrixFloat **weights_mat, MatrixFloat **old_weights_mat) const
const char * getDescription ()
AllAllMLP * clone ()
void loadModel (const char *filename)
void saveModel (const char *filename)
void randomizeWeights (MTRand *rnd, float low, float high, bool use_fanin)
Public Member Functions inherited from ANN::MLP
MLP (ANNConfiguration conf)
~MLP ()
void setErrorFunction (ErrorFunction *error_func)
void setOption (const char *name, double value)
bool hasOption (const char *name)
double getOption (const char *name)
void showNetworkAtts ()
void doForward ()
void doBackward ()
void showActivations ()
void showWeights ()
void pushBackAllAllLayer (ActivationUnits *inputs, ActivationUnits *outputs, ActivationFunction *actf, Connections **weights, bool transpose_weights, bool has_bias, Connections **bias)
Public Member Functions inherited from ANN::ANNBase
virtual ~ANNBase ()
void registerActivationUnits (ActivationUnits *actu)
void registerConnections (Connections *conn)
void registerAction (Action *action)
void registerInput (ActivationUnits *actu)
void registerOutput (ActivationUnits *actu)
void releaseOutput ()
This method converts output neurons into hidden neurons, and it sets output to zero.
unsigned int getInputSize () const
It returns the input (or domain) size of the function.
unsigned int getOutputSize () const
It returns the output (or range) size of the function.
unsigned int getLayerConnectionsSize () const
unsigned int getLayerActivationsSize () const
Connections * getLayerConnections (unsigned int layer)
ActivationUnits * getLayerActivations (unsigned int layer)
Action * getAction (unsigned int idx)
virtual void setInput (const float *input, unsigned int bunch_pos)
virtual void copyOutput (float *output, unsigned int bunch_pos)
virtual void setDesiredOutput (float *target_output, unsigned int bunch_pos)
void resetErrorVectors ()
void resetPatternErrorsAuxiliarVector ()
bool calculate (const float *input_vector, unsigned int input_size, float *output_vector, unsigned int output_size)
void calculateInPipeline (Functions::FloatDataProducer *producer, unsigned int input_size, Functions::FloatDataConsumer *consumer, unsigned int output_size)
const ANNConfiguration & getConfReference () const
ANNConfiguration getConf () const
void cloneTopologyTo (ANNBase *other)
void pruneSubnormalAndCheckNormal ()
virtual void setUseCuda (bool use_cuda, bool pinned)
virtual bool getUseCuda ()
float getMaxWeights () const
unsigned int getNumWeights () const
Public Member Functions inherited from Trainable::TrainableSupervised
virtual ~TrainableSupervised ()
Functions::NS_function_io::type getInputType () const
It returns the data type of the input (or domain).
Functions::NS_function_io::type getOutputType () const
It returns the data type of the output (or range).
virtual float trainOnePattern (float *input, float *target_output)
virtual float validateOnePattern (float *input, float *target_output)
virtual float trainDataset (DataSetFloat *input_dataset, DataSetFloat *target_output_dataset, MTRand *shuffle=0)
virtual float trainDatasetWithReplacement (DataSetFloat *input_dataset, DataSetFloat *target_output_dataset, MTRand *shuffle, int replacement)
virtual float trainDatasetWithDistribution (int num_classes, DataSetFloat **input_datasets, DataSetFloat **target_output_datasets, double *aprioris, MTRand *shuffle, int replacement)
virtual float validateDataset (DataSetFloat *input_dataset, DataSetFloat *target_output_dataset)
virtual float validateDatasetWithReplacement (DataSetFloat *input_dataset, DataSetFloat *target_output_dataset, MTRand *shuffle, int replacement)
virtual void useDataset (DataSetFloat *input_dataset, DataSetFloat *output_dataset)
Public Member Functions inherited from Functions::FunctionInterface< I, O >
virtual ~FunctionInterface ()
virtual bool calculate (const I *input_vector, unsigned int input_size, O *output_vector, unsigned int output_size)=0
A new abstract method that computes output vector given input vector.
virtual void calculateInPipeline (DataProducer< I > *producer, unsigned int input_size, DataConsumer< O > *consumer, unsigned int output_size)
Method for flow computation of outputs in a pipeline system.
Public Member Functions inherited from Functions::FunctionBase
FunctionBase ()
virtual ~FunctionBase ()
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Protected Member Functions
void generateActionsAllAll (const char *description)
Protected Member Functions inherited from ANN::MLP
void beginTrainingBatch ()
Entre begin y end va el conjunto de patrones de una epoca.
void trainPattern (float *input, float *target_output)
void doTraining ()
float endTrainingBatch ()
void beginValidateBatch ()
void validatePattern (float *input, float *target_output)
float endValidateBatch ()
Protected Member Functions inherited from ANN::ANNBase
ANNBase (ANNConfiguration configuration)
virtual void setNumBunch (unsigned int num_bunch)
virtual unsigned int getNumBunch ()
void clearTopology ()
float patternErrorsSum ()
Private Attributes
char * description
Additional Inherited Members
Protected Attributes inherited from ANN::MLP
unsigned int num_patterns_processed
unsigned int cur_bunch_pos
float learning_rate
float momentum
float weight_decay
float c_weight_decay
ErrorFunction * error_func
Detailed Description
Class that represents a neural network with all-all connections.
Constructor & Destructor Documentation
ANN::AllAllMLP::AllAllMLP (ANNConfiguration configuration)
References description.
Referenced by clone().
ANN::AllAllMLP::~AllAllMLP ()
References description.
Member Function Documentation
AllAllMLP * ANN::AllAllMLP::clone ()
Reimplemented from ANN::MLP.
References AllAllMLP(), ANN::MLP::c_weight_decay, ANN::ErrorFunction::clone(), ANN::ANNBase::cloneTopologyTo(), copystr(), description, ANN::MLP::error_func, ANN::ANNBase::getConf(), ANN::MLP::learning_rate, ANN::MLP::momentum, ANN::MLP::setErrorFunction(), and ANN::MLP::weight_decay.
unsigned int ANN::AllAllMLP::copyWeightsTo (MatrixFloat ** weights_mat, MatrixFloat ** old_weights_mat) const virtual
Reimplemented from ANN::ANNBase.
References ANN::ANNBase::activations, ANN::ANNBase::connections, and ANN::ANNBase::getNumWeights().
Referenced by saveModel().
void ANN::AllAllMLP::generateActionsAllAll (const char * description) protected
References ANN::ANNBase::activations, ANN::ANNBase::conf, ANN::ANNBase::connections, copystr(), description, ERROR_EXIT, constString::extract_token(), constString::extract_unsigned_int(), ANN::getActivationFunctionByTypeString(), ANN::HIDDEN_TYPE, ANN::INPUTS_TYPE, ANN::OUTPUTS_TYPE, april_utils::vector< T >::push_back(), ANN::ANNBase::registerAction(), ANN::ANNBase::registerActivationUnits(), ANN::ANNBase::registerConnections(), ANN::ANNBase::registerInput(), and ANN::ANNBase::registerOutput().
Referenced by generateAllAll().
void ANN::AllAllMLP::generateAllAll (const char * str, MTRand * rnd, float low, float high, bool use_fanin)
References generateActionsAllAll(), and randomizeWeights().
Referenced by loadModel().
void ANN::AllAllMLP::generateAllAll (const char * str, MatrixFloat * weights_mat, MatrixFloat * old_weights_mat)
References ANN::ANNBase::activations, ANN::ANNBase::connections, ERROR_EXIT, generateActionsAllAll(), ANN::ANNBase::getNumWeights(), and Matrix< T >::size.
const char* ANN::AllAllMLP::getDescription () inline
References description.
void ANN::AllAllMLP::loadModel (const char * filename) virtual
Reimplemented from ANN::MLP.
References ERROR_PRINT1, constString::extract_line(), generateAllAll(), IGNORE_RESULT, constString::newString(), and readMatrixFloatFromStream< constString >().
void ANN::AllAllMLP::randomizeWeights (MTRand * rnd, float low, float high, bool use_fanin) virtual
Reimplemented from ANN::MLP.
References ANN::ANNBase::actions, and ANN::ANNBase::connections.
Referenced by generateAllAll().
void ANN::AllAllMLP::saveModel (const char * filename) virtual
Reimplemented from ANN::MLP.
References copyWeightsTo(), description, and saveMatrixFloatToString().
Member Data Documentation
char* ANN::AllAllMLP::description private
Referenced by AllAllMLP(), clone(), generateActionsAllAll(), getDescription(), saveModel(), and ~AllAllMLP().