april-ann
ANN::MultiClassCrossEntropyLossFunction Class Reference
Public Member Functions
MultiClassCrossEntropyLossFunction (unsigned int size)
virtual ~MultiClassCrossEntropyLossFunction ()
virtual float addLoss (Token *input, Token *target)
virtual Token * computeGradient (Token *input, Token *target)
virtual float getAccumLoss ()
virtual void reset ()
virtual LossFunction * clone ()
Public Member Functions inherited from ANN::LossFunction
LossFunction (unsigned int size)
virtual ~LossFunction ()
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Member Functions
MultiClassCrossEntropyLossFunction (unsigned int size, float accumulated_loss, unsigned int N)
Private Attributes
float accumulated_loss
unsigned int N
Additional Inherited Members
Protected Member Functions inherited from ANN::LossFunction
void throwErrorAndGetMatrixFromTokens (Token *input, Token *target, MatrixFloat *&input_mat, MatrixFloat *&target_mat) const
Protected Attributes inherited from ANN::LossFunction
Token * error_output
unsigned int size
Constructor & Destructor Documentation
ANN::MultiClassCrossEntropyLossFunction::MultiClassCrossEntropyLossFunction (unsigned int size, float accumulated_loss, unsigned int N) inline private
Referenced by clone().
ANN::MultiClassCrossEntropyLossFunction::MultiClassCrossEntropyLossFunction (unsigned int size)
References ERROR_EXIT.
ANN::MultiClassCrossEntropyLossFunction::~MultiClassCrossEntropyLossFunction () virtual
Member Function Documentation
float ANN::MultiClassCrossEntropyLossFunction::addLoss (Token * input, Token * target) virtual
Implements ANN::LossFunction.
References accumulated_loss, doMultiClassCrossEntropyLossFunction(), Matrix< T >::getCudaFlag(), Matrix< T >::getDimSize(), Matrix< T >::getRawDataAccess(), N, NEAR_ZERO, and ANN::LossFunction::throwErrorAndGetMatrixFromTokens().
virtual LossFunction* ANN::MultiClassCrossEntropyLossFunction::clone () inline virtual
Implements ANN::LossFunction.
References accumulated_loss, MultiClassCrossEntropyLossFunction(), N, and ANN::LossFunction::size.
Token * ANN::MultiClassCrossEntropyLossFunction::computeGradient (Token * input, Token * target) virtual
Implements ANN::LossFunction.
References AssignRef, Matrix< T >::cloneOnlyDims(), doComputeCrossEntropyGradient(), ANN::LossFunction::error_output, Matrix< T >::getCudaFlag(), Matrix< T >::getDimSize(), Matrix< T >::getRawDataAccess(), NEAR_ZERO, and ANN::LossFunction::throwErrorAndGetMatrixFromTokens().
float ANN::MultiClassCrossEntropyLossFunction::getAccumLoss () virtual
Implements ANN::LossFunction.
References accumulated_loss, and N.
void ANN::MultiClassCrossEntropyLossFunction::reset () virtual
Reimplemented from ANN::LossFunction.
References accumulated_loss, N, and ANN::LossFunction::reset().
Member Data Documentation
float ANN::MultiClassCrossEntropyLossFunction::accumulated_loss private
Referenced by addLoss(), clone(), getAccumLoss(), and reset().
unsigned int ANN::MultiClassCrossEntropyLossFunction::N private
Referenced by addLoss(), clone(), getAccumLoss(), and reset().