april-ann
GPUMirroredMemoryBlock< T > Class Template Reference
Math
Classes
class PoolFreeBeforeExit
Public Member Functions
GPUMirroredMemoryBlock (unsigned int sz, bool initialize=false)
~GPUMirroredMemoryBlock ()
unsigned int getSize () const
const T * getPPALForRead () const
T * getPPALForWrite ()
T * getPPALForReadAndWrite ()
bool getCudaFlag ()
T & get (unsigned int pos)
T & operator[] (unsigned int pos)
const T & get (unsigned int pos) const
const T & operator[] (unsigned int pos) const
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Static Private Member Functions
static const PoolFreeBeforeExit pool_free_before_exit ()
Private Attributes
unsigned int size
T * mem_ppal
Static Private Attributes
static const unsigned int MAX_POOL_LIST_SIZE = 100
static april_utils::hash
< unsigned int,
april_utils::list< T * > > pool_lists
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Constructor & Destructor Documentation
template<typename T> GPUMirroredMemoryBlock< T >::GPUMirroredMemoryBlock (unsigned int sz, bool initialize = false) inline
template<typename T> GPUMirroredMemoryBlock< T >::~GPUMirroredMemoryBlock () inline
Member Function Documentation
template<typename T> T& GPUMirroredMemoryBlock< T >::get (unsigned int pos) inline
template<typename T> const T& GPUMirroredMemoryBlock< T >::get (unsigned int pos) const inline
template<typename T> bool GPUMirroredMemoryBlock< T >::getCudaFlag () inline
Referenced by TokenMemoryBlock::getCudaFlag().
template<typename T> const T* GPUMirroredMemoryBlock< T >::getPPALForRead () const inline
Referenced by ANN::MaxPoolingANNComponent::doBackprop(), TokenMemoryBlock::printDebug(), and DataSetFloat2TokenWrapper::putPattern().
template<typename T> T* GPUMirroredMemoryBlock< T >::getPPALForReadAndWrite () inline
Referenced by Image< T >::affine_transform(), hmm_trainer_model::backward(), ANN::MaxPoolingANNComponent::doBackprop(), hmm_trainer_model::forward(), and ANN::Connections::pruneSubnormalAndCheckNormal().
template<typename T> T* GPUMirroredMemoryBlock< T >::getPPALForWrite () inline
Referenced by ANN::ActivationFunctionANNComponent::doForward(), DataSetFloat2TokenWrapper::getPattern(), DataSetFloat2TokenWrapper::getPatternBunch(), Matrix< float >::maxSelDim(), DataSetFloat2TokenWrapper::putPatternBunch(), and TokenMemoryBlock::setData().
template<typename T> unsigned int GPUMirroredMemoryBlock< T >::getSize () const inline
Referenced by TokenMemoryBlock::clone(), ANN::MaxPoolingANNComponent::doBackprop(), ANN::ActivationFunctionANNComponent::doForward(), TokenMemoryBlock::getMaxSize(), Matrix< T >::Matrix(), ANN::LogSoftmaxActfANNComponent::multiplyDerivatives(), ANN::LogLogisticActfANNComponent::multiplyDerivatives(), TokenMemoryBlock::resize(), and TokenMemoryBlock::setToZero().
template<typename T> T& GPUMirroredMemoryBlock< T >::operator[] (unsigned int pos) inline
template<typename T> const T& GPUMirroredMemoryBlock< T >::operator[] (unsigned int pos) const inline
template<typename T> static const PoolFreeBeforeExit GPUMirroredMemoryBlock< T >::pool_free_before_exit () static private
Member Data Documentation
template<typename T> const unsigned int GPUMirroredMemoryBlock< T >::MAX_POOL_LIST_SIZE = 100 static private
Referenced by GPUMirroredMemoryBlock< float >::~GPUMirroredMemoryBlock().
template<typename T> T* GPUMirroredMemoryBlock< T >::mem_ppal mutable private
Referenced by GPUMirroredMemoryBlock< float >::get(), GPUMirroredMemoryBlock< float >::getPPALForRead(), GPUMirroredMemoryBlock< float >::getPPALForReadAndWrite(), GPUMirroredMemoryBlock< float >::getPPALForWrite(), GPUMirroredMemoryBlock< float >::GPUMirroredMemoryBlock(), and GPUMirroredMemoryBlock< float >::~GPUMirroredMemoryBlock().
template<typename T> unsigned int GPUMirroredMemoryBlock< T >::size private
Referenced by GPUMirroredMemoryBlock< float >::getSize(), GPUMirroredMemoryBlock< float >::GPUMirroredMemoryBlock(), and GPUMirroredMemoryBlock< float >::~GPUMirroredMemoryBlock().