april-ann
Functions::FloatContextualizerProducerFromDouble Class Reference
A specialization of FloatDataProducer which gets data from another producer.
Public Member Functions
FloatContextualizerProducerFromDouble (DataProducer< double > *orig_producer, int input_size, int left_context, int right_context, float *means, float *devs)
~FloatContextualizerProducerFromDouble ()
float * get ()
Returns a pointer and its property. A 0 inidicates data sequence ending.
void reset ()
Reinitialize the sequence iterator if it is possible.
Public Member Functions inherited from Functions::DataProducer< float >
virtual void destroy ()
It destroys the object content and forces to return a 0 on next get().
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Attributes
DataProducer< double > * orig_producer
Internal DoubleDataProducer source.
int input_size
Size of vectors at orig_producer.
int output_size
Size of vectros after context addition.
int left_context
Left context added to data vectors.
int right_context
Right context added to data vectors.
float * means
Means vector, for mean normalization of data.
float * devs
Standard deviations vector, for variance normalization of data.
april_utils::context_of_vectors
< float > ctxt
Context object, it implements the contextualizer logic.
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Detailed Description
A specialization of FloatDataProducer which gets data from another producer.
A specialization of FloatDataProducer class which works as a source of data vectors. Data vectors are stored at the internal DoubleDataProducer attribute. A context is added to data vectors, in order to being used as inputs of classifiers, as for example a neural network. Also, this object could normalize the data vectors substracting the mean and dividing by the standard deviation.
Constructor & Destructor Documentation
Functions::FloatContextualizerProducerFromDouble::FloatContextualizerProducerFromDouble (DataProducer< double > * orig_producer, int input_size, int left_context, int right_context, float * means = 0, float * devs = 0)
References IncRef, output_size, and right_context.
Functions::FloatContextualizerProducerFromDouble::~FloatContextualizerProducerFromDouble ()
References DecRef, devs, means, and orig_producer.
Member Function Documentation
float * Functions::FloatContextualizerProducerFromDouble::get () virtual
Returns a pointer and its property. A 0 inidicates data sequence ending.
Implements Functions::DataProducer< float >.
References ctxt, devs, april_utils::context_of_vectors< T >::end_input(), Functions::DataProducer< T >::get(), april_utils::context_of_vectors< T >::getOutputVector(), input_size, april_utils::context_of_vectors< T >::insert(), april_utils::context_of_vectors< T >::is_ended(), means, orig_producer, april_utils::context_of_vectors< T >::ready(), april_utils::context_of_vectors< T >::reset(), and april_utils::context_of_vectors< T >::shift().
void Functions::FloatContextualizerProducerFromDouble::reset () virtual
Reinitialize the sequence iterator if it is possible.
Implements Functions::DataProducer< float >.
References ctxt, orig_producer, Functions::DataProducer< T >::reset(), and april_utils::context_of_vectors< T >::reset().
Member Data Documentation
april_utils::context_of_vectors<float> Functions::FloatContextualizerProducerFromDouble::ctxt private
Context object, it implements the contextualizer logic.
Referenced by get(), and reset().
float* Functions::FloatContextualizerProducerFromDouble::devs private
Standard deviations vector, for variance normalization of data.
Referenced by get(), and ~FloatContextualizerProducerFromDouble().
int Functions::FloatContextualizerProducerFromDouble::input_size private
Size of vectors at orig_producer.
Referenced by get().
int Functions::FloatContextualizerProducerFromDouble::left_context private
Left context added to data vectors.
float* Functions::FloatContextualizerProducerFromDouble::means private
Means vector, for mean normalization of data.
Referenced by get(), and ~FloatContextualizerProducerFromDouble().
DataProducer<double>* Functions::FloatContextualizerProducerFromDouble::orig_producer private
Internal DoubleDataProducer source.
Referenced by get(), reset(), and ~FloatContextualizerProducerFromDouble().
int Functions::FloatContextualizerProducerFromDouble::output_size private
Size of vectros after context addition.
Referenced by FloatContextualizerProducerFromDouble().
int Functions::FloatContextualizerProducerFromDouble::right_context private
Right context added to data vectors.
Referenced by FloatContextualizerProducerFromDouble().