april-ann
april_utils::stopwatch Class Reference
Public Member Functions
stopwatch ()
void reset ()
void stop ()
void go ()
double read_cpu_time () const
double read_wall_time () const
double read () const
bool is_on () const
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Member Functions
double get_cpu_clock () const
devuelve tiempo en segundos
double get_wall_clock () const
Private Attributes
double cpu_elapsed
tiempo acumulado de cpu
double wall_elapsed
tiempo acumulado
double cpu_t_ini
auxiliar
double wall_t_ini
auxiliar
bool _is_on
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Constructor & Destructor Documentation
april_utils::stopwatch::stopwatch ()
References _is_on, and reset().
Member Function Documentation
double april_utils::stopwatch::get_cpu_clock () const inline private
devuelve tiempo en segundos
Referenced by go(), read_cpu_time(), reset(), and stop().
double april_utils::stopwatch::get_wall_clock () const inline private
Referenced by go(), read_wall_time(), reset(), and stop().
void april_utils::stopwatch::go ()
References _is_on, cpu_t_ini, get_cpu_clock(), get_wall_clock(), and wall_t_ini.
bool april_utils::stopwatch::is_on () const inline
References _is_on.
double april_utils::stopwatch::read () const inline
References read_cpu_time().
double april_utils::stopwatch::read_cpu_time () const
References _is_on, cpu_elapsed, cpu_t_ini, and get_cpu_clock().
Referenced by read().
double april_utils::stopwatch::read_wall_time () const
References _is_on, get_wall_clock(), wall_elapsed, and wall_t_ini.
void april_utils::stopwatch::reset ()
References cpu_elapsed, cpu_t_ini, get_cpu_clock(), get_wall_clock(), wall_elapsed, and wall_t_ini.
Referenced by stopwatch().
void april_utils::stopwatch::stop ()
References _is_on, cpu_elapsed, cpu_t_ini, get_cpu_clock(), get_wall_clock(), wall_elapsed, and wall_t_ini.
Member Data Documentation
bool april_utils::stopwatch::_is_on private
significado obvio
Referenced by go(), is_on(), read_cpu_time(), read_wall_time(), stop(), and stopwatch().
double april_utils::stopwatch::cpu_elapsed private
tiempo acumulado de cpu
Referenced by read_cpu_time(), reset(), and stop().
double april_utils::stopwatch::cpu_t_ini private
auxiliar
Referenced by go(), read_cpu_time(), reset(), and stop().
double april_utils::stopwatch::wall_elapsed private
tiempo acumulado
Referenced by read_wall_time(), reset(), and stop().
double april_utils::stopwatch::wall_t_ini private
auxiliar
Referenced by go(), read_wall_time(), reset(), and stop().