april-ann
ANN::HyperplaneANNComponent Class Reference
Public Member Functions
HyperplaneANNComponent (const char *name, const char *dot_product_name, const char *bias_name, const char *dot_product_weights_name, const char *bias_weights_name, unsigned int input_size=0, unsigned int output_size=0, bool transpose_weights=false)
virtual ~HyperplaneANNComponent ()
virtual Token * getInput ()
virtual Token * getOutput ()
virtual Token * getErrorInput ()
virtual Token * getErrorOutput ()
virtual Token * doForward (Token *input, bool during_training)
virtual Token * doBackprop (Token *input_error)
virtual void doUpdate ()
virtual void reset ()
virtual ANNComponent * clone ()
virtual void setUseCuda (bool v)
virtual void setOption (const char *name, double value)
Virtual method for setting the value of a training parameter.
virtual bool hasOption (const char *name)
virtual double getOption (const char *name)
virtual void build (unsigned int input_size, unsigned int output_size, hash< string, Connections * > &weights_dict, hash< string, ANNComponent * > &components_dict)
virtual void copyWeights (hash< string, Connections * > &weights_dict)
Abstract method to retrieve Connections objects from ANNComponents.
virtual void copyComponents (hash< string, ANNComponent * > &components_dict)
virtual ANNComponent * getComponent (string &name)
virtual void resetConnections ()
virtual void debugInfo ()
Public Member Functions inherited from ANN::ANNComponent
ANNComponent (const char *name=0, const char *weights_name=0, unsigned int input_size=0, unsigned int output_size=0)
virtual ~ANNComponent ()
const string & getName () const
const string & getWeightsName () const
bool hasWeightsName () const
bool getIsBuilt () const
void generateDefaultWeightsName ()
unsigned int getInputSize () const
unsigned int getOutputSize () const
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Member Functions
HyperplaneANNComponent (const char *name)
Private Attributes
DotProductANNComponent * dot_product
BiasANNComponent * bias
Additional Inherited Members
Protected Attributes inherited from ANN::ANNComponent
string name
string weights_name
unsigned int input_size
unsigned int output_size
bool use_cuda
Static Protected Attributes inherited from ANN::ANNComponent
static unsigned int next_name_id = 1
static unsigned int next_weights_id = 1
Constructor & Destructor Documentation
ANN::HyperplaneANNComponent::HyperplaneANNComponent (const char * name) private
Referenced by clone().
ANN::HyperplaneANNComponent::HyperplaneANNComponent (const char * name, const char * dot_product_name, const char * bias_name, const char * dot_product_weights_name, const char * bias_weights_name, unsigned int input_size = 0, unsigned int output_size = 0, bool transpose_weights = false)
References bias, dot_product, and IncRef.
ANN::HyperplaneANNComponent::~HyperplaneANNComponent () virtual
References bias, DecRef, and dot_product.
Member Function Documentation
void ANN::HyperplaneANNComponent::build (unsigned int _input_size, unsigned int _output_size, hash< string, Connections * > & weights_dict, hash< string, ANNComponent * > & components_dict) virtual
Abstract method to finish building of component hierarchy and set weights objects pointers. All childs which rewrite this method must call parent method before do anything.
Reimplemented from ANN::ANNComponent.
References bias, ANN::BiasANNComponent::build(), ANN::DotProductANNComponent::build(), ANN::ANNComponent::build(), dot_product, ERROR_EXIT, ANN::ANNComponent::input_size, and ANN::ANNComponent::output_size.
ANNComponent * ANN::HyperplaneANNComponent::clone () virtual
Reimplemented from ANN::ANNComponent.
References bias, april_utils::string::c_str(), ANN::BiasANNComponent::clone(), ANN::DotProductANNComponent::clone(), dot_product, HyperplaneANNComponent(), IncRef, ANN::ANNComponent::input_size, ANN::ANNComponent::name, and ANN::ANNComponent::output_size.
void ANN::HyperplaneANNComponent::copyComponents (hash< string, ANNComponent * > & components_dict) virtual
Abstract method to retrieve ANNComponents objects. All childs which rewrite this method must call parent method before do anything.
Reimplemented from ANN::ANNComponent.
References bias, ANN::ANNComponent::copyComponents(), and dot_product.
void ANN::HyperplaneANNComponent::copyWeights (hash< string, Connections * > & weights_dict) virtual
Abstract method to retrieve Connections objects from ANNComponents.
Reimplemented from ANN::ANNComponent.
References bias, ANN::BiasANNComponent::copyWeights(), ANN::DotProductANNComponent::copyWeights(), and dot_product.
virtual void ANN::HyperplaneANNComponent::debugInfo () inline virtual
Reimplemented from ANN::ANNComponent.
References bias, ANN::ANNComponent::debugInfo(), and dot_product.
Token * ANN::HyperplaneANNComponent::doBackprop (Token * input_error) virtual
Virtual method that back-propagates error derivatives and computes other useful stuff. Receives input error gradients, and returns its output error gradients Token.
Reimplemented from ANN::ANNComponent.
References bias, ANN::BiasANNComponent::doBackprop(), ANN::DotProductANNComponent::doBackprop(), and dot_product.
Token * ANN::HyperplaneANNComponent::doForward (Token * input, bool during_training) virtual
Virtual method that executes the set of operations required for each block of connections when performing the forward step of the Backpropagation algorithm, and returns its output Token
Reimplemented from ANN::ANNComponent.
References bias, ANN::BiasANNComponent::doForward(), ANN::DotProductANNComponent::doForward(), and dot_product.
void ANN::HyperplaneANNComponent::doUpdate () virtual
Virtual method that update weights given gradients and input/output data
Reimplemented from ANN::ANNComponent.
References bias, dot_product, ANN::BiasANNComponent::doUpdate(), and ANN::DotProductANNComponent::doUpdate().
ANNComponent * ANN::HyperplaneANNComponent::getComponent (string & name) virtual
Virtual method which returns the component with the given name if exists, otherwise it returns 0. By default, base components only contains itself. Component composition will need to look to itself and all contained components. All childs which rewrite this method must call parent method before do anything.
Reimplemented from ANN::ANNComponent.
References bias, dot_product, and ANN::ANNComponent::getComponent().
Token * ANN::HyperplaneANNComponent::getErrorInput () virtual
Reimplemented from ANN::ANNComponent.
References bias, and ANN::BiasANNComponent::getErrorInput().
Token * ANN::HyperplaneANNComponent::getErrorOutput () virtual
Reimplemented from ANN::ANNComponent.
References dot_product, and ANN::DotProductANNComponent::getErrorOutput().
Token * ANN::HyperplaneANNComponent::getInput () virtual
Reimplemented from ANN::ANNComponent.
References dot_product, and ANN::DotProductANNComponent::getInput().
double ANN::HyperplaneANNComponent::getOption (const char * name) virtual
Virtual method for getting the value of a training parameter. All childs which rewrite this method must call parent method after their process, if the looked option is not found to show the error message.
Reimplemented from ANN::ANNComponent.
References bias, dot_product, ANN::BiasANNComponent::getOption(), ANN::DotProductANNComponent::getOption(), ANN::ANNComponent::getOption(), ANN::BiasANNComponent::hasOption(), and ANN::DotProductANNComponent::hasOption().
Token * ANN::HyperplaneANNComponent::getOutput () virtual
Reimplemented from ANN::ANNComponent.
References bias, and ANN::BiasANNComponent::getOutput().
bool ANN::HyperplaneANNComponent::hasOption (const char * name) virtual
Virtual method for determining if a training parameter is being used or can be used within the network.
Reimplemented from ANN::ANNComponent.
References bias, dot_product, ANN::BiasANNComponent::hasOption(), and ANN::DotProductANNComponent::hasOption().
void ANN::HyperplaneANNComponent::reset () virtual
Virtual method to reset to zero gradients and outputs (inputs are not reseted)
Reimplemented from ANN::ANNComponent.
References bias, dot_product, ANN::BiasANNComponent::reset(), and ANN::DotProductANNComponent::reset().
virtual void ANN::HyperplaneANNComponent::resetConnections () inline virtual
Reimplemented from ANN::ANNComponent.
References bias, dot_product, ANN::BiasANNComponent::resetConnections(), and ANN::DotProductANNComponent::resetConnections().
void ANN::HyperplaneANNComponent::setOption (const char * name, double value) virtual
Virtual method for setting the value of a training parameter.
Reimplemented from ANN::ANNComponent.
References bias, dot_product, ANN::BiasANNComponent::setOption(), and ANN::DotProductANNComponent::setOption().
void ANN::HyperplaneANNComponent::setUseCuda (bool v) virtual
Virtual method to set use_cuda option. All childs which rewrite this method must call parent method before do anything.
Reimplemented from ANN::ANNComponent.
References bias, dot_product, and ANN::ANNComponent::setUseCuda().
Member Data Documentation
BiasANNComponent* ANN::HyperplaneANNComponent::bias private
Referenced by build(), clone(), copyComponents(), copyWeights(), debugInfo(), doBackprop(), doForward(), doUpdate(), getComponent(), getErrorInput(), getOption(), getOutput(), hasOption(), HyperplaneANNComponent(), reset(), resetConnections(), setOption(), setUseCuda(), and ~HyperplaneANNComponent().
DotProductANNComponent* ANN::HyperplaneANNComponent::dot_product private
Referenced by build(), clone(), copyComponents(), copyWeights(), debugInfo(), doBackprop(), doForward(), doUpdate(), getComponent(), getErrorOutput(), getInput(), getOption(), hasOption(), HyperplaneANNComponent(), reset(), resetConnections(), setOption(), setUseCuda(), and ~HyperplaneANNComponent().