april-ann
ANN::ActivationUnits Class Reference
Public Member Functions
ActivationUnits (const ANNConfiguration &conf)
virtual ~ActivationUnits ()
virtual unsigned int size () const =0
virtual unsigned int numNeurons () const =0
devuelve el numero de neuronas de la entrada
virtual
FloatGPUMirroredMemoryBlock * getPtr ()=0
virtual
FloatGPUMirroredMemoryBlock * getErrorVectorPtr ()=0
devuelve un puntero al vector con la suma de los errores
virtual unsigned int getOffset () const =0
virtual ActivationUnits * clone (const ANNConfiguration &conf)=0
virtual void reset (bool use_cuda)=0
pone a 0 los contadores, deltas de error, etc
const ANNConfiguration & getConfReference () const
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Protected Attributes
const ANNConfiguration & conf
Protected Attributes inherited from Referenced
int refs
Constructor & Destructor Documentation
ANN::ActivationUnits::ActivationUnits (const ANNConfiguration & conf) inline
virtual ANN::ActivationUnits::~ActivationUnits () inline virtual
Member Function Documentation
virtual ActivationUnits* ANN::ActivationUnits::clone (const ANNConfiguration & conf) pure virtual
Implemented in ANN::ActivationUnitsSlice, ANN::LocalActivationUnits, and ANN::RealActivationUnits.
const ANNConfiguration& ANN::ActivationUnits::getConfReference () const inline
References conf.
virtual FloatGPUMirroredMemoryBlock* ANN::ActivationUnits::getErrorVectorPtr () pure virtual
devuelve un puntero al vector con la suma de los errores
Implemented in ANN::ActivationUnitsSlice, ANN::LocalActivationUnits, and ANN::RealActivationUnits.
Referenced by ANN::ActivationsAction::doBackward(), ANN::ForwardBiasAction::doBackward(), ANN::DotProductAction::doBackward(), ANN::ActivationUnitsSlice::getErrorVectorPtr(), and ANN::ANNBase::registerOutput().
virtual unsigned int ANN::ActivationUnits::getOffset () const pure virtual
devuelve el valor de offset, que sumado al size(), puede que el vector no comienze en 0
Implemented in ANN::ActivationUnitsSlice, ANN::LocalActivationUnits, and ANN::RealActivationUnits.
Referenced by ANN::DotProductAction::doBackward(), and ANN::DotProductAction::doForward().
virtual FloatGPUMirroredMemoryBlock* ANN::ActivationUnits::getPtr () pure virtual
devuelve un puntero al vector de unidades, tantas unidades como size()*bunch_size
Implemented in ANN::ActivationUnitsSlice, ANN::LocalActivationUnits, and ANN::RealActivationUnits.
Referenced by ANN::ActivationsAction::doBackward(), ANN::DotProductAction::doBackward(), ANN::ActivationsAction::doForward(), ANN::ForwardBiasAction::doForward(), ANN::DotProductAction::doForward(), ANN::ActivationUnitsSlice::getPtr(), and ANN::ANNBase::registerOutput().
virtual unsigned int ANN::ActivationUnits::numNeurons () const pure virtual
devuelve el numero de neuronas de la entrada
Implemented in ANN::ActivationUnitsSlice, ANN::LocalActivationUnits, and ANN::RealActivationUnits.
Referenced by ANN::ActivationUnitsSlice::ActivationUnitsSlice(), ANN::BiasConnections::checkInputOutputSizes(), ANN::AllAllConnections::checkInputOutputSizes(), ANN::ForwardBiasAction::doBackward(), and ANN::ForwardBiasAction::doForward().
virtual void ANN::ActivationUnits::reset (bool use_cuda) pure virtual
pone a 0 los contadores, deltas de error, etc
Implemented in ANN::ActivationUnitsSlice, ANN::LocalActivationUnits, and ANN::RealActivationUnits.
Referenced by ANN::ActivationUnitsSlice::reset().
virtual unsigned int ANN::ActivationUnits::size () const pure virtual
devuelve el tamanyo del vector que representa la entrada (no tiene porque ser igual al numero de neuronas)
Implemented in ANN::ActivationUnitsSlice, ANN::LocalActivationUnits, and ANN::RealActivationUnits.
Referenced by ANN::ActivationUnitsSlice::ActivationUnitsSlice(), ANN::ActivationsAction::doBackward(), ANN::ActivationsAction::doForward(), ANN::ANNBase::registerInput(), and ANN::ANNBase::registerOutput().
Member Data Documentation
const ANNConfiguration& ANN::ActivationUnits::conf protected
Referenced by getConfReference(), and ANN::RealActivationUnits::reset().