april-ann
ANN::ANNBase Class Reference
Public Member Functions
virtual ~ANNBase ()
void registerActivationUnits (ActivationUnits *actu)
void registerConnections (Connections *conn)
void registerAction (Action *action)
void registerInput (ActivationUnits *actu)
void registerOutput (ActivationUnits *actu)
unsigned int getInputSize () const
It returns the input (or domain) size of the function.
unsigned int getOutputSize () const
It returns the output (or range) size of the function.
virtual void setInput (const float *input, unsigned int bunch_pos)
virtual void copyOutput (float *output, unsigned int bunch_pos)
virtual void setDesiredOutput (float *target_output, unsigned int bunch_pos)
void resetErrorVectors ()
void resetPatternErrorsAuxiliarVector ()
bool calculate (const float *input_vector, unsigned int input_size, float *output_vector, unsigned int output_size)
void calculateInPipeline (Functions::FloatDataProducer *producer, unsigned int input_size, Functions::FloatDataConsumer *consumer, unsigned int output_size)
const ANNConfiguration & getConfReference () const
ANNConfiguration getConf () const
void cloneTopologyTo (ANNBase *other)
void pruneSubnormalAndCheckNormal ()
virtual void setUseCuda (bool use_cuda, bool pinned)
virtual bool getUseCuda ()
float getMaxWeights () const
virtual unsigned int getNumWeights () const =0
Public Member Functions inherited from Trainable::TrainableSupervised
virtual ~TrainableSupervised ()
virtual void setOption (const char *name, double value)=0
virtual bool hasOption (const char *name)=0
virtual double getOption (const char *name)=0
virtual void loadModel (const char *filename)=0
virtual void saveModel (const char *filename)=0
Functions::NS_function_io::type getInputType () const
It returns the data type of the input (or domain).
Functions::NS_function_io::type getOutputType () const
It returns the data type of the output (or range).
virtual float trainOnePattern (float *input, float *target_output)
virtual float validateOnePattern (float *input, float *target_output)
virtual float trainDataset (DataSetFloat *input_dataset, DataSetFloat *target_output_dataset, MTRand *shuffle=0)
virtual float trainDatasetWithReplacement (DataSetFloat *input_dataset, DataSetFloat *target_output_dataset, MTRand *shuffle, int replacement)
virtual float trainDatasetWithDistribution (int num_classes, DataSetFloat **input_datasets, DataSetFloat **target_output_datasets, double *aprioris, MTRand *shuffle, int replacement)
virtual float validateDataset (DataSetFloat *input_dataset, DataSetFloat *target_output_dataset)
virtual float validateDatasetWithReplacement (DataSetFloat *input_dataset, DataSetFloat *target_output_dataset, MTRand *shuffle, int replacement)
virtual void useDataset (DataSetFloat *input_dataset, DataSetFloat *output_dataset)
Public Member Functions inherited from Functions::FunctionInterface< I, O >
virtual ~FunctionInterface ()
virtual bool calculate (const I *input_vector, unsigned int input_size, O *output_vector, unsigned int output_size)=0
A new abstract method that computes output vector given input vector.
virtual void calculateInPipeline (DataProducer< I > *producer, unsigned int input_size, DataConsumer< O > *consumer, unsigned int output_size)
Method for flow computation of outputs in a pipeline system.
Public Member Functions inherited from Functions::FunctionBase
FunctionBase ()
virtual ~FunctionBase ()
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Protected Member Functions
ANNBase (ANNConfiguration configuration)
virtual void setNumBunch (unsigned int num_bunch)
virtual unsigned int getNumBunch ()
virtual void doForward ()=0
virtual void doBackward ()=0
void clearTopology ()
float patternErrorsSum ()
Protected Member Functions inherited from Trainable::TrainableSupervised
virtual void beginTrainingBatch ()=0
Entre begin y end va el conjunto de patrones de una epoca.
virtual void trainPattern (float *input, float *target_output)=0
virtual float endTrainingBatch ()=0
virtual void beginValidateBatch ()=0
virtual void validatePattern (float *input, float *target_output)=0
virtual float endValidateBatch ()=0
Protected Attributes
ANNConfiguration conf
FloatGPUMirroredMemoryBlock * output_neurons
FloatGPUMirroredMemoryBlock * desired_output
FloatGPUMirroredMemoryBlock * output_errors
FloatGPUMirroredMemoryBlock * pattern_errors
unsigned int total_num_inputs
unsigned int total_num_outputs
vector< ActivationUnits * > inputs
vector< ActivationUnits * > activations
vector< Connections * > connections
vector< Action * > actions
Detailed Description
Clase base para definir objetos tipo ANN. Estos atributos son los minimos esperados: – Vector de acciones, que permite ejecutar la red. – Vector de activaciones, con las neuronas de cada capa. – Vector de conexiones, con las conexiones entre capas – Vector de entrada, salida deseada, salida, y errores a la salida. – Tamanyo del bunch. – Flag para el uso de CUDA
Constructor & Destructor Documentation
ANN::ANNBase::ANNBase (ANNConfiguration configuration) protected
References desired_output, output_errors, output_neurons, pattern_errors, total_num_inputs, and total_num_outputs.
ANN::ANNBase::~ANNBase () virtual
References actions, activations, connections, DecRef, desired_output, and pattern_errors.
Member Function Documentation
bool ANN::ANNBase::calculate (const float * input_vector, unsigned int input_size, float * output_vector, unsigned int output_size)
References conf, copyOutput(), ANNConfiguration::cur_bunch_size, doForward(), ERROR_EXIT, getInputSize(), getOutputSize(), and setInput().
void ANN::ANNBase::calculateInPipeline (Functions::FloatDataProducer * producer, unsigned int input_size, Functions::FloatDataConsumer * consumer, unsigned int output_size)
References conf, copyOutput(), ANNConfiguration::cur_bunch_size, doForward(), ERROR_EXIT, Functions::DataProducer< T >::get(), getInputSize(), getOutputSize(), Functions::DataConsumer< T >::put(), and setInput().
void ANN::ANNBase::clearTopology () inline protected
References actions, activations, connections, DecRef, desired_output, inputs, and output_errors.
void ANN::ANNBase::cloneTopologyTo (ANNBase * other)
References actions, activations, connections, getConfReference(), inputs, output_neurons, registerAction(), registerActivationUnits(), registerConnections(), registerInput(), and registerOutput().
Referenced by ANN::AllAllMLP::clone(), and ANN::MLP::clone().
void ANN::ANNBase::copyOutput (float * output, unsigned int bunch_pos) virtual
References conf, GPUMirroredMemoryBlock< T >::getPPALForRead(), ANNConfiguration::max_bunch_size, output_neurons, and total_num_outputs.
Referenced by calculate(), and calculateInPipeline().
virtual void ANN::ANNBase::doBackward () protected pure virtual
Implemented in ANN::MLP.
virtual void ANN::ANNBase::doForward () protected pure virtual
Implemented in ANN::MLP.
Referenced by calculate(), and calculateInPipeline().
ANNConfiguration ANN::ANNBase::getConf () const inline
References conf.
Referenced by ANN::AllAllMLP::clone().
const ANNConfiguration& ANN::ANNBase::getConfReference () const inline
References conf.
Referenced by ANN::MLP::clone(), and cloneTopologyTo().
unsigned int ANN::ANNBase::getInputSize () const virtual
It returns the input (or domain) size of the function.
Implements Functions::FunctionBase.
References total_num_inputs.
Referenced by calculate(), and calculateInPipeline().
float ANN::ANNBase::getMaxWeights () const
unsigned int ANN::ANNBase::getNumBunch () protected virtual
References conf, and ANNConfiguration::cur_bunch_size.
virtual unsigned int ANN::ANNBase::getNumWeights () const pure virtual
Implemented in ANN::MLP.
unsigned int ANN::ANNBase::getOutputSize () const virtual
It returns the output (or range) size of the function.
Implements Functions::FunctionBase.
References total_num_outputs.
Referenced by calculate(), and calculateInPipeline().
bool ANN::ANNBase::getUseCuda () virtual
References conf, and ANNConfiguration::use_cuda_flag.
float ANN::ANNBase::patternErrorsSum () inline protected
References conf, GPUMirroredMemoryBlock< T >::getPPALForRead(), ANNConfiguration::max_bunch_size, pattern_errors, and total_num_outputs.
Referenced by ANN::MLP::endTrainingBatch(), and ANN::MLP::endValidateBatch().
void ANN::ANNBase::pruneSubnormalAndCheckNormal ()
References connections.
Referenced by ANN::MLP::endTrainingBatch(), and ANN::MLP::trainPattern().
void ANN::ANNBase::registerAction (Action * action)
References actions, and IncRef.
Referenced by cloneTopologyTo(), and ANN::AllAllMLP::generateActionsAllAll().
void ANN::ANNBase::registerActivationUnits (ActivationUnits * actu)
References activations, and IncRef.
Referenced by cloneTopologyTo(), and ANN::AllAllMLP::generateActionsAllAll().
void ANN::ANNBase::registerConnections (Connections * conn)
References connections, and IncRef.
Referenced by cloneTopologyTo(), and ANN::AllAllMLP::generateActionsAllAll().
void ANN::ANNBase::registerInput (ActivationUnits * actu)
References inputs, ANN::ActivationUnits::size(), and total_num_inputs.
Referenced by cloneTopologyTo(), and ANN::AllAllMLP::generateActionsAllAll().
void ANN::ANNBase::registerOutput (ActivationUnits * actu)
References conf, desired_output, ERROR_EXIT, ANN::ActivationUnits::getErrorVectorPtr(), ANN::ActivationUnits::getPtr(), ANNConfiguration::max_bunch_size, output_errors, output_neurons, pattern_errors, ANN::ActivationUnits::size(), and total_num_outputs.
Referenced by cloneTopologyTo(), and ANN::AllAllMLP::generateActionsAllAll().
void ANN::ANNBase::resetErrorVectors ()
References activations, conf, ANNConfiguration::max_bunch_size, and ANNConfiguration::use_cuda_flag.
Referenced by ANN::MLP::doTraining().
void ANN::ANNBase::resetPatternErrorsAuxiliarVector ()
References conf, doVectorSetToZero(), ANNConfiguration::max_bunch_size, pattern_errors, total_num_outputs, and ANNConfiguration::use_cuda_flag.
Referenced by ANN::MLP::beginTrainingBatch(), and ANN::MLP::beginValidateBatch().
void ANN::ANNBase::setDesiredOutput (float * target_output, unsigned int bunch_pos) virtual
References conf, desired_output, GPUMirroredMemoryBlock< T >::getPPALForWrite(), ANNConfiguration::max_bunch_size, and total_num_outputs.
Referenced by ANN::MLP::trainPattern(), and ANN::MLP::validatePattern().
void ANN::ANNBase::setInput (const float * input, unsigned int bunch_pos) virtual
References conf, inputs, and ANNConfiguration::max_bunch_size.
Referenced by calculate(), calculateInPipeline(), ANN::MLP::trainPattern(), and ANN::MLP::validatePattern().
void ANN::ANNBase::setNumBunch (unsigned int num_bunch) protected virtual
References conf, and ANNConfiguration::cur_bunch_size.
void ANN::ANNBase::setUseCuda (bool use_cuda, bool pinned) virtual
References conf, desired_output, inputs, output_neurons, and ANNConfiguration::use_cuda_flag.
Member Data Documentation
vector<Action*> ANN::ANNBase::actions protected
Referenced by clearTopology(), cloneTopologyTo(), ANN::MLP::doBackward(), ANN::MLP::doForward(), registerAction(), ANN::MLP::setOption(), and ~ANNBase().
vector<ActivationUnits*> ANN::ANNBase::activations protected
Referenced by clearTopology(), cloneTopologyTo(), ANN::AllAllMLP::copyWeightsToMatrix(), ANN::AllAllMLP::generateActionsAllAll(), ANN::AllAllMLP::generateAllAll(), registerActivationUnits(), resetErrorVectors(), ANN::MLP::showActivations(), and ~ANNBase().
ANNConfiguration ANN::ANNBase::conf protected
Referenced by calculate(), calculateInPipeline(), copyOutput(), ANN::MLP::doTraining(), ANN::MLP::endTrainingBatch(), ANN::MLP::endValidateBatch(), ANN::AllAllMLP::generateActionsAllAll(), getConf(), getConfReference(), getNumBunch(), getUseCuda(), patternErrorsSum(), registerOutput(), resetErrorVectors(), resetPatternErrorsAuxiliarVector(), setDesiredOutput(), setInput(), setNumBunch(), setUseCuda(), ANN::MLP::showActivations(), ANN::MLP::trainPattern(), and ANN::MLP::validatePattern().
vector<Connections*> ANN::ANNBase::connections protected
Referenced by clearTopology(), cloneTopologyTo(), ANN::AllAllMLP::copyWeightsToMatrix(), ANN::AllAllMLP::generateActionsAllAll(), ANN::AllAllMLP::generateAllAll(), ANN::AllAllMLP::getLayerConnections(), ANN::AllAllMLP::getNumberOfWeights(), ANN::MLP::getNumWeights(), pruneSubnormalAndCheckNormal(), ANN::AllAllMLP::randomizeWeights(), ANN::MLP::randomizeWeights(), registerConnections(), and ~ANNBase().
FloatGPUMirroredMemoryBlock * ANN::ANNBase::desired_output protected
Referenced by ANNBase(), clearTopology(), ANN::MLP::doTraining(), ANN::MLP::endValidateBatch(), registerOutput(), setDesiredOutput(), setUseCuda(), ANN::MLP::validatePattern(), and ~ANNBase().
vector<ActivationUnits*> ANN::ANNBase::inputs protected
Referenced by clearTopology(), cloneTopologyTo(), registerInput(), setInput(), and setUseCuda().
FloatGPUMirroredMemoryBlock * ANN::ANNBase::output_errors protected
Referenced by ANNBase(), clearTopology(), ANN::MLP::doTraining(), ANN::MLP::endValidateBatch(), registerOutput(), and ANN::MLP::validatePattern().
FloatGPUMirroredMemoryBlock* ANN::ANNBase::output_neurons protected
Referenced by ANNBase(), cloneTopologyTo(), copyOutput(), ANN::MLP::doTraining(), ANN::MLP::endValidateBatch(), registerOutput(), setUseCuda(), and ANN::MLP::validatePattern().
FloatGPUMirroredMemoryBlock * ANN::ANNBase::pattern_errors protected
Referenced by ANNBase(), ANN::MLP::doTraining(), ANN::MLP::endValidateBatch(), patternErrorsSum(), registerOutput(), resetPatternErrorsAuxiliarVector(), ANN::MLP::validatePattern(), and ~ANNBase().
unsigned int ANN::ANNBase::total_num_inputs protected
Referenced by ANNBase(), getInputSize(), and registerInput().
unsigned int ANN::ANNBase::total_num_outputs protected
Referenced by ANNBase(), copyOutput(), ANN::MLP::doTraining(), ANN::MLP::endValidateBatch(), getOutputSize(), patternErrorsSum(), registerOutput(), resetPatternErrorsAuxiliarVector(), setDesiredOutput(), and ANN::MLP::validatePattern().