april-ann
ANN::DotProductANNComponent Class Reference
Public Member Functions
DotProductANNComponent (const char *name=0, const char *weights_name=0, unsigned int input_size=0, unsigned int output_size=0, bool transpose_weights=false)
virtual ~DotProductANNComponent ()
virtual Token * getInput ()
virtual Token * getOutput ()
virtual Token * getErrorInput ()
virtual Token * getErrorOutput ()
virtual Token * doForward (Token *input, bool during_training)
virtual Token * doBackprop (Token *input_error)
virtual void doUpdate ()
virtual void reset ()
virtual ANNComponent * clone ()
virtual void setOption (const char *name, double value)
Virtual method for setting the value of a training parameter.
virtual bool hasOption (const char *name)
virtual double getOption (const char *name)
virtual void build (unsigned int input_size, unsigned int output_size, hash< string, Connections * > &weights_dict, hash< string, ANNComponent * > &components_dict)
virtual void copyWeights (hash< string, Connections * > &weights_dict)
Abstract method to retrieve Connections objects from ANNComponents.
virtual void resetConnections ()
virtual char * toLuaString ()
bool transposed ()
Public Member Functions inherited from ANN::ANNComponent
ANNComponent (const char *name=0, const char *weights_name=0, unsigned int input_size=0, unsigned int output_size=0)
virtual ~ANNComponent ()
const string & getName () const
const string & getWeightsName () const
bool hasWeightsName () const
bool getIsBuilt () const
void generateDefaultWeightsName (string &dest, const char *prefix=0)
unsigned int getInputSize () const
unsigned int getOutputSize () const
virtual void computeAllGradients (hash< string, MatrixFloat * > &weight_grads_dict)
virtual void setUseCuda (bool v)
bool getUseCuda () const
virtual void copyComponents (hash< string, ANNComponent * > &components_dict)
virtual void debugInfo ()
virtual ANNComponent * getComponent (string &name)
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Protected Member Functions
virtual void computeGradients (MatrixFloat *&weight_grads)
Private Member Functions
void computeBP (MatrixFloat *weights_mat, Token *input_token, MatrixFloat *error_input_mat, const float alpha, const float beta)
Private Attributes
Token * input
TokenMatrixFloat * error_input
TokenMatrixFloat * output
TokenMatrixFloat * error_output
Connections * weights_matrix
unsigned int num_updates_from_last_prune
bool sparse_input
float learning_rate
learning parameters
float momentum
float weight_decay
float c_weight_decay
float max_norm_penalty
CBLAS_TRANSPOSE transpose_weights
Additional Inherited Members
Protected Attributes inherited from ANN::ANNComponent
string name
string weights_name
unsigned int input_size
unsigned int output_size
bool use_cuda
Static Protected Attributes inherited from ANN::ANNComponent
static unsigned int next_name_id = 1
static unsigned int next_weights_id = 1
Constructor & Destructor Documentation
ANN::DotProductANNComponent::DotProductANNComponent (const char * name = 0, const char * weights_name = 0, unsigned int input_size = 0, unsigned int output_size = 0, bool transpose_weights = false)
References ANN::ANNComponent::generateDefaultWeightsName(), and transpose_weights.
Referenced by clone().
ANN::DotProductANNComponent::~DotProductANNComponent () virtual
References DecRef, error_input, error_output, input, output, and weights_matrix.
Member Function Documentation
void ANN::DotProductANNComponent::build (unsigned int _input_size, unsigned int _output_size, hash< string, Connections * > & weights_dict, hash< string, ANNComponent * > & components_dict) virtual
Abstract method to finish building of component hierarchy and set weights objects pointers. All childs which rewrite this method must call parent method before do anything.
Reimplemented from ANN::ANNComponent.
References AssignRef, ANN::ANNComponent::build(), april_utils::string::c_str(), ANN::Connections::checkInputOutputSizes(), ANN::Connections::countReference(), ERROR_EXIT1, ERROR_EXIT3, IncRef, ANN::ANNComponent::input_size, ANN::ANNComponent::name, ANN::ANNComponent::output_size, april_utils::swap(), transpose_weights, weights_matrix, and ANN::ANNComponent::weights_name.
Referenced by ANN::HyperplaneANNComponent::build().
ANNComponent * ANN::DotProductANNComponent::clone () virtual
Reimplemented from ANN::ANNComponent.
References april_utils::string::c_str(), c_weight_decay, DotProductANNComponent(), ANN::ANNComponent::input_size, learning_rate, max_norm_penalty, momentum, ANN::ANNComponent::name, ANN::ANNComponent::output_size, transpose_weights, weight_decay, and ANN::ANNComponent::weights_name.
Referenced by ANN::HyperplaneANNComponent::clone().
void ANN::DotProductANNComponent::computeBP (MatrixFloat * weights_mat, Token * input_token, MatrixFloat * error_input_mat, const float alpha, const float beta) private
References Matrix< T >::axpy(), april_utils::string::c_str(), Token::convertTo(), ERROR_EXIT1, Matrix< T >::gemm(), Matrix< T >::ger(), Matrix< T >::getDimSize(), TokenMatrix< T >::getMatrix(), ANN::ANNComponent::input_size, ANN::ANNComponent::name, Matrix< T >::scal(), Matrix< T >::select(), TokenVector< T >::size(), sparse_input, and transpose_weights.
Referenced by computeGradients(), and doUpdate().
void ANN::DotProductANNComponent::computeGradients (MatrixFloat *& weight_grads) protected virtual
Method which computes the gradient of the weights on the given MatrixFloat object
Reimplemented from ANN::ANNComponent.
References Matrix< T >::cloneOnlyDims(), computeBP(), ERROR_EXIT, error_input, Matrix< T >::getDimSize(), TokenMatrix< T >::getMatrix(), ANN::Connections::getPtr(), input, Matrix< T >::sameDim(), weights_matrix, and Matrix< T >::zeros().
void ANN::DotProductANNComponent::copyWeights (hash< string, Connections * > & weights_dict) virtual
Abstract method to retrieve Connections objects from ANNComponents.
Reimplemented from ANN::ANNComponent.
References april_utils::string::c_str(), ERROR_EXIT1, ERROR_EXIT2, ANN::ANNComponent::name, weights_matrix, and ANN::ANNComponent::weights_name.
Referenced by ANN::HyperplaneANNComponent::copyWeights().
Token * ANN::DotProductANNComponent::doBackprop (Token * input_error) virtual
Virtual method that back-propagates error derivatives and computes other useful stuff. Receives input error gradients, and returns its output error gradients Token.
Reimplemented from ANN::ANNComponent.
References ASSERT_MATRIX, AssignRef, april_utils::string::c_str(), Matrix< T >::clone(), Token::convertTo(), DecRef, ERROR_EXIT1, error_input, error_output, Matrix< T >::gemm(), Matrix< T >::gemv(), Matrix< T >::getDimSize(), TokenMatrix< T >::getMatrix(), ANN::Connections::getPtr(), Matrix< T >::getStrideSize(), Token::getTokenCode(), ANN::ANNComponent::input_size, ANN::ANNComponent::name, NEGATE_CBLAS_TRANSPOSE, output, ANN::ANNComponent::output_size, Matrix< T >::sameDim(), Matrix< T >::setUseCuda(), sparse_input, table_of_token_codes::token_matrix, transpose_weights, ANN::ANNComponent::use_cuda, and weights_matrix.
Referenced by ANN::HyperplaneANNComponent::doBackprop().
Token * ANN::DotProductANNComponent::doForward (Token * input, bool during_training) virtual
Virtual method that executes the set of operations required for each block of connections when performing the forward step of the Backpropagation algorithm, and returns its output Token
Reimplemented from ANN::ANNComponent.
References ASSERT_MATRIX, AssignRef, Matrix< T >::axpy(), april_utils::string::c_str(), Token::convertTo(), ERROR_EXIT1, ERROR_EXIT2, Matrix< T >::gemm(), Matrix< T >::gemv(), TokenMatrix< T >::getMatrix(), ANN::Connections::getPtr(), Token::getTokenCode(), input, ANN::ANNComponent::input_size, ANN::ANNComponent::name, NEGATE_CBLAS_TRANSPOSE, output, ANN::ANNComponent::output_size, TokenVector< T >::push_back(), Matrix< T >::select(), Matrix< T >::setUseCuda(), TokenVector< T >::size(), sparse_input, table_of_token_codes::token_matrix, transpose_weights, ANN::ANNComponent::use_cuda, table_of_token_codes::vector_float_sparse, table_of_token_codes::vector_Tokens, and weights_matrix.
Referenced by ANN::HyperplaneANNComponent::doForward().
void ANN::DotProductANNComponent::doUpdate () virtual
Virtual method that update weights given gradients and input/output data
Reimplemented from ANN::ANNComponent.
References ANN::Connections::applyMaxNormPenalty(), ANN::Connections::beginUpdate(), c_weight_decay, computeBP(), ANN::Connections::computeMomentumOnPrevVector(), ANN::Connections::computeWeightDecayOnPrevVector(), ANN::Connections::copyToPrevVector(), ANN::Connections::endUpdate(), error_input, Matrix< T >::getDimSize(), TokenMatrix< T >::getMatrix(), ANN::Connections::getNumReferences(), ANN::Connections::getPrevPtr(), ANN::Connections::getPtr(), input, ANN::Connections::isFirstUpdateCall(), learning_rate, max_norm_penalty, MAX_UPDATES_WITHOUT_PRUNE, momentum, num_updates_from_last_prune, ANN::ANNComponent::output_size, ANN::Connections::pruneSubnormalAndCheckNormal(), ANN::ANNComponent::use_cuda, and weights_matrix.
Referenced by ANN::HyperplaneANNComponent::doUpdate().
virtual Token* ANN::DotProductANNComponent::getErrorInput () inline virtual
Reimplemented from ANN::ANNComponent.
References error_input.
virtual Token* ANN::DotProductANNComponent::getErrorOutput () inline virtual
Reimplemented from ANN::ANNComponent.
References error_output.
Referenced by ANN::HyperplaneANNComponent::getErrorOutput().
virtual Token* ANN::DotProductANNComponent::getInput () inline virtual
Reimplemented from ANN::ANNComponent.
References input.
Referenced by ANN::HyperplaneANNComponent::getInput().
double ANN::DotProductANNComponent::getOption (const char * name) virtual
Virtual method for getting the value of a training parameter. All childs which rewrite this method must call parent method after their process, if the looked option is not found to show the error message.
Reimplemented from ANN::ANNComponent.
References ANN::ANNComponent::getOption(), learning_rate, LEARNING_RATE_STRING, max_norm_penalty, MAX_NORM_PENALTY_STRING, mGetOption, momentum, MOMENTUM_STRING, weight_decay, and WEIGHT_DECAY_STRING.
Referenced by ANN::HyperplaneANNComponent::getOption().
virtual Token* ANN::DotProductANNComponent::getOutput () inline virtual
Reimplemented from ANN::ANNComponent.
References output.
bool ANN::DotProductANNComponent::hasOption (const char * name) virtual
Virtual method for determining if a training parameter is being used or can be used within the network.
Reimplemented from ANN::ANNComponent.
References LEARNING_RATE_STRING, MAX_NORM_PENALTY_STRING, mHasOption, MOMENTUM_STRING, and WEIGHT_DECAY_STRING.
Referenced by ANN::HyperplaneANNComponent::getOption(), and ANN::HyperplaneANNComponent::hasOption().
void ANN::DotProductANNComponent::reset () virtual
Virtual method to reset to zero gradients and outputs (inputs are not reseted)
Reimplemented from ANN::ANNComponent.
References DecRef, error_input, error_output, input, and output.
Referenced by ANN::HyperplaneANNComponent::reset().
virtual void ANN::DotProductANNComponent::resetConnections () inline virtual
Reimplemented from ANN::ANNComponent.
References ANN::Connections::reset(), and weights_matrix.
Referenced by ANN::HyperplaneANNComponent::resetConnections().
void ANN::DotProductANNComponent::setOption (const char * name, double value) virtual
Virtual method for setting the value of a training parameter.
Reimplemented from ANN::ANNComponent.
References c_weight_decay, learning_rate, LEARNING_RATE_STRING, max_norm_penalty, MAX_NORM_PENALTY_STRING, momentum, MOMENTUM_STRING, mSetOption, ANN::ANNComponent::setOption(), weight_decay, and WEIGHT_DECAY_STRING.
Referenced by ANN::HyperplaneANNComponent::setOption().
char * ANN::DotProductANNComponent::toLuaString () virtual
Reimplemented from ANN::ANNComponent.
References april_utils::string::c_str(), ANN::ANNComponent::input_size, ANN::ANNComponent::name, buffer_list::NULL_TERMINATED, ANN::ANNComponent::output_size, buffer_list::printf(), buffer_list::to_string(), transpose_weights, and ANN::ANNComponent::weights_name.
bool ANN::DotProductANNComponent::transposed () inline
References transpose_weights.
Referenced by ANN::HyperplaneANNComponent::toLuaString().
Member Data Documentation
float ANN::DotProductANNComponent::c_weight_decay private
Referenced by clone(), doUpdate(), and setOption().
TokenMatrixFloat* ANN::DotProductANNComponent::error_input private
Referenced by computeGradients(), doBackprop(), doUpdate(), getErrorInput(), reset(), and ~DotProductANNComponent().
TokenMatrixFloat * ANN::DotProductANNComponent::error_output private
Referenced by doBackprop(), getErrorOutput(), reset(), and ~DotProductANNComponent().
Token* ANN::DotProductANNComponent::input private
Referenced by computeGradients(), doForward(), doUpdate(), getInput(), reset(), and ~DotProductANNComponent().
float ANN::DotProductANNComponent::learning_rate private
learning parameters
Referenced by clone(), doUpdate(), getOption(), and setOption().
float ANN::DotProductANNComponent::max_norm_penalty private
Referenced by clone(), doUpdate(), getOption(), and setOption().
float ANN::DotProductANNComponent::momentum private
Referenced by clone(), doUpdate(), getOption(), and setOption().
unsigned int ANN::DotProductANNComponent::num_updates_from_last_prune private
Referenced by doUpdate().
TokenMatrixFloat * ANN::DotProductANNComponent::output private
Referenced by doBackprop(), doForward(), getOutput(), reset(), and ~DotProductANNComponent().
bool ANN::DotProductANNComponent::sparse_input private
Referenced by computeBP(), doBackprop(), and doForward().
CBLAS_TRANSPOSE ANN::DotProductANNComponent::transpose_weights private
Referenced by build(), clone(), computeBP(), doBackprop(), doForward(), DotProductANNComponent(), toLuaString(), and transposed().
float ANN::DotProductANNComponent::weight_decay private
Referenced by clone(), getOption(), and setOption().
Connections* ANN::DotProductANNComponent::weights_matrix private
Referenced by build(), computeGradients(), copyWeights(), doBackprop(), doForward(), doUpdate(), resetConnections(), and ~DotProductANNComponent().