april-ann
ANN::GaussianNoiseANNComponent Class Reference
Public Member Functions
GaussianNoiseANNComponent (MTRand *random, float mean, float variance, const char *name=0, unsigned int size=0)
virtual ~GaussianNoiseANNComponent ()
virtual Token * getInput ()
virtual Token * getOutput ()
virtual Token * getErrorInput ()
virtual Token * getErrorOutput ()
virtual Token * doForward (Token *input, bool during_training)
virtual Token * doBackprop (Token *input_error)
virtual void reset ()
virtual ANNComponent * clone ()
virtual void build (unsigned int _input_size, unsigned int _output_size, hash< string, Connections * > &weights_dict, hash< string, ANNComponent * > &components_dict)
virtual char * toLuaString ()
Public Member Functions inherited from ANN::ANNComponent
ANNComponent (const char *name=0, const char *weights_name=0, unsigned int input_size=0, unsigned int output_size=0)
virtual ~ANNComponent ()
const string & getName () const
const string & getWeightsName () const
bool hasWeightsName () const
bool getIsBuilt () const
void generateDefaultWeightsName (string &dest, const char *prefix=0)
unsigned int getInputSize () const
unsigned int getOutputSize () const
virtual void doUpdate ()
virtual void computeAllGradients (hash< string, MatrixFloat * > &weight_grads_dict)
virtual void setUseCuda (bool v)
bool getUseCuda () const
virtual void setOption (const char *name, double value)
Virtual method for setting the value of a training parameter.
virtual bool hasOption (const char *name)
virtual double getOption (const char *name)
virtual void copyWeights (hash< string, Connections * > &weights_dict)
Abstract method to retrieve Connections objects from ANNComponents.
virtual void copyComponents (hash< string, ANNComponent * > &components_dict)
virtual void resetConnections ()
virtual void debugInfo ()
virtual ANNComponent * getComponent (string &name)
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Attributes
MTRand * random
TokenMatrixFloat * input
TokenMatrixFloat * output
Token * error_input
Token * error_output
float mean
float variance
Additional Inherited Members
Protected Member Functions inherited from ANN::ANNComponent
virtual void computeGradients (MatrixFloat *&weight_grads)
Protected Attributes inherited from ANN::ANNComponent
string name
string weights_name
unsigned int input_size
unsigned int output_size
bool use_cuda
Static Protected Attributes inherited from ANN::ANNComponent
static unsigned int next_name_id = 1
static unsigned int next_weights_id = 1
Constructor & Destructor Documentation
ANN::GaussianNoiseANNComponent::GaussianNoiseANNComponent (MTRand * random, float mean, float variance, const char * name = 0, unsigned int size = 0)
References IncRef.
Referenced by clone().
ANN::GaussianNoiseANNComponent::~GaussianNoiseANNComponent () virtual
References DecRef, error_input, error_output, input, output, and random.
Member Function Documentation
void ANN::GaussianNoiseANNComponent::build (unsigned int _input_size, unsigned int _output_size, hash< string, Connections * > & weights_dict, hash< string, ANNComponent * > & components_dict) virtual
Abstract method to finish building of component hierarchy and set weights objects pointers. All childs which rewrite this method must call parent method before do anything.
Reimplemented from ANN::ANNComponent.
References ANN::ANNComponent::build(), april_utils::string::c_str(), ERROR_EXIT3, ANN::ANNComponent::input_size, ANN::ANNComponent::name, and ANN::ANNComponent::output_size.
ANNComponent * ANN::GaussianNoiseANNComponent::clone () virtual
Reimplemented from ANN::ANNComponent.
References april_utils::string::c_str(), GaussianNoiseANNComponent(), ANN::ANNComponent::input_size, mean, ANN::ANNComponent::name, random, and variance.
Token * ANN::GaussianNoiseANNComponent::doBackprop (Token * input_error) virtual
Virtual method that back-propagates error derivatives and computes other useful stuff. Receives input error gradients, and returns its output error gradients Token.
Reimplemented from ANN::ANNComponent.
References AssignRef, error_input, and error_output.
Token * ANN::GaussianNoiseANNComponent::doForward (Token * input, bool during_training) virtual
Virtual method that executes the set of operations required for each block of connections when performing the forward step of the Backpropagation algorithm, and returns its output Token
Reimplemented from ANN::ANNComponent.
References AssignRef, Matrix< T >::axpy(), Matrix< T >::begin(), april_utils::string::c_str(), Matrix< T >::cloneOnlyDims(), Token::convertTo(), Matrix< T >::end(), ERROR_EXIT1, Matrix< T >::getMajorOrder(), TokenMatrix< T >::getMatrix(), Token::getTokenCode(), input, mean, ANN::ANNComponent::name, output, MTRand::randNorm(), random, table_of_token_codes::token_matrix, ANN::ANNComponent::use_cuda, and variance.
virtual Token* ANN::GaussianNoiseANNComponent::getErrorInput () inline virtual
Reimplemented from ANN::ANNComponent.
References error_input.
virtual Token* ANN::GaussianNoiseANNComponent::getErrorOutput () inline virtual
Reimplemented from ANN::ANNComponent.
References error_output.
virtual Token* ANN::GaussianNoiseANNComponent::getInput () inline virtual
Reimplemented from ANN::ANNComponent.
References input.
virtual Token* ANN::GaussianNoiseANNComponent::getOutput () inline virtual
Reimplemented from ANN::ANNComponent.
References output.
void ANN::GaussianNoiseANNComponent::reset () virtual
Virtual method to reset to zero gradients and outputs (inputs are not reseted)
Reimplemented from ANN::ANNComponent.
References DecRef, error_input, error_output, input, and output.
char * ANN::GaussianNoiseANNComponent::toLuaString () virtual
Reimplemented from ANN::ANNComponent.
References april_utils::string::c_str(), ANN::ANNComponent::input_size, ANN::ANNComponent::name, buffer_list::NULL_TERMINATED, buffer_list::printf(), and buffer_list::to_string().
Member Data Documentation
Token* ANN::GaussianNoiseANNComponent::error_input private
Referenced by doBackprop(), getErrorInput(), reset(), and ~GaussianNoiseANNComponent().
Token * ANN::GaussianNoiseANNComponent::error_output private
Referenced by doBackprop(), getErrorOutput(), reset(), and ~GaussianNoiseANNComponent().
TokenMatrixFloat* ANN::GaussianNoiseANNComponent::input private
Referenced by doForward(), getInput(), reset(), and ~GaussianNoiseANNComponent().
float ANN::GaussianNoiseANNComponent::mean private
Referenced by clone(), and doForward().
TokenMatrixFloat * ANN::GaussianNoiseANNComponent::output private
Referenced by doForward(), getOutput(), reset(), and ~GaussianNoiseANNComponent().
MTRand* ANN::GaussianNoiseANNComponent::random private
Referenced by clone(), doForward(), and ~GaussianNoiseANNComponent().
float ANN::GaussianNoiseANNComponent::variance private
Referenced by clone(), and doForward().