april-ann
april_utils::maxiphobic_minheap< T > Class Template Reference
Classes
struct node
Public Member Functions
maxiphobic_minheap ()
maxiphobic_minheap (const maxiphobic_minheap &other)
maxiphobic_minheap & operator= (const maxiphobic_minheap &other)
~maxiphobic_minheap ()
void clear ()
void insert (const T &data)
void delete_min ()
T read_min ()
T extract_min ()
void foreach (void(*func)(T))
bool empty () const
int size () const
Private Member Functions
void delete_tree (node *n)
node * copy (node *other)
Static Private Member Functions
static node * merge (node *node1, node *node2)
Private Attributes
node * root
Constructor & Destructor Documentation
template<typename T > april_utils::maxiphobic_minheap< T >::maxiphobic_minheap () inline
template<typename T > april_utils::maxiphobic_minheap< T >::maxiphobic_minheap (const maxiphobic_minheap< T > & other) inline
References april_utils::maxiphobic_minheap< T >::copy(), and april_utils::maxiphobic_minheap< T >::root.
template<typename T > april_utils::maxiphobic_minheap< T >::~maxiphobic_minheap () inline
References april_utils::maxiphobic_minheap< T >::delete_tree(), and april_utils::maxiphobic_minheap< T >::root.
Member Function Documentation
template<typename T > void april_utils::maxiphobic_minheap< T >::clear () inline
References april_utils::maxiphobic_minheap< T >::delete_tree(), and april_utils::maxiphobic_minheap< T >::root.
template<typename T > node* april_utils::maxiphobic_minheap< T >::copy (node * other) inline private
References april_utils::maxiphobic_minheap< T >::node::data, april_utils::maxiphobic_minheap< T >::node::left, and april_utils::maxiphobic_minheap< T >::node::right.
Referenced by april_utils::maxiphobic_minheap< T >::maxiphobic_minheap(), and april_utils::maxiphobic_minheap< T >::operator=().
template<typename T > void april_utils::maxiphobic_minheap< T >::delete_min () inline
References april_utils::maxiphobic_minheap< T >::node::left, april_utils::maxiphobic_minheap< T >::merge(), april_utils::maxiphobic_minheap< T >::node::right, and april_utils::maxiphobic_minheap< T >::root.
Referenced by april_utils::maxiphobic_minheap< T >::extract_min().
template<typename T > void april_utils::maxiphobic_minheap< T >::delete_tree (node * n) inline private
References april_utils::maxiphobic_minheap< T >::node::left, and april_utils::maxiphobic_minheap< T >::node::right.
Referenced by april_utils::maxiphobic_minheap< T >::clear(), april_utils::maxiphobic_minheap< T >::operator=(), and april_utils::maxiphobic_minheap< T >::~maxiphobic_minheap().
template<typename T > bool april_utils::maxiphobic_minheap< T >::empty () const inline
References april_utils::maxiphobic_minheap< T >::root.
Referenced by april_utils::maxiphobic_minheap< T >::size().
template<typename T > T april_utils::maxiphobic_minheap< T >::extract_min () inline
References april_utils::maxiphobic_minheap< T >::delete_min(), and april_utils::maxiphobic_minheap< T >::read_min().
template<typename T > void april_utils::maxiphobic_minheap< T >::foreach (void(*)(T) func) inline
References april_utils::vector< T >::back(), april_utils::maxiphobic_minheap< T >::node::data, april_utils::vector< T >::empty(), april_utils::maxiphobic_minheap< T >::node::left, april_utils::vector< T >::pop_back(), april_utils::vector< T >::push_back(), april_utils::vector< T >::reserve(), april_utils::maxiphobic_minheap< T >::node::right, april_utils::maxiphobic_minheap< T >::root, and april_utils::maxiphobic_minheap< T >::node::size.
template<typename T > void april_utils::maxiphobic_minheap< T >::insert (const T & data) inline
References april_utils::maxiphobic_minheap< T >::merge(), and april_utils::maxiphobic_minheap< T >::root.
template<typename T > static node* april_utils::maxiphobic_minheap< T >::merge (node * node1, node * node2) inline static private
References april_utils::maxiphobic_minheap< T >::node::data, april_utils::maxiphobic_minheap< T >::node::left, april_utils::min(), april_utils::maxiphobic_minheap< T >::node::right, april_utils::maxiphobic_minheap< T >::node::size, and april_utils::swap().
Referenced by april_utils::maxiphobic_minheap< T >::delete_min(), and april_utils::maxiphobic_minheap< T >::insert().
template<typename T > maxiphobic_minheap& april_utils::maxiphobic_minheap< T >::operator= (const maxiphobic_minheap< T > & other) inline
References april_utils::maxiphobic_minheap< T >::copy(), april_utils::maxiphobic_minheap< T >::delete_tree(), and april_utils::maxiphobic_minheap< T >::root.
template<typename T > T april_utils::maxiphobic_minheap< T >::read_min () inline
References april_utils::maxiphobic_minheap< T >::node::data, and april_utils::maxiphobic_minheap< T >::root.
Referenced by april_utils::maxiphobic_minheap< T >::extract_min().
template<typename T > int april_utils::maxiphobic_minheap< T >::size () const inline
References april_utils::maxiphobic_minheap< T >::empty(), april_utils::maxiphobic_minheap< T >::root, and april_utils::maxiphobic_minheap< T >::node::size.
Member Data Documentation
template<typename T > node* april_utils::maxiphobic_minheap< T >::root private
Referenced by april_utils::maxiphobic_minheap< T >::clear(), april_utils::maxiphobic_minheap< T >::delete_min(), april_utils::maxiphobic_minheap< T >::empty(), april_utils::maxiphobic_minheap< T >::foreach(), april_utils::maxiphobic_minheap< T >::insert(), april_utils::maxiphobic_minheap< T >::maxiphobic_minheap(), april_utils::maxiphobic_minheap< T >::operator=(), april_utils::maxiphobic_minheap< T >::read_min(), april_utils::maxiphobic_minheap< T >::size(), and april_utils::maxiphobic_minheap< T >::~maxiphobic_minheap().