april-ann
TokenMatrix< T > Class Template Reference
Tokens
Public Member Functions
TokenMatrix (Matrix< T > *mat)
~TokenMatrix ()
Matrix< T > * getMatrix ()
const Matrix< T > * getMatrix () const
unsigned int size () const
Token * clone () const
This method implements a deep copy.
buffer_list * toString ()
Abstract method for serialization purposes.
buffer_list * debugString (const char *prefix, int debugLevel)
FOR DEBUG PURPOSES.
TokenCode getTokenCode () const
Abstract method which indicates the TokenCode of child Token classes.
bool getCudaFlag ()
void printDebug ()
Public Member Functions inherited from Token
Token ()
virtual ~Token ()
template<typename T >
bool isA () const
template<typename T >
T convertTo ()
template<typename T >
const T convertTo () const
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Static Public Member Functions
static Token * fromString (constString &cs)
Private Attributes
Matrix< T > * mat
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Member Function Documentation
template<typename T > static Token* TokenMatrix< T >::fromString (constString & cs) inline static
template<typename T > bool TokenMatrix< T >::getCudaFlag () inline
References TokenMatrix< T >::mat.
template<typename T > Matrix<T>* TokenMatrix< T >::getMatrix () inline
References TokenMatrix< T >::mat.
Referenced by ANN::JoinANNComponent::buildErrorInputBunchVector(), ANN::JoinANNComponent::buildInputBunchVector(), ANN::DotProductANNComponent::computeBP(), ANN::BiasANNComponent::computeGradients(), ANN::DotProductANNComponent::computeGradients(), ANN::ConvolutionBiasANNComponent::computeGradients(), ANN::ConvolutionANNComponent::computeGradients(), ANN::SelectANNComponent::doBackprop(), ANN::FlattenANNComponent::doBackprop(), ANN::RewrapANNComponent::doBackprop(), ANN::CopyANNComponent::doBackprop(), ANN::BiasANNComponent::doBackprop(), ANN::DotProductANNComponent::doBackprop(), ANN::ActivationFunctionANNComponent::doBackprop(), ANN::ConvolutionBiasANNComponent::doBackprop(), ANN::MaxPoolingANNComponent::doBackprop(), ANN::ConvolutionANNComponent::doBackprop(), ANN::RewrapANNComponent::doForward(), ANN::FlattenANNComponent::doForward(), ANN::SelectANNComponent::doForward(), ANN::GaussianNoiseANNComponent::doForward(), ANN::SaltAndPepperANNComponent::doForward(), ANN::BiasANNComponent::doForward(), ANN::ActivationFunctionANNComponent::doForward(), ANN::DotProductANNComponent::doForward(), ANN::ConvolutionBiasANNComponent::doForward(), ANN::MaxPoolingANNComponent::doForward(), ANN::ConvolutionANNComponent::doForward(), ANN::BiasANNComponent::doUpdate(), ANN::DotProductANNComponent::doUpdate(), ANN::ConvolutionBiasANNComponent::doUpdate(), ANN::ConvolutionANNComponent::doUpdate(), DataSetToken::getPatternBunch(), DataSetFloat2TokenWrapper::putPattern(), DataSetFloat2TokenWrapper::putPatternBunch(), and ANN::LossFunction::throwErrorAndGetMatrixFromTokens().
template<typename T > const Matrix<T>* TokenMatrix< T >::getMatrix () const inline
References TokenMatrix< T >::mat.
template<typename T > void TokenMatrix< T >::printDebug () inline
template<typename T > unsigned int TokenMatrix< T >::size () const inline
References TokenMatrix< T >::mat.
Referenced by ANN::LossFunction::throwErrorAndGetMatrixFromTokens().
Member Data Documentation
template<typename T > Matrix<T>* TokenMatrix< T >::mat private
Referenced by TokenMatrix< T >::getCudaFlag(), TokenMatrix< T >::getMatrix(), and TokenMatrix< T >::size().