april-ann
ANN::ActivationsAction Class Reference
Public Member Functions
ActivationsAction (const ANNConfiguration &conf, ActivationUnits *units, ActivationFunction *act_func)
virtual ~ActivationsAction ()
virtual void doForward ()
virtual void doBackward ()
virtual Action * clone (hash< void *, void * > &clone_dict, const ANNConfiguration &conf)
Public Member Functions inherited from ANN::Action
Action (const ANNConfiguration &conf)
virtual ~Action ()
virtual void setOption (const char *name, double value)
virtual bool hasOption (const char *name)
virtual double getOption (const char *name)
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Attributes
ActivationUnits * units
ActivationFunction * act_func
Additional Inherited Members
Protected Attributes inherited from ANN::Action
const ANNConfiguration & conf
Constructor & Destructor Documentation
ANN::ActivationsAction::ActivationsAction (const ANNConfiguration & conf, ActivationUnits * units, ActivationFunction * act_func)
References IncRef.
Referenced by clone().
ANN::ActivationsAction::~ActivationsAction () virtual
References act_func, DecRef, and units.
Member Function Documentation
Action * ANN::ActivationsAction::clone (hash< void *, void * > & clone_dict, const ANNConfiguration & conf) virtual
Implements ANN::Action.
References act_func, ActivationsAction(), ANN::ActivationFunction::clone(), and units.
void ANN::ActivationsAction::doBackward () virtual
Implements ANN::Action.
References act_func, ANN::Action::conf, ANN::ActivationUnits::getErrorVectorPtr(), ANN::ActivationUnits::getPtr(), ANN::ActivationFunction::multiplyDerivatives(), ANN::ActivationUnits::size(), units, and ANNConfiguration::use_cuda_flag.
void ANN::ActivationsAction::doForward () virtual
Implements ANN::Action.
References act_func, ANN::ActivationFunction::applyActivation(), ANN::Action::conf, ANN::ActivationUnits::getPtr(), ANN::ActivationUnits::size(), units, and ANNConfiguration::use_cuda_flag.
Member Data Documentation
ActivationFunction* ANN::ActivationsAction::act_func private
Referenced by clone(), doBackward(), doForward(), and ~ActivationsAction().
ActivationUnits* ANN::ActivationsAction::units private
Referenced by clone(), doBackward(), doForward(), and ~ActivationsAction().