april-ann
april_utils::Trie4lua Class Reference
Public Member Functions
Trie4lua ()
int reserveId ()
int find (int *wordsequence, int lenght)
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Types
typedef hash< int_pair, int > hash_type
Private Attributes
int lastId
hash_type transition_t
Static Private Attributes
static const int rootNode = 0
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Member Typedef Documentation
typedef hash<int_pair, int> april_utils::Trie4lua::hash_type private
Constructor & Destructor Documentation
april_utils::Trie4lua::Trie4lua ()
References lastId, and rootNode.
Member Function Documentation
int april_utils::Trie4lua::find (int * wordsequence, int lenght)
References april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::find_and_add_pair(), april_utils::make_pair(), reserveId(), rootNode, april_utils::pair< T1, T2 >::second, and transition_t.
int april_utils::Trie4lua::reserveId ()
References lastId.
Referenced by find().
Member Data Documentation
int april_utils::Trie4lua::lastId private
Referenced by reserveId(), and Trie4lua().
const int april_utils::Trie4lua::rootNode = 0 static private
Referenced by find(), and Trie4lua().
hash_type april_utils::Trie4lua::transition_t private
Referenced by find().