april-ann
ANN::SelectANNComponent Class Reference
Public Member Functions
SelectANNComponent (int dimension, int index, const char *name=0)
virtual ~SelectANNComponent ()
virtual Token * getInput ()
virtual Token * getOutput ()
virtual Token * getErrorInput ()
virtual Token * getErrorOutput ()
virtual Token * doForward (Token *input, bool during_training)
virtual Token * doBackprop (Token *input_error)
virtual void reset ()
virtual ANNComponent * clone ()
virtual void build (unsigned int _input_size, unsigned int _output_size, hash< string, Connections * > &weights_dict, hash< string, ANNComponent * > &components_dict)
virtual char * toLuaString ()
Public Member Functions inherited from ANN::ANNComponent
ANNComponent (const char *name=0, const char *weights_name=0, unsigned int input_size=0, unsigned int output_size=0)
virtual ~ANNComponent ()
const string & getName () const
const string & getWeightsName () const
bool hasWeightsName () const
bool getIsBuilt () const
void generateDefaultWeightsName (string &dest, const char *prefix=0)
unsigned int getInputSize () const
unsigned int getOutputSize () const
virtual void doUpdate ()
virtual void computeAllGradients (hash< string, MatrixFloat * > &weight_grads_dict)
virtual void setUseCuda (bool v)
bool getUseCuda () const
virtual void setOption (const char *name, double value)
Virtual method for setting the value of a training parameter.
virtual bool hasOption (const char *name)
virtual double getOption (const char *name)
virtual void copyWeights (hash< string, Connections * > &weights_dict)
Abstract method to retrieve Connections objects from ANNComponents.
virtual void copyComponents (hash< string, ANNComponent * > &components_dict)
virtual void resetConnections ()
virtual void debugInfo ()
virtual ANNComponent * getComponent (string &name)
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Attributes
int dimension
int index
TokenMatrixFloat * input
TokenMatrixFloat * output
TokenMatrixFloat * error_input
TokenMatrixFloat * error_output
Additional Inherited Members
Protected Member Functions inherited from ANN::ANNComponent
virtual void computeGradients (MatrixFloat *&weight_grads)
Protected Attributes inherited from ANN::ANNComponent
string name
string weights_name
unsigned int input_size
unsigned int output_size
bool use_cuda
Static Protected Attributes inherited from ANN::ANNComponent
static unsigned int next_name_id = 1
static unsigned int next_weights_id = 1
Constructor & Destructor Documentation
ANN::SelectANNComponent::SelectANNComponent (int dimension, int index, const char * name = 0)
Referenced by clone().
ANN::SelectANNComponent::~SelectANNComponent () virtual
References DecRef, error_input, error_output, input, and output.
Member Function Documentation
void ANN::SelectANNComponent::build (unsigned int _input_size, unsigned int _output_size, hash< string, Connections * > & weights_dict, hash< string, ANNComponent * > & components_dict) virtual
Abstract method to finish building of component hierarchy and set weights objects pointers. All childs which rewrite this method must call parent method before do anything.
Reimplemented from ANN::ANNComponent.
References ANN::ANNComponent::build().
ANNComponent * ANN::SelectANNComponent::clone () virtual
Reimplemented from ANN::ANNComponent.
References april_utils::string::c_str(), dimension, index, ANN::ANNComponent::name, and SelectANNComponent().
Token * ANN::SelectANNComponent::doBackprop (Token * input_error) virtual
Virtual method that back-propagates error derivatives and computes other useful stuff. Receives input error gradients, and returns its output error gradients Token.
Reimplemented from ANN::ANNComponent.
References AssignRef, april_utils::string::c_str(), Token::convertTo(), Matrix< T >::copy(), DecRef, dimension, ERROR_EXIT1, error_input, error_output, TokenMatrix< T >::getMatrix(), Token::getTokenCode(), index, input, ANN::ANNComponent::name, output, Matrix< T >::select(), Matrix< T >::setUseCuda(), table_of_token_codes::token_matrix, ANN::ANNComponent::use_cuda, and Matrix< T >::zeros().
Token * ANN::SelectANNComponent::doForward (Token * input, bool during_training) virtual
Virtual method that executes the set of operations required for each block of connections when performing the forward step of the Backpropagation algorithm, and returns its output Token
Reimplemented from ANN::ANNComponent.
References AssignRef, april_utils::string::c_str(), Matrix< T >::clone(), Token::convertTo(), dimension, ERROR_EXIT1, ERROR_EXIT2, TokenMatrix< T >::getMatrix(), Matrix< T >::getNumDim(), Token::getTokenCode(), index, input, ANN::ANNComponent::name, output, Matrix< T >::select(), Matrix< T >::setUseCuda(), table_of_token_codes::token_matrix, and ANN::ANNComponent::use_cuda.
virtual Token* ANN::SelectANNComponent::getErrorInput () inline virtual
Reimplemented from ANN::ANNComponent.
References error_input.
virtual Token* ANN::SelectANNComponent::getErrorOutput () inline virtual
Reimplemented from ANN::ANNComponent.
References error_output.
virtual Token* ANN::SelectANNComponent::getInput () inline virtual
Reimplemented from ANN::ANNComponent.
References input.
virtual Token* ANN::SelectANNComponent::getOutput () inline virtual
Reimplemented from ANN::ANNComponent.
References output.
void ANN::SelectANNComponent::reset () virtual
Virtual method to reset to zero gradients and outputs (inputs are not reseted)
Reimplemented from ANN::ANNComponent.
References DecRef, error_input, error_output, input, and output.
char * ANN::SelectANNComponent::toLuaString () virtual
Reimplemented from ANN::ANNComponent.
References april_utils::string::c_str(), dimension, index, ANN::ANNComponent::name, buffer_list::NULL_TERMINATED, buffer_list::printf(), and buffer_list::to_string().
Member Data Documentation
int ANN::SelectANNComponent::dimension private
Referenced by clone(), doBackprop(), doForward(), and toLuaString().
TokenMatrixFloat * ANN::SelectANNComponent::error_input private
Referenced by doBackprop(), getErrorInput(), reset(), and ~SelectANNComponent().
TokenMatrixFloat * ANN::SelectANNComponent::error_output private
Referenced by doBackprop(), getErrorOutput(), reset(), and ~SelectANNComponent().
int ANN::SelectANNComponent::index private
Referenced by clone(), doBackprop(), doForward(), and toLuaString().
TokenMatrixFloat* ANN::SelectANNComponent::input private
Referenced by doBackprop(), doForward(), getInput(), reset(), and ~SelectANNComponent().
TokenMatrixFloat * ANN::SelectANNComponent::output private
Referenced by doBackprop(), doForward(), getOutput(), reset(), and ~SelectANNComponent().