april-ann
ANN::ConvolutionBiasANNComponent Class Reference
Public Member Functions
ConvolutionBiasANNComponent (int input_num_dims, unsigned int num_output_planes, const char *name=0, const char *bias_name=0)
virtual ~ConvolutionBiasANNComponent ()
virtual Token * getInput ()
virtual Token * getOutput ()
virtual Token * getErrorInput ()
virtual Token * getErrorOutput ()
virtual Token * doForward (Token *input, bool during_training)
virtual Token * doBackprop (Token *input_error)
virtual void doUpdate ()
virtual void reset ()
virtual ANNComponent * clone ()
virtual void setOption (const char *name, double value)
Virtual method for setting the value of a training parameter.
virtual bool hasOption (const char *name)
virtual double getOption (const char *name)
virtual void build (unsigned int input_size, unsigned int output_size, hash< string, Connections * > &weights_dict, hash< string, ANNComponent * > &components_dict)
virtual void copyWeights (hash< string, Connections * > &weights_dict)
Abstract method to retrieve Connections objects from ANNComponents.
virtual void resetConnections ()
virtual char * toLuaString ()
Public Member Functions inherited from ANN::ANNComponent
ANNComponent (const char *name=0, const char *weights_name=0, unsigned int input_size=0, unsigned int output_size=0)
virtual ~ANNComponent ()
const string & getName () const
const string & getWeightsName () const
bool hasWeightsName () const
bool getIsBuilt () const
void generateDefaultWeightsName (string &dest, const char *prefix=0)
unsigned int getInputSize () const
unsigned int getOutputSize () const
virtual void computeAllGradients (hash< string, MatrixFloat * > &weight_grads_dict)
virtual void setUseCuda (bool v)
bool getUseCuda () const
virtual void copyComponents (hash< string, ANNComponent * > &components_dict)
virtual void debugInfo ()
virtual ANNComponent * getComponent (string &name)
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Protected Member Functions
virtual void computeGradients (MatrixFloat *&weight_grads)
Private Member Functions
void initializeArrays (const int *input_dims)
MatrixFloat * prepareBiasBunch ()
void computeBP (MatrixFloat *weights_mat, MatrixFloat *error_mat, const float alpha)
Private Attributes
TokenMatrixFloat * input
TokenMatrixFloat * error
TokenMatrixFloat * output
Connections * bias_vector
MatrixFloat * bias_matrix
unsigned int num_updates_from_last_prune
int number_input_windows
The number of convolutions computed during last forward.
unsigned int hidden_size
int num_dims
int * window_size
int * window_step
int * window_num_steps
float learning_rate
learning parameters
float momentum
Additional Inherited Members
Protected Attributes inherited from ANN::ANNComponent
string name
string weights_name
unsigned int input_size
unsigned int output_size
bool use_cuda
Static Protected Attributes inherited from ANN::ANNComponent
static unsigned int next_name_id = 1
static unsigned int next_weights_id = 1
Constructor & Destructor Documentation
ANN::ConvolutionBiasANNComponent::ConvolutionBiasANNComponent (int input_num_dims, unsigned int num_output_planes, const char * name = 0, const char * bias_name = 0)
References ANN::ANNComponent::generateDefaultWeightsName(), hidden_size, num_dims, ANN::ANNComponent::weights_name, window_num_steps, window_size, and window_step.
Referenced by clone().
ANN::ConvolutionBiasANNComponent::~ConvolutionBiasANNComponent () virtual
References bias_matrix, bias_vector, DecRef, error, input, output, window_num_steps, window_size, and window_step.
Member Function Documentation
void ANN::ConvolutionBiasANNComponent::build (unsigned int _input_size, unsigned int _output_size, hash< string, Connections * > & weights_dict, hash< string, ANNComponent * > & components_dict) virtual
Abstract method to finish building of component hierarchy and set weights objects pointers. All childs which rewrite this method must call parent method before do anything.
Reimplemented from ANN::ANNComponent.
References AssignRef, bias_vector, ANN::ANNComponent::build(), april_utils::string::c_str(), ANN::Connections::checkInputOutputSizes(), ANN::Connections::countReference(), ERROR_EXIT2, hidden_size, IncRef, ANN::ANNComponent::name, and ANN::ANNComponent::weights_name.
ANNComponent * ANN::ConvolutionBiasANNComponent::clone () virtual
Reimplemented from ANN::ANNComponent.
References april_utils::string::c_str(), ConvolutionBiasANNComponent(), hidden_size, ANN::ANNComponent::input_size, learning_rate, momentum, ANN::ANNComponent::name, num_dims, ANN::ANNComponent::output_size, and ANN::ANNComponent::weights_name.
void ANN::ConvolutionBiasANNComponent::computeBP (MatrixFloat * weights_mat, MatrixFloat * error_mat, const float alpha) private
References DecRef, doSaxpyLoop(), Matrix< T >::getDimSize(), Matrix< T >::getOffset(), Matrix< T >::getRawDataAccess(), Matrix< T >::getStrideSize(), hidden_size, IncRef, number_input_windows, ANN::ANNComponent::use_cuda, window_num_steps, window_size, and window_step.
Referenced by computeGradients(), and doUpdate().
void ANN::ConvolutionBiasANNComponent::computeGradients (MatrixFloat *& weight_grads) protected virtual
Method which computes the gradient of the weights on the given MatrixFloat object
Reimplemented from ANN::ANNComponent.
References bias_vector, Matrix< T >::cloneOnlyDims(), computeBP(), error, TokenMatrix< T >::getMatrix(), ANN::Connections::getPtr(), and Matrix< T >::zeros().
void ANN::ConvolutionBiasANNComponent::copyWeights (hash< string, Connections * > & weights_dict) virtual
Abstract method to retrieve Connections objects from ANNComponents.
Reimplemented from ANN::ANNComponent.
References bias_vector, april_utils::string::c_str(), ERROR_EXIT1, ERROR_EXIT2, ANN::ANNComponent::name, and ANN::ANNComponent::weights_name.
Token * ANN::ConvolutionBiasANNComponent::doBackprop (Token * input_error) virtual
Virtual method that back-propagates error derivatives and computes other useful stuff. Receives input error gradients, and returns its output error gradients Token.
Reimplemented from ANN::ANNComponent.
References AssignRef, april_utils::string::c_str(), Token::convertTo(), error, ERROR_EXIT1, TokenMatrix< T >::getMatrix(), Token::getTokenCode(), ANN::ANNComponent::name, output, Matrix< T >::setUseCuda(), table_of_token_codes::token_matrix, and ANN::ANNComponent::use_cuda.
Token * ANN::ConvolutionBiasANNComponent::doForward (Token * input, bool during_training) virtual
Virtual method that executes the set of operations required for each block of connections when performing the forward step of the Backpropagation algorithm, and returns its output Token
Reimplemented from ANN::ANNComponent.
References AssignRef, Matrix< T >::axpy(), bias_matrix, bias_vector, april_utils::string::c_str(), Matrix< T >::clone(), Token::convertTo(), DecRef, ERROR_EXIT1, ERROR_EXIT3, Matrix< T >::getDimPtr(), TokenMatrix< T >::getMatrix(), Matrix< T >::getNumDim(), Token::getTokenCode(), hidden_size, IncRef, initializeArrays(), input, ANN::ANNComponent::name, num_dims, number_input_windows, output, prepareBiasBunch(), Matrix< T >::setUseCuda(), table_of_token_codes::token_matrix, ANN::ANNComponent::use_cuda, window_num_steps, window_size, and window_step.
void ANN::ConvolutionBiasANNComponent::doUpdate () virtual
Virtual method that update weights given gradients and input/output data
Reimplemented from ANN::ANNComponent.
References ANN::Connections::beginUpdate(), bias_vector, computeBP(), ANN::Connections::computeMomentumOnPrevVector(), ANN::Connections::computeWeightDecayOnPrevVector(), ANN::Connections::copyToPrevVector(), ANN::Connections::endUpdate(), error, Matrix< T >::getDimSize(), TokenMatrix< T >::getMatrix(), ANN::Connections::getNumReferences(), ANN::Connections::getPrevPtr(), ANN::Connections::isFirstUpdateCall(), learning_rate, MAX_UPDATES_WITHOUT_PRUNE, momentum, num_updates_from_last_prune, number_input_windows, ANN::Connections::pruneSubnormalAndCheckNormal(), and ANN::ANNComponent::use_cuda.
virtual Token* ANN::ConvolutionBiasANNComponent::getErrorInput () inline virtual
Reimplemented from ANN::ANNComponent.
References error.
virtual Token* ANN::ConvolutionBiasANNComponent::getErrorOutput () inline virtual
Reimplemented from ANN::ANNComponent.
References error.
virtual Token* ANN::ConvolutionBiasANNComponent::getInput () inline virtual
Reimplemented from ANN::ANNComponent.
References input.
double ANN::ConvolutionBiasANNComponent::getOption (const char * name) virtual
Virtual method for getting the value of a training parameter. All childs which rewrite this method must call parent method after their process, if the looked option is not found to show the error message.
Reimplemented from ANN::ANNComponent.
References ANN::ANNComponent::getOption(), learning_rate, LEARNING_RATE_STRING, mGetOption, momentum, and MOMENTUM_STRING.
virtual Token* ANN::ConvolutionBiasANNComponent::getOutput () inline virtual
Reimplemented from ANN::ANNComponent.
References output.
bool ANN::ConvolutionBiasANNComponent::hasOption (const char * name) virtual
Virtual method for determining if a training parameter is being used or can be used within the network.
Reimplemented from ANN::ANNComponent.
References LEARNING_RATE_STRING, mHasOption, and MOMENTUM_STRING.
void ANN::ConvolutionBiasANNComponent::initializeArrays (const int * input_dims) private
References num_dims, window_num_steps, and window_size.
Referenced by doForward().
MatrixFloat * ANN::ConvolutionBiasANNComponent::prepareBiasBunch () private
References bias_matrix, bias_vector, Matrix< T >::copy(), DecRef, Matrix< T >::getDimSize(), ANN::Connections::getPtr(), IncRef, num_dims, Matrix< T >::rewrap(), Matrix< T >::select(), and window_size.
Referenced by doForward().
void ANN::ConvolutionBiasANNComponent::reset () virtual
Virtual method to reset to zero gradients and outputs (inputs are not reseted)
Reimplemented from ANN::ANNComponent.
References DecRef, error, input, and output.
virtual void ANN::ConvolutionBiasANNComponent::resetConnections () inline virtual
Reimplemented from ANN::ANNComponent.
References bias_vector, and ANN::Connections::reset().
void ANN::ConvolutionBiasANNComponent::setOption (const char * name, double value) virtual
Virtual method for setting the value of a training parameter.
Reimplemented from ANN::ANNComponent.
References learning_rate, LEARNING_RATE_STRING, momentum, MOMENTUM_STRING, mSetOption, and ANN::ANNComponent::setOption().
char * ANN::ConvolutionBiasANNComponent::toLuaString () virtual
Reimplemented from ANN::ANNComponent.
References april_utils::string::c_str(), hidden_size, ANN::ANNComponent::name, buffer_list::NULL_TERMINATED, num_dims, buffer_list::printf(), buffer_list::to_string(), and ANN::ANNComponent::weights_name.
Member Data Documentation
MatrixFloat* ANN::ConvolutionBiasANNComponent::bias_matrix private
Referenced by doForward(), prepareBiasBunch(), and ~ConvolutionBiasANNComponent().
Connections* ANN::ConvolutionBiasANNComponent::bias_vector private
Referenced by build(), computeGradients(), copyWeights(), doForward(), doUpdate(), prepareBiasBunch(), resetConnections(), and ~ConvolutionBiasANNComponent().
TokenMatrixFloat * ANN::ConvolutionBiasANNComponent::error private
Referenced by computeGradients(), doBackprop(), doUpdate(), getErrorInput(), getErrorOutput(), reset(), and ~ConvolutionBiasANNComponent().
unsigned int ANN::ConvolutionBiasANNComponent::hidden_size private
Referenced by build(), clone(), computeBP(), ConvolutionBiasANNComponent(), doForward(), and toLuaString().
TokenMatrixFloat* ANN::ConvolutionBiasANNComponent::input private
Referenced by doForward(), getInput(), reset(), and ~ConvolutionBiasANNComponent().
float ANN::ConvolutionBiasANNComponent::learning_rate private
learning parameters
Referenced by clone(), doUpdate(), getOption(), and setOption().
float ANN::ConvolutionBiasANNComponent::momentum private
Referenced by clone(), doUpdate(), getOption(), and setOption().
int ANN::ConvolutionBiasANNComponent::num_dims private
Referenced by clone(), ConvolutionBiasANNComponent(), doForward(), initializeArrays(), prepareBiasBunch(), and toLuaString().
unsigned int ANN::ConvolutionBiasANNComponent::num_updates_from_last_prune private
Referenced by doUpdate().
int ANN::ConvolutionBiasANNComponent::number_input_windows private
The number of convolutions computed during last forward.
Referenced by computeBP(), doForward(), and doUpdate().
TokenMatrixFloat * ANN::ConvolutionBiasANNComponent::output private
Referenced by doBackprop(), doForward(), getOutput(), reset(), and ~ConvolutionBiasANNComponent().
int* ANN::ConvolutionBiasANNComponent::window_num_steps private
Referenced by computeBP(), ConvolutionBiasANNComponent(), doForward(), initializeArrays(), and ~ConvolutionBiasANNComponent().
int* ANN::ConvolutionBiasANNComponent::window_size private
Referenced by computeBP(), ConvolutionBiasANNComponent(), doForward(), initializeArrays(), prepareBiasBunch(), and ~ConvolutionBiasANNComponent().
int* ANN::ConvolutionBiasANNComponent::window_step private
Referenced by computeBP(), ConvolutionBiasANNComponent(), doForward(), and ~ConvolutionBiasANNComponent().