april-ann
Functions::DataProducer< T > Class Template Reference
A pure abstract templatized class that serves as interface.
Public Member Functions
virtual T * get ()=0
Returns a pointer and its property. A 0 inidicates data sequence ending.
virtual void reset ()=0
Reinitialize the sequence iterator if it is possible.
virtual void destroy ()
It destroys the object content and forces to return a 0 on next get().
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Detailed Description
template<typename T>
class Functions::DataProducer< T >
A pure abstract templatized class that serves as interface.
A DataProducer is an abstraction of an object which produces a sequence a vectors of a given type, followed by a 0 indicating sequence ending. The object could be reinitialized (if it is possible) using the reset method. Finally, it could be destroyed using destroy method.
Destroy method is needed to make feasible the destruction of a DataProducer without calling its destructor, forcing the object to send a 0 in the next get() call.
Member Function Documentation
template<typename T> virtual void Functions::DataProducer< T >::destroy () inline virtual
It destroys the object content and forces to return a 0 on next get().
Reimplemented in Functions::DataSetFloatProducer.
template<typename T> virtual T* Functions::DataProducer< T >::get () pure virtual
Returns a pointer and its property. A 0 inidicates data sequence ending.
Implemented in Functions::FloatContextualizerProducerFromDouble, and Functions::DataSetFloatProducer.
Referenced by ANN::ANNBase::calculateInPipeline(), Functions::FunctionInterface< I, O >::calculateInPipeline(), and Functions::FloatContextualizerProducerFromDouble::get().
template<typename T> virtual void Functions::DataProducer< T >::reset () pure virtual
Reinitialize the sequence iterator if it is possible.
Implemented in Functions::FloatContextualizerProducerFromDouble, and Functions::DataSetFloatProducer.
Referenced by Functions::FloatContextualizerProducerFromDouble::reset().