april-ann
april_utils::TrieOpenAddr< O > Class Template Reference
Classes
class iterator
Public Types
typedef
april_utils::open_addr_hash_timestamp
< int_pair, int > transitions_t
typedef april_utils::hash< int,
O >::iterator outputs_iterator
Public Member Functions
TrieOpenAddr (int num_nodes=8)
Reserva memoria, el tamanyo del Trie debe ser conocido a priori.
~TrieOpenAddr ()
Libera los recursos.
void clear ()
int get_state_level (int st)
int get_size ()
void insert (int orig, int dest, int key, int level)
Crea una transicion entre estados.
void set_state_output (int st, O value)
Guarda los outputs.
const O * get_state_output (int st)
Devuelve los outputs.
void insert (const int *key, O value, int key_size)
Inserta una secuencia en trie, y le asocia value como salida.
void insert (const int *key, int last_key, O value, int key_size)
Inserta una secuencia en trie, y le asocia value como salida.
void resize (int n)
bool search_transition (int current_node, int key, int &dest_node_id)
const O * find (const int *key, int key_size)
const O * find (const int *key, int last_key, int key_size)
bool search_dest_state (const int *key, int key_size, int &dest_node_id)
O & get (const int *key, int key_size)
iterator begin ()
iterator end ()
outputs_iterator begin_outputs ()
outputs_iterator end_outputs ()
Private Attributes
april_utils::open_addr_hash_timestamp
< int, O > outputs_tbl
transitions_t transitions_tbl
int * levels_tbl
int num_nodes
int next_node
Detailed Description
template<typename O>
class april_utils::TrieOpenAddr< O >
Plantilla para implementar un Trie generico, que guarda transiciones entre estados con el tipo int, y da como salida el tipo O.
Member Typedef Documentation
template<typename O > typedef april_utils::hash<int, O>::iterator april_utils::TrieOpenAddr< O >::outputs_iterator
template<typename O > typedef april_utils::open_addr_hash_timestamp<int_pair, int> april_utils::TrieOpenAddr< O >::transitions_t
Constructor & Destructor Documentation
template<typename O > april_utils::TrieOpenAddr< O >::TrieOpenAddr (int num_nodes = 8) inline
Reserva memoria, el tamanyo del Trie debe ser conocido a priori.
References april_utils::TrieOpenAddr< O >::levels_tbl, april_utils::TrieOpenAddr< O >::next_node, and april_utils::TrieOpenAddr< O >::num_nodes.
template<typename O > april_utils::TrieOpenAddr< O >::~TrieOpenAddr () inline
Libera los recursos.
References april_utils::TrieOpenAddr< O >::levels_tbl.
Member Function Documentation
template<typename O > iterator april_utils::TrieOpenAddr< O >::begin () inline
References april_utils::open_addr_hash_timestamp< KeyType, DataType, HashFcn, EqualKey >::begin(), and april_utils::TrieOpenAddr< O >::transitions_tbl.
template<typename O > outputs_iterator april_utils::TrieOpenAddr< O >::begin_outputs () inline
References april_utils::open_addr_hash_timestamp< KeyType, DataType, HashFcn, EqualKey >::begin(), and april_utils::TrieOpenAddr< O >::outputs_tbl.
template<typename O > void april_utils::TrieOpenAddr< O >::clear () inline
References april_utils::open_addr_hash_timestamp< KeyType, DataType, HashFcn, EqualKey >::clear(), april_utils::TrieOpenAddr< O >::next_node, april_utils::TrieOpenAddr< O >::outputs_tbl, and april_utils::TrieOpenAddr< O >::transitions_tbl.
template<typename O > iterator april_utils::TrieOpenAddr< O >::end () inline
References april_utils::open_addr_hash_timestamp< KeyType, DataType, HashFcn, EqualKey >::end(), and april_utils::TrieOpenAddr< O >::transitions_tbl.
template<typename O > outputs_iterator april_utils::TrieOpenAddr< O >::end_outputs () inline
References april_utils::open_addr_hash_timestamp< KeyType, DataType, HashFcn, EqualKey >::end(), and april_utils::TrieOpenAddr< O >::outputs_tbl.
template<typename O > const O* april_utils::TrieOpenAddr< O >::find (const int * key, int key_size) inline
Busca la secuencia determinada por key de tipo int *, de tamanyo key_size, y si la encuentra, y es un nodo de salida, devuelve el valor tipo O guardado en dicho nodo.
References april_utils::open_addr_hash_timestamp< KeyType, DataType, HashFcn, EqualKey >::find(), april_utils::TrieOpenAddr< O >::outputs_tbl, and april_utils::TrieOpenAddr< O >::transitions_tbl.
template<typename O > const O* april_utils::TrieOpenAddr< O >::find (const int * key, int last_key, int key_size) inline
Busca la secuencia determinada por key de tipo int *, de tamanyo key_size, y si la encuentra, y es un nodo de salida, devuelve el valor tipo O guardado en dicho nodo.
References april_utils::open_addr_hash_timestamp< KeyType, DataType, HashFcn, EqualKey >::find(), april_utils::TrieOpenAddr< O >::outputs_tbl, and april_utils::TrieOpenAddr< O >::transitions_tbl.
template<typename O > O& april_utils::TrieOpenAddr< O >::get (const int * key, int key_size) inline
Busca la secuencia determinada por key de tipo int *, de tamanyo key_size, y si la encuentra, y es un nodo de salida, devuelve el valor tipo O guardado en dicho nodo.
References april_utils::open_addr_hash_timestamp< KeyType, DataType, HashFcn, EqualKey >::find(), april_utils::TrieOpenAddr< O >::levels_tbl, april_utils::TrieOpenAddr< O >::next_node, april_utils::TrieOpenAddr< O >::num_nodes, april_utils::TrieOpenAddr< O >::outputs_tbl, april_utils::TrieOpenAddr< O >::resize(), and april_utils::TrieOpenAddr< O >::transitions_tbl.
template<typename O > int april_utils::TrieOpenAddr< O >::get_size () inline
References april_utils::TrieOpenAddr< O >::next_node.
template<typename O > int april_utils::TrieOpenAddr< O >::get_state_level (int st) inline
References april_utils::TrieOpenAddr< O >::levels_tbl.
template<typename O > const O* april_utils::TrieOpenAddr< O >::get_state_output (int st) inline
Devuelve los outputs.
References april_utils::open_addr_hash_timestamp< KeyType, DataType, HashFcn, EqualKey >::find(), and april_utils::TrieOpenAddr< O >::outputs_tbl.
template<typename O > void april_utils::TrieOpenAddr< O >::insert (int orig, int dest, int key, int level) inline
Crea una transicion entre estados.
References april_utils::TrieOpenAddr< O >::levels_tbl, april_utils::TrieOpenAddr< O >::next_node, april_utils::TrieOpenAddr< O >::num_nodes, april_utils::TrieOpenAddr< O >::resize(), and april_utils::TrieOpenAddr< O >::transitions_tbl.
template<typename O > void april_utils::TrieOpenAddr< O >::insert (const int * key, O value, int key_size) inline
Inserta una secuencia en trie, y le asocia value como salida.
References april_utils::open_addr_hash_timestamp< KeyType, DataType, HashFcn, EqualKey >::find(), april_utils::TrieOpenAddr< O >::levels_tbl, april_utils::TrieOpenAddr< O >::next_node, april_utils::TrieOpenAddr< O >::num_nodes, april_utils::TrieOpenAddr< O >::outputs_tbl, april_utils::TrieOpenAddr< O >::resize(), and april_utils::TrieOpenAddr< O >::transitions_tbl.
template<typename O > void april_utils::TrieOpenAddr< O >::insert (const int * key, int last_key, O value, int key_size) inline
Inserta una secuencia en trie, y le asocia value como salida.
References april_utils::open_addr_hash_timestamp< KeyType, DataType, HashFcn, EqualKey >::find(), april_utils::TrieOpenAddr< O >::levels_tbl, april_utils::TrieOpenAddr< O >::next_node, april_utils::TrieOpenAddr< O >::num_nodes, april_utils::TrieOpenAddr< O >::outputs_tbl, april_utils::TrieOpenAddr< O >::resize(), and april_utils::TrieOpenAddr< O >::transitions_tbl.
template<typename O > void april_utils::TrieOpenAddr< O >::resize (int n) inline
References april_utils::TrieOpenAddr< O >::levels_tbl, and april_utils::TrieOpenAddr< O >::num_nodes.
Referenced by april_utils::TrieOpenAddr< O >::get(), and april_utils::TrieOpenAddr< O >::insert().
template<typename O > bool april_utils::TrieOpenAddr< O >::search_dest_state (const int * key, int key_size, int & dest_node_id) inline
Busca la secuencia determinada por key de tipo int *, de tamanyo key_size, y si la encuentra, devuelve el estado destino
References april_utils::open_addr_hash_timestamp< KeyType, DataType, HashFcn, EqualKey >::find(), and april_utils::TrieOpenAddr< O >::transitions_tbl.
template<typename O > bool april_utils::TrieOpenAddr< O >::search_transition (int current_node, int key, int & dest_node_id) inline
References april_utils::open_addr_hash_timestamp< KeyType, DataType, HashFcn, EqualKey >::find(), and april_utils::TrieOpenAddr< O >::transitions_tbl.
template<typename O > void april_utils::TrieOpenAddr< O >::set_state_output (int st, O value) inline
Guarda los outputs.
References april_utils::TrieOpenAddr< O >::outputs_tbl.
Member Data Documentation
template<typename O > int* april_utils::TrieOpenAddr< O >::levels_tbl private
Referenced by april_utils::TrieOpenAddr< O >::get(), april_utils::TrieOpenAddr< O >::iterator::get_level(), april_utils::TrieOpenAddr< O >::get_state_level(), april_utils::TrieOpenAddr< O >::insert(), april_utils::TrieOpenAddr< O >::resize(), april_utils::TrieOpenAddr< O >::TrieOpenAddr(), and april_utils::TrieOpenAddr< O >::~TrieOpenAddr().
template<typename O > int april_utils::TrieOpenAddr< O >::next_node private
Referenced by april_utils::TrieOpenAddr< O >::clear(), april_utils::TrieOpenAddr< O >::get(), april_utils::TrieOpenAddr< O >::get_size(), april_utils::TrieOpenAddr< O >::insert(), and april_utils::TrieOpenAddr< O >::TrieOpenAddr().
template<typename O > int april_utils::TrieOpenAddr< O >::num_nodes private
Referenced by april_utils::TrieOpenAddr< O >::get(), april_utils::TrieOpenAddr< O >::insert(), april_utils::TrieOpenAddr< O >::resize(), and april_utils::TrieOpenAddr< O >::TrieOpenAddr().
template<typename O > april_utils::open_addr_hash_timestamp<int, O> april_utils::TrieOpenAddr< O >::outputs_tbl private
Referenced by april_utils::TrieOpenAddr< O >::begin_outputs(), april_utils::TrieOpenAddr< O >::clear(), april_utils::TrieOpenAddr< O >::end_outputs(), april_utils::TrieOpenAddr< O >::find(), april_utils::TrieOpenAddr< O >::get(), april_utils::TrieOpenAddr< O >::iterator::get_outputs(), april_utils::TrieOpenAddr< O >::get_state_output(), april_utils::TrieOpenAddr< O >::insert(), and april_utils::TrieOpenAddr< O >::set_state_output().
template<typename O > transitions_t april_utils::TrieOpenAddr< O >::transitions_tbl private
Referenced by april_utils::TrieOpenAddr< O >::begin(), april_utils::TrieOpenAddr< O >::clear(), april_utils::TrieOpenAddr< O >::end(), april_utils::TrieOpenAddr< O >::find(), april_utils::TrieOpenAddr< O >::get(), april_utils::TrieOpenAddr< O >::insert(), april_utils::TrieOpenAddr< O >::search_dest_state(), and april_utils::TrieOpenAddr< O >::search_transition().