april-ann
ANN::RewrapANNComponent Class Reference
Public Member Functions
RewrapANNComponent (const int *rewrap_dims, int n, const char *name=0)
virtual ~RewrapANNComponent ()
virtual Token * getInput ()
virtual Token * getOutput ()
virtual Token * getErrorInput ()
virtual Token * getErrorOutput ()
virtual Token * doForward (Token *input, bool during_training)
virtual Token * doBackprop (Token *input_error)
virtual void reset ()
virtual ANNComponent * clone ()
virtual void build (unsigned int _input_size, unsigned int _output_size, hash< string, Connections * > &weights_dict, hash< string, ANNComponent * > &components_dict)
virtual char * toLuaString ()
Public Member Functions inherited from ANN::ANNComponent
ANNComponent (const char *name=0, const char *weights_name=0, unsigned int input_size=0, unsigned int output_size=0)
virtual ~ANNComponent ()
const string & getName () const
const string & getWeightsName () const
bool hasWeightsName () const
bool getIsBuilt () const
void generateDefaultWeightsName (string &dest, const char *prefix=0)
unsigned int getInputSize () const
unsigned int getOutputSize () const
virtual void doUpdate ()
virtual void computeAllGradients (hash< string, MatrixFloat * > &weight_grads_dict)
virtual void setUseCuda (bool v)
bool getUseCuda () const
virtual void setOption (const char *name, double value)
Virtual method for setting the value of a training parameter.
virtual bool hasOption (const char *name)
virtual double getOption (const char *name)
virtual void copyWeights (hash< string, Connections * > &weights_dict)
Abstract method to retrieve Connections objects from ANNComponents.
virtual void copyComponents (hash< string, ANNComponent * > &components_dict)
virtual void resetConnections ()
virtual void debugInfo ()
virtual ANNComponent * getComponent (string &name)
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Attributes
int * rewrap_dims
int n
TokenMatrixFloat * input
TokenMatrixFloat * output
TokenMatrixFloat * error_input
TokenMatrixFloat * error_output
Additional Inherited Members
Protected Member Functions inherited from ANN::ANNComponent
virtual void computeGradients (MatrixFloat *&weight_grads)
Protected Attributes inherited from ANN::ANNComponent
string name
string weights_name
unsigned int input_size
unsigned int output_size
bool use_cuda
Static Protected Attributes inherited from ANN::ANNComponent
static unsigned int next_name_id = 1
static unsigned int next_weights_id = 1
Constructor & Destructor Documentation
ANN::RewrapANNComponent::RewrapANNComponent (const int * rewrap_dims, int n, const char * name = 0)
References n.
Referenced by clone().
ANN::RewrapANNComponent::~RewrapANNComponent () virtual
References DecRef, error_input, error_output, input, output, and rewrap_dims.
Member Function Documentation
void ANN::RewrapANNComponent::build (unsigned int _input_size, unsigned int _output_size, hash< string, Connections * > & weights_dict, hash< string, ANNComponent * > & components_dict) virtual
Abstract method to finish building of component hierarchy and set weights objects pointers. All childs which rewrite this method must call parent method before do anything.
Reimplemented from ANN::ANNComponent.
References ANN::ANNComponent::build().
ANNComponent * ANN::RewrapANNComponent::clone () virtual
Reimplemented from ANN::ANNComponent.
References april_utils::string::c_str(), n, ANN::ANNComponent::name, rewrap_dims, and RewrapANNComponent().
Token * ANN::RewrapANNComponent::doBackprop (Token * input_error) virtual
Virtual method that back-propagates error derivatives and computes other useful stuff. Receives input error gradients, and returns its output error gradients Token.
Reimplemented from ANN::ANNComponent.
References AssignRef, april_utils::string::c_str(), Matrix< T >::clone(), Token::convertTo(), DecRef, ERROR_EXIT1, error_input, error_output, Matrix< T >::getDimPtr(), Matrix< T >::getIsContiguous(), TokenMatrix< T >::getMatrix(), Matrix< T >::getNumDim(), Token::getTokenCode(), input, ANN::ANNComponent::name, output, Matrix< T >::rewrap(), Matrix< T >::setUseCuda(), table_of_token_codes::token_matrix, and ANN::ANNComponent::use_cuda.
Token * ANN::RewrapANNComponent::doForward (Token * input, bool during_training) virtual
Virtual method that executes the set of operations required for each block of connections when performing the forward step of the Backpropagation algorithm, and returns its output Token
Reimplemented from ANN::ANNComponent.
References AssignRef, april_utils::string::c_str(), Matrix< T >::clone(), Token::convertTo(), ERROR_EXIT1, ERROR_EXIT2, Matrix< T >::getDimSize(), Matrix< T >::getIsContiguous(), TokenMatrix< T >::getMatrix(), Matrix< T >::getNumDim(), Token::getTokenCode(), input, n, ANN::ANNComponent::name, output, Matrix< T >::rewrap(), rewrap_dims, Matrix< T >::setUseCuda(), table_of_token_codes::token_matrix, and ANN::ANNComponent::use_cuda.
virtual Token* ANN::RewrapANNComponent::getErrorInput () inline virtual
Reimplemented from ANN::ANNComponent.
References error_input.
virtual Token* ANN::RewrapANNComponent::getErrorOutput () inline virtual
Reimplemented from ANN::ANNComponent.
References error_output.
virtual Token* ANN::RewrapANNComponent::getInput () inline virtual
Reimplemented from ANN::ANNComponent.
References input.
virtual Token* ANN::RewrapANNComponent::getOutput () inline virtual
Reimplemented from ANN::ANNComponent.
References output.
void ANN::RewrapANNComponent::reset () virtual
Virtual method to reset to zero gradients and outputs (inputs are not reseted)
Reimplemented from ANN::ANNComponent.
References DecRef, error_input, error_output, input, and output.
char * ANN::RewrapANNComponent::toLuaString () virtual
Reimplemented from ANN::ANNComponent.
References april_utils::string::c_str(), n, ANN::ANNComponent::name, buffer_list::NULL_TERMINATED, buffer_list::printf(), rewrap_dims, and buffer_list::to_string().
Member Data Documentation
TokenMatrixFloat * ANN::RewrapANNComponent::error_input private
Referenced by doBackprop(), getErrorInput(), reset(), and ~RewrapANNComponent().
TokenMatrixFloat * ANN::RewrapANNComponent::error_output private
Referenced by doBackprop(), getErrorOutput(), reset(), and ~RewrapANNComponent().
TokenMatrixFloat* ANN::RewrapANNComponent::input private
Referenced by doBackprop(), doForward(), getInput(), reset(), and ~RewrapANNComponent().
int ANN::RewrapANNComponent::n private
Referenced by clone(), doForward(), RewrapANNComponent(), and toLuaString().
TokenMatrixFloat * ANN::RewrapANNComponent::output private
Referenced by doBackprop(), doForward(), getOutput(), reset(), and ~RewrapANNComponent().
int* ANN::RewrapANNComponent::rewrap_dims private
Referenced by clone(), doForward(), toLuaString(), and ~RewrapANNComponent().