april-ann
ANN::CrossEntropyLossFunction Class Reference
Public Member Functions
CrossEntropyLossFunction (unsigned int size)
virtual ~CrossEntropyLossFunction ()
virtual float addLoss (Token *input, Token *target)
virtual Token * computeGradient (Token *input, Token *target)
virtual float getAccumLoss ()
virtual void reset ()
virtual LossFunction * clone ()
Public Member Functions inherited from ANN::LossFunction
LossFunction (unsigned int size)
virtual ~LossFunction ()
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Member Functions
CrossEntropyLossFunction (unsigned int size, float accumulated_loss, unsigned int N)
Private Attributes
float accumulated_loss
unsigned int N
Additional Inherited Members
Protected Member Functions inherited from ANN::LossFunction
void throwErrorAndGetMatrixFromTokens (Token *input, Token *target, MatrixFloat *&input_mat, MatrixFloat *&target_mat) const
Protected Attributes inherited from ANN::LossFunction
Token * error_output
unsigned int size
Constructor & Destructor Documentation
ANN::CrossEntropyLossFunction::CrossEntropyLossFunction (unsigned int size, float accumulated_loss, unsigned int N) inline private
Referenced by clone().
ANN::CrossEntropyLossFunction::CrossEntropyLossFunction (unsigned int size)
ANN::CrossEntropyLossFunction::~CrossEntropyLossFunction () virtual
Member Function Documentation
float ANN::CrossEntropyLossFunction::addLoss (Token * input, Token * target) virtual
Implements ANN::LossFunction.
References accumulated_loss, doCrossEntropyLossFunction(), Matrix< T >::getCudaFlag(), Matrix< T >::getDimSize(), Matrix< T >::getRawDataAccess(), N, NEAR_ZERO, and ANN::LossFunction::throwErrorAndGetMatrixFromTokens().
virtual LossFunction* ANN::CrossEntropyLossFunction::clone () inline virtual
Implements ANN::LossFunction.
References accumulated_loss, CrossEntropyLossFunction(), N, and ANN::LossFunction::size.
Token * ANN::CrossEntropyLossFunction::computeGradient (Token * input, Token * target) virtual
Implements ANN::LossFunction.
References AssignRef, Matrix< T >::cloneOnlyDims(), doComputeCrossEntropyGradient(), ANN::LossFunction::error_output, Matrix< T >::getCudaFlag(), Matrix< T >::getDimSize(), Matrix< T >::getRawDataAccess(), NEAR_ZERO, and ANN::LossFunction::throwErrorAndGetMatrixFromTokens().
float ANN::CrossEntropyLossFunction::getAccumLoss () virtual
Implements ANN::LossFunction.
References accumulated_loss, and N.
void ANN::CrossEntropyLossFunction::reset () virtual
Reimplemented from ANN::LossFunction.
References accumulated_loss, N, and ANN::LossFunction::reset().
Member Data Documentation
float ANN::CrossEntropyLossFunction::accumulated_loss private
Referenced by addLoss(), clone(), getAccumLoss(), and reset().
unsigned int ANN::CrossEntropyLossFunction::N private
Referenced by addLoss(), clone(), getAccumLoss(), and reset().