april-ann
april_utils::PartQ< T > Class Template Reference
Public Member Functions
PartQ ()
~PartQ ()
void configure (T *vector, int size)
bool extractMin (T &value)
void sort_up_to (int index)
int getSize ()
Private Member Functions
void push (int x)
int top ()
void pop ()
void increase_lastSorted ()
Private Attributes
T * v
int size
int first
int stack [sizestack]
int topStack
int lastSorted
Static Private Attributes
static const int threshold = 15
static const int sizestack = 200
Constructor & Destructor Documentation
template<typename T > april_utils::PartQ< T >::PartQ () inline
template<typename T > april_utils::PartQ< T >::~PartQ () inline
Member Function Documentation
template<typename T > void april_utils::PartQ< T >::configure (T * vector, int size) inline
References april_utils::PartQ< T >::first, april_utils::PartQ< T >::lastSorted, april_utils::PartQ< T >::push(), april_utils::PartQ< T >::size, april_utils::PartQ< T >::topStack, and april_utils::PartQ< T >::v.
template<typename T > bool april_utils::PartQ< T >::extractMin (T & value) inline
References april_utils::PartQ< T >::first, april_utils::PartQ< T >::increase_lastSorted(), april_utils::PartQ< T >::lastSorted, april_utils::PartQ< T >::size, and april_utils::PartQ< T >::v.
template<typename T > int april_utils::PartQ< T >::getSize () inline
References april_utils::PartQ< T >::first, and april_utils::PartQ< T >::size.
template<typename T > void april_utils::PartQ< T >::increase_lastSorted () inline private
References april_utils::InsertionSort(), april_utils::PartQ< T >::lastSorted, april_utils::partition(), april_utils::PartQ< T >::pop(), april_utils::PartQ< T >::push(), april_utils::PartQ< T >::threshold, april_utils::PartQ< T >::top(), and april_utils::PartQ< T >::v.
Referenced by april_utils::PartQ< T >::extractMin(), and april_utils::PartQ< T >::sort_up_to().
template<typename T > void april_utils::PartQ< T >::pop () inline private
References april_utils::PartQ< T >::topStack.
Referenced by april_utils::PartQ< T >::increase_lastSorted().
template<typename T > void april_utils::PartQ< T >::push (int x) inline private
References april_utils::PartQ< T >::stack, and april_utils::PartQ< T >::topStack.
Referenced by april_utils::PartQ< T >::configure(), and april_utils::PartQ< T >::increase_lastSorted().
template<typename T > void april_utils::PartQ< T >::sort_up_to (int index) inline
References april_utils::PartQ< T >::increase_lastSorted(), april_utils::PartQ< T >::lastSorted, and april_utils::PartQ< T >::size.
template<typename T > int april_utils::PartQ< T >::top () inline private
References april_utils::PartQ< T >::stack, and april_utils::PartQ< T >::topStack.
Referenced by april_utils::PartQ< T >::increase_lastSorted().
Member Data Documentation
template<typename T > int april_utils::PartQ< T >::first private
Referenced by april_utils::PartQ< T >::configure(), april_utils::PartQ< T >::extractMin(), and april_utils::PartQ< T >::getSize().
template<typename T > int april_utils::PartQ< T >::lastSorted private
Referenced by april_utils::PartQ< T >::configure(), april_utils::PartQ< T >::extractMin(), april_utils::PartQ< T >::increase_lastSorted(), and april_utils::PartQ< T >::sort_up_to().
template<typename T > int april_utils::PartQ< T >::size private
Referenced by april_utils::PartQ< T >::configure(), april_utils::PartQ< T >::extractMin(), april_utils::PartQ< T >::getSize(), and april_utils::PartQ< T >::sort_up_to().
template<typename T > const int april_utils::PartQ< T >::sizestack = 200 static private
template<typename T > int april_utils::PartQ< T >::stack[sizestack] private
Referenced by april_utils::PartQ< T >::push(), and april_utils::PartQ< T >::top().
template<typename T > const int april_utils::PartQ< T >::threshold = 15 static private
Referenced by april_utils::PartQ< T >::increase_lastSorted().
template<typename T > int april_utils::PartQ< T >::topStack private
Referenced by april_utils::PartQ< T >::configure(), april_utils::PartQ< T >::pop(), april_utils::PartQ< T >::push(), and april_utils::PartQ< T >::top().
template<typename T > T* april_utils::PartQ< T >::v private
Referenced by april_utils::PartQ< T >::configure(), april_utils::PartQ< T >::extractMin(), and april_utils::PartQ< T >::increase_lastSorted().