april-ann
april_utils::min_heap< T, CmpLess > Class Template Reference
Classes
class iterator
Public Member Functions
min_heap (int initial_max_size, CmpLess cmpless=CmpLess())
~min_heap ()
void clear ()
bool empty () const
int size () const
const T & top () const
void pop ()
void push (const T &elemento)
void push_back (const T &elemento)
void buildheap ()
iterator begin ()
iterator end ()
void del (const min_heap< T, CmpLess >::iterator &idx)
Private Member Functions
int parent (int pos)
int left_child (int pos)
void heapify (int pos)
void incr_size ()
Private Attributes
CmpLess cmpless
T * vec
int vector_size
int the_size
Constructor & Destructor Documentation
template<typename T, typename CmpLess = CmpLessDefault<T>> april_utils::min_heap< T, CmpLess >::min_heap (int initial_max_size, CmpLess cmpless = CmpLess()) inline
References april_utils::min_heap< T, CmpLess >::the_size, april_utils::min_heap< T, CmpLess >::vec, and april_utils::min_heap< T, CmpLess >::vector_size.
template<typename T, typename CmpLess = CmpLessDefault<T>> april_utils::min_heap< T, CmpLess >::~min_heap () inline
References april_utils::min_heap< T, CmpLess >::vec.
Member Function Documentation
template<typename T, typename CmpLess = CmpLessDefault<T>> iterator april_utils::min_heap< T, CmpLess >::begin () inline
template<typename T, typename CmpLess = CmpLessDefault<T>> void april_utils::min_heap< T, CmpLess >::buildheap () inline
References april_utils::min_heap< T, CmpLess >::heapify(), and april_utils::min_heap< T, CmpLess >::the_size.
template<typename T, typename CmpLess = CmpLessDefault<T>> void april_utils::min_heap< T, CmpLess >::clear () inline
References april_utils::min_heap< T, CmpLess >::the_size.
template<typename T, typename CmpLess = CmpLessDefault<T>> void april_utils::min_heap< T, CmpLess >::del (const min_heap< T, CmpLess >::iterator & idx) inline
References april_utils::min_heap< T, CmpLess >::heapify(), april_utils::min_heap< T, CmpLess >::iterator::idx, april_utils::min_heap< T, CmpLess >::the_size, and april_utils::min_heap< T, CmpLess >::vec.
template<typename T, typename CmpLess = CmpLessDefault<T>> bool april_utils::min_heap< T, CmpLess >::empty () const inline
References april_utils::min_heap< T, CmpLess >::the_size.
template<typename T, typename CmpLess = CmpLessDefault<T>> iterator april_utils::min_heap< T, CmpLess >::end () inline
References april_utils::min_heap< T, CmpLess >::the_size.
template<typename T , typename CmpLess > void april_utils::min_heap< T, CmpLess >::heapify (int pos) private
Referenced by april_utils::min_heap< T, CmpLess >::buildheap(), april_utils::min_heap< T, CmpLess >::del(), and april_utils::min_heap< T, CmpLess >::pop().
template<typename T , typename CmpLess > void april_utils::min_heap< T, CmpLess >::incr_size () private
Referenced by april_utils::min_heap< T, CmpLess >::push(), and april_utils::min_heap< T, CmpLess >::push_back().
template<typename T, typename CmpLess = CmpLessDefault<T>> int april_utils::min_heap< T, CmpLess >::left_child (int pos) inline private
template<typename T, typename CmpLess = CmpLessDefault<T>> int april_utils::min_heap< T, CmpLess >::parent (int pos) inline private
Referenced by april_utils::min_heap< T, CmpLess >::push().
template<typename T, typename CmpLess = CmpLessDefault<T>> void april_utils::min_heap< T, CmpLess >::pop () inline
References april_utils::min_heap< T, CmpLess >::heapify(), april_utils::min_heap< T, CmpLess >::the_size, and april_utils::min_heap< T, CmpLess >::vec.
template<typename T, typename CmpLess = CmpLessDefault<T>> void april_utils::min_heap< T, CmpLess >::push (const T & elemento) inline
References april_utils::min_heap< T, CmpLess >::cmpless, april_utils::min_heap< T, CmpLess >::incr_size(), april_utils::min_heap< T, CmpLess >::parent(), april_utils::min_heap< T, CmpLess >::the_size, and april_utils::min_heap< T, CmpLess >::vec.
template<typename T, typename CmpLess = CmpLessDefault<T>> void april_utils::min_heap< T, CmpLess >::push_back (const T & elemento) inline
References april_utils::min_heap< T, CmpLess >::incr_size(), april_utils::min_heap< T, CmpLess >::the_size, and april_utils::min_heap< T, CmpLess >::vec.
template<typename T, typename CmpLess = CmpLessDefault<T>> int april_utils::min_heap< T, CmpLess >::size () const inline
References april_utils::min_heap< T, CmpLess >::the_size.
template<typename T, typename CmpLess = CmpLessDefault<T>> const T& april_utils::min_heap< T, CmpLess >::top () const inline
References april_utils::min_heap< T, CmpLess >::vec.
Member Data Documentation
template<typename T, typename CmpLess = CmpLessDefault<T>> CmpLess april_utils::min_heap< T, CmpLess >::cmpless private
Referenced by april_utils::min_heap< T, CmpLess >::push().
template<typename T, typename CmpLess = CmpLessDefault<T>> int april_utils::min_heap< T, CmpLess >::the_size private
Referenced by april_utils::min_heap< T, CmpLess >::buildheap(), april_utils::min_heap< T, CmpLess >::clear(), april_utils::min_heap< T, CmpLess >::del(), april_utils::min_heap< T, CmpLess >::empty(), april_utils::min_heap< T, CmpLess >::end(), april_utils::min_heap< T, CmpLess >::min_heap(), april_utils::min_heap< T, CmpLess >::pop(), april_utils::min_heap< T, CmpLess >::push(), april_utils::min_heap< T, CmpLess >::push_back(), and april_utils::min_heap< T, CmpLess >::size().
template<typename T, typename CmpLess = CmpLessDefault<T>> T* april_utils::min_heap< T, CmpLess >::vec private
Referenced by april_utils::min_heap< T, CmpLess >::del(), april_utils::min_heap< T, CmpLess >::min_heap(), april_utils::min_heap< T, CmpLess >::pop(), april_utils::min_heap< T, CmpLess >::push(), april_utils::min_heap< T, CmpLess >::push_back(), april_utils::min_heap< T, CmpLess >::top(), and april_utils::min_heap< T, CmpLess >::~min_heap().
template<typename T, typename CmpLess = CmpLessDefault<T>> int april_utils::min_heap< T, CmpLess >::vector_size private
Referenced by april_utils::min_heap< T, CmpLess >::min_heap().