april-ann
MTRand Class Reference
Random
Public Member Functions
MTRand (const uint32_t &oneSeed)
MTRand (uint32_t *const bigSeed, uint32_t const seedLength=N)
MTRand ()
MTRand & operator= (const MTRand &)
MTRand (const MTRand &r)
double rand ()
double rand (const double &n)
double randExc ()
double randExc (const double &n)
double randDblExc ()
double randDblExc (const double &n)
uint32_t randInt ()
uint32_t randInt (const uint32_t &n)
double operator() ()
double rand53 ()
double randNorm (const double &mean=0.0, const double &variance=0.0)
void seed (const uint32_t oneSeed)
void seed (uint32_t *const bigSeed, const uint32_t seedLength=N)
void seed ()
void save (uint32_t *saveArray) const
void load (uint32_t *const loadArray)
void shuffle (int size, int *vector)
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Static Public Attributes
static const unsigned int N = 624
static const unsigned int SAVE = N+1
Protected Types
enum { M = 397 }
Protected Member Functions
void initialize (const uint32_t oneSeed)
void reload ()
uint32_t hiBit (const uint32_t &u) const
uint32_t loBit (const uint32_t &u) const
uint32_t loBits (const uint32_t &u) const
uint32_t mixBits (const uint32_t &u, const uint32_t &v) const
uint32_t twist (const uint32_t &m, const uint32_t &s0, const uint32_t &s1) const
Static Protected Member Functions
static uint32_t hash (time_t t, clock_t c)
Protected Attributes
uint32_t state [N]
uint32_t * pNext
int left
Protected Attributes inherited from Referenced
int refs
Member Enumeration Documentation
anonymous enum protected
Enumerator:
M
Member Function Documentation
uint32_t MTRand::hiBit (const uint32_t & u) const inline protected
Referenced by mixBits().
uint32_t MTRand::loBit (const uint32_t & u) const inline protected
Referenced by twist().
uint32_t MTRand::loBits (const uint32_t & u) const inline protected
Referenced by mixBits().
uint32_t MTRand::mixBits (const uint32_t & u, const uint32_t & v) const inline protected
References hiBit(), and loBits().
Referenced by twist().
double MTRand::operator() () inline
References rand().
uint32_t MTRand::twist (const uint32_t & m, const uint32_t & s0, const uint32_t & s1) const inline protected
References loBit(), and mixBits().
Referenced by reload().
Member Data Documentation
int MTRand::left protected
Referenced by load(), MTRand(), operator=(), randInt(), reload(), and save().
uint32_t* MTRand::pNext protected
Referenced by load(), MTRand(), operator=(), randInt(), and reload().
uint32_t MTRand::state[N] protected
Referenced by initialize(), load(), MTRand(), operator=(), reload(), save(), and seed().