april-ann
april_utils::hash< KeyType, DataType, HashFcn, EqualKey > Class Template Reference
Classes
class const_iterator
class iterator
struct node
Public Types
typedef KeyType key_type
typedef DataType data_type
typedef pair< const key_type,
data_type > value_type
typedef value_type & reference
typedef const reference const_reference
typedef value_type * pointer
typedef ptrdiff_t difference_type
typedef size_t size_type
Public Member Functions
hash (int nbckts=8, float mxloadf=4.0)
hash (const hash &)
~hash ()
hash & operator= (const hash &)
void clear ()
data_type * find (const key_type &k)
value_type * find_pair (const key_type &k) const
bool search (const key_type &k) const
void erase (const key_type &k)
template<typename predicate >
void delete_if (predicate &p)
value_type * find_and_add_pair (const key_type &k, bool &isNew)
data_type & operator[] (const key_type &k)
bool insert (const key_type &k, const data_type &d)
void resize (int n)
int bucket_count () const
int size () const
bool empty () const
float get_max_load_factor () const
int get_num_buckets () const
void get_hash_nodes (vector< pointer > &output_vector) const
iterator begin ()
iterator end ()
Private Member Functions
int first_power_of_2 (int value)
void copy_buckets (const hash &)
Private Attributes
node ** buckets
int num_buckets
int hash_mask
int the_size
int rehash_threshold
float max_load_factor
HashFcn hash_function
EqualKey equal_key
iterator end_iterator
Member Typedef Documentation
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> typedef const reference april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::const_reference
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> typedef DataType april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::data_type
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> typedef ptrdiff_t april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::difference_type
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> typedef KeyType april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::key_type
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> typedef value_type* april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::pointer
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> typedef value_type& april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::reference
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> typedef size_t april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::size_type
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> typedef pair<const key_type, data_type> april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::value_type
Constructor & Destructor Documentation
template<typename ky , typename dt , typename hfcn , typename eqky > april_utils::hash< ky, dt, hfcn, eqky >::hash (int nbckts = 8, float mxloadf = 4.0)
template<typename ky , typename dt , typename hfcn , typename eqky > april_utils::hash< ky, dt, hfcn, eqky >::hash (const hash< KeyType, DataType, HashFcn, EqualKey > & other)
References april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::hash_mask, april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::max_load_factor, april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::num_buckets, april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::rehash_threshold, and april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::the_size.
template<typename ky , typename dt , typename hfcn , typename eqky > april_utils::hash< ky, dt, hfcn, eqky >::~hash ()
Member Function Documentation
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> iterator april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::begin () inline
Referenced by april_utils::Trie< O >::begin(), and april_utils::Trie< O >::begin_outputs().
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> int april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::bucket_count () const inline
template<typename ky , typename dt , typename hfcn , typename eqky > void april_utils::hash< ky, dt, hfcn, eqky >::clear ()
References april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::node::next.
Referenced by april_utils::Trie< O >::clear().
template<typename ky , typename dt , typename hfcn , typename eqky > void april_utils::hash< ky, dt, hfcn, eqky >::copy_buckets (const hash< KeyType, DataType, HashFcn, EqualKey > & other) inline private
References april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::buckets, and april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::node::next.
template<typename ky , typename dt , typename hfcn , typename eqky > template<typename predicate > void april_utils::hash< ky, dt, hfcn, eqky >::delete_if (predicate & p)
References april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::node::next, and april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::node::value.
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> bool april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::empty () const inline
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> iterator april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::end () inline
Referenced by april_utils::Trie< O >::end(), and april_utils::Trie< O >::end_outputs().
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> void april_utils::hash< ky, dt, hfcn, eqky >::erase (const key_type & k)
References april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::node::next.
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> dt * april_utils::hash< ky, dt, hfcn, eqky >::find (const key_type & k)
References april_utils::pair< T1, T2 >::second.
Referenced by april_utils::Trie< O >::find(), april_utils::Trie< O >::get(), april_utils::Trie< O >::iterator::get_outputs(), april_utils::Trie< O >::get_state_output(), april_utils::Trie< O >::insert(), april_utils::Trie< O >::search_dest_state(), and april_utils::Trie< O >::search_transition().
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> pair< const ky, dt > * april_utils::hash< ky, dt, hfcn, eqky >::find_and_add_pair (const key_type & k, bool & isNew)
References april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::node::next, and april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::node::value.
Referenced by april_utils::Trie4lua::find(), april_utils::hash< int_pair, int >::insert(), and april_utils::hash< int_pair, int >::operator[]().
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> pair< const ky, dt > * april_utils::hash< ky, dt, hfcn, eqky >::find_pair (const key_type & k) const
References april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::node::next.
Referenced by april_utils::hash< int_pair, int >::search().
template<typename ky , typename dt , typename hfcn , typename eqky > int april_utils::hash< ky, dt, hfcn, eqky >::first_power_of_2 (int value) private
template<typename ky , typename dt , typename hfcn , typename eqky > void april_utils::hash< ky, dt, hfcn, eqky >::get_hash_nodes (vector< pointer > & output_vector) const
References april_utils::vector< T >::clear(), april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::node::next, and april_utils::vector< T >::push_back().
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> float april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::get_max_load_factor () const inline
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> int april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::get_num_buckets () const inline
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> bool april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::insert (const key_type & k, const data_type & d) inline
template<typename ky , typename dt , typename hfcn , typename eqky > hash< ky, dt, hfcn, eqky > & april_utils::hash< ky, dt, hfcn, eqky >::operator= (const hash< KeyType, DataType, HashFcn, EqualKey > & other)
References april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::hash_mask, april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::max_load_factor, april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::num_buckets, april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::rehash_threshold, and april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::the_size.
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> data_type& april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::operator[] (const key_type & k) inline
template<typename ky , typename dt , typename hfcn , typename eqky > void april_utils::hash< ky, dt, hfcn, eqky >::resize (int n)
References april_utils::pair< T1, T2 >::first, april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::node::next, and april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::node::value.
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> bool april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::search (const key_type & k) const inline
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> int april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::size () const inline
Member Data Documentation
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> node** april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::buckets private
Referenced by april_utils::hash< int_pair, int >::begin(), april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::copy_buckets(), april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::iterator::operator++(), and april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::const_iterator::operator++().
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> iterator april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::end_iterator private
Referenced by april_utils::hash< int_pair, int >::end().
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> EqualKey april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::equal_key private
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> HashFcn april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::hash_function private
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> int april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::hash_mask private
Referenced by april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::hash(), and april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::operator=().
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> float april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::max_load_factor private
Referenced by april_utils::hash< int_pair, int >::get_max_load_factor(), april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::hash(), and april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::operator=().
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> int april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::num_buckets private
Referenced by april_utils::hash< int_pair, int >::begin(), april_utils::hash< int_pair, int >::bucket_count(), april_utils::hash< int_pair, int >::get_num_buckets(), april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::hash(), april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::iterator::operator++(), april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::const_iterator::operator++(), and april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::operator=().
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> int april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::rehash_threshold private
Referenced by april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::hash(), and april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::operator=().
template<typename KeyType, typename DataType, typename HashFcn = default_hash_function<KeyType>, typename EqualKey = default_equality_comparison_function<KeyType>> int april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::the_size private
Referenced by april_utils::hash< int_pair, int >::empty(), april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::hash(), april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::operator=(), and april_utils::hash< int_pair, int >::size().