april-ann
ANN::BiasANNComponent Class Reference
Public Member Functions
BiasANNComponent (unsigned int size=0, const char *name=0, const char *weights_name=0)
virtual ~BiasANNComponent ()
virtual Token * getInput ()
virtual Token * getOutput ()
virtual Token * getErrorInput ()
virtual Token * getErrorOutput ()
virtual Token * doForward (Token *input, bool during_training)
virtual Token * doBackprop (Token *input_error)
In BiasANNComponent this method is a by-pass.
virtual void doUpdate ()
virtual void reset ()
virtual ANNComponent * clone ()
virtual void setOption (const char *name, double value)
Virtual method for setting the value of a training parameter.
virtual bool hasOption (const char *name)
virtual double getOption (const char *name)
virtual void build (unsigned int input_size, unsigned int output_size, hash< string, Connections * > &weights_dict, hash< string, ANNComponent * > &components_dict)
virtual void copyWeights (hash< string, Connections * > &weights_dict)
Abstract method to retrieve Connections objects from ANNComponents.
virtual void resetConnections ()
virtual char * toLuaString ()
Public Member Functions inherited from ANN::ANNComponent
ANNComponent (const char *name=0, const char *weights_name=0, unsigned int input_size=0, unsigned int output_size=0)
virtual ~ANNComponent ()
const string & getName () const
const string & getWeightsName () const
bool hasWeightsName () const
bool getIsBuilt () const
void generateDefaultWeightsName (string &dest, const char *prefix=0)
unsigned int getInputSize () const
unsigned int getOutputSize () const
virtual void computeAllGradients (hash< string, MatrixFloat * > &weight_grads_dict)
virtual void setUseCuda (bool v)
bool getUseCuda () const
virtual void copyComponents (hash< string, ANNComponent * > &components_dict)
virtual void debugInfo ()
virtual ANNComponent * getComponent (string &name)
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Protected Member Functions
virtual void computeGradients (MatrixFloat *&weight_grads)
Private Member Functions
void computeBP (MatrixFloat *weights_mat, MatrixFloat *input_error_mat, const float alpha)
Private Attributes
TokenMatrixFloat * input
TokenMatrixFloat * output
TokenMatrixFloat * error
Connections * bias_vector
unsigned int num_updates_from_last_prune
float learning_rate
learning parameters
float momentum
Additional Inherited Members
Protected Attributes inherited from ANN::ANNComponent
string name
string weights_name
unsigned int input_size
unsigned int output_size
bool use_cuda
Static Protected Attributes inherited from ANN::ANNComponent
static unsigned int next_name_id = 1
static unsigned int next_weights_id = 1
Constructor & Destructor Documentation
ANN::BiasANNComponent::BiasANNComponent (unsigned int size = 0, const char * name = 0, const char * weights_name = 0)
References ANN::ANNComponent::generateDefaultWeightsName().
Referenced by clone().
ANN::BiasANNComponent::~BiasANNComponent () virtual
References bias_vector, DecRef, error, input, and output.
Member Function Documentation
void ANN::BiasANNComponent::build (unsigned int _input_size, unsigned int _output_size, hash< string, Connections * > & weights_dict, hash< string, ANNComponent * > & components_dict) virtual
Abstract method to finish building of component hierarchy and set weights objects pointers. All childs which rewrite this method must call parent method before do anything.
Reimplemented from ANN::ANNComponent.
References AssignRef, bias_vector, ANN::ANNComponent::build(), april_utils::string::c_str(), ANN::Connections::checkInputOutputSizes(), ANN::Connections::countReference(), ERROR_EXIT1, ERROR_EXIT3, IncRef, ANN::ANNComponent::input_size, ANN::ANNComponent::name, ANN::ANNComponent::output_size, and ANN::ANNComponent::weights_name.
Referenced by ANN::HyperplaneANNComponent::build().
ANNComponent * ANN::BiasANNComponent::clone () virtual
Reimplemented from ANN::ANNComponent.
References BiasANNComponent(), april_utils::string::c_str(), ANN::ANNComponent::input_size, learning_rate, momentum, ANN::ANNComponent::name, and ANN::ANNComponent::weights_name.
Referenced by ANN::HyperplaneANNComponent::clone().
void ANN::BiasANNComponent::computeBP (MatrixFloat * weights_mat, MatrixFloat * input_error_mat, const float alpha) private
References Matrix< T >::axpy(), doSaxpyLoop(), Matrix< T >::getDimSize(), Matrix< T >::getRawDataAccess(), Matrix< T >::getStrideSize(), ANN::ANNComponent::output_size, and ANN::ANNComponent::use_cuda.
Referenced by computeGradients(), and doUpdate().
void ANN::BiasANNComponent::computeGradients (MatrixFloat *& weight_grads) protected virtual
Method which computes the gradient of the weights on the given MatrixFloat object
Reimplemented from ANN::ANNComponent.
References bias_vector, Matrix< T >::cloneOnlyDims(), computeBP(), error, ERROR_EXIT, Matrix< T >::getDimSize(), TokenMatrix< T >::getMatrix(), ANN::Connections::getPtr(), Matrix< T >::sameDim(), and Matrix< T >::zeros().
void ANN::BiasANNComponent::copyWeights (hash< string, Connections * > & weights_dict) virtual
Abstract method to retrieve Connections objects from ANNComponents.
Reimplemented from ANN::ANNComponent.
References bias_vector, april_utils::string::c_str(), ERROR_EXIT1, ERROR_EXIT2, ANN::ANNComponent::name, and ANN::ANNComponent::weights_name.
Referenced by ANN::HyperplaneANNComponent::copyWeights().
Token * ANN::BiasANNComponent::doBackprop (Token * input_error) virtual
In BiasANNComponent this method is a by-pass.
Reimplemented from ANN::ANNComponent.
References AssignRef, april_utils::string::c_str(), Token::convertTo(), error, ERROR_EXIT1, TokenMatrix< T >::getMatrix(), Token::getTokenCode(), ANN::ANNComponent::name, table_of_token_codes::token_matrix, and ANN::ANNComponent::use_cuda.
Referenced by ANN::HyperplaneANNComponent::doBackprop().
Token * ANN::BiasANNComponent::doForward (Token * input, bool during_training) virtual
Virtual method that executes the set of operations required for each block of connections when performing the forward step of the Backpropagation algorithm, and returns its output Token
Reimplemented from ANN::ANNComponent.
References ASSERT_MATRIX, AssignRef, Matrix< T >::axpy(), bias_vector, april_utils::string::c_str(), Matrix< T >::clone(), Token::convertTo(), doSaxpyLoop(), ERROR_EXIT1, Matrix< T >::getDimSize(), TokenMatrix< T >::getMatrix(), ANN::Connections::getPtr(), Matrix< T >::getRawDataAccess(), Matrix< T >::getStrideSize(), Token::getTokenCode(), input, ANN::ANNComponent::input_size, ANN::ANNComponent::name, output, ANN::ANNComponent::output_size, Matrix< T >::setUseCuda(), table_of_token_codes::token_matrix, and ANN::ANNComponent::use_cuda.
Referenced by ANN::HyperplaneANNComponent::doForward().
void ANN::BiasANNComponent::doUpdate () virtual
Virtual method that update weights given gradients and input/output data
Reimplemented from ANN::ANNComponent.
References ASSERT_MATRIX, ANN::Connections::beginUpdate(), bias_vector, computeBP(), ANN::Connections::computeMomentumOnPrevVector(), ANN::Connections::computeWeightDecayOnPrevVector(), ANN::Connections::copyToPrevVector(), ANN::Connections::endUpdate(), error, Matrix< T >::getDimSize(), TokenMatrix< T >::getMatrix(), ANN::Connections::getNumReferences(), ANN::Connections::getPrevPtr(), ANN::Connections::getPtr(), ANN::ANNComponent::input_size, ANN::Connections::isFirstUpdateCall(), learning_rate, MAX_UPDATES_WITHOUT_PRUNE, momentum, num_updates_from_last_prune, ANN::Connections::pruneSubnormalAndCheckNormal(), and ANN::ANNComponent::use_cuda.
Referenced by ANN::HyperplaneANNComponent::doUpdate().
virtual Token* ANN::BiasANNComponent::getErrorInput () inline virtual
Reimplemented from ANN::ANNComponent.
References error.
Referenced by ANN::HyperplaneANNComponent::getErrorInput().
virtual Token* ANN::BiasANNComponent::getErrorOutput () inline virtual
Reimplemented from ANN::ANNComponent.
References error.
virtual Token* ANN::BiasANNComponent::getInput () inline virtual
Reimplemented from ANN::ANNComponent.
References input.
double ANN::BiasANNComponent::getOption (const char * name) virtual
Virtual method for getting the value of a training parameter. All childs which rewrite this method must call parent method after their process, if the looked option is not found to show the error message.
Reimplemented from ANN::ANNComponent.
References ANN::ANNComponent::getOption(), learning_rate, LEARNING_RATE_STRING, mGetOption, momentum, and MOMENTUM_STRING.
Referenced by ANN::HyperplaneANNComponent::getOption().
virtual Token* ANN::BiasANNComponent::getOutput () inline virtual
Reimplemented from ANN::ANNComponent.
References output.
Referenced by ANN::HyperplaneANNComponent::getOutput().
bool ANN::BiasANNComponent::hasOption (const char * name) virtual
Virtual method for determining if a training parameter is being used or can be used within the network.
Reimplemented from ANN::ANNComponent.
References LEARNING_RATE_STRING, mHasOption, and MOMENTUM_STRING.
Referenced by ANN::HyperplaneANNComponent::getOption(), and ANN::HyperplaneANNComponent::hasOption().
void ANN::BiasANNComponent::reset () virtual
Virtual method to reset to zero gradients and outputs (inputs are not reseted)
Reimplemented from ANN::ANNComponent.
References DecRef, error, input, and output.
Referenced by ANN::HyperplaneANNComponent::reset().
virtual void ANN::BiasANNComponent::resetConnections () inline virtual
Reimplemented from ANN::ANNComponent.
References bias_vector, and ANN::Connections::reset().
Referenced by ANN::HyperplaneANNComponent::resetConnections().
void ANN::BiasANNComponent::setOption (const char * name, double value) virtual
Virtual method for setting the value of a training parameter.
Reimplemented from ANN::ANNComponent.
References learning_rate, LEARNING_RATE_STRING, momentum, MOMENTUM_STRING, mSetOption, and ANN::ANNComponent::setOption().
Referenced by ANN::HyperplaneANNComponent::setOption().
char * ANN::BiasANNComponent::toLuaString () virtual
Reimplemented from ANN::ANNComponent.
References april_utils::string::c_str(), ANN::ANNComponent::input_size, ANN::ANNComponent::name, buffer_list::NULL_TERMINATED, buffer_list::printf(), buffer_list::to_string(), and ANN::ANNComponent::weights_name.
Member Data Documentation
Connections* ANN::BiasANNComponent::bias_vector private
Referenced by build(), computeGradients(), copyWeights(), doForward(), doUpdate(), resetConnections(), and ~BiasANNComponent().
TokenMatrixFloat * ANN::BiasANNComponent::error private
Referenced by computeGradients(), doBackprop(), doUpdate(), getErrorInput(), getErrorOutput(), reset(), and ~BiasANNComponent().
TokenMatrixFloat* ANN::BiasANNComponent::input private
Referenced by doForward(), getInput(), reset(), and ~BiasANNComponent().
float ANN::BiasANNComponent::learning_rate private
learning parameters
Referenced by clone(), doUpdate(), getOption(), and setOption().
float ANN::BiasANNComponent::momentum private
Referenced by clone(), doUpdate(), getOption(), and setOption().
unsigned int ANN::BiasANNComponent::num_updates_from_last_prune private
Referenced by doUpdate().
TokenMatrixFloat * ANN::BiasANNComponent::output private
Referenced by doForward(), getOutput(), reset(), and ~BiasANNComponent().