april-ann
ANN::CopyANNComponent Class Reference
Public Member Functions
CopyANNComponent (unsigned int times, const char *name=0, unsigned int input_size=0, unsigned int output_size=0)
virtual ~CopyANNComponent ()
virtual Token * getInput ()
virtual Token * getOutput ()
virtual Token * getErrorInput ()
virtual Token * getErrorOutput ()
virtual Token * doForward (Token *input, bool during_training)
virtual Token * doBackprop (Token *input_error)
virtual void reset ()
virtual ANNComponent * clone ()
virtual void build (unsigned int _input_size, unsigned int _output_size, hash< string, Connections * > &weights_dict, hash< string, ANNComponent * > &components_dict)
Public Member Functions inherited from ANN::ANNComponent
ANNComponent (const char *name=0, const char *weights_name=0, unsigned int input_size=0, unsigned int output_size=0)
virtual ~ANNComponent ()
const string & getName () const
const string & getWeightsName () const
bool hasWeightsName () const
bool getIsBuilt () const
void generateDefaultWeightsName ()
unsigned int getInputSize () const
unsigned int getOutputSize () const
virtual void doUpdate ()
virtual void setUseCuda (bool v)
virtual void setOption (const char *name, double value)
Virtual method for setting the value of a training parameter.
virtual bool hasOption (const char *name)
virtual double getOption (const char *name)
virtual void copyWeights (hash< string, Connections * > &weights_dict)
Abstract method to retrieve Connections objects from ANNComponents.
virtual void copyComponents (hash< string, ANNComponent * > &components_dict)
virtual void resetConnections ()
virtual void debugInfo ()
virtual ANNComponent * getComponent (string &name)
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Attributes
vector< ANNComponent * > components
Token * input
Token * error_output
TokenBunchVector * output
TokenBunchVector * error_input
unsigned int times
Additional Inherited Members
Protected Attributes inherited from ANN::ANNComponent
string name
string weights_name
unsigned int input_size
unsigned int output_size
bool use_cuda
Static Protected Attributes inherited from ANN::ANNComponent
static unsigned int next_name_id = 1
static unsigned int next_weights_id = 1
Constructor & Destructor Documentation
ANN::CopyANNComponent::CopyANNComponent (unsigned int times, const char * name = 0, unsigned int input_size = 0, unsigned int output_size = 0)
References ERROR_EXIT.
Referenced by clone().
ANN::CopyANNComponent::~CopyANNComponent () virtual
References DecRef, error_input, error_output, input, and output.
Member Function Documentation
void ANN::CopyANNComponent::build (unsigned int _input_size, unsigned int _output_size, hash< string, Connections * > & weights_dict, hash< string, ANNComponent * > & components_dict) virtual
Abstract method to finish building of component hierarchy and set weights objects pointers. All childs which rewrite this method must call parent method before do anything.
Reimplemented from ANN::ANNComponent.
References ANN::ANNComponent::build(), ERROR_EXIT2, ANN::ANNComponent::input_size, ANN::ANNComponent::output_size, and times.
ANNComponent * ANN::CopyANNComponent::clone () virtual
Reimplemented from ANN::ANNComponent.
References april_utils::string::c_str(), CopyANNComponent(), ANN::ANNComponent::input_size, ANN::ANNComponent::name, ANN::ANNComponent::output_size, and times.
Token * ANN::CopyANNComponent::doBackprop (Token * input_error) virtual
Virtual method that back-propagates error derivatives and computes other useful stuff. Receives input error gradients, and returns its output error gradients Token.
Reimplemented from ANN::ANNComponent.
References AssignRef, Token::convertTo(), DecRef, doSaxpy(), doScopy(), ERROR_EXIT, ERROR_EXIT2, error_input, error_output, TokenMemoryBlock::getMemBlock(), Token::getTokenCode(), TokenMemoryBlock::getUsedSize(), ANN::ANNComponent::input_size, TokenVector< T >::size(), times, table_of_token_codes::token_mem_block, ANN::ANNComponent::use_cuda, and table_of_token_codes::vector_Tokens.
Token * ANN::CopyANNComponent::doForward (Token * input, bool during_training) virtual
Virtual method that executes the set of operations required for each block of connections when performing the forward step of the Backpropagation algorithm, and returns its output Token
Reimplemented from ANN::ANNComponent.
References AssignRef, IncRef, input, output, and times.
virtual Token* ANN::CopyANNComponent::getErrorInput () inline virtual
Reimplemented from ANN::ANNComponent.
References error_input.
virtual Token* ANN::CopyANNComponent::getErrorOutput () inline virtual
Reimplemented from ANN::ANNComponent.
References error_output.
virtual Token* ANN::CopyANNComponent::getInput () inline virtual
Reimplemented from ANN::ANNComponent.
References input.
virtual Token* ANN::CopyANNComponent::getOutput () inline virtual
Reimplemented from ANN::ANNComponent.
References output.
void ANN::CopyANNComponent::reset () virtual
Virtual method to reset to zero gradients and outputs (inputs are not reseted)
Reimplemented from ANN::ANNComponent.
References DecRef, error_input, error_output, input, and output.
Member Data Documentation
vector<ANNComponent*> ANN::CopyANNComponent::components private
TokenBunchVector * ANN::CopyANNComponent::error_input private
Referenced by doBackprop(), getErrorInput(), reset(), and ~CopyANNComponent().
Token * ANN::CopyANNComponent::error_output private
Referenced by doBackprop(), getErrorOutput(), reset(), and ~CopyANNComponent().
Token* ANN::CopyANNComponent::input private
Referenced by doForward(), getInput(), reset(), and ~CopyANNComponent().
TokenBunchVector* ANN::CopyANNComponent::output private
Referenced by doForward(), getOutput(), reset(), and ~CopyANNComponent().
unsigned int ANN::CopyANNComponent::times private
Referenced by build(), clone(), doBackprop(), and doForward().