april-ann
ANN::Tanh Class Reference
Public Member Functions
Tanh ()
virtual ~Tanh ()
void computePatternErrorFunction (FloatGPUMirroredMemoryBlock *output, FloatGPUMirroredMemoryBlock *target_output, FloatGPUMirroredMemoryBlock *output_error, FloatGPUMirroredMemoryBlock *pattern_errors, unsigned int output_size, const ANNConfiguration &conf)
float computeBatchErrorFunction (float error_sums, unsigned int num_patterns)
ErrorFunction * clone ()
bool logisticMandatory () const
Public Member Functions inherited from ANN::ErrorFunction
virtual ~ErrorFunction ()
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Constructor & Destructor Documentation
ANN::Tanh::Tanh ()
Referenced by clone().
virtual ANN::Tanh::~Tanh () inline virtual
Member Function Documentation
ErrorFunction* ANN::Tanh::clone () inline virtual
Implements ANN::ErrorFunction.
References Tanh().
float ANN::Tanh::computeBatchErrorFunction (float error_sums, unsigned int num_patterns) virtual
Implements ANN::ErrorFunction.
void ANN::Tanh::computePatternErrorFunction (FloatGPUMirroredMemoryBlock * output, FloatGPUMirroredMemoryBlock * target_output, FloatGPUMirroredMemoryBlock * output_error, FloatGPUMirroredMemoryBlock * pattern_errors, unsigned int output_size, const ANNConfiguration & conf) virtual
Implements ANN::ErrorFunction.
References ANNConfiguration::cur_bunch_size, doCalculateTanhErrorFunction(), and ANNConfiguration::use_cuda_flag.
bool ANN::Tanh::logisticMandatory () const inline virtual
Implements ANN::ErrorFunction.