april-ann
MatrixDataSet< T > Class Template Reference
Dataset
DataSet specialization to put or get patterns from a Matrix object.
Public Member Functions
MatrixDataSet (Matrix< T > *m)
virtual ~MatrixDataSet ()
void setOffset (int *v)
Setter for offset attribute.
void setStep (int *v)
Setter for step attribute.
void setSubMatrixSize (int *v)
Setter for submatrixsize attribute.
void setNumSteps (int *v)
Setter for numSteps attribute.
void setCircular (bool *v)
Setter for circular attribute.
void setOrderStep (int *v)
Setter for orderStep attribute.
void setDefaultValue (T f)
Setter for default value attribute.
int numPatterns ()
Number of patterns in the set.
int patternSize ()
Size of each pattern.
int getPattern (int index, T *pat)
int putPattern (int index, const T *pat)
Public Member Functions inherited from DataSet< T >
virtual ~DataSet ()
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Member Functions
void setValue (int *dest, int *orig)
void setValue (bool *dest, bool *orig)
void index2coordinate (int index)
void auxGetPattern (int offsetmatrix, int d)
void auxPutPattern (int offsetmatrix, int d)
Private Attributes
Matrix< T > * matrix
A pointer referenced to the underlying Matrix object, shared pointer.
int * offset
Initial position of each dimension.
int * subMatrixSize
subPattern size.
bool * circular
Circular boolean indicator for each dimension.
T defaultValue
Default value of positions out of Matrix limits.
int * step
Step of each dimension for the sliding window.
int * numSteps
Number of movements on each dimension (number of steps).
int * orderStep
Order of movement for each dimension.
int numPatternsv
int patternSizev
int * coordinate
Auxiliar, for getPattern.
T * pattern
Auxiliar, for getPattern.
const T * const_pattern
Auxiliar, for putPattern.
int offsetpat
Auxiliar, for getPattern.
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Detailed Description
template<typename T>
class MatrixDataSet< T >
DataSet specialization to put or get patterns from a Matrix object.
Member Function Documentation
template<typename T > int MatrixDataSet< T >::numPatterns () inline virtual
Number of patterns in the set.
Implements DataSet< T >.
References MatrixDataSet< T >::numPatternsv.
template<typename T > int MatrixDataSet< T >::patternSize () inline virtual
Size of each pattern.
Implements DataSet< T >.
References MatrixDataSet< T >::patternSizev.
template<typename T > void MatrixDataSet< T >::setCircular (bool * v) inline
Setter for circular attribute.
References MatrixDataSet< T >::circular, and MatrixDataSet< T >::setValue().
template<typename T > void MatrixDataSet< T >::setDefaultValue (T f) inline
Setter for default value attribute.
References MatrixDataSet< T >::defaultValue.
template<typename T > void MatrixDataSet< T >::setOffset (int * v) inline
Setter for offset attribute.
References MatrixDataSet< T >::offset, and MatrixDataSet< T >::setValue().
template<typename T > void MatrixDataSet< T >::setOrderStep (int * v) inline
Setter for orderStep attribute.
References MatrixDataSet< T >::orderStep, and MatrixDataSet< T >::setValue().
template<typename T > void MatrixDataSet< T >::setStep (int * v) inline
Setter for step attribute.
References MatrixDataSet< T >::setValue(), and MatrixDataSet< T >::step.
Member Data Documentation
template<typename T > bool* MatrixDataSet< T >::circular private
Circular boolean indicator for each dimension.
Referenced by MatrixDataSet< T >::setCircular().
template<typename T > const T* MatrixDataSet< T >::const_pattern private
Auxiliar, for putPattern.
template<typename T > int* MatrixDataSet< T >::coordinate private
Auxiliar, for getPattern.
template<typename T > T MatrixDataSet< T >::defaultValue private
Default value of positions out of Matrix limits.
Referenced by MatrixDataSet< T >::setDefaultValue().
template<typename T > Matrix<T>* MatrixDataSet< T >::matrix private
A pointer referenced to the underlying Matrix object, shared pointer.
template<typename T > int MatrixDataSet< T >::numPatternsv private
Referenced by MatrixDataSet< T >::numPatterns().
template<typename T > int* MatrixDataSet< T >::numSteps private
Number of movements on each dimension (number of steps).
template<typename T > int* MatrixDataSet< T >::offset private
Initial position of each dimension.
Referenced by MatrixDataSet< T >::setOffset().
template<typename T > int MatrixDataSet< T >::offsetpat private
Auxiliar, for getPattern.
template<typename T > int* MatrixDataSet< T >::orderStep private
Order of movement for each dimension.
Referenced by MatrixDataSet< T >::setOrderStep().
template<typename T > T* MatrixDataSet< T >::pattern private
Auxiliar, for getPattern.
template<typename T > int MatrixDataSet< T >::patternSizev private
Referenced by MatrixDataSet< T >::patternSize().
template<typename T > int* MatrixDataSet< T >::step private
Step of each dimension for the sliding window.
Referenced by MatrixDataSet< T >::setStep().
template<typename T > int* MatrixDataSet< T >::subMatrixSize private
subPattern size.