april-ann
ANN::AllAllConnections Class Reference
Public Member Functions
AllAllConnections (unsigned int num_inputs, unsigned int num_outputs)
~AllAllConnections ()
bool checkInputOutputSizes (ActivationUnits *input, ActivationUnits *output) const
void randomizeWeights (MTRand *rnd, float low, float high)
void randomizeWeightsAtColumn (unsigned int col, MTRand *rnd, float low, float high)
unsigned int loadWeights (MatrixFloat *data, MatrixFloat *old_data, unsigned int first_weight_pos, unsigned int column_size)
unsigned int copyWeightsTo (MatrixFloat *data, MatrixFloat *old_data, unsigned int first_weight_pos, unsigned int column_size)
Connections * clone ()
Public Member Functions inherited from ANN::Connections
Connections (unsigned int total_size)
virtual ~Connections ()
void countReference ()
unsigned int getNumReferences () const
void beginUpdate ()
void endUpdate ()
bool isFirstUpdateCall ()
void computeMomentumOnPrevVector (float momentum, bool use_cuda)
void computeWeightDecayOnPrevVector (float c_weight_decay, bool use_cuda)
void copyToPrevVector (bool use_cuda)
unsigned int size () const
void pruneSubnormalAndCheckNormal ()
FloatGPUMirroredMemoryBlock * getPtr ()
FloatGPUMirroredMemoryBlock * getPrevPtr ()
virtual unsigned int getNumWeights () const
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Attributes
unsigned int num_inputs
unsigned int num_outputs
Additional Inherited Members
Static Public Attributes inherited from ANN::Connections
static const double weightnearzero = 1e-10
Protected Attributes inherited from ANN::Connections
FloatGPUMirroredMemoryBlock * weights
FloatGPUMirroredMemoryBlock * prev_weights
unsigned int total_size
unsigned int num_inputs
numero de inputs y numero de outputs
unsigned int num_outputs
unsigned int num_references
unsigned int update_weights_calls
Constructor & Destructor Documentation
ANN::AllAllConnections::AllAllConnections (unsigned int num_inputs, unsigned int num_outputs)
Referenced by clone().
ANN::AllAllConnections::~AllAllConnections () inline
Member Function Documentation
bool ANN::AllAllConnections::checkInputOutputSizes (ActivationUnits * input, ActivationUnits * output) const virtual
Implements ANN::Connections.
References ERROR_PRINT, num_inputs, num_outputs, and ANN::ActivationUnits::numNeurons().
Connections * ANN::AllAllConnections::clone () virtual
Implements ANN::Connections.
References AllAllConnections(), GPUMirroredMemoryBlock< T >::getPPALForRead(), GPUMirroredMemoryBlock< T >::getPPALForReadAndWrite(), num_inputs, num_outputs, ANN::Connections::prev_weights, ANN::Connections::total_size, and ANN::Connections::weights.
unsigned int ANN::AllAllConnections::copyWeightsTo (MatrixFloat * data, MatrixFloat * old_data, unsigned int first_weight_pos, unsigned int column_size) virtual
Implements ANN::Connections.
References Matrix< T >::data, GPUMirroredMemoryBlock< T >::getPPALForRead(), num_inputs, num_outputs, ANN::Connections::prev_weights, and ANN::Connections::weights.
unsigned int ANN::AllAllConnections::loadWeights (MatrixFloat * data, MatrixFloat * old_data, unsigned int first_weight_pos, unsigned int column_size) virtual
Implements ANN::Connections.
References Matrix< T >::data, GPUMirroredMemoryBlock< T >::getPPALForReadAndWrite(), num_inputs, num_outputs, ANN::Connections::prev_weights, and ANN::Connections::weights.
void ANN::AllAllConnections::randomizeWeights (MTRand * rnd, float low, float high) virtual
Implements ANN::Connections.
References GPUMirroredMemoryBlock< T >::getPPALForReadAndWrite(), num_inputs, num_outputs, ANN::Connections::prev_weights, rnd_weight, ANN::Connections::weightnearzero, and ANN::Connections::weights.
void ANN::AllAllConnections::randomizeWeightsAtColumn (unsigned int col, MTRand * rnd, float low, float high) virtual
Implements ANN::Connections.
References GPUMirroredMemoryBlock< T >::getPPALForReadAndWrite(), num_inputs, num_outputs, ANN::Connections::prev_weights, rnd_weight, ANN::Connections::weightnearzero, and ANN::Connections::weights.
Member Data Documentation
unsigned int ANN::AllAllConnections::num_inputs private
Referenced by checkInputOutputSizes(), clone(), copyWeightsTo(), loadWeights(), randomizeWeights(), and randomizeWeightsAtColumn().
unsigned int ANN::AllAllConnections::num_outputs private
Referenced by checkInputOutputSizes(), clone(), copyWeightsTo(), loadWeights(), randomizeWeights(), and randomizeWeightsAtColumn().