april-ann
ANN::ActivationUnitsSlice Class Reference
Public Member Functions
ActivationUnitsSlice (ActivationUnits *units, unsigned int begin_unit, unsigned int end_unit, const ANNConfiguration &conf)
~ActivationUnitsSlice ()
void activate (bool use_cuda)
unsigned int size () const
FloatGPUMirroredMemoryBlock * getPtr ()
FloatGPUMirroredMemoryBlock * getErrorVectorPtr ()
devuelve un puntero al vector con la suma de los errores
unsigned int getOffset () const
ActivationUnits * clone (const ANNConfiguration &conf)
unsigned int numNeurons () const
devuelve el numero de neuronas de la entrada
void reset (bool use_cuda)
pone a 0 los contadores, deltas de error, etc
Public Member Functions inherited from ANN::ActivationUnits
ActivationUnits (const ANNConfiguration &conf)
virtual ~ActivationUnits ()
const ANNConfiguration & getConfReference () const
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Attributes
ActivationUnits * units
unsigned int begin_unit
unsigned int end_unit
unsigned int num_units
unsigned int num_neurons
Additional Inherited Members
Protected Attributes inherited from ANN::ActivationUnits
const ANNConfiguration & conf
Detailed Description
implementa un subvector de neuronas que se encuentra como secuencia DENTRO de otro. Es util cuando hay matrices compartidas entre varias capas.
Constructor & Destructor Documentation
ANN::ActivationUnitsSlice::ActivationUnitsSlice (ActivationUnits * units, unsigned int begin_unit, unsigned int end_unit, const ANNConfiguration & conf)
References IncRef, num_neurons, num_units, ANN::ActivationUnits::numNeurons(), and ANN::ActivationUnits::size().
ANN::ActivationUnitsSlice::~ActivationUnitsSlice ()
References DecRef, and units.
Member Function Documentation
void ANN::ActivationUnitsSlice::activate (bool use_cuda)
ActivationUnits * ANN::ActivationUnitsSlice::clone (const ANNConfiguration & conf) virtual
Implements ANN::ActivationUnits.
References ERROR_PRINT.
FloatGPUMirroredMemoryBlock * ANN::ActivationUnitsSlice::getErrorVectorPtr () virtual
devuelve un puntero al vector con la suma de los errores
Implements ANN::ActivationUnits.
References ANN::ActivationUnits::getErrorVectorPtr(), and units.
unsigned int ANN::ActivationUnitsSlice::getOffset () const virtual
devuelve el valor de offset, que sumado al size(), puede que el vector no comienze en 0
Implements ANN::ActivationUnits.
References begin_unit.
FloatGPUMirroredMemoryBlock * ANN::ActivationUnitsSlice::getPtr () virtual
devuelve un puntero al vector de unidades, tantas unidades como size()*bunch_size
Implements ANN::ActivationUnits.
References ANN::ActivationUnits::getPtr(), and units.
unsigned int ANN::ActivationUnitsSlice::numNeurons () const inline virtual
devuelve el numero de neuronas de la entrada
Implements ANN::ActivationUnits.
References num_neurons.
void ANN::ActivationUnitsSlice::reset (bool use_cuda) virtual
pone a 0 los contadores, deltas de error, etc
Implements ANN::ActivationUnits.
References ANN::ActivationUnits::reset(), and units.
unsigned int ANN::ActivationUnitsSlice::size () const virtual
devuelve el tamanyo del vector que representa la entrada (no tiene porque ser igual al numero de neuronas)
Implements ANN::ActivationUnits.
References num_units.
Member Data Documentation
unsigned int ANN::ActivationUnitsSlice::begin_unit private
Referenced by getOffset().
unsigned int ANN::ActivationUnitsSlice::end_unit private
unsigned int ANN::ActivationUnitsSlice::num_neurons private
Referenced by ActivationUnitsSlice(), and numNeurons().
unsigned int ANN::ActivationUnitsSlice::num_units private
Referenced by ActivationUnitsSlice(), and size().
ActivationUnits* ANN::ActivationUnitsSlice::units private
Referenced by getErrorVectorPtr(), getPtr(), reset(), and ~ActivationUnitsSlice().