april-ann
ANN::BiasConnections Class Reference
Public Member Functions
BiasConnections (unsigned int bias_size)
~BiasConnections ()
bool checkInputOutputSizes (ActivationUnits *input, ActivationUnits *output) const
void randomizeWeights (MTRand *rnd, float low, float high, bool use_fanin)
void randomizeWeightsAtColumn (unsigned int col, MTRand *rnd, float low, float high, bool use_fanin)
unsigned int loadWeights (MatrixFloat *data, MatrixFloat *old_data, unsigned int first_weight_pos, unsigned int column_size)
unsigned int copyWeightsTo (MatrixFloat *data, MatrixFloat *old_data, unsigned int first_weight_pos, unsigned int column_size)
Connections * clone ()
Public Member Functions inherited from ANN::Connections
Connections (unsigned int total_size, unsigned int num_inputs, unsigned int num_outputs)
virtual ~Connections ()
void countReference ()
unsigned int getNumReferences () const
void beginUpdate ()
void endUpdate ()
bool isFirstUpdateCall ()
void computeMomentumOnPrevVector (float momentum, bool use_cuda)
void computeWeightDecayOnPrevVector (float c_weight_decay, bool use_cuda)
void copyToPrevVector (bool use_cuda)
unsigned int size () const
void pruneSubnormalAndCheckNormal ()
FloatGPUMirroredMemoryBlock * getPtr ()
FloatGPUMirroredMemoryBlock * getPrevPtr ()
virtual unsigned int getNumWeights () const
virtual unsigned int getNumInputs () const
virtual unsigned int getNumOutputs () const
void setFanIn (unsigned int value)
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Additional Inherited Members
Static Public Attributes inherited from ANN::Connections
static const double weightnearzero = 1e-7
Protected Attributes inherited from ANN::Connections
FloatGPUMirroredMemoryBlock * weights
FloatGPUMirroredMemoryBlock * prev_weights
unsigned int total_size
unsigned int num_inputs
numero de inputs y numero de outputs
unsigned int num_outputs
unsigned int num_references
unsigned int update_weights_calls
unsigned int fanin
Constructor & Destructor Documentation
ANN::BiasConnections::BiasConnections (unsigned int bias_size)
Referenced by clone().
ANN::BiasConnections::~BiasConnections () inline
Member Function Documentation
bool ANN::BiasConnections::checkInputOutputSizes (ActivationUnits * input, ActivationUnits * output) const virtual
Implements ANN::Connections.
References ERROR_EXIT, ERROR_PRINT, ANN::ActivationUnits::numNeurons(), and ANN::Connections::total_size.
Connections * ANN::BiasConnections::clone () virtual
Implements ANN::Connections.
References BiasConnections(), GPUMirroredMemoryBlock< T >::getPPALForRead(), GPUMirroredMemoryBlock< T >::getPPALForReadAndWrite(), ANN::Connections::prev_weights, ANN::Connections::total_size, and ANN::Connections::weights.
unsigned int ANN::BiasConnections::copyWeightsTo (MatrixFloat * data, MatrixFloat * old_data, unsigned int first_weight_pos, unsigned int column_size) virtual
Implements ANN::Connections.
References Matrix< T >::data, ERROR_EXIT2, GPUMirroredMemoryBlock< T >::getPPALForRead(), april_utils::max(), ANN::Connections::num_inputs, ANN::Connections::prev_weights, Matrix< T >::size, ANN::Connections::total_size, and ANN::Connections::weights.
unsigned int ANN::BiasConnections::loadWeights (MatrixFloat * data, MatrixFloat * old_data, unsigned int first_weight_pos, unsigned int column_size) virtual
Implements ANN::Connections.
References Matrix< T >::data, ERROR_EXIT2, GPUMirroredMemoryBlock< T >::getPPALForReadAndWrite(), april_utils::max(), ANN::Connections::num_inputs, ANN::Connections::prev_weights, Matrix< T >::size, ANN::Connections::total_size, and ANN::Connections::weights.
void ANN::BiasConnections::randomizeWeights (MTRand * rnd, float low, float high, bool use_fanin) virtual
Implements ANN::Connections.
References ANN::Connections::fanin, GPUMirroredMemoryBlock< T >::getPPALForReadAndWrite(), ANN::Connections::prev_weights, rnd_weight, ANN::Connections::total_size, ANN::Connections::weightnearzero, and ANN::Connections::weights.
void ANN::BiasConnections::randomizeWeightsAtColumn (unsigned int col, MTRand * rnd, float low, float high, bool use_fanin) virtual
Implements ANN::Connections.
References ANN::Connections::fanin, GPUMirroredMemoryBlock< T >::getPPALForReadAndWrite(), ANN::Connections::prev_weights, rnd_weight, ANN::Connections::weightnearzero, and ANN::Connections::weights.