april-ann
log_double Class Reference
Util
Public Member Functions
log_double (double x)
log_double (const log_float &f)
log_double ()
double to_double () const
float to_float () const
double log () const
log_double raise_to (double exponent)
log_double operator+= (const log_double &y)
log_double operator*= (const log_double &y)
log_double operator/= (const log_double &y)
log_double operator-= (const log_double &y)
log_double & operator= (double &value)
log_double & operator= (float &value)
log_double & operator= (log_float &value)
log_double (double x)
log_double (const log_float &f)
log_double ()
double to_double () const
float to_float () const
double log () const
log_double raise_to (double exponent)
log_double operator+= (const log_double &y)
log_double operator*= (const log_double &y)
log_double operator/= (const log_double &y)
log_double operator-= (const log_double &y)
log_double & operator= (double &value)
log_double & operator= (float &value)
log_double & operator= (log_float &value)
log_double (double x)
log_double (const log_float &f)
log_double ()
double to_double () const
float to_float () const
double log () const
log_double raise_to (double exponent)
log_double operator+= (const log_double &y)
log_double operator*= (const log_double &y)
log_double operator/= (const log_double &y)
log_double operator-= (const log_double &y)
log_double & operator= (double &value)
log_double & operator= (float &value)
log_double & operator= (log_float &value)
Static Public Member Functions
static log_double from_double (double value)
static log_double zero ()
static log_double one ()
static log_double from_double (double value)
static log_double zero ()
static log_double one ()
static log_double from_double (double value)
static log_double zero ()
static log_double one ()
Private Attributes
double raw_value
Static Private Attributes
static const double doublenearzero = 1e-37
static const double rawscorenearzero = -85
static const double rawscorezero = -1e8
static const double rawscoreone = 0
Friends
class log_float
log_double operator+ (const log_double &x, const log_double &y)
log_double operator* (const log_double &x, const log_double &y)
log_double operator/ (const log_double &x, const log_double &y)
log_double operator- (const log_double &x, const log_double &y)
bool operator== (const log_double &x, const log_double &y)
bool operator!= (const log_double &x, const log_double &y)
bool operator>= (const log_double &x, const log_double &y)
bool operator<= (const log_double &x, const log_double &y)
bool operator> (const log_double &x, const log_double &y)
bool operator< (const log_double &x, const log_double &y)
log_double operator+ (const log_double &x, const log_double &y)
log_double operator* (const log_double &x, const log_double &y)
log_double operator/ (const log_double &x, const log_double &y)
log_double operator- (const log_double &x, const log_double &y)
bool operator== (const log_double &x, const log_double &y)
bool operator!= (const log_double &x, const log_double &y)
bool operator>= (const log_double &x, const log_double &y)
bool operator<= (const log_double &x, const log_double &y)
bool operator> (const log_double &x, const log_double &y)
bool operator< (const log_double &x, const log_double &y)
log_double operator+ (const log_double &x, const log_double &y)
log_double operator* (const log_double &x, const log_double &y)
log_double operator/ (const log_double &x, const log_double &y)
log_double operator- (const log_double &x, const log_double &y)
bool operator== (const log_double &x, const log_double &y)
bool operator!= (const log_double &x, const log_double &y)
bool operator>= (const log_double &x, const log_double &y)
bool operator<= (const log_double &x, const log_double &y)
bool operator> (const log_double &x, const log_double &y)
bool operator< (const log_double &x, const log_double &y)
Constructor & Destructor Documentation
log_double::log_double (double x) inline
log_double::log_double (const log_float & f) inline
log_double::log_double () inline
Referenced by from_double(), one(), raise_to(), and zero().
log_double::log_double (double x) inline
log_double::log_double (const log_float & f) inline
log_double::log_double () inline
log_double::log_double (double x) inline
log_double::log_double (const log_float & f) inline
log_double::log_double () inline
Member Function Documentation
static log_double log_double::from_double (double value) inline static
References doublenearzero, log(), log_double(), and rawscorezero.
static log_double log_double::from_double (double value) inline static
References doublenearzero, log(), log_double(), and rawscorezero.
Referenced by constString::extract_log_double_binary().
static log_double log_double::from_double (double value) inline static
References doublenearzero, log(), log_double(), and rawscorezero.
double log_double::log () const inline
References raw_value.
double log_double::log () const inline
References raw_value.
Referenced by from_double().
double log_double::log () const inline
References raw_value.
static log_double log_double::one () inline static
References log_double(), and rawscoreone.
static log_double log_double::one () inline static
References log_double(), and rawscoreone.
static log_double log_double::one () inline static
References log_double(), and rawscoreone.
log_double log_double::operator*= (const log_double & y) inline
log_double log_double::operator*= (const log_double & y) inline
References raw_value, and rawscorezero.
log_double log_double::operator*= (const log_double & y) inline
References raw_value, and rawscorezero.
log_double log_double::operator+= (const log_double & y) inline
log_double log_double::operator+= (const log_double & y) inline
References raw_value, and rawscorezero.
log_double log_double::operator+= (const log_double & y) inline
References raw_value, and rawscorezero.
log_double log_double::operator-= (const log_double & y) inline
log_double log_double::operator-= (const log_double & y) inline
References raw_value, and rawscorezero.
log_double log_double::operator-= (const log_double & y) inline
References raw_value, and rawscorezero.
log_double log_double::operator/= (const log_double & y) inline
log_double log_double::operator/= (const log_double & y) inline
References raw_value, and rawscorezero.
log_double log_double::operator/= (const log_double & y) inline
References raw_value, and rawscorezero.
log_double& log_double::operator= (double & value) inline
References raw_value.
log_double& log_double::operator= (float & value) inline
References raw_value.
log_double& log_double::operator= (log_float & value) inline
References raw_value.
log_double& log_double::operator= (double & value) inline
References raw_value, and rawscorezero.
log_double& log_double::operator= (float & value) inline
References raw_value, and rawscorezero.
log_double& log_double::operator= (double & value) inline
References raw_value, and rawscorezero.
log_double& log_double::operator= (log_float & value) inline
References raw_value, and rawscorezero.
log_double& log_double::operator= (float & value) inline
References raw_value, and rawscorezero.
log_double& log_double::operator= (log_float & value) inline
References raw_value, and rawscorezero.
log_double log_double::raise_to (double exponent) inline
References log_double(), and raw_value.
log_double log_double::raise_to (double exponent) inline
References log_double(), raw_value, and rawscorezero.
log_double log_double::raise_to (double exponent) inline
References log_double(), raw_value, and rawscorezero.
double log_double::to_double () const inline
References raw_value.
double log_double::to_double () const inline
References raw_value.
double log_double::to_double () const inline
References raw_value.
float log_double::to_float () const inline
References raw_value.
float log_double::to_float () const inline
References raw_value.
float log_double::to_float () const inline
References raw_value.
static log_double log_double::zero () inline static
References log_double(), and rawscorezero.
static log_double log_double::zero () inline static
References log_double(), and rawscorezero.
static log_double log_double::zero () inline static
References log_double(), and rawscorezero.
Friends And Related Function Documentation
log_float friend
bool operator!= (const log_double & x, const log_double & y) friend
bool operator!= (const log_double & x, const log_double & y) friend
bool operator!= (const log_double & x, const log_double & y) friend
log_double operator* (const log_double & x, const log_double & y) friend
log_double operator* (const log_double & x, const log_double & y) friend
log_double operator* (const log_double & x, const log_double & y) friend
log_double operator+ (const log_double & x, const log_double & y) friend
log_double operator+ (const log_double & x, const log_double & y) friend
log_double operator+ (const log_double & x, const log_double & y) friend
log_double operator- (const log_double & x, const log_double & y) friend
log_double operator- (const log_double & x, const log_double & y) friend
log_double operator- (const log_double & x, const log_double & y) friend
log_double operator/ (const log_double & x, const log_double & y) friend
log_double operator/ (const log_double & x, const log_double & y) friend
log_double operator/ (const log_double & x, const log_double & y) friend
bool operator< (const log_double & x, const log_double & y) friend
bool operator< (const log_double & x, const log_double & y) friend
bool operator< (const log_double & x, const log_double & y) friend
bool operator<= (const log_double & x, const log_double & y) friend
bool operator<= (const log_double & x, const log_double & y) friend
bool operator<= (const log_double & x, const log_double & y) friend
bool operator== (const log_double & x, const log_double & y) friend
bool operator== (const log_double & x, const log_double & y) friend
bool operator== (const log_double & x, const log_double & y) friend
bool operator> (const log_double & x, const log_double & y) friend
bool operator> (const log_double & x, const log_double & y) friend
bool operator> (const log_double & x, const log_double & y) friend
bool operator>= (const log_double & x, const log_double & y) friend
bool operator>= (const log_double & x, const log_double & y) friend
bool operator>= (const log_double & x, const log_double & y) friend
Member Data Documentation
double log_double::raw_value private
Referenced by log(), operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator<(), operator<=(), log_float::operator=(), operator=(), operator==(), operator>(), operator>=(), raise_to(), to_double(), and to_float().