april-ann
ANN::MSELossFunction Class Reference
Public Member Functions
MSELossFunction (unsigned int size)
virtual ~MSELossFunction ()
virtual float addLoss (Token *input, Token *target)
virtual Token * computeGradient (Token *input, Token *target)
virtual float getAccumLoss ()
virtual void reset ()
virtual LossFunction * clone ()
Public Member Functions inherited from ANN::LossFunction
LossFunction (unsigned int size)
virtual ~LossFunction ()
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Member Functions
MSELossFunction (unsigned int size, float accumulated_loss, unsigned int N)
Private Attributes
float accumulated_loss
unsigned int N
Additional Inherited Members
Protected Attributes inherited from ANN::LossFunction
Token * error_output
unsigned int size
Constructor & Destructor Documentation
ANN::MSELossFunction::MSELossFunction (unsigned int size, float accumulated_loss, unsigned int N) inline private
Referenced by clone().
ANN::MSELossFunction::MSELossFunction (unsigned int size)
ANN::MSELossFunction::~MSELossFunction () virtual
Member Function Documentation
float ANN::MSELossFunction::addLoss (Token * input, Token * target) virtual
Implements ANN::LossFunction.
References accumulated_loss, Token::convertTo(), doMSELossFunction(), ERROR_EXIT, TokenMemoryBlock::getCudaFlag(), TokenMemoryBlock::getMemBlock(), Token::getTokenCode(), TokenMemoryBlock::getUsedSize(), N, ANN::LossFunction::size, and table_of_token_codes::token_mem_block.
virtual LossFunction* ANN::MSELossFunction::clone () inline virtual
Implements ANN::LossFunction.
References accumulated_loss, MSELossFunction(), N, and ANN::LossFunction::size.
Token * ANN::MSELossFunction::computeGradient (Token * input, Token * target) virtual
Implements ANN::LossFunction.
References AssignRef, Token::convertTo(), doComputeMSEGradient(), ERROR_EXIT, ERROR_EXIT2, ANN::LossFunction::error_output, TokenMemoryBlock::getCudaFlag(), TokenMemoryBlock::getMemBlock(), Token::getTokenCode(), TokenMemoryBlock::getUsedSize(), ANN::LossFunction::size, and table_of_token_codes::token_mem_block.
float ANN::MSELossFunction::getAccumLoss () virtual
Implements ANN::LossFunction.
References accumulated_loss, and N.
void ANN::MSELossFunction::reset () virtual
Reimplemented from ANN::LossFunction.
References accumulated_loss, N, and ANN::LossFunction::reset().
Member Data Documentation
float ANN::MSELossFunction::accumulated_loss private
Referenced by addLoss(), clone(), getAccumLoss(), and reset().
unsigned int ANN::MSELossFunction::N private
Referenced by addLoss(), clone(), getAccumLoss(), and reset().