april-ann
Matrix< T > Class Template Reference
Matrix
Classes
class best_span_iterator
class col_major_iterator
class const_col_major_iterator
class const_iterator
class iterator
class sliding_window
Public Member Functions
int computeRawPos (const int *coords) const
Computes the position at data array given it coordinates.
void computeCoords (const int raw_pos, int *coords) const
Computes the coordinates given the raw data position.
bool nextCoordVectorRowOrder (int *coords, int &raw_pos) const
Updates with the following coordinates vector.
bool nextCoordVectorColOrder (int *coords, int &raw_pos) const
bool nextCoordVectorRowOrder (int *coords) const
bool nextCoordVectorColOrder (int *coords) const
Matrix (int numDim, const int *dim, CBLAS_ORDER major_order=CblasRowMajor, GPUMirroredMemoryBlock< T > *data=0, int offset=0)
Full constructor given numDim, dim, and major_order.
Matrix (int numDim, int d1,...)
Constructor with T() values and CblasRowMajor order.
Matrix (Matrix< T > *other, bool clone=true)
Constructor for copy or clone other given matrix.
Matrix (Matrix< T > *other, const int *coords, const int *sizes, bool clone=true)
Sub-matrix constructor.
virtual ~Matrix ()
Destructor.
Matrix< T > * rewrap (const int *new_dims, int len)
Modify sizes of matrix.
int getNumDim () const
const int * getDimPtr () const
const int * getStridePtr () const
int getDimSize (int i) const
int getStrideSize (int i) const
int size () const
CBLAS_ORDER getMajorOrder () const
void setUseCuda (bool v)
bool getCudaFlag () const
bool isSimple () const
bool getIsContiguous () const
Indicates if it is a contiguous matrix.
int getOffset () const
Returns the offset of first data value (sub-matrix)
iterator begin ()
iterator iteratorAt (int c0)
iterator iteratorAt (int c0, int c1)
iterator iteratorAt (int *coords, int len)
const iterator & end ()
const best_span_iterator & end_span_iterator () const
const_iterator begin () const
const_iterator iteratorAt (int c0) const
const_iterator iteratorAt (int c0, int c1) const
const_iterator iteratorAt (int *coords, int len) const
const const_iterator & end () const
Matrix< T > * transpose () const
Transposition.
Matrix< T > * cloneOnlyDims () const
Copy only sizes, but not data.
Matrix< T > * clone ()
Deep copy.
Matrix< T > * clone (CBLAS_ORDER major_order)
Deep copy with different major_order.
Matrix< T > * shallow_copy ()
Shallow copy.
T & operator[] (int i)
Raw access operator [].
const T & operator[] (int i) const
T & operator() (int i)
T & operator() (int row, int col)
T & operator() (int coord0, int coord1, int coord2,...)
T & operator() (int *coords, int sz)
const T & operator() (int i) const
const T & operator() (int row, int col) const
const T & operator() (int coord0, int coord1, int coord2,...) const
const T & operator() (int *coords, int sz) const
GPUMirroredMemoryBlock< T > * getRawDataAccess ()
const GPUMirroredMemoryBlock< T > * getRawDataAccess () const
bool getCol (int col, T *vec, int vecsize)
bool putCol (int col, T *vec, int vecsize)
bool putSubCol (int col, int first_row, T *vec, int vecsize)
bool sameDim (const Matrix< T > *other) const
Matrix< T > * select (int dim, int index)
void clamp (T lower, T upper)
void fill (T value)
void zeros ()
void ones ()
void diag (T value)
Matrix< T > * addition (const Matrix< T > *other)
Matrix< T > * substraction (const Matrix< T > *other)
Matrix< T > * multiply (const Matrix< T > *other) const
T sum () const
bool equals (const Matrix< T > *other, T epsilon) const
void log ()
void log1p ()
void exp ()
void sqrt ()
void pow (T value)
void tanh ()
Matrix< T > * cmul (const Matrix< T > *other)
void adjustRange (T rmin, T rmax)
void scalarAdd (T s)
void copy (const Matrix< T > *other)
void axpy (T alpha, const Matrix< T > *other)
void gemm (CBLAS_TRANSPOSE trans_A, CBLAS_TRANSPOSE trans_B, T alpha, const Matrix< T > *otherA, const Matrix< T > *otherB, T beta)
void gemv (CBLAS_TRANSPOSE trans_A, T alpha, const Matrix< T > *otherA, const Matrix< T > *otherX, T beta)
void ger (T alpha, const Matrix< T > *otherX, const Matrix< T > *otherY)
T dot (const Matrix< T > *other) const
void scal (T value)
T norm2 () const
T min (int &arg_min, int &arg_min_raw_pos) const
T max (int &arg_max, int &arg_max_raw_pos) const
void minAndMax (T &min, T &max) const
Matrix< T > * maxSelDim (const int dim, IntGPUMirroredMemoryBlock *raw_positions=0, int shift=0) const
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Static Public Member Functions
static bool nextCoordVectorRowOrder (int *coords, const int *sizes, const int numDim)
static bool nextCoordVectorColOrder (int *coords, const int *sizes, const int numDim)
static bool nextCoordVectorRowOrder (int *coords, int &raw_pos, const int *sizes, const int *strides, const int numDim, const int last_raw_pos)
static bool nextCoordVectorColOrder (int *coords, int &raw_pos, const int *sizes, const int *strides, const int numDim, const int last_raw_pos)
Protected Member Functions
T * getData ()
Constructor... -> Integer array with the size of each dimension.
const T * getData () const
Returns the data pointer for read.
int getLastRawPos () const
bool isVector () const
Returns if the matrix is a vector.
bool isColVector () const
int getVectorSize () const
int getVectorStride () const
Protected Attributes
int numDim
Number of dimensions.
int * stride
Size of each dimension.
int offset
Offset for sub-matrix.
int * matrixSize
Sub-matrix size of each dimension.
int total_size
Total size of the matrix (number of elements)
int last_raw_pos
GPUMirroredMemoryBlock< T > * data
Pointer to data.
CBLAS_ORDER major_order
Major type (only when numDim=2)
bool use_cuda
For CUDA purposes.
matrix_contiguous_enum_t is_contiguous
To know if it is contiguous.
Protected Attributes inherited from Referenced
int refs
Private Types
enum matrix_contiguous_enum_t { NONE =0, CONTIGUOUS =1, NONCONTIGUOUS =2 }
Private Member Functions
Matrix ()
Matrix (int numDim, const int *stride, const int offset, const int *matrixSize, const int total_size, const int last_raw_pos, GPUMirroredMemoryBlock< T > *data, const CBLAS_ORDER major_order, const bool use_cuda)
Null constructor.
void allocate_memory (int size)
Allocation of memory for data pointer. It is Referenced for sharing.
void release_memory ()
Release of the memory allocated for data pointer.
void initialize (const int *dim)
Private Attributes
const iterator end_iterator
const const_iterator end_const_iterator
const best_span_iterator end_best_span_iterator
Member Enumeration Documentation
template<typename T> enum Matrix::matrix_contiguous_enum_t private
Enumerator
NONE
CONTIGUOUS
NONCONTIGUOUS
Constructor & Destructor Documentation
template<typename T> Matrix< T >::Matrix () inline private
Referenced by Matrix< float >::cmul().
Member Function Documentation
template<typename T> iterator Matrix< T >::begin () inline
Referenced by AffineTransform2D::accumulate(), Matrix< T >::clone(), ANN::Connections::copyWeightsTo(), ANN::MaxPoolingANNComponent::doBackprop(), ANN::GaussianNoiseANNComponent::doForward(), ANN::SaltAndPepperANNComponent::doForward(), ANN::Connections::loadWeights(), Matrix< T >::Matrix(), Matrix< float >::max(), Matrix< float >::min(), Matrix< float >::minAndMax(), ANN::Connections::printDebug(), ANN::Connections::randomizeWeights(), readMatrixFloatFromStream(), readMatrixFloatHEX(), readMatrixFloatPNM(), saveMatrixFloatHEX(), saveMatrixFloatPNM(), saveMatrixFloatToFile(), saveMatrixFloatToString(), Matrix< T >::transpose(), and hmm_trainer_model::viterbi().
template<typename T> const_iterator Matrix< T >::begin () const inline
template<typename T> const iterator& Matrix< T >::end () inline
Referenced by Matrix< T >::clone(), ANN::MaxPoolingANNComponent::doBackprop(), ANN::GaussianNoiseANNComponent::doForward(), ANN::SaltAndPepperANNComponent::doForward(), Matrix< T >::Matrix(), Matrix< float >::max(), Matrix< float >::min(), Matrix< float >::minAndMax(), ANN::Connections::printDebug(), ANN::Connections::randomizeWeights(), readMatrixFloatFromStream(), saveMatrixFloatToFile(), saveMatrixFloatToString(), and Matrix< T >::transpose().
template<typename T> const const_iterator& Matrix< T >::end () const inline
template<typename T> const best_span_iterator& Matrix< T >::end_span_iterator () const inline
template<typename T> bool Matrix< T >::getCudaFlag () const inline
Referenced by ANN::MAELossFunction::addLoss(), ANN::MSELossFunction::addLoss(), ANN::MultiClassCrossEntropyLossFunction::addLoss(), ANN::CrossEntropyLossFunction::addLoss(), ANN::LocalFMeasureLossFunction::addLoss(), ANN::MSELossFunction::computeGradient(), ANN::MAELossFunction::computeGradient(), ANN::MultiClassCrossEntropyLossFunction::computeGradient(), ANN::CrossEntropyLossFunction::computeGradient(), ANN::LocalFMeasureLossFunction::computeGradient(), clamp_functor::operator()(), sum_functor::operator()(), equals_functor::operator()(), copy_functor::operator()(), axpy_functor::operator()(), and norm2_functor::operator()().
template<typename T> T* Matrix< T >::getData () inline protected
Constructor... -> Integer array with the size of each dimension.
Returns the data pointer for read and write
Referenced by Matrix< T >::col_major_iterator::col_major_iterator(), Matrix< T >::const_col_major_iterator::const_col_major_iterator(), Matrix< T >::const_iterator::const_iterator(), and Matrix< T >::iterator::iterator().
template<typename T> const T* Matrix< T >::getData () const inline protected
Returns the data pointer for read.
template<typename T> const int* Matrix< T >::getDimPtr () const inline
Referenced by ANN::FlattenANNComponent::doBackprop(), ANN::RewrapANNComponent::doBackprop(), ANN::ConvolutionANNComponent::doBackprop(), ANN::ConvolutionBiasANNComponent::doForward(), ANN::MaxPoolingANNComponent::doForward(), and ANN::ConvolutionANNComponent::doForward().
template<typename T> int Matrix< T >::getDimSize (int i) const inline
Referenced by ANN::MAELossFunction::addLoss(), ANN::MSELossFunction::addLoss(), ANN::MultiClassCrossEntropyLossFunction::addLoss(), ANN::CrossEntropyLossFunction::addLoss(), ANN::LocalFMeasureLossFunction::addLoss(), hmm_trainer_model::backward(), ANN::Connections::clone(), ANN::BiasANNComponent::computeBP(), ANN::DotProductANNComponent::computeBP(), ANN::ConvolutionBiasANNComponent::computeBP(), ANN::ConvolutionANNComponent::computeBP(), ANN::MAELossFunction::computeGradient(), ANN::MSELossFunction::computeGradient(), ANN::MultiClassCrossEntropyLossFunction::computeGradient(), ANN::CrossEntropyLossFunction::computeGradient(), ANN::LocalFMeasureLossFunction::computeGradient(), ANN::BiasANNComponent::computeGradients(), ANN::DotProductANNComponent::computeGradients(), ANN::Connections::copyWeightsTo(), ANN::DotProductANNComponent::doBackprop(), ANN::ActivationFunctionANNComponent::doBackprop(), ANN::FlattenANNComponent::doForward(), ANN::RewrapANNComponent::doForward(), ANN::BiasANNComponent::doForward(), ANN::ActivationFunctionANNComponent::doForward(), ANN::MaxPoolingANNComponent::doForward(), ANN::BiasANNComponent::doUpdate(), ANN::DotProductANNComponent::doUpdate(), ANN::ConvolutionBiasANNComponent::doUpdate(), ANN::ConvolutionANNComponent::doUpdate(), hmm_trainer_model::forward(), hmm_trainer_model::forward_backward(), ANN::Connections::getInputSize(), ANN::Connections::getNumInputs(), ANN::Connections::getNumOutputs(), ANN::Connections::getOutputSize(), ANN::Connections::loadWeights(), MatrixDataSet< T >::MatrixDataSet(), ANN::ConvolutionBiasANNComponent::prepareBiasBunch(), ANN::Connections::printDebug(), saveMatrixFloatHEX(), saveMatrixFloatPNM(), saveMatrixFloatToFile(), saveMatrixFloatToString(), and hmm_trainer_model::viterbi().
template<typename T> int Matrix< T >::getLastRawPos () const inline protected
template<typename T> CBLAS_ORDER Matrix< T >::getMajorOrder () const inline
Referenced by Matrix< T >::col_major_iterator::col_major_iterator(), Matrix< T >::const_col_major_iterator::const_col_major_iterator(), Matrix< T >::const_iterator::const_iterator(), ANN::ActivationFunctionANNComponent::doBackprop(), ANN::GaussianNoiseANNComponent::doForward(), ANN::SaltAndPepperANNComponent::doForward(), ANN::ActivationFunctionANNComponent::doForward(), Matrix< T >::iterator::iterator(), saveMatrixFloatToFile(), saveMatrixFloatToString(), and ANN::LossFunction::throwErrorAndGetMatrixFromTokens().
template<typename T> int Matrix< T >::getNumDim () const inline
Referenced by Matrix< T >::col_major_iterator::col_major_iterator(), Matrix< T >::const_col_major_iterator::const_col_major_iterator(), Matrix< T >::const_iterator::const_iterator(), ANN::Connections::copyWeightsTo(), ANN::FlattenANNComponent::doBackprop(), ANN::RewrapANNComponent::doBackprop(), ANN::ActivationFunctionANNComponent::doBackprop(), ANN::ConvolutionANNComponent::doBackprop(), ANN::FlattenANNComponent::doForward(), ANN::RewrapANNComponent::doForward(), ANN::SelectANNComponent::doForward(), ANN::ActivationFunctionANNComponent::doForward(), ANN::ConvolutionBiasANNComponent::doForward(), ANN::MaxPoolingANNComponent::doForward(), ANN::ConvolutionANNComponent::doForward(), Matrix< T >::iterator::iterator(), ANN::Connections::loadWeights(), MatrixDataSet< T >::MatrixDataSet(), saveMatrixFloatHEX(), saveMatrixFloatPNM(), saveMatrixFloatToFile(), saveMatrixFloatToString(), ANN::LossFunction::throwErrorAndGetMatrixFromTokens(), and hmm_trainer_model::viterbi().
template<typename T> int Matrix< T >::getOffset () const inline
Returns the offset of first data value (sub-matrix)
Referenced by Matrix< T >::col_major_iterator::col_major_iterator(), ANN::ConvolutionBiasANNComponent::computeBP(), Matrix< T >::const_col_major_iterator::const_col_major_iterator(), Matrix< T >::const_iterator::const_iterator(), and Matrix< T >::iterator::iterator().
template<typename T> GPUMirroredMemoryBlock<T>* Matrix< T >::getRawDataAccess () inline
Function to obtain RAW access to data pointer. Be careful with it, because you are losing sub-matrix abstraction, and the major order.
Referenced by ANN::MAELossFunction::addLoss(), ANN::MSELossFunction::addLoss(), ANN::MultiClassCrossEntropyLossFunction::addLoss(), ANN::CrossEntropyLossFunction::addLoss(), ANN::LocalFMeasureLossFunction::addLoss(), Image< T >::affine_transform(), hmm_trainer_model::backward(), Image< T >::clone(), ANN::BiasANNComponent::computeBP(), ANN::ConvolutionBiasANNComponent::computeBP(), ANN::MSELossFunction::computeGradient(), ANN::MAELossFunction::computeGradient(), ANN::MultiClassCrossEntropyLossFunction::computeGradient(), ANN::CrossEntropyLossFunction::computeGradient(), ANN::LocalFMeasureLossFunction::computeGradient(), ANN::ActivationFunctionANNComponent::doBackprop(), ANN::MaxPoolingANNComponent::doBackprop(), ANN::ConvolutionANNComponent::doBackprop(), ANN::BiasANNComponent::doForward(), ANN::ActivationFunctionANNComponent::doForward(), ANN::ConvolutionANNComponent::doForward(), hmm_trainer_model::forward(), DataSetFloat2TokenWrapper::getPattern(), DataSetFloat2TokenWrapper::getPatternBunch(), Matrix< float >::maxSelDim(), clamp_functor::operator()(), sum_functor::operator()(), equals_functor::operator()(), copy_functor::operator()(), axpy_functor::operator()(), norm2_functor::operator()(), ANN::Connections::pruneSubnormalAndCheckNormal(), DataSetFloat2TokenWrapper::putPatternBunch(), Image< T >::shear_h(), and SparseDataset< T >::SparseDataset().
template<typename T> const GPUMirroredMemoryBlock<T>* Matrix< T >::getRawDataAccess () const inline
template<typename T> const int* Matrix< T >::getStridePtr () const inline
template<typename T> int Matrix< T >::getStrideSize (int i) const inline
Referenced by ANN::BiasANNComponent::computeBP(), ANN::ConvolutionBiasANNComponent::computeBP(), ANN::DotProductANNComponent::doBackprop(), and ANN::BiasANNComponent::doForward().
template<typename T> int Matrix< T >::getVectorSize () const inline protected
Returns the size of the vector, the coordinate which is different of 1. It only works if the matrix is a vector (precondition).
Referenced by Matrix< float >::dot(), Matrix< float >::gemv(), Matrix< float >::ger(), and Matrix< float >::multiply().
template<typename T> int Matrix< T >::getVectorStride () const inline protected
Referenced by Matrix< float >::dot(), Matrix< float >::gemv(), and Matrix< float >::ger().
template<typename T> bool Matrix< T >::isColVector () const inline protected
Referenced by Matrix< float >::multiply().
template<typename T> bool Matrix< T >::isSimple () const inline
Referenced by ANN::Connections::copyWeightsTo(), Image< T >::Image(), ANN::Connections::loadWeights(), MatrixDataSet< T >::MatrixDataSet(), and SparseDataset< T >::SparseDataset().
template<typename T> bool Matrix< T >::isVector () const inline protected
Returns if the matrix is a vector.
Referenced by Matrix< float >::dot(), Matrix< float >::gemv(), Matrix< float >::ger(), and Matrix< float >::multiply().
template<typename T> iterator Matrix< T >::iteratorAt (int c0) inline
Referenced by ANN::Connections::randomizeWeightsAtColumn().
template<typename T> iterator Matrix< T >::iteratorAt (int c0, int c1) inline
template<typename T> iterator Matrix< T >::iteratorAt (int * coords, int len) inline
template<typename T> const_iterator Matrix< T >::iteratorAt (int c0) const inline
template<typename T> const_iterator Matrix< T >::iteratorAt (int c0, int c1) const inline
template<typename T> const_iterator Matrix< T >::iteratorAt (int * coords, int len) const inline
template<typename T> void Matrix< T >::setUseCuda (bool v) inline
Referenced by ANN::JoinANNComponent::buildInputBunchVector(), ANN::JoinANNComponent::buildMatrixFloatToken(), Matrix< T >::clone(), Matrix< T >::cloneOnlyDims(), Matrix< float >::cmul(), ANN::Connections::computeMomentumOnPrevVector(), ANN::Connections::computeWeightDecayOnPrevVector(), ANN::Connections::copyToPrevVector(), ANN::RewrapANNComponent::doBackprop(), ANN::SelectANNComponent::doBackprop(), ANN::FlattenANNComponent::doBackprop(), ANN::CopyANNComponent::doBackprop(), ANN::ActivationFunctionANNComponent::doBackprop(), ANN::DotProductANNComponent::doBackprop(), ANN::ConvolutionBiasANNComponent::doBackprop(), ANN::MaxPoolingANNComponent::doBackprop(), ANN::ConvolutionANNComponent::doBackprop(), ANN::RewrapANNComponent::doForward(), ANN::SelectANNComponent::doForward(), ANN::FlattenANNComponent::doForward(), ANN::BiasANNComponent::doForward(), ANN::ActivationFunctionANNComponent::doForward(), ANN::DotProductANNComponent::doForward(), ANN::ConvolutionBiasANNComponent::doForward(), ANN::MaxPoolingANNComponent::doForward(), ANN::ConvolutionANNComponent::doForward(), Matrix< float >::maxSelDim(), Matrix< float >::multiply(), Matrix< T >::rewrap(), and Matrix< T >::transpose().
template<typename T> int Matrix< T >::size () const inline
Referenced by Matrix< float >::axpy(), Matrix< float >::cmul(), Matrix< float >::copy(), ANN::Connections::copyWeightsTo(), ANN::ActivationFunctionANNComponent::doBackprop(), ANN::MaxPoolingANNComponent::doBackprop(), ANN::FlattenANNComponent::doForward(), ANN::ActivationFunctionANNComponent::doForward(), ANN::Connections::getNumWeights(), ANN::Connections::loadWeights(), Matrix< T >::Matrix(), ANN::Connections::pruneSubnormalAndCheckNormal(), saveMatrixFloatToString(), ANN::Connections::size(), and SparseDataset< T >::SparseDataset().
Member Data Documentation
template<typename T> GPUMirroredMemoryBlock<T>* Matrix< T >::data protected
Pointer to data.
Referenced by Matrix< float >::cmul(), Matrix< float >::diag(), Matrix< float >::dot(), Matrix< float >::gemm(), Matrix< float >::gemv(), Matrix< float >::ger(), Matrix< float >::getData(), Matrix< float >::getRawDataAccess(), Matrix< T >::Matrix(), Matrix< float >::maxSelDim(), Matrix< float >::norm2(), Matrix< T >::iterator::operator*(), Matrix< T >::col_major_iterator::operator*(), Matrix< T >::const_iterator::operator*(), Matrix< T >::const_col_major_iterator::operator*(), Matrix< T >::iterator::operator=(), AffineTransform2D::rotate(), AffineTransform2D::scale(), Matrix< T >::select(), AffineTransform2D::shear(), and AffineTransform2D::translate().
template<typename T> const best_span_iterator Matrix< T >::end_best_span_iterator private
Referenced by Matrix< float >::end_span_iterator().
template<typename T> const const_iterator Matrix< T >::end_const_iterator private
Referenced by Matrix< float >::end().
template<typename T> const iterator Matrix< T >::end_iterator private
Referenced by Matrix< float >::end().
template<typename T> matrix_contiguous_enum_t Matrix< T >::is_contiguous mutable protected
To know if it is contiguous.
Referenced by Matrix< T >::Matrix().
template<typename T> int Matrix< T >::last_raw_pos protected
Referenced by Matrix< float >::end(), Matrix< float >::end_span_iterator(), Matrix< float >::getLastRawPos(), Matrix< T >::sliding_window::getMatrix(), Matrix< T >::Matrix(), Matrix< T >::sliding_window::operator=(), and Matrix< T >::select().
template<typename T> CBLAS_ORDER Matrix< T >::major_order protected
Major type (only when numDim=2)
Referenced by Matrix< float >::axpy(), Matrix< T >::best_span_iterator::best_span_iterator(), Matrix< float >::cmul(), Matrix< float >::copy(), Matrix< float >::dot(), Matrix< float >::gemm(), Matrix< float >::gemv(), Matrix< float >::ger(), Matrix< float >::getMajorOrder(), Matrix< float >::getVectorStride(), Matrix< float >::isSimple(), Matrix< T >::Matrix(), Matrix< float >::maxSelDim(), Matrix< float >::minAndMax(), Matrix< float >::multiply(), and Matrix< T >::select().
template<typename T> int* Matrix< T >::matrixSize protected
Sub-matrix size of each dimension.
Referenced by Matrix< T >::best_span_iterator::best_span_iterator(), Matrix< float >::diag(), Matrix< float >::gemm(), Matrix< float >::gemv(), Matrix< float >::ger(), Matrix< float >::getDimPtr(), Matrix< float >::getDimSize(), Matrix< float >::getVectorSize(), Matrix< float >::isColVector(), Matrix< float >::isVector(), Matrix< T >::Matrix(), Matrix< float >::maxSelDim(), Matrix< float >::multiply(), Matrix< T >::sameDim(), Matrix< T >::select(), and Matrix< T >::sliding_window::sliding_window().
template<typename T> int Matrix< T >::numDim protected
Number of dimensions.
Referenced by Matrix< T >::best_span_iterator::best_span_iterator(), Matrix< float >::diag(), Matrix< float >::gemm(), Matrix< float >::gemv(), Matrix< float >::ger(), Matrix< float >::getNumDim(), Matrix< float >::getVectorSize(), Matrix< float >::getVectorStride(), Matrix< float >::isColVector(), Matrix< float >::isVector(), Matrix< float >::iteratorAt(), Matrix< T >::Matrix(), Matrix< float >::maxSelDim(), Matrix< float >::multiply(), Matrix< T >::sliding_window::next(), Matrix< float >::norm2(), Matrix< T >::best_span_iterator::operator++(), Matrix< T >::sameDim(), Matrix< T >::select(), and Matrix< T >::sliding_window::sliding_window().
template<typename T> int Matrix< T >::offset protected
Offset for sub-matrix.
Referenced by Matrix< float >::cmul(), Matrix< float >::dot(), Matrix< float >::gemm(), Matrix< float >::gemv(), Matrix< float >::ger(), Matrix< float >::getOffset(), Matrix< T >::Matrix(), Matrix< float >::maxSelDim(), Matrix< T >::sliding_window::next(), Matrix< float >::norm2(), Matrix< T >::sliding_window::operator=(), Matrix< T >::select(), Matrix< T >::sliding_window::setAtWindow(), and Matrix< T >::sliding_window::~sliding_window().
template<typename T> int* Matrix< T >::stride protected
Size of each dimension.
Referenced by Matrix< float >::gemm(), Matrix< float >::gemv(), Matrix< float >::ger(), Matrix< float >::getStridePtr(), Matrix< float >::getStrideSize(), Matrix< float >::getVectorStride(), Matrix< T >::Matrix(), Matrix< float >::maxSelDim(), Matrix< float >::norm2(), Matrix< T >::select(), and Matrix< T >::sliding_window::sliding_window().
template<typename T> int Matrix< T >::total_size protected
Total size of the matrix (number of elements)
Referenced by Matrix< float >::cmul(), Matrix< T >::sliding_window::getMatrix(), Matrix< T >::Matrix(), Matrix< float >::norm2(), Matrix< T >::sliding_window::operator=(), Matrix< T >::select(), and Matrix< float >::size().
template<typename T> bool Matrix< T >::use_cuda protected
For CUDA purposes.
Referenced by Matrix< float >::cmul(), Matrix< float >::copy(), Matrix< float >::diag(), Matrix< float >::dot(), Matrix< float >::gemm(), Matrix< float >::gemv(), Matrix< float >::ger(), Matrix< float >::getCudaFlag(), Matrix< float >::maxSelDim(), Matrix< float >::multiply(), Matrix< float >::norm2(), Matrix< T >::select(), and Matrix< float >::setUseCuda().