april-ann
april_utils::list< T > Class Template Reference
Classes
struct const_iterator
Const iterator used to iterate through a list.
struct const_reverse_iterator
Iterator used to iterate backwards through a list.
struct iterator
Iterator used to iterate through a list.
struct node
struct reverse_iterator
Iterator used to iterate backwards through a list.
Public Types
typedef T value_type
typedef T * pointer
typedef T & reference
typedef const T & const_reference
typedef size_t size_type
typedef ptrdiff_t difference_type
Public Member Functions
iterator begin ()
Returns an iterator pointing to the beginning of the list.
iterator end ()
Returns an iterator pointing to the end of the list.
const_iterator begin () const
Returns a const iterator pointing to the beginning of the list.
const_iterator end () const
Returns a const iterator pointing to the end of the list.
reverse_iterator rbegin ()
Returns a reverse iterator pointing to the beginning of the reversed list.
reverse_iterator rend ()
Returns a reverse iterator pointing to the end of the reversed list.
const_reverse_iterator rbegin () const
Returns a const reverse iterator pointing to the beginning of the reversed list.
const_reverse_iterator rend () const
Returns a const reverse iterator pointing to the end of the reversed list.
size_type size () const
size_type max_size () const
Returns the largest possible size of the list.
bool empty () const
true if the list's size is 0.
list ()
Creates an empty list.
list (size_type n)
Creates a list with n elements, each of which is a copy of T().
list (const list &l)
The copy constructor.
list (size_type n, const_reference t)
Creates a list with n copies of t.
template<class InputIterator >
list (InputIterator f, InputIterator l)
~list ()
The destructor.
list & operator= (const list &l)
The assignment operator.
reference front ()
const_reference front () const
reference back ()
const_reference back () const
void push_front (const_reference t)
Inserts a new element at the beginning.
void push_back (const_reference t)
Inserts a new element at the end.
void pop_front ()
void pop_back ()
void swap (list &l)
Swaps the contents of two lists.
iterator insert (iterator pos, const T &x)
template<class InputIterator >
void insert (iterator pos, InputIterator f, InputIterator l)
Inserts the range [f, l) before pos.
void insert (iterator pos, size_type n, const T &x)
Inserts n copies of x before pos.
iterator erase (iterator pos)
iterator erase (iterator first, iterator last)
void clear ()
Erases all of the elements.
void resize (int n, T x=T())
Inserts or erases elements at the end such that the size becomes n.
void splice (iterator position, list< T > &x)
void splice (iterator position, list< T > &x, iterator i)
void splice (iterator position, list< T > &x, iterator f, iterator l)
void remove (const T &val)
template<class Predicate >
void remove_if (Predicate p)
void unique ()
template<class BinaryPredicate >
void unique (BinaryPredicate p)
void merge (list< T > &x)
template<class BinaryPredicate >
void merge (list< T > &x, BinaryPredicate Comp)
void reverse ()
void sort ()
template<class BinaryPredicate >
void sort (BinaryPredicate comp)
Private Member Functions
void init_list ()
template<typename I >
void init_dispatch (I n, I x, list_aux_templates::_true_type)
template<typename InputIterator >
void init_dispatch (InputIterator f, InputIterator l, list_aux_templates::_false_type)
void init_fill (size_type n, const_reference t)
template<class InputIterator >
void init_range (InputIterator f, InputIterator l)
Creates a list with a copy of a range.
template<typename I >
void insert_dispatch (iterator pos, I n, I x, list_aux_templates::_true_type)
template<typename InputIterator >
void insert_dispatch (iterator pos, InputIterator f, InputIterator l, list_aux_templates::_false_type)
void insert_copies (iterator pos, size_type n, const_reference x)
Inserts n copies of x before pos.
template<class InputIterator >
void insert_range (iterator pos, InputIterator f, InputIterator l)
Inserts the range [f, l) before pos.
Private Attributes
node sentinel
size_t list_size
Member Typedef Documentation
template<class T> typedef const T& april_utils::list< T >::const_reference
template<class T> typedef ptrdiff_t april_utils::list< T >::difference_type
template<class T> typedef T* april_utils::list< T >::pointer
template<class T> typedef T& april_utils::list< T >::reference
template<class T> typedef size_t april_utils::list< T >::size_type
template<class T> typedef T april_utils::list< T >::value_type
Constructor & Destructor Documentation
template<class T> april_utils::list< T >::list () inline
Creates an empty list.
References april_utils::list< T >::init_list().
template<class T> april_utils::list< T >::list (size_type n) inline
Creates a list with n elements, each of which is a copy of T().
References april_utils::list< T >::init_list(), and april_utils::list< T >::push_front().
template<class T> april_utils::list< T >::list (const list< T > & l) inline
The copy constructor.
References april_utils::list< T >::begin(), april_utils::list< T >::end(), april_utils::list< T >::init_list(), and april_utils::list< T >::push_back().
template<class T> april_utils::list< T >::list (size_type n, const_reference t) inline
Creates a list with n copies of t.
References april_utils::list< T >::init_fill().
template<class T> template<class InputIterator > april_utils::list< T >::list (InputIterator f, InputIterator l) inline
References april_utils::list< T >::init_dispatch().
template<class T> april_utils::list< T >::~list () inline
The destructor.
References april_utils::list< T >::clear().
Member Function Documentation
template<class T> reference april_utils::list< T >::back () inline
Returns the last element. Precondition: !empty()
References april_utils::list< T >::node::data, april_utils::list< T >::node::prev, and april_utils::list< T >::sentinel.
template<class T> const_reference april_utils::list< T >::back () const inline
Returns the last element. Precondition: !empty()
References april_utils::list< T >::node::data, april_utils::list< T >::node::prev, and april_utils::list< T >::sentinel.
template<class T> iterator april_utils::list< T >::begin () inline
Returns an iterator pointing to the beginning of the list.
References april_utils::list< T >::node::next, and april_utils::list< T >::sentinel.
Referenced by april_utils::list< T >::clear(), GPUMirroredMemoryBlock< T >::GPUMirroredMemoryBlock(), april_utils::list< T >::list(), april_utils::list< T >::operator=(), april_utils::list< T >::pop_front(), april_utils::list< T >::push_front(), april_utils::list< T >::remove(), april_utils::list< T >::remove_if(), april_utils::list< T >::rend(), and april_utils::list< T >::splice().
template<class T> const_iterator april_utils::list< T >::begin () const inline
Returns a const iterator pointing to the beginning of the list.
References april_utils::list< T >::node::next, and april_utils::list< T >::sentinel.
template<class T> void april_utils::list< T >::clear () inline
Erases all of the elements.
References april_utils::list< T >::begin(), april_utils::list< T >::end(), and april_utils::list< T >::erase().
Referenced by april_utils::list< T >::operator=(), and april_utils::list< T >::~list().
template<class T> bool april_utils::list< T >::empty () const inline
true if the list's size is 0.
References april_utils::list< T >::list_size.
Referenced by GPUMirroredMemoryBlock< T >::GPUMirroredMemoryBlock().
template<class T> iterator april_utils::list< T >::end () inline
Returns an iterator pointing to the end of the list.
References april_utils::list< T >::sentinel.
Referenced by april_utils::list< T >::clear(), april_utils::list< T >::list(), april_utils::list< T >::operator=(), april_utils::list< T >::push_back(), april_utils::list< T >::rbegin(), april_utils::list< T >::remove(), april_utils::list< T >::remove_if(), and april_utils::list< T >::splice().
template<class T> const_iterator april_utils::list< T >::end () const inline
Returns a const iterator pointing to the end of the list.
References april_utils::list< T >::sentinel.
template<class T> iterator april_utils::list< T >::erase (iterator pos) inline
Erases the element at position pos. Returns an iterator to the element immediately following the one that was erased. Precondition: pos must be a dereferenceable iterator
References april_utils::list< T >::list_size, april_utils::list< T >::node::next, april_utils::list< T >::node::prev, and april_utils::list< T >::iterator::ptr.
Referenced by april_utils::list< T >::clear(), april_utils::list< T >::erase(), april_utils::list< T >::pop_back(), april_utils::list< T >::pop_front(), april_utils::list< T >::remove(), and april_utils::list< T >::remove_if().
template<class T> iterator april_utils::list< T >::erase (iterator first, iterator last) inline
Erases the elements in range [first, last) Returns last
References april_utils::list< T >::erase().
template<class T> reference april_utils::list< T >::front () inline
Returns the first element. Precondition: !empty()
References april_utils::list< T >::node::data, april_utils::list< T >::node::next, and april_utils::list< T >::sentinel.
template<class T> const_reference april_utils::list< T >::front () const inline
Returns the first element. Precondition: !empty()
References april_utils::list< T >::node::data, april_utils::list< T >::node::next, and april_utils::list< T >::sentinel.
template<class T> template<typename I > void april_utils::list< T >::init_dispatch (I n, I x, list_aux_templates::_true_type) inline private
References april_utils::list< T >::init_fill().
Referenced by april_utils::list< T >::list().
template<class T> template<typename InputIterator > void april_utils::list< T >::init_dispatch (InputIterator f, InputIterator l, list_aux_templates::_false_type) inline private
References april_utils::list< T >::init_range().
template<class T> void april_utils::list< T >::init_fill (size_type n, const_reference t) inline private
References april_utils::list< T >::init_list(), and april_utils::list< T >::push_front().
Referenced by april_utils::list< T >::init_dispatch(), and april_utils::list< T >::list().
template<class T> void april_utils::list< T >::init_list () inline private
References april_utils::list< T >::list_size, april_utils::list< T >::node::next, april_utils::list< T >::node::prev, and april_utils::list< T >::sentinel.
Referenced by april_utils::list< T >::init_fill(), april_utils::list< T >::init_range(), and april_utils::list< T >::list().
template<class T> template<class InputIterator > void april_utils::list< T >::init_range (InputIterator f, InputIterator l) inline private
Creates a list with a copy of a range.
References april_utils::list< T >::init_list(), and april_utils::list< T >::push_back().
Referenced by april_utils::list< T >::init_dispatch().
template<class T> iterator april_utils::list< T >::insert (iterator pos, const T & x) inline
Inserts x before pos. Returns an iterator pointing to the inserted element
References april_utils::list< T >::list_size, april_utils::list< T >::node::next, april_utils::list< T >::node::prev, and april_utils::list< T >::iterator::ptr.
Referenced by april_utils::list< T >::insert_copies(), april_utils::list< T >::insert_range(), april_utils::list< T >::push_back(), and april_utils::list< T >::push_front().
template<class T> template<class InputIterator > void april_utils::list< T >::insert (iterator pos, InputIterator f, InputIterator l) inline
Inserts the range [f, l) before pos.
References april_utils::list< T >::insert_dispatch().
template<class T> void april_utils::list< T >::insert (iterator pos, size_type n, const T & x) inline
Inserts n copies of x before pos.
References april_utils::list< T >::insert_copies().
template<class T> void april_utils::list< T >::insert_copies (iterator pos, size_type n, const_reference x) inline private
Inserts n copies of x before pos.
References april_utils::list< T >::insert().
Referenced by april_utils::list< T >::insert(), and april_utils::list< T >::insert_dispatch().
template<class T> template<typename I > void april_utils::list< T >::insert_dispatch (iterator pos, I n, I x, list_aux_templates::_true_type) inline private
References april_utils::list< T >::insert_copies().
Referenced by april_utils::list< T >::insert().
template<class T> template<typename InputIterator > void april_utils::list< T >::insert_dispatch (iterator pos, InputIterator f, InputIterator l, list_aux_templates::_false_type) inline private
References april_utils::list< T >::insert_range().
template<class T> template<class InputIterator > void april_utils::list< T >::insert_range (iterator pos, InputIterator f, InputIterator l) inline private
Inserts the range [f, l) before pos.
References april_utils::list< T >::insert().
Referenced by april_utils::list< T >::insert_dispatch().
template<class T> size_type april_utils::list< T >::max_size () const inline
Returns the largest possible size of the list.
template<class T> void april_utils::list< T >::merge (list< T > & x)
Both *this and x must be sorted according to operator<, and they must be distinct. (That is, it is required that &x != this.) This function removes all of x's elements and inserts them in order into *this. The merge is stable; that is, if an element from *this is equivalent to one from x, then the element from *this will precede the one from x. All iterators to elements in *this and x remain valid. This function is linear time: it performs at most size() + x.size() - 1 comparisons.
template<class T> template<class BinaryPredicate > void april_utils::list< T >::merge (list< T > & x, BinaryPredicate Comp)
Comp must be a comparison function that induces a strict weak ordering (as defined in the LessThan Comparable requirements) on objects of type T, and both *this and x must be sorted according to that ordering. The lists x and *this must be distinct. (That is, it is required that &x != this.) This function removes all of x's elements and inserts them in order into *this. The merge is stable; that is, if an element from *this is equivalent to one from x, then the element from *this will precede the one from x. All iterators to elements in *this and x remain valid. This function is linear time: it performs at most size() + x.size() - 1 applications of Comp.
template<class T> list& april_utils::list< T >::operator= (const list< T > & l) inline
The assignment operator.
References april_utils::list< T >::begin(), april_utils::list< T >::clear(), april_utils::list< T >::end(), and april_utils::list< T >::push_back().
template<class T> void april_utils::list< T >::pop_back () inline
Removes the last element. Precondition: !empty()
References april_utils::list< T >::erase(), april_utils::list< T >::node::prev, and april_utils::list< T >::sentinel.
Referenced by april_utils::list< T >::resize().
template<class T> void april_utils::list< T >::pop_front () inline
Removes the first element. Precondition: !empty()
References april_utils::list< T >::begin(), and april_utils::list< T >::erase().
Referenced by GPUMirroredMemoryBlock< T >::GPUMirroredMemoryBlock().
template<class T> void april_utils::list< T >::push_back (const_reference t) inline
Inserts a new element at the end.
References april_utils::list< T >::end(), and april_utils::list< T >::insert().
Referenced by april_utils::list< T >::init_range(), april_utils::list< T >::list(), april_utils::list< T >::operator=(), and april_utils::list< T >::resize().
template<class T> void april_utils::list< T >::push_front (const_reference t) inline
Inserts a new element at the beginning.
References april_utils::list< T >::begin(), and april_utils::list< T >::insert().
Referenced by april_utils::list< T >::init_fill(), april_utils::list< T >::list(), and GPUMirroredMemoryBlock< T >::~GPUMirroredMemoryBlock().
template<class T> reverse_iterator april_utils::list< T >::rbegin () inline
Returns a reverse iterator pointing to the beginning of the reversed list.
References april_utils::list< T >::end().
template<class T> const_reverse_iterator april_utils::list< T >::rbegin () const inline
Returns a const reverse iterator pointing to the beginning of the reversed list.
References april_utils::list< T >::end().
template<class T> void april_utils::list< T >::remove (const T & val) inline
Removes all elements that compare equal to val. The relative order of elements that are not removed is unchanged, and iterators to elements that are not removed remain valid. This function is linear time: it performs exactly size() comparisons for equality.
References april_utils::list< T >::begin(), april_utils::list< T >::end(), and april_utils::list< T >::erase().
template<class T> template<class Predicate > void april_utils::list< T >::remove_if (Predicate p) inline
Removes all elements *i such that p(*i) is true. The relative order of elements that are not removed is unchanged, and iterators to elements that are not removed remain valid. This function is linear time: it performs exactly size() applications of p.
References april_utils::list< T >::begin(), april_utils::list< T >::end(), and april_utils::list< T >::erase().
template<class T> reverse_iterator april_utils::list< T >::rend () inline
Returns a reverse iterator pointing to the end of the reversed list.
References april_utils::list< T >::begin().
template<class T> const_reverse_iterator april_utils::list< T >::rend () const inline
Returns a const reverse iterator pointing to the end of the reversed list.
References april_utils::list< T >::begin().
template<class T> void april_utils::list< T >::resize (int n, T x = T()) inline
Inserts or erases elements at the end such that the size becomes n.
References april_utils::list< T >::list_size, april_utils::list< T >::pop_back(), and april_utils::list< T >::push_back().
template<class T> void april_utils::list< T >::reverse ()
Reverses the order of elements in the list. All iterators remain valid and continue to point to the same elements. This function is linear time.
template<class T> size_type april_utils::list< T >::size () const inline
Returns the size of the list. This is not required to be constant time by the standard. However, this is NOT std::list, and we have decided to keep size() constant time at the expense of having linear time splices.
References april_utils::list< T >::list_size.
Referenced by GPUMirroredMemoryBlock< T >::~GPUMirroredMemoryBlock().
template<class T> void april_utils::list< T >::sort ()
Sorts *this according to operator<. The sort is stable, that is, the relative order of equivalent elements is preserved. All iterators remain valid and continue to point to the same elements. [6] The number of comparisons is approximately N log N, where N is the list's size.
template<class T> template<class BinaryPredicate > void april_utils::list< T >::sort (BinaryPredicate comp)
Comp must be a comparison function that induces a strict weak ordering (as defined in the LessThan Comparable requirements on objects of type T. This function sorts the list *this according to Comp. The sort is stable, that is, the relative order of equivalent elements is preserved. All iterators remain valid and continue to point to the same elements. [6] The number of comparisons is approximately N log N, where N is the list's size.
template<class T> void april_utils::list< T >::splice (iterator position, list< T > & x) inline
position must be a valid iterator in *this, and x must be a list that is distinct from *this. (That is, it is required that &x != this.) All of the elements of x are inserted before position and removed from x. All iterators remain valid, including iterators that point to elements of x. NOTE: This function is linear time in order to keep size() constant time
References april_utils::list< T >::begin(), and april_utils::list< T >::end().
Referenced by april_utils::list< T >::splice().
template<class T> void april_utils::list< T >::splice (iterator position, list< T > & x, iterator i) inline
position must be a valid iterator in *this, and i must be a dereferenceable iterator in x. Splice moves the element pointed to by i from x to *this, inserting it before position. All iterators remain valid, including iterators that point to elements of x. If position == i or position == ++i, this function is a null operation. This function is linear time in order to keep size() constant time.
References april_utils::list< T >::splice().
template<class T> void april_utils::list< T >::splice (iterator position, list< T > & x, iterator f, iterator l) inline
position must be a valid iterator in *this, and [first, last) must be a valid range in x. position may not be an iterator in the range [first, last). Splice moves the elements in [first, last) from x to *this, inserting them before position. All iterators remain valid, including iterators that point to elements of x. [3] This function is linear time in order to keep size() constant time.
References april_utils::list< T >::list_size, april_utils::list< T >::node::next, april_utils::list< T >::node::prev, and april_utils::list< T >::iterator::ptr.
template<class T> void april_utils::list< T >::swap (list< T > & l) inline
Swaps the contents of two lists.
References april_utils::list< T >::list_size, april_utils::list< T >::node::next, april_utils::list< T >::node::prev, april_utils::list< T >::sentinel, and april_utils::swap().
template<class T> void april_utils::list< T >::unique ()
Removes all but the first element in every consecutive group of equal elements. The relative order of elements that are not removed is unchanged, and iterators to elements that are not removed remain valid. This function is linear time: it performs exactly size() - 1 comparisons for equality.
template<class T> template<class BinaryPredicate > void april_utils::list< T >::unique (BinaryPredicate p)
Removes all but the first element in every consecutive group of equivalent elements, where two elements *i and *j are considered equivalent if p(*i, *j) is true. The relative order of elements that are not removed is unchanged, and iterators to elements that are not removed remain valid. This function is linear time: it performs exactly size() - 1 comparisons for equality.
Member Data Documentation
template<class T> size_t april_utils::list< T >::list_size private
Referenced by april_utils::list< T >::empty(), april_utils::list< T >::erase(), april_utils::list< T >::init_list(), april_utils::list< T >::insert(), april_utils::list< T >::resize(), april_utils::list< T >::size(), april_utils::list< T >::splice(), and april_utils::list< T >::swap().
template<class T> node april_utils::list< T >::sentinel private
Referenced by april_utils::list< T >::back(), april_utils::list< T >::begin(), april_utils::list< T >::end(), april_utils::list< T >::front(), april_utils::list< T >::init_list(), april_utils::list< T >::pop_back(), and april_utils::list< T >::swap().