april-ann
ANN::MSE Class Reference
Public Member Functions
MSE ()
virtual ~MSE ()
void computePatternErrorFunction (FloatGPUMirroredMemoryBlock *output, FloatGPUMirroredMemoryBlock *target_output, FloatGPUMirroredMemoryBlock *output_error, FloatGPUMirroredMemoryBlock *pattern_errors, unsigned int output_size, const ANNConfiguration &conf)
float computeBatchErrorFunction (float error_sums, unsigned int num_patterns)
ErrorFunction * clone ()
bool logisticMandatory () const
Public Member Functions inherited from ANN::ErrorFunction
virtual ~ErrorFunction ()
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Attributes
const float zero_epsilon_distance
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Constructor & Destructor Documentation
ANN::MSE::MSE ()
Referenced by clone().
virtual ANN::MSE::~MSE () inline virtual
Member Function Documentation
ErrorFunction* ANN::MSE::clone () inline virtual
Implements ANN::ErrorFunction.
References MSE().
float ANN::MSE::computeBatchErrorFunction (float error_sums, unsigned int num_patterns) virtual
Implements ANN::ErrorFunction.
void ANN::MSE::computePatternErrorFunction (FloatGPUMirroredMemoryBlock * output, FloatGPUMirroredMemoryBlock * target_output, FloatGPUMirroredMemoryBlock * output_error, FloatGPUMirroredMemoryBlock * pattern_errors, unsigned int output_size, const ANNConfiguration & conf) virtual
Implements ANN::ErrorFunction.
References ANNConfiguration::cur_bunch_size, doCalculateMSEErrorFunction(), ANNConfiguration::use_cuda_flag, and zero_epsilon_distance.
bool ANN::MSE::logisticMandatory () const inline virtual
Implements ANN::ErrorFunction.
Member Data Documentation
const float ANN::MSE::zero_epsilon_distance private
Referenced by computePatternErrorFunction().