april-ann
april_utils::MFSet Class Reference
Public Member Functions
MFSet (MFSet *obj)
MFSet (int size=DEFAULT_MFSET_SIZE)
void setSize (int sz)
void print ()
int32_t find (const int32_t value)
void merge (const int32_t value1, const int32_t value2)
void clear ()
int32_t size ()
MFSet * clone ()
int toString (char **buffer)
void fromString (constString cs)
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Attributes
vector< int32_t > data
int32_t max_vector_size
int32_t vector_size
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Constructor & Destructor Documentation
april_utils::MFSet::MFSet (MFSet * obj) inline
References data, max_vector_size, april_utils::vector< T >::reserve(), and vector_size.
Referenced by clone().
april_utils::MFSet::MFSet (int size = DEFAULT_MFSET_SIZE) inline
References data, max_vector_size, april_utils::vector< T >::reserve(), size(), and vector_size.
Member Function Documentation
void april_utils::MFSet::clear () inline
References april_utils::vector< T >::clear(), data, max_vector_size, april_utils::vector< T >::reserve(), and vector_size.
MFSet* april_utils::MFSet::clone () inline
References MFSet().
int32_t april_utils::MFSet::find (const int32_t value) inline
References data, and vector_size.
Referenced by merge().
void april_utils::MFSet::fromString (constString cs) inline
References data, constString::extract_int32_binary(), max_vector_size, april_utils::vector< T >::resize(), and vector_size.
void april_utils::MFSet::merge (const int32_t value1, const int32_t value2) inline
References data, find(), april_utils::max(), max_vector_size, april_utils::vector< T >::resize(), and vector_size.
void april_utils::MFSet::print () inline
References data, and vector_size.
void april_utils::MFSet::setSize (int sz) inline
References data, max_vector_size, april_utils::vector< T >::resize(), and vector_size.
int32_t april_utils::MFSet::size () inline
References vector_size.
Referenced by MFSet().
int april_utils::MFSet::toString (char ** buffer) inline
References april_utils::vector< T >::begin(), binarizer::buffer_size_32(), binarizer::code_int32(), binarizer::code_vector_int32(), data, and vector_size.
Member Data Documentation
vector<int32_t> april_utils::MFSet::data private
Referenced by clear(), find(), fromString(), merge(), MFSet(), print(), setSize(), and toString().
int32_t april_utils::MFSet::max_vector_size private
Referenced by clear(), fromString(), merge(), MFSet(), and setSize().
int32_t april_utils::MFSet::vector_size private
Referenced by clear(), find(), fromString(), merge(), MFSet(), print(), setSize(), size(), and toString().