april-ann
Functions::FunctionInterface< I, O > Class Template Reference
A virtual templatized class which implement some basic functionality and describe methods for functions.
Public Member Functions
virtual ~FunctionInterface ()
virtual bool calculate (const I *input_vector, unsigned int input_size, O *output_vector, unsigned int output_size)=0
A new abstract method that computes output vector given input vector.
virtual void calculateInPipeline (DataProducer< I > *producer, unsigned int input_size, DataConsumer< O > *consumer, unsigned int output_size)
Method for flow computation of outputs in a pipeline system.
Public Member Functions inherited from Functions::FunctionBase
FunctionBase ()
virtual ~FunctionBase ()
virtual NS_function_io::type getInputType () const =0
It returns the data type of the input (or domain).
virtual NS_function_io::type getOutputType () const =0
It returns the data type of the output (or range).
virtual unsigned int getInputSize () const =0
It returns the input (or domain) size of the function.
virtual unsigned int getOutputSize () const =0
It returns the output (or range) size of the function.
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Detailed Description
template<typename I, typename O>
class Functions::FunctionInterface< I, O >
A virtual templatized class which implement some basic functionality and describe methods for functions.
A FunctionInterface is an abstraction of an object which represents a mathematical function, as a especialization of the FunctionBase class. It adds to the interface one abstract method which calculates output vector given input vector, and a basic implementation of a method that consumes input vectors (from a DataProducer) and produces output vectros (to a DataConsumer).
This class needs to be instantiated, fixing input/output types, and needs to be extended in order to implement abstract methods.
Constructor & Destructor Documentation
template<typename I , typename O > virtual Functions::FunctionInterface< I, O >::~FunctionInterface () inline virtual
Member Function Documentation
template<typename I , typename O > virtual bool Functions::FunctionInterface< I, O >::calculate (const I * input_vector, unsigned int input_size, O * output_vector, unsigned int output_size) pure virtual
A new abstract method that computes output vector given input vector.
Referenced by Functions::FunctionInterface< I, O >::calculateInPipeline().
template<typename I , typename O > virtual void Functions::FunctionInterface< I, O >::calculateInPipeline (DataProducer< I > * producer, unsigned int input_size, DataConsumer< O > * consumer, unsigned int output_size) inline virtual
Method for flow computation of outputs in a pipeline system.
This method process a flow of data vectors, computed by a DataProducer, and produces an output vector for each of them. Output vectors are given to a DataConsumer. The end of the flow is indicated by DataProducer using a 0 pointer. Is mandatory to produces a 0 pointer to feed the DataConsumer when the flow ends. Input vector pointer is property of this method, needs to be freed. Output vector pointer is property of the DataConsumer object.
References Functions::FunctionInterface< I, O >::calculate(), ERROR_PRINT, Functions::DataProducer< T >::get(), Functions::FunctionBase::getInputSize(), Functions::FunctionBase::getOutputSize(), and Functions::DataConsumer< T >::put().
Referenced by Trainable::TrainableSupervised::useDataset().