april-ann
DataSetTokenVector Class Reference
Dataset
Public Member Functions
DataSetTokenVector (int pattern_size)
virtual ~DataSetTokenVector ()
void push_back (Token *token)
virtual int numPatterns ()
Number of patterns in the set.
virtual int patternSize ()
Size of each pattern.
virtual Token * getPattern (int index)
Get the pattern index to the vector pat.
virtual Token * getPatternBunch (const int *indexes, unsigned int bunch_size)
Get the pattern index to the vector pat.
virtual void putPattern (int index, Token *pat)
Put the given vector pat at pattern index.
virtual void putPatternBunch (const int *indexes, unsigned int bunch_size, Token *pat)
Put the pattern bunch.
Public Member Functions inherited from DataSetToken
virtual ~DataSetToken ()
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Attributes
april_utils::vector< Token * > data
int pattern_size
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Constructor & Destructor Documentation
DataSetTokenVector::DataSetTokenVector (int pattern_size) inline
virtual DataSetTokenVector::~DataSetTokenVector () inline virtual
References data, DecRef, and april_utils::vector< T >::size().
Member Function Documentation
virtual Token* DataSetTokenVector::getPattern (int index) inline virtual
Get the pattern index to the vector pat.
Implements DataSetToken.
References data, and numPatterns().
Referenced by getPatternBunch().
virtual Token* DataSetTokenVector::getPatternBunch (const int * indexes, unsigned int bunch_size) inline virtual
Get the pattern index to the vector pat.
Implements DataSetToken.
References Token::convertTo(), DecRef, doScopy(), TokenMemoryBlock::getCudaFlag(), TokenMemoryBlock::getMemBlock(), getPattern(), Token::getTokenCode(), IncRef, pattern_size, and table_of_token_codes::token_mem_block.
virtual int DataSetTokenVector::numPatterns () inline virtual
Number of patterns in the set.
Implements DataSetToken.
References data, and april_utils::vector< T >::size().
Referenced by getPattern(), and putPattern().
virtual int DataSetTokenVector::patternSize () inline virtual
Size of each pattern.
Implements DataSetToken.
References pattern_size.
void DataSetTokenVector::push_back (Token * token) inline
References data, IncRef, and april_utils::vector< T >::push_back().
virtual void DataSetTokenVector::putPattern (int index, Token * pat) inline virtual
Put the given vector pat at pattern index.
Implements DataSetToken.
References AssignRef, data, and numPatterns().
virtual void DataSetTokenVector::putPatternBunch (const int * indexes, unsigned int bunch_size, Token * pat) inline virtual
Put the pattern bunch.
Implements DataSetToken.
References ERROR_EXIT.
Member Data Documentation
april_utils::vector<Token*> DataSetTokenVector::data private
Referenced by getPattern(), numPatterns(), push_back(), putPattern(), and ~DataSetTokenVector().
int DataSetTokenVector::pattern_size private
Referenced by getPatternBunch(), and patternSize().