april-ann
ANN::LocalFMeasure Class Reference
Public Member Functions
LocalFMeasure (float alpha=2.0f)
virtual ~LocalFMeasure ()
void computePatternErrorFunction (FloatGPUMirroredMemoryBlock *output, FloatGPUMirroredMemoryBlock *target_output, FloatGPUMirroredMemoryBlock *output_error, FloatGPUMirroredMemoryBlock *pattern_errors, unsigned int output_size, const ANNConfiguration &conf)
float computeBatchErrorFunction (float error_sums, unsigned int num_patterns)
ErrorFunction * clone ()
Public Member Functions inherited from ANN::ErrorFunction
virtual ~ErrorFunction ()
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Attributes
float alpha
unsigned int N
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Constructor & Destructor Documentation
ANN::LocalFMeasure::LocalFMeasure (float alpha = 2.0f)
Referenced by clone().
virtual ANN::LocalFMeasure::~LocalFMeasure () inline virtual
Member Function Documentation
ErrorFunction* ANN::LocalFMeasure::clone () inline virtual
Implements ANN::ErrorFunction.
References alpha, and LocalFMeasure().
float ANN::LocalFMeasure::computeBatchErrorFunction (float error_sums, unsigned int num_patterns) virtual
Implements ANN::ErrorFunction.
References N.
void ANN::LocalFMeasure::computePatternErrorFunction (FloatGPUMirroredMemoryBlock * output, FloatGPUMirroredMemoryBlock * target_output, FloatGPUMirroredMemoryBlock * output_error, FloatGPUMirroredMemoryBlock * pattern_errors, unsigned int output_size, const ANNConfiguration & conf) virtual
Implements ANN::ErrorFunction.
References alpha, ANNConfiguration::cur_bunch_size, doCalculateLocalFMeasure(), N, and ANNConfiguration::use_cuda_flag.
Member Data Documentation
float ANN::LocalFMeasure::alpha private
Referenced by clone(), and computePatternErrorFunction().
unsigned int ANN::LocalFMeasure::N private
Referenced by computeBatchErrorFunction(), and computePatternErrorFunction().