april-ann
ANN::Connections Class Reference
Public Member Functions
Connections (unsigned int num_inputs, unsigned int num_outputs, const MatrixFloat *w=0, const MatrixFloat *oldw=0)
~Connections ()
void reset ()
void countReference ()
unsigned int getNumReferences () const
unsigned int getInputSize () const
unsigned int getNumInputs () const
unsigned int getOutputSize () const
unsigned int getNumOutputs () const
void beginUpdate ()
bool endUpdate ()
bool isFirstUpdateCall ()
void computeMomentumOnPrevVector (float momentum, bool use_cuda)
void computeWeightDecayOnPrevVector (float c_weight_decay, bool use_cuda)
void applyMaxNormPenalty (float max_norm_penalty)
void copyToPrevVector (bool use_cuda)
unsigned int size () const
void pruneSubnormalAndCheckNormal ()
MatrixFloat * getPtr ()
MatrixFloat * getPrevPtr ()
bool checkInputOutputSizes (unsigned int input_size, unsigned int output_size) const
void randomizeWeights (MTRand *rnd, float low, float high)
void randomizeWeightsAtColumn (unsigned int col, MTRand *rnd, float low, float high)
unsigned int loadWeights (MatrixFloat *data, MatrixFloat *old_data, unsigned int first_weight_pos, unsigned int column_size)
unsigned int copyWeightsTo (MatrixFloat *data, MatrixFloat *old_data, unsigned int first_weight_pos, unsigned int column_size)
Connections * clone ()
unsigned int getNumWeights () const
void printDebug ()
char * toLuaString ()
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Static Public Attributes
static const double weightnearzero = 1e-7
Protected Attributes
MatrixFloat * weights
MatrixFloat * prev_weights
unsigned int num_references
unsigned int update_weights_calls
Protected Attributes inherited from Referenced
int refs
Constructor & Destructor Documentation
ANN::Connections::Connections (unsigned int num_inputs, unsigned int num_outputs, const MatrixFloat * w = 0, const MatrixFloat * oldw = 0)
References Matrix< T >::copy(), ERROR_EXIT, IncRef, prev_weights, and weights.
Referenced by clone().
ANN::Connections::~Connections ()
References DecRef, prev_weights, and weights.
Member Function Documentation
void ANN::Connections::applyMaxNormPenalty (float max_norm_penalty)
References Matrix< T >::norm2(), prev_weights, Matrix< T >::scal(), and weights.
Referenced by ANN::DotProductANNComponent::doUpdate(), and ANN::ConvolutionANNComponent::doUpdate().
void ANN::Connections::beginUpdate ()
References update_weights_calls.
Referenced by ANN::BiasANNComponent::doUpdate(), ANN::DotProductANNComponent::doUpdate(), ANN::ConvolutionBiasANNComponent::doUpdate(), and ANN::ConvolutionANNComponent::doUpdate().
bool ANN::Connections::checkInputOutputSizes (unsigned int input_size, unsigned int output_size) const
References ERROR_PRINT, getInputSize(), and getOutputSize().
Referenced by ANN::BiasANNComponent::build(), ANN::DotProductANNComponent::build(), ANN::ConvolutionBiasANNComponent::build(), and ANN::ConvolutionANNComponent::build().
Connections * ANN::Connections::clone ()
References Connections(), Matrix< T >::getDimSize(), prev_weights, and weights.
void ANN::Connections::computeMomentumOnPrevVector (float momentum, bool use_cuda)
References Matrix< T >::axpy(), prev_weights, Matrix< T >::scal(), Matrix< T >::setUseCuda(), and weights.
Referenced by ANN::BiasANNComponent::doUpdate(), ANN::DotProductANNComponent::doUpdate(), ANN::ConvolutionBiasANNComponent::doUpdate(), and ANN::ConvolutionANNComponent::doUpdate().
void ANN::Connections::computeWeightDecayOnPrevVector (float c_weight_decay, bool use_cuda)
References Matrix< T >::axpy(), prev_weights, Matrix< T >::setUseCuda(), and weights.
Referenced by ANN::BiasANNComponent::doUpdate(), ANN::DotProductANNComponent::doUpdate(), ANN::ConvolutionBiasANNComponent::doUpdate(), and ANN::ConvolutionANNComponent::doUpdate().
void ANN::Connections::copyToPrevVector (bool use_cuda)
References Matrix< T >::copy(), prev_weights, Matrix< T >::setUseCuda(), and weights.
Referenced by ANN::BiasANNComponent::doUpdate(), ANN::DotProductANNComponent::doUpdate(), ANN::ConvolutionBiasANNComponent::doUpdate(), and ANN::ConvolutionANNComponent::doUpdate().
unsigned int ANN::Connections::copyWeightsTo (MatrixFloat * data, MatrixFloat * old_data, unsigned int first_weight_pos, unsigned int column_size)
References Matrix< T >::begin(), ERROR_EXIT, ERROR_EXIT2, Matrix< T >::getDimSize(), Matrix< T >::getNumDim(), Matrix< T >::isSimple(), april_utils::max(), prev_weights, Matrix< T >::size(), and weights.
void ANN::Connections::countReference ()
References num_references.
Referenced by ANN::BiasANNComponent::build(), ANN::DotProductANNComponent::build(), ANN::ConvolutionBiasANNComponent::build(), and ANN::ConvolutionANNComponent::build().
bool ANN::Connections::endUpdate ()
References num_references, prev_weights, april_utils::swap(), update_weights_calls, and weights.
Referenced by ANN::BiasANNComponent::doUpdate(), ANN::DotProductANNComponent::doUpdate(), ANN::ConvolutionBiasANNComponent::doUpdate(), and ANN::ConvolutionANNComponent::doUpdate().
unsigned int ANN::Connections::getInputSize () const inline
References Matrix< T >::getDimSize(), and weights.
Referenced by checkInputOutputSizes(), and toLuaString().
unsigned int ANN::Connections::getNumInputs () const inline
References Matrix< T >::getDimSize(), and weights.
unsigned int ANN::Connections::getNumOutputs () const inline
References Matrix< T >::getDimSize(), and weights.
unsigned int ANN::Connections::getNumReferences () const
References num_references.
Referenced by ANN::BiasANNComponent::doUpdate(), ANN::DotProductANNComponent::doUpdate(), ANN::ConvolutionBiasANNComponent::doUpdate(), and ANN::ConvolutionANNComponent::doUpdate().
unsigned int ANN::Connections::getNumWeights () const inline
References Matrix< T >::size(), and weights.
unsigned int ANN::Connections::getOutputSize () const inline
References Matrix< T >::getDimSize(), and weights.
Referenced by checkInputOutputSizes(), and toLuaString().
MatrixFloat * ANN::Connections::getPrevPtr ()
References prev_weights.
Referenced by ANN::BiasANNComponent::doUpdate(), ANN::DotProductANNComponent::doUpdate(), ANN::ConvolutionBiasANNComponent::doUpdate(), and ANN::ConvolutionANNComponent::doUpdate().
MatrixFloat * ANN::Connections::getPtr ()
References weights.
Referenced by ANN::BiasANNComponent::computeGradients(), ANN::DotProductANNComponent::computeGradients(), ANN::ConvolutionBiasANNComponent::computeGradients(), ANN::ConvolutionANNComponent::computeGradients(), ANN::DotProductANNComponent::doBackprop(), ANN::ConvolutionANNComponent::doBackprop(), ANN::BiasANNComponent::doForward(), ANN::DotProductANNComponent::doForward(), ANN::ConvolutionANNComponent::doForward(), ANN::BiasANNComponent::doUpdate(), ANN::DotProductANNComponent::doUpdate(), and ANN::ConvolutionBiasANNComponent::prepareBiasBunch().
bool ANN::Connections::isFirstUpdateCall ()
References update_weights_calls.
Referenced by ANN::BiasANNComponent::doUpdate(), ANN::DotProductANNComponent::doUpdate(), ANN::ConvolutionBiasANNComponent::doUpdate(), and ANN::ConvolutionANNComponent::doUpdate().
unsigned int ANN::Connections::loadWeights (MatrixFloat * data, MatrixFloat * old_data, unsigned int first_weight_pos, unsigned int column_size)
References Matrix< T >::begin(), ERROR_EXIT, ERROR_EXIT2, Matrix< T >::getDimSize(), Matrix< T >::getNumDim(), Matrix< T >::isSimple(), april_utils::max(), prev_weights, Matrix< T >::size(), and weights.
void ANN::Connections::printDebug ()
References Matrix< T >::begin(), Matrix< T >::end(), Matrix< T >::getDimSize(), num_references, prev_weights, update_weights_calls, and weights.
void ANN::Connections::pruneSubnormalAndCheckNormal ()
References april_utils::check_floats(), ERROR_EXIT, GPUMirroredMemoryBlock< T >::getPPALForReadAndWrite(), Matrix< T >::getRawDataAccess(), Matrix< T >::size(), and weights.
Referenced by ANN::BiasANNComponent::doUpdate(), ANN::DotProductANNComponent::doUpdate(), ANN::ConvolutionBiasANNComponent::doUpdate(), and ANN::ConvolutionANNComponent::doUpdate().
void ANN::Connections::randomizeWeights (MTRand * rnd, float low, float high)
References Matrix< T >::begin(), Matrix< T >::end(), prev_weights, rnd_weight, weightnearzero, and weights.
void ANN::Connections::randomizeWeightsAtColumn (unsigned int col, MTRand * rnd, float low, float high)
References Matrix< T >::iteratorAt(), prev_weights, rnd_weight, weightnearzero, and weights.
void ANN::Connections::reset () inline
References num_references, and update_weights_calls.
Referenced by ANN::BiasANNComponent::resetConnections(), ANN::DotProductANNComponent::resetConnections(), ANN::ConvolutionBiasANNComponent::resetConnections(), and ANN::ConvolutionANNComponent::resetConnections().
unsigned int ANN::Connections::size () const
References Matrix< T >::size(), and weights.
char * ANN::Connections::toLuaString ()
References getInputSize(), getOutputSize(), buffer_list::NULL_TERMINATED, prev_weights, buffer_list::printf(), saveMatrixFloatToString(), buffer_list::to_string(), and weights.
Member Data Documentation
unsigned int ANN::Connections::num_references protected
Referenced by countReference(), endUpdate(), getNumReferences(), printDebug(), and reset().
MatrixFloat* ANN::Connections::prev_weights protected
Referenced by applyMaxNormPenalty(), clone(), computeMomentumOnPrevVector(), computeWeightDecayOnPrevVector(), Connections(), copyToPrevVector(), copyWeightsTo(), endUpdate(), getPrevPtr(), loadWeights(), printDebug(), randomizeWeights(), randomizeWeightsAtColumn(), toLuaString(), and ~Connections().
unsigned int ANN::Connections::update_weights_calls protected
numero de veces que se ha llamado al metodo update_weights_call, se inicia a 0 cuando este valor llega a getNumReferences()
Referenced by beginUpdate(), endUpdate(), isFirstUpdateCall(), printDebug(), and reset().
const double ANN::Connections::weightnearzero = 1e-7 static
Referenced by randomizeWeights(), and randomizeWeightsAtColumn().
MatrixFloat* ANN::Connections::weights protected
Referenced by applyMaxNormPenalty(), clone(), computeMomentumOnPrevVector(), computeWeightDecayOnPrevVector(), Connections(), copyToPrevVector(), copyWeightsTo(), endUpdate(), getInputSize(), getNumInputs(), getNumOutputs(), getNumWeights(), getOutputSize(), getPtr(), loadWeights(), printDebug(), pruneSubnormalAndCheckNormal(), randomizeWeights(), randomizeWeightsAtColumn(), size(), toLuaString(), and ~Connections().