april-ann
log_float Class Reference
Util
Public Member Functions
log_float (float x)
log_float ()
float to_float () const
double to_double () const
float log () const
log_float raise_to (float exponent)
log_float operator+= (const log_float &y)
log_float operator+= (const log_double &y)
log_float operator*= (const log_float &y)
log_float operator*= (const log_double &y)
log_float operator/= (const log_float &y)
log_float operator/= (const log_double &y)
log_float operator-= (const log_float &y)
log_float operator-= (const log_double &y)
operator float () const
operator double () const
operator unsigned int () const
log_float & operator= (float &value)
log_float & operator= (double &value)
log_float & operator= (const log_double &value)
log_float (float x)
log_float ()
float to_float () const
double to_double () const
float log () const
log_float raise_to (float exponent) const
log_float operator+= (const log_float &y)
log_float operator+= (const log_double &y)
log_float operator*= (const log_float &y)
log_float operator*= (const log_double &y)
log_float operator/= (const log_float &y)
log_float operator/= (const log_double &y)
log_float operator-= (const log_float &y)
log_float operator-= (const log_double &y)
operator float () const
operator double () const
operator unsigned int () const
log_float & operator= (float &value)
log_float & operator= (double &value)
log_float & operator= (const log_double &value)
log_float (float x)
log_float ()
float to_float () const
double to_double () const
float log () const
log_float raise_to (float exponent)
log_float operator+= (const log_float &y)
log_float operator+= (const log_double &y)
log_float operator*= (const log_float &y)
log_float operator*= (const log_double &y)
log_float operator/= (const log_float &y)
log_float operator/= (const log_double &y)
log_float operator-= (const log_float &y)
log_float operator-= (const log_double &y)
operator float () const
operator double () const
operator unsigned int () const
log_float & operator= (float &value)
log_float & operator= (double &value)
log_float & operator= (const log_double &value)
Static Public Member Functions
static log_float zero ()
static log_float one ()
static log_float from_float (float value)
static log_float zero ()
static log_float one ()
static log_float from_float (float value)
static log_float from_double (double value)
static log_float zero ()
static log_float one ()
static log_float from_float (float value)
Private Attributes
float raw_value
Static Private Attributes
static const float floatnearzero = 1e-37
static const float rawscorenearzero = -99
static const float rawscorezero = -1e12
static const float rawscoreone = 0
Friends
log_float operator+ (const log_float &x, const log_float &y)
log_float operator* (const log_float &x, const log_float &y)
log_float operator/ (const log_float &x, const log_float &y)
log_float operator- (const log_float &x, const log_float &y)
bool operator== (const log_float &x, const log_float &y)
bool operator!= (const log_float &x, const log_float &y)
bool operator>= (const log_float &x, const log_float &y)
bool operator<= (const log_float &x, const log_float &y)
bool operator> (const log_float &x, const log_float &y)
bool operator< (const log_float &x, const log_float &y)
log_float operator+ (const log_float &x, const log_float &y)
log_float operator* (const log_float &x, const log_float &y)
log_float operator/ (const log_float &x, const log_float &y)
log_float operator- (const log_float &x, const log_float &y)
bool operator== (const log_float &x, const log_float &y)
bool operator!= (const log_float &x, const log_float &y)
bool operator>= (const log_float &x, const log_float &y)
bool operator<= (const log_float &x, const log_float &y)
bool operator> (const log_float &x, const log_float &y)
bool operator< (const log_float &x, const log_float &y)
log_float operator+ (const log_float &x, const log_float &y)
log_float operator* (const log_float &x, const log_float &y)
log_float operator/ (const log_float &x, const log_float &y)
log_float operator- (const log_float &x, const log_float &y)
bool operator== (const log_float &x, const log_float &y)
bool operator!= (const log_float &x, const log_float &y)
bool operator>= (const log_float &x, const log_float &y)
bool operator<= (const log_float &x, const log_float &y)
bool operator> (const log_float &x, const log_float &y)
bool operator< (const log_float &x, const log_float &y)
Constructor & Destructor Documentation
log_float::log_float (float x) inline
log_float::log_float () inline
Referenced by from_double(), from_float(), one(), operator*(), operator+(), operator-(), operator/(), raise_to(), and zero().
log_float::log_float (float x) inline
log_float::log_float () inline
log_float::log_float (float x) inline
log_float::log_float () inline
Member Function Documentation
static log_float log_float::from_double (double value) inline static
References floatnearzero, log(), log_float(), and rawscorezero.
static log_float log_float::from_float (float value) inline static
References floatnearzero, log(), log_float(), and rawscorezero.
static log_float log_float::from_float (float value) inline static
References floatnearzero, log(), log_float(), and rawscorezero.
static log_float log_float::from_float (float value) inline static
References floatnearzero, log(), log_float(), and rawscorezero.
float log_float::log () const inline
References raw_value.
float log_float::log () const inline
References raw_value.
Referenced by from_double(), and from_float().
float log_float::log () const inline
References raw_value.
static log_float log_float::one () inline static
References log_float(), and rawscoreone.
static log_float log_float::one () inline static
References log_float(), and rawscoreone.
static log_float log_float::one () inline static
References log_float(), and rawscoreone.
log_float::operator double () const inline
References raw_value.
log_float::operator double () const inline
References raw_value.
log_float::operator double () const inline
References raw_value.
log_float::operator float () const inline
References raw_value.
log_float::operator float () const inline
References raw_value.
log_float::operator float () const inline
References raw_value.
log_float::operator unsigned int () const inline
References raw_value.
log_float::operator unsigned int () const inline
References raw_value.
log_float::operator unsigned int () const inline
References raw_value.
log_float log_float::operator*= (const log_float & y) inline
log_float log_float::operator*= (const log_float & y) inline
References raw_value, and rawscorezero.
log_float log_float::operator*= (const log_float & y) inline
References raw_value, and rawscorezero.
log_float log_float::operator*= (const log_double & y)
log_float log_float::operator*= (const log_double & y)
log_float log_float::operator+= (const log_float & y) inline
References raw_value, and rawscorezero.
log_float log_float::operator+= (const log_float & y) inline
References raw_value, and rawscorezero.
log_float log_float::operator+= (const log_float & y) inline
log_float log_float::operator+= (const log_double & y)
log_float log_float::operator+= (const log_double & y)
log_float log_float::operator-= (const log_float & y) inline
log_float log_float::operator-= (const log_double & y)
log_float log_float::operator-= (const log_float & y) inline
References raw_value, and rawscorezero.
log_float log_float::operator-= (const log_float & y) inline
References raw_value, and rawscorezero.
log_float log_float::operator-= (const log_double & y)
log_float log_float::operator/= (const log_float & y) inline
log_float log_float::operator/= (const log_double & y)
log_float log_float::operator/= (const log_float & y) inline
References raw_value, and rawscorezero.
log_float log_float::operator/= (const log_float & y) inline
References raw_value, and rawscorezero.
log_float log_float::operator/= (const log_double & y)
log_float& log_float::operator= (float & value) inline
References raw_value.
log_float& log_float::operator= (double & value) inline
References raw_value.
log_float& log_float::operator= (float & value) inline
References raw_value, and rawscorezero.
log_float& log_float::operator= (const log_double & value)
log_float& log_float::operator= (float & value) inline
References raw_value, and rawscorezero.
log_float& log_float::operator= (double & value) inline
References raw_value, and rawscorezero.
log_float& log_float::operator= (double & value) inline
References raw_value, and rawscorezero.
log_float& log_float::operator= (const log_double & value)
log_float log_float::raise_to (float exponent) inline
References log_float(), raw_value, and rawscorezero.
log_float log_float::raise_to (float exponent) inline
References log_float(), raw_value, and rawscorezero.
log_float log_float::raise_to (float exponent) const inline
References log_float(), and raw_value.
double log_float::to_double () const inline
References raw_value.
double log_float::to_double () const inline
References raw_value.
double log_float::to_double () const inline
References raw_value.
float log_float::to_float () const inline
References raw_value.
float log_float::to_float () const inline
References raw_value.
float log_float::to_float () const inline
References raw_value.
static log_float log_float::zero () inline static
References log_float(), and rawscorezero.
static log_float log_float::zero () inline static
References log_float(), and rawscorezero.
static log_float log_float::zero () inline static
References log_float(), and rawscorezero.
Referenced by operator*(), operator+(), operator-(), and operator/().
Friends And Related Function Documentation
bool operator!= (const log_float & x, const log_float & y) friend
bool operator!= (const log_float & x, const log_float & y) friend
bool operator!= (const log_float & x, const log_float & y) friend
log_float operator* (const log_float & x, const log_float & y) friend
log_float operator* (const log_float & x, const log_float & y) friend
log_float operator* (const log_float & x, const log_float & y) friend
log_float operator+ (const log_float & x, const log_float & y) friend
log_float operator+ (const log_float & x, const log_float & y) friend
log_float operator+ (const log_float & x, const log_float & y) friend
log_float operator- (const log_float & x, const log_float & y) friend
log_float operator- (const log_float & x, const log_float & y) friend
log_float operator- (const log_float & x, const log_float & y) friend
log_float operator/ (const log_float & x, const log_float & y) friend
log_float operator/ (const log_float & x, const log_float & y) friend
log_float operator/ (const log_float & x, const log_float & y) friend
bool operator< (const log_float & x, const log_float & y) friend
bool operator< (const log_float & x, const log_float & y) friend
bool operator< (const log_float & x, const log_float & y) friend
bool operator<= (const log_float & x, const log_float & y) friend
bool operator<= (const log_float & x, const log_float & y) friend
bool operator<= (const log_float & x, const log_float & y) friend
bool operator== (const log_float & x, const log_float & y) friend
bool operator== (const log_float & x, const log_float & y) friend
bool operator== (const log_float & x, const log_float & y) friend
bool operator> (const log_float & x, const log_float & y) friend
bool operator> (const log_float & x, const log_float & y) friend
bool operator> (const log_float & x, const log_float & y) friend
bool operator>= (const log_float & x, const log_float & y) friend
bool operator>= (const log_float & x, const log_float & y) friend
bool operator>= (const log_float & x, const log_float & y) friend
Member Data Documentation
float log_float::raw_value private
Referenced by log(), operator double(), operator float(), operator unsigned int(), operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), raise_to(), to_double(), and to_float().