april-ann
april_utils::string Class Reference
Public Types
typedef char value_type
typedef vector< char > container
typedef char & reference
typedef const char & const_reference
typedef container::iterator iterator
typedef container::const_iterator const_iterator
typedef container::difference_type difference_type
typedef container::size_type size_type
Public Member Functions
string ()
string (const char *ptr)
string (const char *ptr, size_t len)
string (const string &other)
~string ()
string & operator= (const string &other)
string & operator+= (const string &other)
void append (const string &other)
bool operator== (const string &other) const
bool operator< (const string &other) const
bool operator<= (const string &other) const
char & operator[] (unsigned int i)
char operator[] (unsigned int i) const
void push_back (char c)
void pop_back ()
const char * c_str () const
const char * data () const
char * begin ()
char * end ()
const char * begin () const
const char * end () const
size_type size () const
size_type max_size () const
void resize (size_type size)
size_type capacity ()
void reserve (size_type size)
void clear ()
bool empty () const
void swap (string &other)
char at (unsigned int i) const
char & at (unsigned int i)
char front () const
char & front ()
char back () const
char & back ()
Private Attributes
vector< char > vec
Member Typedef Documentation
typedef container::const_iterator april_utils::string::const_iterator
typedef const char& april_utils::string::const_reference
typedef vector<char> april_utils::string::container
typedef container::difference_type april_utils::string::difference_type
typedef container::iterator april_utils::string::iterator
typedef char& april_utils::string::reference
typedef container::size_type april_utils::string::size_type
typedef char april_utils::string::value_type
Constructor & Destructor Documentation
april_utils::string::string ()
april_utils::string::string (const char * ptr)
april_utils::string::string (const char * ptr, size_t len)
april_utils::string::string (const string & other)
april_utils::string::~string ()
Member Function Documentation
void april_utils::string::append (const string & other)
References april_utils::vector< T >::push_back(), size(), and vec.
Referenced by operator+=().
char april_utils::string::at (unsigned int i) const
References vec.
char & april_utils::string::at (unsigned int i)
References vec.
char april_utils::string::back () const
References april_utils::vector< T >::back(), and vec.
char & april_utils::string::back ()
References april_utils::vector< T >::back(), and vec.
char * april_utils::string::begin ()
References april_utils::vector< T >::begin(), and vec.
Referenced by april_utils::default_hash_function< string >::operator()().
const char * april_utils::string::begin () const
References april_utils::vector< T >::begin(), and vec.
const char * april_utils::string::c_str () const
References april_utils::vector< T >::begin(), and vec.
Referenced by ANN::ActivationFunctionANNComponent::build(), ANN::ANNComponent::build(), ANN::HardtanhActfANNComponent::clone(), ANN::SinActfANNComponent::clone(), ANN::LinearActfANNComponent::clone(), ANN::LogisticActfANNComponent::clone(), ANN::SoftmaxActfANNComponent::clone(), ANN::SoftplusActfANNComponent::clone(), ANN::SoftsignActfANNComponent::clone(), ANN::TanhActfANNComponent::clone(), ANN::LogLogisticActfANNComponent::clone(), ANN::LogSoftmaxActfANNComponent::clone(), ANN::StackANNComponent::clone(), ANN::BiasANNComponent::clone(), ANN::CopyANNComponent::clone(), ANN::HyperplaneANNComponent::clone(), ANN::DotProductANNComponent::clone(), ANN::JoinANNComponent::clone(), ANN::ANNComponent::clone(), ANN::BiasANNComponent::copyWeights(), ANN::DotProductANNComponent::copyWeights(), and ANN::ANNComponent::debugInfo().
string::size_type april_utils::string::capacity ()
References april_utils::vector< T >::capacity(), and vec.
void april_utils::string::clear ()
References april_utils::vector< T >::clear(), and vec.
const char * april_utils::string::data () const
References april_utils::vector< T >::begin(), and vec.
bool april_utils::string::empty () const
References april_utils::vector< T >::size(), and vec.
Referenced by ANN::ANNComponent::debugInfo(), and ANN::ANNComponent::hasWeightsName().
char * april_utils::string::end ()
References april_utils::vector< T >::end(), and vec.
Referenced by april_utils::default_hash_function< string >::operator()().
const char * april_utils::string::end () const
References april_utils::vector< T >::end(), and vec.
char april_utils::string::front () const
References vec.
char & april_utils::string::front ()
References vec.
string::size_type april_utils::string::max_size () const
References april_utils::vector< T >::max_size(), and vec.
string & april_utils::string::operator+= (const string & other)
References append().
bool april_utils::string::operator< (const string & other) const
References size(), and vec.
bool april_utils::string::operator<= (const string & other) const
References size(), and vec.
string & april_utils::string::operator= (const string & other)
References vec.
bool april_utils::string::operator== (const string & other) const
References size(), and vec.
char & april_utils::string::operator[] (unsigned int i)
References vec.
char april_utils::string::operator[] (unsigned int i) const
References vec.
void april_utils::string::pop_back ()
References april_utils::vector< T >::pop_back(), and vec.
void april_utils::string::push_back (char c)
References april_utils::vector< T >::push_back(), and vec.
void april_utils::string::reserve (string::size_type size)
References april_utils::vector< T >::reserve(), and vec.
void april_utils::string::resize (string::size_type size)
References april_utils::vector< T >::resize(), and vec.
string::size_type april_utils::string::size () const
References april_utils::vector< T >::size(), and vec.
Referenced by append(), operator<(), operator<=(), and operator==().
void april_utils::string::swap (string & other)
References april_utils::vector< T >::swap(), and vec.
Member Data Documentation
vector<char> april_utils::string::vec private
Referenced by append(), at(), back(), begin(), c_str(), capacity(), clear(), data(), empty(), end(), front(), max_size(), operator<(), operator<=(), operator=(), operator==(), operator[](), pop_back(), push_back(), reserve(), resize(), size(), and swap().