april-ann
april_utils::WordsTable Class Reference
Public Member Functions
WordsTable ()
WordsTable (WordsTable *other, unsigned int *filter)
~WordsTable ()
void insertWords (unsigned int *vec, unsigned int size)
unsigned int getWords (unsigned int index, unsigned int **vec)
unsigned int size () const
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Private Attributes
vector< unsigned int > table_first_index
vector< unsigned int > words
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Constructor & Destructor Documentation
april_utils::WordsTable::WordsTable () inline
la palabra 0 esta reservada
centinela
References april_utils::vector< T >::push_back(), and table_first_index.
april_utils::WordsTable::WordsTable (WordsTable * other, unsigned int * filter) inline
References april_utils::vector< T >::push_back(), april_utils::vector< T >::reserve(), april_utils::vector< T >::size(), table_first_index, and words.
april_utils::WordsTable::~WordsTable () inline
Member Function Documentation
unsigned int april_utils::WordsTable::getWords (unsigned int index, unsigned int ** vec) inline
References table_first_index, and words.
void april_utils::WordsTable::insertWords (unsigned int * vec, unsigned int size) inline
centinela
References april_utils::vector< T >::push_back(), april_utils::vector< T >::size(), size(), table_first_index, and words.
unsigned int april_utils::WordsTable::size () const inline
References april_utils::vector< T >::size(), and table_first_index.
Referenced by insertWords().
Member Data Documentation
vector<unsigned int> april_utils::WordsTable::table_first_index private
Referenced by getWords(), insertWords(), size(), and WordsTable().
vector<unsigned int> april_utils::WordsTable::words private
Referenced by getWords(), insertWords(), and WordsTable().