april-ann
Image_cleaning
Imaging
Classes
class ImageHistogram
Functions
int getIndex (float value, int gray_levels)
static Matrix< float > * ImageHistogram::getHistogram (const ImageFloat *img, int gray_levels)
Light and slow image histogram. It's used for computing the histogram of an image on a traditional way (without computing the integral interval)
ImageHistogram::ImageHistogram (const ImageHistogram &other)
void ImageHistogram::computeIntegralHistogram (ImageFloat *img)
Matrix< float > * ImageHistogram::generateWindowHistogram (int radius)
Given a radius gets for each pixel the histogram of these window.
Matrix< float > * ImageHistogram::getWindowHistogram (int x1, int y1, int x2, int y2)
Matrix< float > * ImageHistogram::getImageHistogram ()
Compute all the image Histogram.
Matrix< float > * ImageHistogram::getHorizontalHistogram ()
Returns a matrix of size width*levels.
Matrix< float > * ImageHistogram::getVerticalHistogram ()
Returns a matrix of size Height*Levels.
Matrix< float > * ImageHistogram::getIntegralHistogram ()
Detailed Description
Function Documentation
void ImageHistogram::computeIntegralHistogram (ImageFloat * img) protected
References getIndex(), ImageHistogram::gray_levels, ImageHistogram::height, ImageHistogram::hist(), and ImageHistogram::width.
Referenced by ImageHistogram::ImageHistogram().
MatrixFloat * ImageHistogram::generateWindowHistogram (int radius)
Given a radius gets for each pixel the histogram of these window.
References ImageHistogram::gray_levels, ImageHistogram::height, ImageHistogram::hist(), april_utils::max(), april_utils::min(), ImageHistogram::width, and Matrix< T >::zeros().
MatrixFloat * ImageHistogram::getHistogram (const ImageFloat * img, int gray_levels) static
Light and slow image histogram. It's used for computing the histogram of an image on a traditional way (without computing the integral interval)
References getIndex(), ImageHistogram::gray_levels, Image< T >::height, ImageHistogram::height, Image< T >::width, ImageHistogram::width, and Matrix< T >::zeros().
MatrixFloat * ImageHistogram::getHorizontalHistogram ()
Returns a matrix of size width*levels.
References ImageHistogram::getWindowHistogram(), ImageHistogram::gray_levels, ImageHistogram::height, and ImageHistogram::width.
MatrixFloat * ImageHistogram::getImageHistogram ()
Compute all the image Histogram.
References ImageHistogram::getWindowHistogram(), ImageHistogram::height, and ImageHistogram::width.
int getIndex (float value, int gray_levels) inline
Class that contains the counters for calculate the histogram of a given image
Referenced by ImageHistogram::computeIntegralHistogram(), and ImageHistogram::getHistogram().
MatrixFloat * ImageHistogram::getIntegralHistogram ()
References ImageHistogram::gray_levels, ImageHistogram::height, ImageHistogram::hist(), and ImageHistogram::width.
MatrixFloat * ImageHistogram::getVerticalHistogram ()
Returns a matrix of size Height*Levels.
References ImageHistogram::getWindowHistogram(), ImageHistogram::gray_levels, ImageHistogram::height, and ImageHistogram::width.
MatrixFloat * ImageHistogram::getWindowHistogram (int x1, int y1, int x2, int y2)
References ImageHistogram::gray_levels, ImageHistogram::hist(), and Matrix< T >::zeros().
Referenced by ImageHistogram::getHorizontalHistogram(), ImageHistogram::getImageHistogram(), and ImageHistogram::getVerticalHistogram().
ImageHistogram::ImageHistogram (const ImageHistogram & other)
References ImageHistogram::gray_levels, ImageHistogram::height, ImageHistogram::integral_histogram, and ImageHistogram::width.