april-ann
Random
Basics
Classes
class dice
class MTRand
Functions
dice::dice (int outcom, double *prob)
dice::~dice ()
int dice::thrown (MTRand *generator)
MTRand::MTRand (const uint32_t &oneSeed)
MTRand::MTRand (uint32_t *const bigSeed, uint32_t const seedLength=N)
MTRand::MTRand ()
MTRand::MTRand (const MTRand &r)
MTRand & MTRand::operator= (const MTRand &)
double MTRand::rand ()
double MTRand::rand (const double &n)
double MTRand::randExc ()
double MTRand::randExc (const double &n)
double MTRand::randDblExc ()
double MTRand::randDblExc (const double &n)
double MTRand::rand53 ()
double MTRand::randNorm (const double &mean=0.0, const double &variance=0.0)
uint32_t MTRand::randInt ()
uint32_t MTRand::randInt (const uint32_t &n)
void MTRand::seed (const uint32_t oneSeed)
void MTRand::seed (uint32_t *const bigSeed, const uint32_t seedLength=N)
void MTRand::seed ()
void MTRand::initialize (const uint32_t oneSeed)
void MTRand::reload ()
static uint32_t MTRand::hash (time_t t, clock_t c)
void MTRand::shuffle (int size, int *vector)
void MTRand::save (uint32_t *saveArray) const
void MTRand::load (uint32_t *const loadArray)
Variables
static const unsigned int MTRand::N = 624
static const unsigned int MTRand::SAVE = N+1
Detailed Description
Function Documentation
dice::dice (int outcom, double * prob)
References dice::outcomes, and dice::threshold.
uint32_t MTRand::hash (time_t t, clock_t c) static protected
Referenced by MTRand::seed().
void MTRand::initialize (const uint32_t oneSeed) protected
References MTRand::N, and MTRand::state.
Referenced by MTRand::seed().
void MTRand::load (uint32_t *const loadArray)
References MTRand::left, MTRand::N, MTRand::pNext, and MTRand::state.
MTRand::MTRand (const uint32_t & oneSeed)
References MTRand::seed().
MTRand::MTRand (uint32_t *const bigSeed, uint32_t const seedLength = N)
References MTRand::seed().
MTRand::MTRand ()
References MTRand::seed().
MTRand::MTRand (const MTRand & r)
References MTRand::left, MTRand::N, MTRand::pNext, and MTRand::state.
MTRand & MTRand::operator= (const MTRand & r)
References MTRand::left, MTRand::N, MTRand::pNext, and MTRand::state.
double MTRand::rand ()
References MTRand::randInt().
Referenced by ANN::SaltAndPepperANNComponent::doForward(), ANN::ActivationFunctionANNComponent::doForward(), MTRand::operator()(), MTRand::rand(), and dice::thrown().
double MTRand::rand (const double & n)
References MTRand::rand().
double MTRand::rand53 ()
References MTRand::randInt().
double MTRand::randDblExc ()
References MTRand::randInt().
Referenced by MTRand::randDblExc(), and MTRand::randNorm().
double MTRand::randDblExc (const double & n)
References MTRand::randDblExc().
double MTRand::randExc ()
References MTRand::randInt().
Referenced by MTRand::randExc(), and MTRand::randNorm().
double MTRand::randExc (const double & n)
References MTRand::randExc().
uint32_t MTRand::randInt ()
References MTRand::left, MTRand::pNext, and MTRand::reload().
Referenced by MTRand::rand(), MTRand::rand53(), MTRand::randDblExc(), MTRand::randExc(), MTRand::randInt(), and MTRand::shuffle().
uint32_t MTRand::randInt (const uint32_t & n)
References MTRand::randInt().
double MTRand::randNorm (const double & mean = 0.0, const double & variance = 0.0)
References MTRand::randDblExc(), and MTRand::randExc().
Referenced by ANN::GaussianNoiseANNComponent::doForward().
void MTRand::reload () protected
References MTRand::left, MTRand::M, MTRand::N, MTRand::pNext, MTRand::state, and MTRand::twist().
Referenced by MTRand::randInt(), and MTRand::seed().
void MTRand::save (uint32_t * saveArray) const
References MTRand::left, MTRand::N, and MTRand::state.
void MTRand::seed (const uint32_t oneSeed)
References MTRand::initialize(), and MTRand::reload().
void MTRand::seed (uint32_t *const bigSeed, const uint32_t seedLength = N)
References MTRand::initialize(), MTRand::N, MTRand::reload(), and MTRand::state.
void MTRand::seed ()
References MTRand::hash(), and MTRand::N.
Referenced by MTRand::MTRand().
void MTRand::shuffle (int size, int * vector)
References MTRand::randInt(), and april_utils::swap().
int dice::thrown (MTRand * generator)
References dice::outcomes, MTRand::rand(), and dice::threshold.
dice::~dice ()
References dice::threshold.
Variable Documentation
const unsigned int MTRand::N = 624 static
Referenced by MTRand::initialize(), MTRand::load(), MTRand::MTRand(), MTRand::operator=(), MTRand::reload(), MTRand::save(), and MTRand::seed().
const unsigned int MTRand::SAVE = N+1 static