april-ann
Tokens
Basics
Classes
class table_of_token_codes
Static class which contains TokenCodes for each corresponding Token type.
class Token
class TokenMemoryBlock
class TokenVectorGeneric
class TokenVector< T >
Typedefs
typedef uint32_t TokenCode
Definition of TokenCode type.
typedef TokenVector< float > TokenVectorFloat
typedef TokenVector< double > TokenVectorDouble
typedef TokenVector< int32_t > TokenVectorInt32
typedef TokenVector< uint32_t > TokenVectorUint32
typedef TokenVector< char > TokenVectorChar
typedef TokenVector< Token * > TokenBunchVector
typedef TokenVector
< april_utils::pair< unsigned
int, float > > TokenSparseVectorFloat
Functions
void concatBunchOfTokens (Token *&result, TokenBunchVector *bunch)
Token::Token ()
virtual Token::~Token ()
TokenMemoryBlock::TokenMemoryBlock ()
TokenMemoryBlock::TokenMemoryBlock (unsigned int size)
TokenMemoryBlock::~TokenMemoryBlock ()
void TokenMemoryBlock::setData (float *data, unsigned int size)
void TokenMemoryBlock::resize (unsigned int size)
Token * TokenMemoryBlock::clone () const
This method implements a deep copy.
buffer_list * TokenMemoryBlock::toString ()
Abstract method for serialization purposes.
buffer_list * TokenMemoryBlock::debugString (const char *prefix, int debugLevel)
FOR DEBUG PURPOSES.
TokenCode TokenMemoryBlock::getTokenCode () const
Abstract method which indicates the TokenCode of child Token classes.
void TokenMemoryBlock::setToZero (bool use_cuda)
TokenVector< T >::TokenVector ()
TokenVector< T >::TokenVector (unsigned int vlength)
TokenVector< T >::TokenVector (const T *vec, unsigned int vlength)
TokenVector< T >::TokenVector (const april_utils::vector< T > &vec)
TokenVector< T >::~TokenVector ()
Token * TokenVector< T >::clone () const
This method implements a deep copy.
buffer_list * TokenVector< T >::toString ()
Abstract method for serialization purposes.
buffer_list * TokenVector< T >::debugString (const char *prefix, int debugLevel)
FOR DEBUG PURPOSES.
TokenCode TokenVector< T >::getTokenCode () const
Abstract method which indicates the TokenCode of child Token classes.
static Token * TokenVector< T >::fromString (constString &cs)
Detailed Description
Typedef Documentation
typedef TokenVector<Token*> TokenBunchVector
typedef uint32_t TokenCode
Definition of TokenCode type.
typedef TokenVector<april_utils::pair<unsigned int, float> > TokenSparseVectorFloat
typedef TokenVector<char> TokenVectorChar
typedef TokenVector<double> TokenVectorDouble
typedef TokenVector<float> TokenVectorFloat
typedef TokenVector<int32_t> TokenVectorInt32
typedef TokenVector<uint32_t> TokenVectorUint32
Function Documentation
Token * TokenMemoryBlock::clone () const virtual
This method implements a deep copy.
Implements Token.
References doScopy(), GPUMirroredMemoryBlock< T >::getSize(), TokenMemoryBlock::mem_block, TokenMemoryBlock::TokenMemoryBlock(), and TokenMemoryBlock::used_size.
template<typename T > Token * TokenVector< T >::clone () const virtual
This method implements a deep copy.
Implements Token.
void concatBunchOfTokens (Token *& result, TokenBunchVector * bunch)
Function which takes a vector of TokenMemoryBlock and produces a block with all the bunch concatenated
buffer_list * TokenMemoryBlock::debugString (const char * prefix, int debugLevel) virtual
FOR DEBUG PURPOSES.
Implements Token.
template<typename T > buffer_list * TokenVector< T >::debugString (const char * prefix, int debugLevel) virtual
FOR DEBUG PURPOSES.
Implements Token.
References buffer_list::add_formatted_string_right().
template<typename T > Token * TokenVector< T >::fromString (constString & cs) static
TokenCode TokenMemoryBlock::getTokenCode () const virtual
Abstract method which indicates the TokenCode of child Token classes.
Implements Token.
References table_of_token_codes::token_mem_block.
template<typename T > TokenCode TokenVector< T >::getTokenCode () const virtual
Abstract method which indicates the TokenCode of child Token classes.
Implements Token.
References table_of_token_codes::error.
void TokenMemoryBlock::resize (unsigned int size)
References GPUMirroredMemoryBlock< T >::getSize(), TokenMemoryBlock::mem_block, and TokenMemoryBlock::used_size.
Referenced by TokenMemoryBlock::setData(), and TokenMemoryBlock::TokenMemoryBlock().
void TokenMemoryBlock::setData (float * data, unsigned int size)
References GPUMirroredMemoryBlock< T >::getPPALForWrite(), TokenMemoryBlock::mem_block, and TokenMemoryBlock::resize().
void TokenMemoryBlock::setToZero (bool use_cuda)
References doVectorSetToZero(), GPUMirroredMemoryBlock< T >::getSize(), and TokenMemoryBlock::mem_block.
Referenced by ANN::DotProductANNComponent::doForward().
Token::Token ()
TokenMemoryBlock::TokenMemoryBlock ()
Referenced by TokenMemoryBlock::clone().
TokenMemoryBlock::TokenMemoryBlock (unsigned int size)
References TokenMemoryBlock::resize().
template<typename T > TokenVector< T >::TokenVector ()
template<typename T > TokenVector< T >::TokenVector (unsigned int vlength)
template<typename T > TokenVector< T >::TokenVector (const T * vec, unsigned int vlength)
template<typename T > TokenVector< T >::TokenVector (const april_utils::vector< T > & vec)
buffer_list * TokenMemoryBlock::toString () virtual
Abstract method for serialization purposes.
Implements Token.
template<typename T > buffer_list * TokenVector< T >::toString () virtual
Abstract method for serialization purposes.
Implements Token.
Token::~Token () virtual
TokenMemoryBlock::~TokenMemoryBlock ()
References TokenMemoryBlock::mem_block.
template<typename T > TokenVector< T >::~TokenVector ()