april-ann
Image_metrics
Imaging
Classes
class ImageMetrics
Functions
void ImageMetrics::processSample (float pred, float ref)
void ImageMetrics::clear ()
int ImageMetrics::nSamples ()
void ImageMetrics::combine (ImageMetrics &m1)
bool ImageMetrics::getMetrics (double &FM, double &PR, double &RC, double &GA, double &MSE, double &TNR, double &ACC, double &PSNR, double &BRP, double &BRR, double &FNR)
void ImageMetrics::processDataset (DataSetFloat *ds, DataSetFloat *GT, bool binary, float threshold)
ImageMetrics * ImageMetrics::clone ()
Detailed Description
Function Documentation
void ImageMetrics::clear ()
References ImageMetrics::false_negatives, ImageMetrics::false_positives, ImageMetrics::n_samples, ImageMetrics::SSE, ImageMetrics::true_negatives, and ImageMetrics::true_positives.
ImageMetrics * ImageMetrics::clone ()
References ImageMetrics::false_negatives, ImageMetrics::false_positives, ImageMetrics::ImageMetrics(), ImageMetrics::n_samples, ImageMetrics::SSE, ImageMetrics::true_negatives, and ImageMetrics::true_positives.
void ImageMetrics::combine (ImageMetrics & m1)
References ImageMetrics::false_negatives, ImageMetrics::false_positives, ImageMetrics::n_samples, ImageMetrics::SSE, ImageMetrics::true_negatives, and ImageMetrics::true_positives.
bool ImageMetrics::getMetrics (double & FM, double & PR, double & RC, double & GA, double & MSE, double & TNR, double & ACC, double & PSNR, double & BRP, double & BRR, double & FNR)
Returns differents measures FM - Fmeasure PR - Precission RC - Recall GA - Geometrical Arithmetic TNR - True Negative Rate PSNR - Peak signal-to-noise ratio ACC - Acurracy BRP - Black Rate Predicted (ratio of black pixels in prediction) BRR - Black Rate Reference
References ImageMetrics::false_negatives, ImageMetrics::false_positives, ImageMetrics::n_samples, ImageMetrics::SSE, ImageMetrics::true_negatives, and ImageMetrics::true_positives.
int ImageMetrics::nSamples ()
References ImageMetrics::n_samples.
void ImageMetrics::processDataset (DataSetFloat * ds, DataSetFloat * GT, bool binary, float threshold)
References ERROR_PRINT, ERROR_PRINT1, ERROR_PRINT2, DataSet< T >::getPattern(), DataSet< T >::numPatterns(), DataSet< T >::patternSize(), and ImageMetrics::processSample().
void ImageMetrics::processSample (float pred, float ref)
References ImageMetrics::false_negatives, ImageMetrics::false_positives, ImageMetrics::n_samples, ImageMetrics::SSE, ImageMetrics::true_negatives, and ImageMetrics::true_positives.
Referenced by ImageMetrics::processDataset().