april-ann
Affine_transform
Basics
Classes
class AffineTransform2D
Functions
AffineTransform2D::AffineTransform2D ()
Identity transform.
AffineTransform2D::AffineTransform2D (Matrix< float > *mat)
AffineTransform2D * AffineTransform2D::accumulate (AffineTransform2D *other)
AffineTransform2D * AffineTransform2D::rotate (float angle)
AffineTransform2D * AffineTransform2D::rotate (float angle, float center_x, float center_y)
AffineTransform2D * AffineTransform2D::translate (float x, float y)
AffineTransform2D * AffineTransform2D::scale (float x, float y)
AffineTransform2D * AffineTransform2D::shear (float angle_x, float angle_y)
void AffineTransform2D::transform (float x, float y, float *dstx, float *dsty) const
Variables
static const int AffineTransform2D::dimensions [2] = {3,3}
Detailed Description
Function Documentation
AffineTransform2D * AffineTransform2D::accumulate (AffineTransform2D * other)
References Matrix< float >::data, Matrix< T >::data, and Matrix< T >::multiply().
Referenced by AffineTransform2D::rotate(), AffineTransform2D::scale(), AffineTransform2D::shear(), and AffineTransform2D::translate().
AffineTransform2D::AffineTransform2D ()
Identity transform.
References Matrix< float >::data.
AffineTransform2D::AffineTransform2D (Matrix< float > * mat)
References Matrix< float >::data, Matrix< float >::matrixSize, and Matrix< float >::numDim.
AffineTransform2D * AffineTransform2D::rotate (float angle)
References AffineTransform2D::accumulate(), and Matrix< T >::data.
Referenced by AffineTransform2D::rotate().
AffineTransform2D * AffineTransform2D::rotate (float angle, float center_x, float center_y)
References AffineTransform2D::rotate(), and AffineTransform2D::translate().
AffineTransform2D * AffineTransform2D::scale (float x, float y)
References AffineTransform2D::accumulate(), and Matrix< T >::data.
AffineTransform2D * AffineTransform2D::shear (float angle_x, float angle_y)
References AffineTransform2D::accumulate(), and Matrix< T >::data.
void AffineTransform2D::transform (float x, float y, float * dstx, float * dsty) const
References Matrix< float >::data.
AffineTransform2D * AffineTransform2D::translate (float x, float y)
References AffineTransform2D::accumulate(), and Matrix< T >::data.
Referenced by AffineTransform2D::rotate().
Variable Documentation
const int AffineTransform2D::dimensions = {3,3} static private