april-ann
Util
Basics
Namespaces
namespace april_utils
Classes
class binarizer
struct buffer_list_node
struct buffer_list
class constString
class log_float
class log_double
class ReadFileStream
class Referenced
struct ReservoirPool< T >
class ReservoirContainer< T >
struct VectorReservoirPool< T >
class VectorReservoirContainer< T >
class StringQueue
Macros
#define VECTOR_ALIGNMENT 16
#define APRIL_BIG_ENDIAN 0xdeadbeef
#define APRIL_LITTLE_ENDIAN 0xefbeadde
#define APRIL_ENDIANNESS APRIL_LITTLE_ENDIAN
#define FORMAT_BUFFER_SIZE 200
#define PI 3.1415926535898f
#define ROW_MAJOR 1
#define LINE_LEN 1025
#define ERROR_PRINT(strformat) fprintf(stderr, "Error in file %s in line %d: " strformat, __FILE__, __LINE__)
#define ERROR_PRINT1(strformat, v1) fprintf(stderr, "Error in file %s in line %d: " strformat, __FILE__, __LINE__, (v1))
#define ERROR_PRINT2(strformat, v1, v2) fprintf(stderr, "Error in file %s in line %d: " strformat, __FILE__, __LINE__, (v1), (v2))
#define ERROR_PRINT3(strformat, v1, v2, v3) fprintf(stderr, "Error in file %s in line %d: " strformat, __FILE__, __LINE__, (v1), (v2), (v3))
#define ERROR_PRINT4(strformat, v1, v2, v3, v4) fprintf(stderr, "Error in file %s in line %d: " strformat, __FILE__, __LINE__, (v1), (v2), (v3), (v4))
#define ERROR_PRINT5(strformat, v1, v2, v3, v4, v5) fprintf(stderr, "Error in file %s in line %d: " strformat, __FILE__, __LINE__, (v1), (v2), (v3), (v4), (v5))
#define ERROR_PRINT6(strformat, v1, v2, v3, v4, v5, v6) fprintf(stderr, "Error in file %s in line %d: " strformat, __FILE__, __LINE__, (v1), (v2), (v3), (v4), (v5), (v6))
#define ERROR_EXIT(errorcode, strformat) do { ERROR_PRINT(strformat); exit(errorcode); } while(0)
#define ERROR_EXIT1(errorcode, strformat, v1) do { ERROR_PRINT1(strformat,v1); exit(errorcode); } while(0)
#define ERROR_EXIT2(errorcode, strformat, v1, v2) do { ERROR_PRINT2(strformat,v1,v2); exit(errorcode); } while(0)
#define ERROR_EXIT3(errorcode, strformat, v1, v2, v3) do { ERROR_PRINT3(strformat,v1,v2,v3); exit(errorcode); } while(0)
#define ERROR_EXIT4(errorcode, strformat, v1, v2, v3, v4) do { ERROR_PRINT4(strformat,v1,v2,v3,v4); exit(errorcode); } while(0)
#define ERROR_EXIT5(errorcode, strformat, v1, v2, v3, v4, v5) do { ERROR_PRINT5(strformat,v1,v2,v3,v4,v5); exit(errorcode); } while(0)
#define ERROR_EXIT6(errorcode, strformat, v1, v2, v3, v4, v5, v6) do { ERROR_PRINT6(strformat,v1,v2,v3,v4,v5,v6); exit(errorcode); } while(0)
#define IGNORE_RESULT(X) ignore_result_helper(0, (X))
#define DEFAULT_MFSET_SIZE 524288
#define READ 0
#define WRITE 1
#define DEFAULT_BUFFER_LEN 4096
#define _REFERENCEDCC_
#define IncRef(x) x->incRef()
#define DecRef(x) if (x->decRef()) delete x
Functions
template<typename T >
T * aligned_malloc (size_t nmemb)
template<typename T >
void aligned_free (T *ptr)
char * copystr (const char *c)
void ignore_result_helper (int __attribute__((unused)) dummy,...)
void least_squares (double x[], double y[], int numPoints, double &a, double &b)
log_float operator+ (const log_float &x, const log_float &y)
log_float operator- (const log_float &x, const log_float &y)
log_float operator* (const log_float &x, const log_float &y)
log_float operator/ (const log_float &x, const log_float &y)
bool operator== (const log_float &x, const log_float &y)
bool operator!= (const log_float &x, const log_float &y)
bool operator>= (const log_float &x, const log_float &y)
bool operator<= (const log_float &x, const log_float &y)
bool operator> (const log_float &x, const log_float &y)
bool operator< (const log_float &x, const log_float &y)
log_double operator+ (const log_double &x, const log_double &y)
log_double operator- (const log_double &x, const log_double &y)
log_double operator* (const log_double &x, const log_double &y)
log_double operator/ (const log_double &x, const log_double &y)
bool operator== (const log_double &x, const log_double &y)
bool operator!= (const log_double &x, const log_double &y)
bool operator>= (const log_double &x, const log_double &y)
bool operator<= (const log_double &x, const log_double &y)
bool operator> (const log_double &x, const log_double &y)
bool operator< (const log_double &x, const log_double &y)
float logadd1 (float x)
float log1sub (float x)
double logadd1 (double x)
double log1sub (double x)
void msleep (unsigned long milisec)
pid_t popen2 (const char *command, int *infp, int *outfp)
char * get_uncommented_line (char *s, int size, FILE *stream)
char * get_line (char *s, int size, FILE *stream)
static void binarizer::init ()
static uint32_t binarizer::decode_uint32 (const char b[5])
static void binarizer::code_uint32 (uint32_t i, char b[5])
static int32_t binarizer::decode_int32 (const char b[5])
static void binarizer::code_int32 (int32_t i, char b[5])
static void binarizer::code_float (float i, char b[5])
static void binarizer::code_double (double i, char b[10])
static float binarizer::decode_float (const char b[5])
static double binarizer::decode_double (const char b[10])
static int binarizer::buffer_size_16 (int num, bool with_newlines=true)
static int binarizer::buffer_size_32 (int num, bool with_newlines=true)
static int binarizer::buffer_size_64 (int num, bool with_newlines=true)
static int binarizer::code_vector_float (const float *vect, int vect_size, char *dest_buffer, int dest_buffer_size, bool with_newlines=true)
static int binarizer::code_vector_int32 (const int32_t *vect, int vect_size, char *dest_buffer, int dest_buffer_size, bool with_newlines=true)
buffer_list_node::buffer_list_node (int sz, buffer_list_node *nxt=0)
buffer_list_node::~buffer_list_node ()
buffer_list::~buffer_list ()
void buffer_list::append (buffer_list *other)
void buffer_list::add_buffer_left (buffer_list_node *nd)
void buffer_list::add_buffer_right (buffer_list_node *nd)
void buffer_list::add_formatted_string_left (const char *fmt,...)
void buffer_list::add_formatted_string_right (const char *fmt,...)
void buffer_list::printf (const char *fmt,...)
void buffer_list::add_constString_left (const constString &cs)
void buffer_list::add_constString_right (const constString &cs)
char * buffer_list::to_string (string_termination t=NON_NULL_TERMINATED)
void buffer_list::add_binarized_int32_left (const int32_t *v, int v_sz)
void buffer_list::add_binarized_int32_right (const int32_t *v, int v_sz)
void buffer_list::add_binarized_uint32_left (const uint32_t *v, int v_sz)
void buffer_list::add_binarized_uint32_right (const uint32_t *v, int v_sz)
void buffer_list::add_binarized_float_left (const float *v, int v_sz)
void buffer_list::add_binarized_float_right (const float *v, int v_sz)
void buffer_list::add_binarized_log_float_left (const log_float *v, int v_sz)
void buffer_list::add_binarized_log_float_right (const log_float *v, int v_sz)
void buffer_list::add_binarized_double_left (const double *v, int v_sz)
void buffer_list::add_binarized_double_right (const double *v, int v_sz)
void buffer_list::add_binarized_log_double_left (const log_double *v, int v_sz)
void buffer_list::add_binarized_log_double_right (const log_double *v, int v_sz)
constString::constString (const char *s, size_t n)
constString::constString (const char *s)
char * constString::newString () const
bool constString::operator== (const constString &otro) const
bool constString::operator!= (const constString &otro) const
bool constString::operator< (const constString &otro) const
bool constString::operator<= (const constString &otro) const
bool constString::operator> (const constString &otro) const
bool constString::operator>= (const constString &otro) const
void constString::skip (size_t n)
void constString::ltrim (const char *acepta=" \t")
bool constString::is_prefix (const constString &theprefix)
bool constString::is_prefix (const char *theprefix)
bool constString::skip (const constString &theprefix)
bool constString::skip (const char *theprefix)
constString constString::extract_prefix (size_t prefix_len)
constString constString::extract_token (const char *separadores=" \t,;\r\n")
constString constString::extract_line ()
constString constString::extract_u_line ()
bool constString::extract_char (char *resul)
bool constString::extract_float (float *resul, const char *separadores=" \t,;\r\n")
bool constString::extract_float_binary (float *resul)
bool constString::extract_double (double *resul, const char *separadores=" \t,;\r\n")
bool constString::extract_log_float_binary (log_float *resul)
bool constString::extract_log_double_binary (log_double *resul)
bool constString::extract_double_binary (double *resul)
bool constString::extract_int (int *resul, int base=10, const char *separadores=" \t,;\r\n")
bool constString::extract_unsigned_int (unsigned int *resul, int base=10, const char *separadores=" \t,;\r\n")
bool constString::extract_long (long int *resul, int base=10, const char *separadores=" \t,;\r\n")
bool constString::extract_long_long (long long int *resul, int base=10, const char *separadores=" \t,;\r\n")
bool constString::extract_uint32_binary (uint32_t *resul)
bool constString::extract_int32_binary (int32_t *resul)
void constString::print (FILE *F=stdout)
log_float & log_float::operator= (const log_double &value)
log_float log_float::operator+= (const log_double &y)
log_float log_float::operator*= (const log_double &y)
log_float log_float::operator/= (const log_double &y)
log_float log_float::operator-= (const log_double &y)
bool ReadFileStream::moveAndFillBuffer ()
bool ReadFileStream::resizeAndFillBuffer ()
bool ReadFileStream::trim (const char *delim)
ReadFileStream::ReadFileStream (const char *path)
ReadFileStream::~ReadFileStream ()
constString ReadFileStream::getToken (const char *delim)
constString ReadFileStream::extract_line ()
constString ReadFileStream::extract_u_line ()
Referenced::Referenced ()
virtual Referenced::~Referenced ()
virtual void Referenced::incRef ()
virtual bool Referenced::decRef ()
StringQueue::StringQueue ()
void StringQueue::clear ()
void StringQueue::checkNonEmpty ()
void StringQueue::checkLast ()
void StringQueue::putchar (char)
void StringQueue::putchars (char c, int times)
void StringQueue::print (const char *str)
void StringQueue::printEsc (const char *str)
void StringQueue::putBuffer (const char *buffer, int buffersz)
void StringQueue::putStringQueue (const StringQueue &other)
void StringQueue::printf (const char *fmt,...)
int StringQueue::getBufferChunk (char **buffer)
char * StringQueue::exportBuffer (int &sz) const
void StringQueue::advanceBuffer (int bufferAdvance)
Variables
static const uint32_t BASE = 85
static const uint32_t BASE1 = 85
static const uint32_t BASE2 = 85*85
static const uint32_t BASE3 = 85*85*85
static const uint32_t BASE4 = 85*85*85*85
static const uint64_t BASE5 = uint64_t(85)*85*85*85*85
static const uint64_t BASE6 = uint64_t(85)*85*85*85*85*85
static const uint64_t BASE7 = uint64_t(85)*85*85*85*85*85*85
static const uint64_t BASE8 = uint64_t(85)*85*85*85*85*85*85*85
static const uint64_t BASE9 = uint64_t(85)*85*85*85*85*85*85*85*85
static enum binarizer::endian_enum binarizer::endianness
static char binarizer::cod []
static char binarizer::uncod []
static const float log_float::floatnearzero = 1e-37
static const float log_float::rawscorenearzero = -99
static const float log_float::rawscorezero = -1e12
static const float log_float::rawscoreone = 0
static const double log_double::doublenearzero = 1e-37
static const double log_double::rawscorenearzero = -85
static const double log_double::rawscorezero = -1e8
static const double log_double::rawscoreone = 0
Detailed Description
Macro Definition Documentation
#define _REFERENCEDCC_
#define APRIL_BIG_ENDIAN 0xdeadbeef
#define APRIL_ENDIANNESS APRIL_LITTLE_ENDIAN
#define APRIL_LITTLE_ENDIAN 0xefbeadde
#define DecRef (x) if (x->decRef()) delete x
Referenced by ANN::ANNBase::clearTopology(), ANN::MLP::setErrorFunction(), ANN::ActivationsAction::~ActivationsAction(), ANN::ActivationUnitsSlice::~ActivationUnitsSlice(), ANN::ANNBase::~ANNBase(), CacheDataSet< T >::~CacheDataSet(), ContextualizerDataSet< T >::~ContextualizerDataSet(), Functions::DataSetFloatConsumer::~DataSetFloatConsumer(), Functions::DataSetFloatProducer::~DataSetFloatProducer(), DerivDataSet< T >::~DerivDataSet(), ANN::DotProductAction::~DotProductAction(), Functions::FloatContextualizerProducerFromDouble::~FloatContextualizerProducerFromDouble(), ANN::ForwardBiasAction::~ForwardBiasAction(), Image< T >::~Image(), IndexDataSet< T >::~IndexDataSet(), IndexFilterDataSet< T >::~IndexFilterDataSet(), JoinDataSet< T >::~JoinDataSet(), LinearCombDataSet< T >::~LinearCombDataSet(), MatrixDataSet< T >::~MatrixDataSet(), ANN::MLP::~MLP(), PerturbationDataSet< T >::~PerturbationDataSet(), ShortListDataSet< T >::~ShortListDataSet(), SparseDataset< T >::~SparseDataset(), SplitDataSet< T >::~SplitDataSet(), ANN::StochasticActivationFunction::~StochasticActivationFunction(), SubDataSet< T >::~SubDataSet(), and UnionDataSet< T >::~UnionDataSet().
#define DEFAULT_BUFFER_LEN 4096
Referenced by ReadFileStream::ReadFileStream().
#define DEFAULT_MFSET_SIZE 524288
#define ERROR_EXIT (errorcode, strformat) do { ERROR_PRINT(strformat); exit(errorcode); } while(0)
Referenced by ANN::SoftmaxActivationFunction::applyActivation(), ANN::ANNBase::calculate(), ANN::ANNBase::calculateInPipeline(), ANN::BiasConnections::checkInputOutputSizes(), ANN::Connections::Connections(), ANN::DotProductAction::DotProductAction(), ANN::ForwardBiasAction::ForwardBiasAction(), ANN::AllAllMLP::generateActionsAllAll(), ANN::getActivationFunctionByTypeString(), ANN::ForwardBiasAction::getOption(), ANN::MLP::getOption(), ANN::DotProductAction::getOption(), ANN::Connections::pruneSubnormalAndCheckNormal(), ANN::RealActivationUnits::RealActivationUnits(), ANN::ANNBase::registerOutput(), ANN::ForwardBiasAction::setOption(), ANN::MLP::setOption(), and GPUMirroredMemoryBlock< T >::~GPUMirroredMemoryBlock().
#define ERROR_EXIT1 (errorcode, strformat, v1) do { ERROR_PRINT1(strformat,v1); exit(errorcode); } while(0)
Referenced by ANN::getActivationFunctionByTypeString(), april_utils::TrieVector::getChild(), april_utils::TrieVector::getPersistentChild(), ANN::DotProductAction::setOption(), and GPUMirroredMemoryBlock< T >::~GPUMirroredMemoryBlock().
#define ERROR_EXIT2 (errorcode, strformat, v1, v2) do { ERROR_PRINT2(strformat,v1,v2); exit(errorcode); } while(0)
Referenced by Trainable::TrainableSupervised::exitOnDatasetSizeError().
#define ERROR_EXIT3 (errorcode, strformat, v1, v2, v3) do { ERROR_PRINT3(strformat,v1,v2,v3); exit(errorcode); } while(0)
#define ERROR_EXIT4 (errorcode, strformat, v1, v2, v3, v4) do { ERROR_PRINT4(strformat,v1,v2,v3,v4); exit(errorcode); } while(0)
#define ERROR_EXIT5 (errorcode, strformat, v1, v2, v3, v4, v5) do { ERROR_PRINT5(strformat,v1,v2,v3,v4,v5); exit(errorcode); } while(0)
#define ERROR_EXIT6 (errorcode, strformat, v1, v2, v3, v4, v5, v6) do { ERROR_PRINT6(strformat,v1,v2,v3,v4,v5,v6); exit(errorcode); } while(0)
#define ERROR_PRINT (strformat) fprintf(stderr, "Error in file %s in line %d: " strformat, __FILE__, __LINE__)
Referenced by ANN::BinarySamplingActivationFunction::applyActivation(), CacheDataSet< T >::CacheDataSet(), Functions::FunctionInterface< I, O >::calculateInPipeline(), ANN::BiasConnections::checkInputOutputSizes(), ANN::AllAllConnections::checkInputOutputSizes(), ANN::ActivationUnitsSlice::clone(), Fmeasure(), ANN::AllAllMLP::getLayerConnections(), ANN::LocalActivationUnits::LocalActivationUnits(), ANN::StochasticActivationFunction::multiplyDerivatives(), april_utils::default_hash_function< T * >::operator()(), SparseDataset< T >::putPattern(), IndexFilterDataSet< T >::putPattern(), PerturbationDataSet< T >::putPattern(), CacheDataSet< T >::putPattern(), and DerivDataSet< T >::putPattern().
#define ERROR_PRINT1 (strformat, v1) fprintf(stderr, "Error in file %s in line %d: " strformat, __FILE__, __LINE__, (v1))
Referenced by Fmeasure(), and ANN::AllAllMLP::loadModel().
#define ERROR_PRINT2 (strformat, v1, v2) fprintf(stderr, "Error in file %s in line %d: " strformat, __FILE__, __LINE__, (v1), (v2))
Referenced by april_utils::check_floats(), Fmeasure(), and SparseDataset< T >::SparseDataset().
#define ERROR_PRINT3 (strformat, v1, v2, v3) fprintf(stderr, "Error in file %s in line %d: " strformat, __FILE__, __LINE__, (v1), (v2), (v3))
#define ERROR_PRINT4 (strformat, v1, v2, v3, v4) fprintf(stderr, "Error in file %s in line %d: " strformat, __FILE__, __LINE__, (v1), (v2), (v3), (v4))
#define ERROR_PRINT5 (strformat, v1, v2, v3, v4, v5) fprintf(stderr, "Error in file %s in line %d: " strformat, __FILE__, __LINE__, (v1), (v2), (v3), (v4), (v5))
#define ERROR_PRINT6 (strformat, v1, v2, v3, v4, v5, v6) fprintf(stderr, "Error in file %s in line %d: " strformat, __FILE__, __LINE__, (v1), (v2), (v3), (v4), (v5), (v6))
#define FORMAT_BUFFER_SIZE 200
Referenced by buffer_list::add_formatted_string_left(), buffer_list::add_formatted_string_right(), and buffer_list::printf().
#define IGNORE_RESULT (X) ignore_result_helper(0, (X))
Referenced by ANN::AllAllMLP::loadModel().
#define IncRef (x) x->incRef()
Referenced by ANN::ActivationsAction::ActivationsAction(), ANN::ActivationUnitsSlice::ActivationUnitsSlice(), CacheDataSet< T >::CacheDataSet(), ANN::BinarySamplingActivationFunction::clone(), ContextualizerDataSet< T >::ContextualizerDataSet(), Functions::DataSetFloatConsumer::DataSetFloatConsumer(), Functions::DataSetFloatProducer::DataSetFloatProducer(), DerivDataSet< T >::DerivDataSet(), ANN::DotProductAction::DotProductAction(), Functions::FloatContextualizerProducerFromDouble::FloatContextualizerProducerFromDouble(), ANN::ForwardBiasAction::ForwardBiasAction(), Image< T >::Image(), IndexDataSet< T >::IndexDataSet(), IndexFilterDataSet< T >::IndexFilterDataSet(), JoinDataSet< T >::JoinDataSet(), LinearCombDataSet< T >::LinearCombDataSet(), MatrixDataSet< T >::MatrixDataSet(), ANN::MLP::MLP(), PerturbationDataSet< T >::PerturbationDataSet(), ANN::ANNBase::registerAction(), ANN::ANNBase::registerActivationUnits(), ANN::ANNBase::registerConnections(), ANN::MLP::setErrorFunction(), ShortListDataSet< T >::ShortListDataSet(), SparseDataset< T >::SparseDataset(), SplitDataSet< T >::SplitDataSet(), ANN::StochasticActivationFunction::StochasticActivationFunction(), SubDataSet< T >::SubDataSet(), and UnionDataSet< T >::UnionDataSet().
#define LINE_LEN 1025
#define PI 3.1415926535898f
#define READ 0
Referenced by popen2().
#define ROW_MAJOR 1
#define VECTOR_ALIGNMENT 16
Referenced by aligned_malloc().
#define WRITE 1
Referenced by popen2().
Function Documentation
void buffer_list::add_binarized_double_left (const double * v, int v_sz)
References buffer_list::add_buffer_left(), buffer_list_node::buffer, and binarizer::code_double().
void buffer_list::add_binarized_double_right (const double * v, int v_sz)
References buffer_list::add_buffer_right(), buffer_list_node::buffer, and binarizer::code_double().
void buffer_list::add_binarized_float_left (const float * v, int v_sz)
References buffer_list::add_buffer_left(), buffer_list_node::buffer, and binarizer::code_float().
void buffer_list::add_binarized_float_right (const float * v, int v_sz)
References buffer_list::add_buffer_right(), buffer_list_node::buffer, and binarizer::code_float().
void buffer_list::add_binarized_int32_left (const int32_t * v, int v_sz)
References buffer_list::add_buffer_left(), buffer_list_node::buffer, and binarizer::code_int32().
void buffer_list::add_binarized_int32_right (const int32_t * v, int v_sz)
References buffer_list::add_buffer_right(), buffer_list_node::buffer, and binarizer::code_int32().
void buffer_list::add_binarized_log_double_left (const log_double * v, int v_sz)
References buffer_list::add_buffer_left(), buffer_list_node::buffer, and binarizer::code_double().
void buffer_list::add_binarized_log_double_right (const log_double * v, int v_sz)
References buffer_list::add_buffer_right(), buffer_list_node::buffer, and binarizer::code_double().
void buffer_list::add_binarized_log_float_left (const log_float * v, int v_sz)
References buffer_list::add_buffer_left(), buffer_list_node::buffer, and binarizer::code_float().
void buffer_list::add_binarized_log_float_right (const log_float * v, int v_sz)
References buffer_list::add_buffer_right(), buffer_list_node::buffer, and binarizer::code_float().
void buffer_list::add_binarized_uint32_left (const uint32_t * v, int v_sz)
References buffer_list::add_buffer_left(), buffer_list_node::buffer, and binarizer::code_uint32().
void buffer_list::add_binarized_uint32_right (const uint32_t * v, int v_sz)
References buffer_list::add_buffer_right(), buffer_list_node::buffer, and binarizer::code_uint32().
void buffer_list::add_buffer_left (buffer_list_node * nd)
References buffer_list::first, buffer_list::last, buffer_list_node::next, buffer_list_node::size, and buffer_list::size.
Referenced by buffer_list::add_binarized_double_left(), buffer_list::add_binarized_float_left(), buffer_list::add_binarized_int32_left(), buffer_list::add_binarized_log_double_left(), buffer_list::add_binarized_log_float_left(), buffer_list::add_binarized_uint32_left(), buffer_list::add_constString_left(), and buffer_list::add_formatted_string_left().
void buffer_list::add_buffer_right (buffer_list_node * nd)
References buffer_list::first, buffer_list::last, buffer_list_node::next, buffer_list_node::size, and buffer_list::size.
Referenced by buffer_list::add_binarized_double_right(), buffer_list::add_binarized_float_right(), buffer_list::add_binarized_int32_right(), buffer_list::add_binarized_log_double_right(), buffer_list::add_binarized_log_float_right(), buffer_list::add_binarized_uint32_right(), buffer_list::add_constString_right(), buffer_list::add_formatted_string_right(), and buffer_list::printf().
void buffer_list::add_constString_left (const constString & cs)
References buffer_list::add_buffer_left(), buffer_list_node::buffer, and constString::len().
void buffer_list::add_constString_right (const constString & cs)
References buffer_list::add_buffer_right(), buffer_list_node::buffer, and constString::len().
void buffer_list::add_formatted_string_left (const char * fmt, ...)
References buffer_list::add_buffer_left(), buffer_list_node::buffer, and FORMAT_BUFFER_SIZE.
void buffer_list::add_formatted_string_right (const char * fmt, ...)
References buffer_list::add_buffer_right(), buffer_list_node::buffer, and FORMAT_BUFFER_SIZE.
void StringQueue::advanceBuffer (int bufferAdvance)
References StringQueue::Node::first, StringQueue::firstNode, StringQueue::Node::last, StringQueue::lastNode, StringQueue::Node::next, and StringQueue::theSize.
template<typename T > void aligned_free (T * ptr) inline
Referenced by Matrix< T >::release_memory(), and GPUMirroredMemoryBlock< T >::~GPUMirroredMemoryBlock().
template<typename T > T* aligned_malloc (size_t nmemb) inline
References VECTOR_ALIGNMENT.
void buffer_list::append (buffer_list * other)
References buffer_list::first, buffer_list::last, buffer_list_node::next, and buffer_list::size.
buffer_list_node::buffer_list_node (int sz, buffer_list_node * nxt = 0)
References buffer_list_node::buffer, buffer_list_node::next, and buffer_list_node::size.
int binarizer::buffer_size_16 (int num, bool with_newlines = true) static
int binarizer::buffer_size_32 (int num, bool with_newlines = true) static
Referenced by binarizer::code_vector_float(), binarizer::code_vector_int32(), saveMatrixFloatToString(), and april_utils::MFSet::toString().
int binarizer::buffer_size_64 (int num, bool with_newlines = true) static
void StringQueue::checkLast () inline private
References StringQueue::Node::bufferSize, StringQueue::Node::last, StringQueue::lastNode, and StringQueue::Node::next.
Referenced by StringQueue::print(), StringQueue::printEsc(), StringQueue::putBuffer(), StringQueue::putchar(), and StringQueue::putchars().
void StringQueue::checkNonEmpty () inline private
References StringQueue::firstNode, and StringQueue::lastNode.
Referenced by StringQueue::print(), StringQueue::printEsc(), StringQueue::putBuffer(), StringQueue::putchar(), and StringQueue::putchars().
void StringQueue::clear ()
References StringQueue::firstNode, StringQueue::lastNode, StringQueue::Node::next, and StringQueue::theSize.
Referenced by StringQueue::~StringQueue().
void binarizer::code_double (double i, char b[10]) static
References binarizer::BIG_ENDIAN, binarizer::code_uint32(), and binarizer::endianness.
Referenced by buffer_list::add_binarized_double_left(), buffer_list::add_binarized_double_right(), buffer_list::add_binarized_log_double_left(), and buffer_list::add_binarized_log_double_right().
void binarizer::code_float (float i, char b[5]) static
References binarizer::code_uint32().
Referenced by buffer_list::add_binarized_float_left(), buffer_list::add_binarized_float_right(), buffer_list::add_binarized_log_float_left(), buffer_list::add_binarized_log_float_right(), binarizer::code_vector_float(), and saveMatrixFloatToFile().
void binarizer::code_int32 (int32_t i, char b[5]) static
References binarizer::code_uint32().
Referenced by buffer_list::add_binarized_int32_left(), buffer_list::add_binarized_int32_right(), binarizer::code_vector_int32(), and april_utils::MFSet::toString().
void binarizer::code_uint32 (uint32_t i, char b[5]) static
References BASE, BASE1, BASE2, BASE3, BASE4, and binarizer::cod.
Referenced by buffer_list::add_binarized_uint32_left(), buffer_list::add_binarized_uint32_right(), binarizer::code_double(), binarizer::code_float(), and binarizer::code_int32().
int binarizer::code_vector_float (const float * vect, int vect_size, char * dest_buffer, int dest_buffer_size, bool with_newlines = true) static
References binarizer::buffer_size_32(), and binarizer::code_float().
Referenced by saveMatrixFloatToString().
int binarizer::code_vector_int32 (const int32_t * vect, int vect_size, char * dest_buffer, int dest_buffer_size, bool with_newlines = true) static
References binarizer::buffer_size_32(), and binarizer::code_int32().
Referenced by april_utils::MFSet::toString().
constString::constString (const char * s)
References constString::buffer, and constString::length.
constString::constString (const char * s, size_t n)
References constString::buffer, and constString::length.
char * copystr (const char * c)
Referenced by ANN::AllAllMLP::clone(), and ANN::AllAllMLP::generateActionsAllAll().
double binarizer::decode_double (const char b[10]) static
References binarizer::BIG_ENDIAN, binarizer::decode_uint32(), and binarizer::endianness.
float binarizer::decode_float (const char b[5]) static
References binarizer::decode_uint32().
Referenced by constString::extract_double_binary(), and constString::extract_float_binary().
int32_t binarizer::decode_int32 (const char b[5]) static
References binarizer::decode_uint32().
Referenced by constString::extract_int32_binary().
uint32_t binarizer::decode_uint32 (const char b[5]) static
References BASE1, BASE2, BASE3, BASE4, and binarizer::uncod.
Referenced by binarizer::decode_double(), binarizer::decode_float(), binarizer::decode_int32(), and constString::extract_uint32_binary().
bool Referenced::decRef () virtual
References Referenced::refs.
char * StringQueue::exportBuffer (int & sz) const
References StringQueue::firstNode, StringQueue::Node::next, and StringQueue::size().
bool constString::extract_char (char * resul)
References constString::buffer, constString::empty(), and constString::skip().
bool constString::extract_double (double * resul, const char * separadores = " \t,;\r\n")
References constString::buffer, constString::length, and constString::ltrim().
bool constString::extract_double_binary (double * resul)
References constString::buffer, binarizer::decode_float(), constString::empty(), constString::length, and constString::skip().
Referenced by constString::extract_log_double_binary().
bool constString::extract_float (float * resul, const char * separadores = " \t,;\r\n")
References constString::buffer, constString::empty(), constString::length, and constString::ltrim().
Referenced by readMatrixFloatFromStream().
bool constString::extract_float_binary (float * resul)
References constString::buffer, binarizer::decode_float(), constString::empty(), constString::length, and constString::skip().
Referenced by constString::extract_log_float_binary(), and readMatrixFloatFromStream().
bool constString::extract_int (int * resul, int base = 10, const char * separadores = " \t,;\r\n")
References constString::extract_long().
Referenced by readMatrixFloatFromStream(), and readMatrixFloatPNM().
bool constString::extract_int32_binary (int32_t * resul)
References constString::buffer, binarizer::decode_int32(), constString::empty(), constString::length, and constString::skip().
Referenced by april_utils::MFSet::fromString().
constString ReadFileStream::extract_line ()
References ReadFileStream::getToken().
constString constString::extract_line ()
References constString::extract_token().
Referenced by ANN::AllAllMLP::loadModel().
bool constString::extract_log_double_binary (log_double * resul)
References constString::extract_double_binary(), and log_double::from_double().
bool constString::extract_log_float_binary (log_float * resul)
References constString::extract_float_binary().
bool constString::extract_long (long int * resul, int base = 10, const char * separadores = " \t,;\r\n")
References constString::buffer, constString::empty(), constString::length, and constString::ltrim().
Referenced by constString::extract_int(), and constString::extract_unsigned_int().
bool constString::extract_long_long (long long int * resul, int base = 10, const char * separadores = " \t,;\r\n")
References constString::buffer, constString::empty(), constString::length, and constString::ltrim().
constString constString::extract_prefix (size_t prefix_len)
References constString::buffer, constString::constString(), constString::empty(), and constString::length.
constString constString::extract_token (const char * separadores = " \t,;\r\n")
References constString::buffer, constString::constString(), constString::empty(), constString::length, constString::ltrim(), and constString::skip().
Referenced by constString::extract_line(), constString::extract_u_line(), ANN::AllAllMLP::generateActionsAllAll(), readMatrixFloatFromStream(), and readMatrixFloatPNM().
constString ReadFileStream::extract_u_line ()
References ReadFileStream::getToken(), and constString::len().
constString constString::extract_u_line ()
References constString::buffer, constString::extract_token(), and constString::length.
Referenced by readMatrixFloatFromStream(), and readMatrixFloatPNM().
bool constString::extract_uint32_binary (uint32_t * resul)
References constString::buffer, binarizer::decode_uint32(), constString::empty(), constString::length, and constString::skip().
bool constString::extract_unsigned_int (unsigned int * resul, int base = 10, const char * separadores = " \t,;\r\n")
References constString::extract_long().
Referenced by ANN::AllAllMLP::generateActionsAllAll().
char* get_line (char * s, int size, FILE * stream) inline
char* get_uncommented_line (char * s, int size, FILE * stream) inline
int StringQueue::getBufferChunk (char ** buffer)
References StringQueue::Node::buffer, StringQueue::Node::first, StringQueue::firstNode, and StringQueue::Node::last.
constString ReadFileStream::getToken (const char * delim)
References ReadFileStream::buffer, ReadFileStream::buffer_len, ReadFileStream::buffer_pos, ReadFileStream::moveAndFillBuffer(), ReadFileStream::resizeAndFillBuffer(), and ReadFileStream::trim().
Referenced by ReadFileStream::extract_line(), and ReadFileStream::extract_u_line().
void ignore_result_helper (int __attribute__((unused)) dummy, ...) inline
void Referenced::incRef () virtual
References Referenced::refs.
void binarizer::init () static
References binarizer::BIG_ENDIAN, binarizer::endianness, binarizer::LITTLE_ENDIAN, and binarizer::UNKNOWN_ENDIAN.
bool constString::is_prefix (const constString & theprefix)
References constString::buffer, and constString::length.
Referenced by constString::is_prefix(), and constString::skip().
bool constString::is_prefix (const char * theprefix)
References constString::constString(), and constString::is_prefix().
void least_squares (double x[], double y[], int numPoints, double & a, double & b)
float log1sub (float x) inline
Referenced by operator-().
double log1sub (double x) inline
float logadd1 (float x) inline
Referenced by operator+().
double logadd1 (double x) inline
void constString::ltrim (const char * acepta = " \t")
References constString::buffer, and constString::length.
Referenced by constString::extract_double(), constString::extract_float(), constString::extract_long(), constString::extract_long_long(), and constString::extract_token().
bool ReadFileStream::moveAndFillBuffer () private
References ReadFileStream::buffer, ReadFileStream::buffer_len, ReadFileStream::buffer_pos, and ReadFileStream::f.
Referenced by ReadFileStream::getToken(), and ReadFileStream::trim().
void msleep (unsigned long milisec)
char * constString::newString () const
References constString::buffer, and constString::length.
Referenced by ANN::AllAllMLP::loadModel().
bool constString::operator!= (const constString & otro) const
References constString::buffer, and constString::length.
bool operator!= (const log_float & x, const log_float & y) inline
References log_float::raw_value.
bool operator!= (const log_double & x, const log_double & y) inline
References log_double::raw_value.
log_float operator* (const log_float & x, const log_float & y) inline
References log_float::log_float(), log_float::raw_value, and log_float::zero().
log_double operator* (const log_double & x, const log_double & y) inline
References log_double::raw_value, and log_float::zero().
log_float log_float::operator*= (const log_double & y) inline
References log_float::raw_value, and log_float::rawscorezero.
log_float operator+ (const log_float & x, const log_float & y) inline
References log_float::log_float(), logadd1(), log_float::raw_value, and log_float::zero().
log_double operator+ (const log_double & x, const log_double & y) inline
References logadd1(), log_double::raw_value, and log_float::zero().
log_float log_float::operator+= (const log_double & y) inline
References log_float::raw_value, and log_float::rawscorezero.
log_float operator- (const log_float & x, const log_float & y) inline
References log1sub(), log_float::log_float(), log_float::raw_value, and log_float::zero().
log_double operator- (const log_double & x, const log_double & y) inline
References log1sub(), log_double::raw_value, and log_float::zero().
log_float log_float::operator-= (const log_double & y) inline
References log_float::raw_value, and log_float::rawscorezero.
log_float operator/ (const log_float & x, const log_float & y) inline
References log_float::log_float(), log_float::raw_value, and log_float::zero().
log_double operator/ (const log_double & x, const log_double & y) inline
References log_double::raw_value, and log_float::zero().
log_float log_float::operator/= (const log_double & y) inline
References log_float::raw_value, and log_float::rawscorezero.
bool constString::operator< (const constString & otro) const
References constString::buffer, constString::length, and april_utils::min().
bool operator< (const log_float & x, const log_float & y) inline
References log_float::raw_value.
bool operator< (const log_double & x, const log_double & y) inline
References log_double::raw_value.
bool constString::operator<= (const constString & otro) const
References constString::buffer, constString::length, and april_utils::min().
bool operator<= (const log_float & x, const log_float & y) inline
References log_float::raw_value.
bool operator<= (const log_double & x, const log_double & y) inline
References log_double::raw_value.
log_float & log_float::operator= (const log_double & value) inline
References log_float::raw_value, log_double::raw_value, and log_float::rawscorezero.
bool constString::operator== (const constString & otro) const
References constString::buffer, and constString::length.
bool operator== (const log_float & x, const log_float & y) inline
References log_float::raw_value.
bool operator== (const log_double & x, const log_double & y) inline
References log_double::raw_value.
bool constString::operator> (const constString & otro) const
References constString::buffer, constString::length, and april_utils::min().
bool operator> (const log_float & x, const log_float & y) inline
References log_float::raw_value.
bool operator> (const log_double & x, const log_double & y) inline
References log_double::raw_value.
bool constString::operator>= (const constString & otro) const
References constString::buffer, constString::length, and april_utils::min().
bool operator>= (const log_float & x, const log_float & y) inline
References log_float::raw_value.
bool operator>= (const log_double & x, const log_double & y) inline
References log_double::raw_value.
pid_t popen2 (const char * command, int * infp, int * outfp)
References READ, and WRITE.
void StringQueue::print (const char * str)
References StringQueue::checkLast(), StringQueue::checkNonEmpty(), StringQueue::lastNode, StringQueue::Node::putCharNoCheck(), and StringQueue::theSize.
Referenced by StringQueue::operator<<().
void constString::print (FILE * F = stdout)
References constString::buffer, and constString::length.
void StringQueue::printEsc (const char * str)
References StringQueue::checkLast(), StringQueue::checkNonEmpty(), StringQueue::lastNode, StringQueue::Node::putCharNoCheck(), and StringQueue::theSize.
void StringQueue::printf (const char * fmt, ...)
References StringQueue::putBuffer().
Referenced by StringQueue::operator<<().
void buffer_list::printf (const char * fmt, ...)
es una copia de add_formatted_string_right TODO: se puede hacer que sea un alias en lugar de una copia?
References buffer_list::add_buffer_right(), buffer_list_node::buffer, and FORMAT_BUFFER_SIZE.
void StringQueue::putBuffer (const char * buffer, int buffersz)
References StringQueue::Node::buffer, StringQueue::checkLast(), StringQueue::checkNonEmpty(), StringQueue::Node::freeSpace(), StringQueue::Node::last, StringQueue::lastNode, april_utils::min(), and StringQueue::theSize.
Referenced by StringQueue::printf(), and StringQueue::putStringQueue().
void StringQueue::putchar (char c)
References StringQueue::checkLast(), StringQueue::checkNonEmpty(), StringQueue::lastNode, StringQueue::Node::putCharNoCheck(), and StringQueue::theSize.
void StringQueue::putchars (char c, int times)
References StringQueue::checkLast(), StringQueue::checkNonEmpty(), StringQueue::lastNode, StringQueue::Node::putCharNoCheck(), and StringQueue::theSize.
void StringQueue::putStringQueue (const StringQueue & other)
References StringQueue::firstNode, StringQueue::Node::next, and StringQueue::putBuffer().
ReadFileStream::ReadFileStream (const char * path)
References ReadFileStream::buffer, ReadFileStream::buffer_len, ReadFileStream::buffer_pos, DEFAULT_BUFFER_LEN, ReadFileStream::f, and ReadFileStream::max_buffer_len.
Referenced::Referenced ()
References Referenced::refs.
bool ReadFileStream::resizeAndFillBuffer () private
References ReadFileStream::buffer, ReadFileStream::buffer_len, ReadFileStream::f, and ReadFileStream::max_buffer_len.
Referenced by ReadFileStream::getToken().
void constString::skip (size_t n)
References constString::buffer, and constString::length.
Referenced by constString::extract_char(), constString::extract_double_binary(), constString::extract_float_binary(), constString::extract_int32_binary(), constString::extract_token(), constString::extract_uint32_binary(), readMatrixFloatPNM(), and constString::skip().
bool constString::skip (const char * theprefix)
References constString::constString(), and constString::skip().
bool constString::skip (const constString & theprefix)
References constString::is_prefix(), constString::length, and constString::skip().
StringQueue::StringQueue ()
References StringQueue::firstNode, StringQueue::lastNode, and StringQueue::theSize.
char * buffer_list::to_string (string_termination t = NON_NULL_TERMINATED)
References buffer_list_node::buffer, buffer_list::first, buffer_list_node::next, buffer_list::NULL_TERMINATED, buffer_list_node::size, and buffer_list::size.
bool ReadFileStream::trim (const char * delim) private
References ReadFileStream::buffer, ReadFileStream::buffer_len, ReadFileStream::buffer_pos, and ReadFileStream::moveAndFillBuffer().
Referenced by ReadFileStream::getToken().
buffer_list::~buffer_list ()
References buffer_list::first, and buffer_list_node::next.
buffer_list_node::~buffer_list_node ()
References buffer_list_node::buffer.
ReadFileStream::~ReadFileStream ()
References ReadFileStream::buffer, and ReadFileStream::f.
Referenced::~Referenced () virtual
References Referenced::refs.
Variable Documentation
const uint32_t BASE = 85 static
Referenced by binarizer::code_uint32().
const uint32_t BASE1 = 85 static
Referenced by binarizer::code_uint32(), and binarizer::decode_uint32().
const uint32_t BASE2 = 85*85 static
Referenced by binarizer::code_uint32(), and binarizer::decode_uint32().
const uint32_t BASE3 = 85*85*85 static
Referenced by binarizer::code_uint32(), and binarizer::decode_uint32().
const uint32_t BASE4 = 85*85*85*85 static
Referenced by binarizer::code_uint32(), and binarizer::decode_uint32().
const uint64_t BASE5 = uint64_t(85)*85*85*85*85 static
const uint64_t BASE6 = uint64_t(85)*85*85*85*85*85 static
const uint64_t BASE7 = uint64_t(85)*85*85*85*85*85*85 static
const uint64_t BASE8 = uint64_t(85)*85*85*85*85*85*85*85 static
const uint64_t BASE9 = uint64_t(85)*85*85*85*85*85*85*85*85 static
char binarizer::cod static private
Initial value:
 {'\041','\044','\045','\046','\047','\050','\051','\052','\053','\054',
                         '\056','\057','\060','\061','\062','\063','\064','\065','\066','\067',
                         '\070','\071','\072','\073','\074','\075','\076','\077','\100','\101',
                         '\102','\103','\104','\105','\106','\107','\110','\111','\112','\113',
                         '\114','\115','\116','\117','\120','\121','\122','\123','\124','\125',
                         '\126','\127','\130','\131','\132','\136','\137','\140','\141','\142',
                         '\143','\144','\145','\146','\147','\150','\151','\152','\153','\154',
                         '\155','\156','\157','\160','\161','\162','\163','\164','\165','\166',
                         '\167','\170','\171','\172','\173',}
Referenced by binarizer::code_uint32().
static const double log_double::doublenearzero = 1e-37 static private
Referenced by log_double::from_double().
binarizer::endian_enum binarizer::endianness static private
Referenced by binarizer::code_double(), binarizer::decode_double(), and binarizer::init().
static const float log_float::floatnearzero = 1e-37 static private
Referenced by log_float::from_double(), and log_float::from_float().
static const float log_float::rawscorenearzero = -99 static private
static const double log_double::rawscorenearzero = -85 static private
static const float log_float::rawscoreone = 0 static private
Referenced by log_float::one().
static const double log_double::rawscoreone = 0 static private
Referenced by log_double::one().
static const float log_float::rawscorezero = -1e12 static private
Referenced by log_float::from_double(), log_float::from_float(), log_float::operator*=(), log_float::operator+=(), log_float::operator-=(), log_float::operator/=(), log_float::operator=(), log_float::raise_to(), and log_float::zero().
static const double log_double::rawscorezero = -1e8 static private
Referenced by log_double::from_double(), log_double::operator*=(), log_double::operator+=(), log_double::operator-=(), log_double::operator/=(), log_double::operator=(), log_double::raise_to(), and log_double::zero().
char binarizer::uncod static private
Initial value:
 {'\000','\000','\000','\000','\000','\000','\000','\000','\000','\000',
                         '\000','\000','\000','\000','\000','\000','\000','\000','\000','\000',
                         '\000','\000','\000','\000','\000','\000','\000','\000','\000','\000',
                         '\000','\000','\000','\000','\000','\000','\001','\002','\003','\004',
                         '\005','\006','\007','\010','\011','\000','\012','\013','\014','\015',
                         '\016','\017','\020','\021','\022','\023','\024','\025','\026','\027',
                         '\030','\031','\032','\033','\034','\035','\036','\037','\040','\041',
                         '\042','\043','\044','\045','\046','\047','\050','\051','\052','\053',
                         '\054','\055','\056','\057','\060','\061','\062','\063','\064','\065',
                         '\066','\000','\000','\000','\067','\070','\071','\072','\073','\074',
                         '\075','\076','\077','\100','\101','\102','\103','\104','\105','\106',
                         '\107','\110','\111','\112','\113','\114','\115','\116','\117','\120',
                         '\121','\122','\123','\124','\000','\000','\000','\000','\000','\000',
                         '\000','\000','\000','\000','\000','\000','\000','\000','\000','\000',
                         '\000','\000','\000','\000','\000','\000','\000','\000','\000','\000',
                         '\000','\000','\000','\000','\000','\000','\000','\000','\000','\000',
                         '\000','\000','\000','\000','\000','\000','\000','\000','\000','\000',
                         '\000','\000','\000','\000','\000','\000','\000','\000','\000','\000',
                         '\000','\000','\000','\000','\000','\000','\000','\000','\000','\000',
                         '\000','\000','\000','\000','\000','\000','\000','\000','\000','\000',
                         '\000','\000','\000','\000','\000','\000','\000','\000','\000','\000',
                         '\000','\000','\000','\000','\000','\000','\000','\000','\000','\000',
                         '\000','\000','\000','\000','\000','\000','\000','\000','\000','\000',
                         '\000','\000','\000','\000','\000','\000','\000','\000','\000','\000',
                         '\000','\000','\000','\000','\000','\000','\000','\000','\000','\000',
                         '\000','\000','\000','\000','\000','\000',}
Referenced by binarizer::decode_uint32().