april-ann
Dataset
Basics
Classes
class DataSet< T >
A pure abstract templatized class that serves as interface.
class MatrixDataSet< T >
DataSet specialization to put or get patterns from a Matrix object.
class UnionDataSet< T >
DataSet specialization to put or get patterns from a union of DataSets.
class IdentityDataSet< T >
DataSet specialization which serves to getPatterns from an IdentityMatrix.
class SubDataSet< T >
A DataSet specialization which takes an interval of patterns from other.
class SplitDataSet< T >
A specialization of DataSet which takes an split of other DataSet.
class JoinDataSet< T >
A specialization of DataSet which join outputs from several DataSets.
class IndexDataSet< T >
A specialization of DataSet which takes a general sub set from other.
class LinearCombConf< T >
An auxiliar object for LinearCombDataSet.
class LinearCombDataSet< T >
A specialization of DataSet, takes a DataSet and outputs a linear combination of its patterns.
class ContextualizerDataSet< T >
A specialization of DataSet which takes a DataSet and adds context to its patterns.
class AccumulateDataSet< T >
A specialization of DataSet for data accumulation using putPattern.
class ByteDataSet< T >
class BitDataSet< T >
class SparseDataset< T >
A specialization of DataSet for use sparse data representation.
class ShortListDataSet< T >
A specialization DataSet for shortlist approach in NNLMs.
class IndexFilterDataSet< T >
Similar to IndexedDataSet but using a vector of unsigned int as indexes.
class PerturbationDataSet< T >
A specialization of DataSet which add gaussian noise to patterns.
class SaltNoiseDataSet< T >
A specialization of DataSet which add a fixed size salt noise to patterns.
class SaltPepperNoiseDataSet< T >
A specialization of DataSet which add a fixed size salt and pepper noise to patterns.
class CacheDataSet< T >
A specialization of DataSet for cacheNNLMs training.
class DerivDataSet< T >
class DataSetToken
class DataSetTokenVector
class UnionDataSetToken
class DataSetFloat2TokenWrapper
Macros
#define DATASET_CC_H
#define positive(v) (v)<=0.1f
Typedefs
typedef DataSet< float > DataSetFloat
typedef MatrixDataSet< float > MatrixDataSetFloat
typedef LinearCombConf< float > LinearCombConfFloat
typedef SparseDataset< float > SparseDatasetFloat
typedef ShortListDataSet< float > ShortListDataSetFloat
typedef IndexFilterDataSet< float > IndexFilterDataSetFloat
typedef PerturbationDataSet
< float > PerturbationDataSetFloat
typedef SaltNoiseDataSet< float > SaltNoiseDataSetFloat
typedef SaltPepperNoiseDataSet
< float > SaltPepperNoiseDataSetFloat
typedef DerivDataSet< float > DerivDataSetFloat
typedef CacheDataSet< float > CacheDataSetFloat
Functions
float Fmeasure (DataSetFloat *ds, DataSetFloat *GT, float &PR, float &RC)
This function computes Fmeasure given two DataSetFloat.
MatrixDataSet< T >::MatrixDataSet (Matrix< T > *m)
void MatrixDataSet< T >::setValue (int *dest, int *orig)
void MatrixDataSet< T >::setValue (bool *dest, bool *orig)
void MatrixDataSet< T >::setNumSteps (int *v)
Setter for numSteps attribute.
void MatrixDataSet< T >::setSubMatrixSize (int *v)
Setter for submatrixsize attribute.
void MatrixDataSet< T >::index2coordinate (int index)
void MatrixDataSet< T >::auxGetPattern (int offsetmatrix, int d)
int MatrixDataSet< T >::getPattern (int index, T *pat)
void MatrixDataSet< T >::auxPutPattern (int offsetmatrix, int d)
int MatrixDataSet< T >::putPattern (int index, const T *pat)
virtual MatrixDataSet< T >::~MatrixDataSet ()
IdentityDataSet< T >::IdentityDataSet (int patternSize, T zerovalue, T onevalue)
virtual IdentityDataSet< T >::~IdentityDataSet ()
int IdentityDataSet< T >::getPattern (int index, T *pat)
int IdentityDataSet< T >::putPattern (int index, const T *pat)
UnionDataSet< T >::UnionDataSet (int n, DataSet< T > **v)
virtual UnionDataSet< T >::~UnionDataSet ()
int UnionDataSet< T >::getPattern (int index, T *pat)
int UnionDataSet< T >::putPattern (int index, const T *pat)
SubDataSet< T >::SubDataSet (int ini, int fin, DataSet< T > *ds)
virtual SubDataSet< T >::~SubDataSet ()
int SubDataSet< T >::getPattern (int index, T *pat)
int SubDataSet< T >::putPattern (int index, const T *pat)
SplitDataSet< T >::SplitDataSet (int ini, int fin, DataSet< T > *ds)
virtual SplitDataSet< T >::~SplitDataSet ()
int SplitDataSet< T >::getPattern (int index, T *pat)
JoinDataSet< T >::JoinDataSet (int n, DataSet< T > **v)
virtual JoinDataSet< T >::~JoinDataSet ()
int JoinDataSet< T >::getPattern (int index, T *pat)
int JoinDataSet< T >::putPattern (int index, const T *pat)
IndexDataSet< T >::IndexDataSet (DataSet< T > **datasets, int firstindex=0)
virtual IndexDataSet< T >::~IndexDataSet ()
int IndexDataSet< T >::getPattern (int index, T *pat)
int IndexDataSet< T >::putPattern (int index, const T *pat)
LinearCombDataSet< T >::LinearCombDataSet (DataSet< T > *ds, LinearCombConf< T > *conf)
virtual LinearCombDataSet< T >::~LinearCombDataSet ()
int LinearCombDataSet< T >::getPattern (int index, T *pat)
ContextualizerDataSet< T >::ContextualizerDataSet (DataSet< T > *ds, int izq, int der, bool reverse=false)
virtual ContextualizerDataSet< T >::~ContextualizerDataSet ()
int ContextualizerDataSet< T >::getPattern (int index, T *pat)
int ContextualizerDataSet< T >::putPattern (int index, const T *pat)
AccumulateDataSet< T >::AccumulateDataSet (int patsz, int numpat)
virtual AccumulateDataSet< T >::~AccumulateDataSet ()
int AccumulateDataSet< T >::getPattern (int index, T *pat)
int AccumulateDataSet< T >::putPattern (int index, const T *pat)
ByteDataSet< T >::ByteDataSet (int patsz, int numpat, double a, double b)
virtual ByteDataSet< T >::~ByteDataSet ()
int ByteDataSet< T >::getPattern (int index, T *pat)
int ByteDataSet< T >::putPattern (int index, const T *pat)
BitDataSet< T >::BitDataSet (int nump, int patsize)
virtual BitDataSet< T >::~BitDataSet ()
int BitDataSet< T >::getPattern (int index, T *pat)
int BitDataSet< T >::putPattern (int index, const T *pat)
SparseDataset< T >::SparseDataset (Matrix< T > *m, int nump, int patsize)
virtual SparseDataset< T >::~SparseDataset ()
int SparseDataset< T >::getPattern (int index, T *pat)
int SparseDataset< T >::putPattern (int index, const T *pat)
ShortListDataSet< T >::ShortListDataSet (DataSet< T > *ds, int short_list_size, int unk_word)
virtual ShortListDataSet< T >::~ShortListDataSet ()
int ShortListDataSet< T >::getPattern (int index, T *pat)
int ShortListDataSet< T >::putPattern (int index, const T *pat)
IndexFilterDataSet< T >::IndexFilterDataSet (DataSet< T > *ds, ReferencedVectorUint *indexes)
virtual IndexFilterDataSet< T >::~IndexFilterDataSet ()
int IndexFilterDataSet< T >::getPattern (int index, T *pat)
int IndexFilterDataSet< T >::putPattern (int index, const T *pat)
PerturbationDataSet< T >::PerturbationDataSet (DataSet< T > *ds, MTRand *random, double mean, double variance)
virtual PerturbationDataSet< T >::~PerturbationDataSet ()
int PerturbationDataSet< T >::getPattern (int index, T *pat)
int PerturbationDataSet< T >::putPattern (int index, const T *pat)
SaltNoiseDataSet< T >::SaltNoiseDataSet (DataSet< T > *ds, MTRand *random, double vd, T zero)
virtual SaltNoiseDataSet< T >::~SaltNoiseDataSet ()
int SaltNoiseDataSet< T >::getPattern (int index, T *pat)
int SaltNoiseDataSet< T >::putPattern (int index, const T *pat)
SaltPepperNoiseDataSet< T >::SaltPepperNoiseDataSet (DataSet< T > *ds, MTRand *random, double vd, T zero, T one)
virtual SaltPepperNoiseDataSet< T >::~SaltPepperNoiseDataSet ()
int SaltPepperNoiseDataSet< T >::getPattern (int index, T *pat)
int SaltPepperNoiseDataSet< T >::putPattern (int index, const T *pat)
DerivDataSet< T >::DerivDataSet (DataSet< T > *ds, bool deriv0, bool deriv1, bool deriv2)
virtual DerivDataSet< T >::~DerivDataSet ()
int DerivDataSet< T >::getPattern (int index, T *pat)
int DerivDataSet< T >::putPattern (int index, const T *pat)
CacheDataSet< T >::CacheDataSet (DataSet< T > *ds, int **word2cache, int *word2cache_sizes, T *decays, int voc_size, int cache_size, T near_zero, int begin_token_id, int end_token_id, int null_token_id, int cache_stop_token_id)
virtual CacheDataSet< T >::~CacheDataSet ()
int CacheDataSet< T >::getPattern (int index, T *pat)
int CacheDataSet< T >::putPattern (int index, const T *pat)
Detailed Description
Macro Definition Documentation
#define DATASET_CC_H
#define positive (v) (v)<=0.1f
Referenced by Fmeasure().
Typedef Documentation
typedef CacheDataSet<float> CacheDataSetFloat
typedef DataSet<float> DataSetFloat
typedef DerivDataSet<float> DerivDataSetFloat
typedef IndexFilterDataSet<float> IndexFilterDataSetFloat
typedef LinearCombConf<float> LinearCombConfFloat
typedef MatrixDataSet<float> MatrixDataSetFloat
typedef PerturbationDataSet<float> PerturbationDataSetFloat
typedef SaltNoiseDataSet<float> SaltNoiseDataSetFloat
typedef SaltPepperNoiseDataSet<float> SaltPepperNoiseDataSetFloat
typedef ShortListDataSet<float> ShortListDataSetFloat
typedef SparseDataset<float> SparseDatasetFloat
Function Documentation
template<typename T > AccumulateDataSet< T >::AccumulateDataSet (int patsz, int numpat)
template<typename T > void MatrixDataSet< T >::auxGetPattern (int offsetmatrix, int d) private
References april_utils::mod().
template<typename T > void MatrixDataSet< T >::auxPutPattern (int offsetmatrix, int d) private
References april_utils::mod().
template<typename T > BitDataSet< T >::BitDataSet (int nump, int patsize)
template<typename T > ByteDataSet< T >::ByteDataSet (int patsz, int numpat, double a, double b)
template<typename T > CacheDataSet< T >::CacheDataSet (DataSet< T > * ds, int ** word2cache, int * word2cache_sizes, T * decays, int voc_size, int cache_size, T near_zero, int begin_token_id, int end_token_id, int null_token_id, int cache_stop_token_id)
References CacheDataSet< T >::cache_size, ERROR_PRINT, IncRef, CacheDataSet< T >::max_history, and DataSet< T >::patternSize().
template<typename T > ContextualizerDataSet< T >::ContextualizerDataSet (DataSet< T > * ds, int izq, int der, bool reverse = false)
References ContextualizerDataSet< T >::ctxtder, ContextualizerDataSet< T >::ctxtizq, IncRef, DataSet< T >::numPatterns(), ContextualizerDataSet< T >::numpatterns, DataSet< T >::patternSize(), and ContextualizerDataSet< T >::patternsize.
template<typename T > DerivDataSet< T >::DerivDataSet (DataSet< T > * ds, bool deriv0, bool deriv1, bool deriv2)
References DerivDataSet< T >::deriv2, IncRef, DerivDataSet< T >::left1, DerivDataSet< T >::left2, DataSet< T >::numPatterns(), DerivDataSet< T >::numpatterns, DerivDataSet< T >::orig, DerivDataSet< T >::origpatternsz, DataSet< T >::patternSize(), DerivDataSet< T >::patternsz, DerivDataSet< T >::right1, and DerivDataSet< T >::right2.
float Fmeasure (DataSetFloat * ds, DataSetFloat * GT, float & PR, float & RC)
This function computes Fmeasure given two DataSetFloat.
References ERROR_PRINT, ERROR_PRINT1, ERROR_PRINT2, DataSet< T >::getPattern(), DataSet< T >::numPatterns(), DataSet< T >::patternSize(), and positive.
template<typename T > int MatrixDataSet< T >::getPattern (int index, T * pat) virtual
Get the pattern index to the vector pat. The function call returns the patternSize().
Implements DataSet< T >.
template<typename T > int UnionDataSet< T >::getPattern (int index, T * pat) virtual
Get the pattern index to the vector pat. The function call returns the patternSize().
Implements DataSet< T >.
template<typename T > int IdentityDataSet< T >::getPattern (int index, T * pat) virtual
Get the pattern index to the vector pat. The function call returns the patternSize().
Implements DataSet< T >.
template<typename T > int SubDataSet< T >::getPattern (int index, T * pat) virtual
Get the pattern index to the vector pat. The function call returns the patternSize().
Implements DataSet< T >.
template<typename T > int SplitDataSet< T >::getPattern (int index, T * pat) virtual
Get the pattern index to the vector pat. The function call returns the patternSize().
Implements DataSet< T >.
template<typename T > int JoinDataSet< T >::getPattern (int index, T * pat) virtual
Get the pattern index to the vector pat. The function call returns the patternSize().
Implements DataSet< T >.
template<typename T > int IndexDataSet< T >::getPattern (int index, T * pat) virtual
Get the pattern index to the vector pat. The function call returns the patternSize().
Implements DataSet< T >.
template<typename T > int LinearCombDataSet< T >::getPattern (int index, T * pat) virtual
Get the pattern index to the vector pat. The function call returns the patternSize().
Implements DataSet< T >.
template<typename T > int ContextualizerDataSet< T >::getPattern (int index, T * pat) virtual
Get the pattern index to the vector pat. The function call returns the patternSize().
Implements DataSet< T >.
template<typename T > int AccumulateDataSet< T >::getPattern (int index, T * pat) virtual
Get the pattern index to the vector pat. The function call returns the patternSize().
Implements DataSet< T >.
template<typename T > int ByteDataSet< T >::getPattern (int index, T * pat) virtual
Get the pattern index to the vector pat. The function call returns the patternSize().
Implements DataSet< T >.
template<typename T > int BitDataSet< T >::getPattern (int index, T * pat) virtual
Get the pattern index to the vector pat. The function call returns the patternSize().
Implements DataSet< T >.
template<typename T > int SparseDataset< T >::getPattern (int index, T * pat) virtual
Get the pattern index to the vector pat. The function call returns the patternSize().
Implements DataSet< T >.
template<typename T > int ShortListDataSet< T >::getPattern (int index, T * pat) virtual
Get the pattern index to the vector pat. The function call returns the patternSize().
Implements DataSet< T >.
template<typename T > int IndexFilterDataSet< T >::getPattern (int index, T * pat) virtual
Get the pattern index to the vector pat. The function call returns the patternSize().
Implements DataSet< T >.
template<typename T > int PerturbationDataSet< T >::getPattern (int index, T * pat) virtual
Get the pattern index to the vector pat. The function call returns the patternSize().
Implements DataSet< T >.
template<typename T > int SaltNoiseDataSet< T >::getPattern (int index, T * pat) virtual
Get the pattern index to the vector pat. The function call returns the patternSize().
Implements DataSet< T >.
template<typename T > int SaltPepperNoiseDataSet< T >::getPattern (int index, T * pat) virtual
Get the pattern index to the vector pat. The function call returns the patternSize().
Implements DataSet< T >.
template<typename T > int CacheDataSet< T >::getPattern (int index, T * pat) virtual
Get the pattern index to the vector pat. The function call returns the patternSize().
Implements DataSet< T >.
template<typename T > int DerivDataSet< T >::getPattern (int index, T * pat) virtual
Get the pattern index to the vector pat. The function call returns the patternSize().
Implements DataSet< T >.
References april_utils::clamp().
template<typename T > IdentityDataSet< T >::IdentityDataSet (int patternSize, T zerovalue, T onevalue)
References IdentityDataSet< T >::patternSize(), and IdentityDataSet< T >::patternsz.
template<typename T > void MatrixDataSet< T >::index2coordinate (int index) private
template<typename T > IndexDataSet< T >::IndexDataSet (DataSet< T > ** datasets, int firstindex = 0)
References IncRef.
template<typename T > IndexFilterDataSet< T >::IndexFilterDataSet (DataSet< T > * ds, ReferencedVectorUint * indexes)
References IncRef.
template<typename T > JoinDataSet< T >::JoinDataSet (int n, DataSet< T > ** v)
References IncRef, DataSet< T >::numPatterns(), and DataSet< T >::patternSize().
template<typename T > LinearCombDataSet< T >::LinearCombDataSet (DataSet< T > * ds, LinearCombConf< T > * conf)
References IncRef, and DataSet< T >::patternSize().
template<typename T > MatrixDataSet< T >::MatrixDataSet (Matrix< T > * m)
References ERROR_EXIT, Matrix< T >::getDimSize(), Matrix< T >::getNumDim(), IncRef, and Matrix< T >::isSimple().
template<typename T > PerturbationDataSet< T >::PerturbationDataSet (DataSet< T > * ds, MTRand * random, double mean, double variance)
References IncRef.
template<typename T > int MatrixDataSet< T >::putPattern (int index, const T * pat) virtual
Put the given vector pat at pattern index. The function returns the patternSize().
Implements DataSet< T >.
template<typename T > int UnionDataSet< T >::putPattern (int index, const T * pat) virtual
Put the given vector pat at pattern index. The function returns the patternSize().
Implements DataSet< T >.
template<typename T > int IdentityDataSet< T >::putPattern (int index, const T * pat) virtual
Put the given vector pat at pattern index. The function returns the patternSize().
Implements DataSet< T >.
template<typename T > int SubDataSet< T >::putPattern (int index, const T * pat) virtual
Put the given vector pat at pattern index. The function returns the patternSize().
Implements DataSet< T >.
template<typename T > int JoinDataSet< T >::putPattern (int index, const T * pat) virtual
Put the given vector pat at pattern index. The function returns the patternSize().
Implements DataSet< T >.
template<typename T > int IndexDataSet< T >::putPattern (int index, const T * pat) virtual
Put the given vector pat at pattern index. The function returns the patternSize().
Implements DataSet< T >.
template<typename T > int ContextualizerDataSet< T >::putPattern (int index, const T * pat) virtual
Put the given vector pat at pattern index. The function returns the patternSize().
Implements DataSet< T >.
template<typename T > int AccumulateDataSet< T >::putPattern (int index, const T * pat) virtual
Put the given vector pat at pattern index. The function returns the patternSize().
Implements DataSet< T >.
template<typename T > int ByteDataSet< T >::putPattern (int index, const T * pat) virtual
Put the given vector pat at pattern index. The function returns the patternSize().
Implements DataSet< T >.
References april_utils::clamp().
template<typename T > int BitDataSet< T >::putPattern (int index, const T * pat) virtual
Put the given vector pat at pattern index. The function returns the patternSize().
Implements DataSet< T >.
template<typename T > int SparseDataset< T >::putPattern (int index, const T * pat) virtual
Put the given vector pat at pattern index. The function returns the patternSize().
Implements DataSet< T >.
References ERROR_PRINT.
template<typename T > int ShortListDataSet< T >::putPattern (int index, const T * pat) virtual
Put the given vector pat at pattern index. The function returns the patternSize().
Implements DataSet< T >.
template<typename T > int IndexFilterDataSet< T >::putPattern (int index, const T * pat) virtual
Put the given vector pat at pattern index. The function returns the patternSize().
Implements DataSet< T >.
References ERROR_PRINT.
template<typename T > int PerturbationDataSet< T >::putPattern (int index, const T * pat) virtual
Put the given vector pat at pattern index. The function returns the patternSize().
Implements DataSet< T >.
References ERROR_PRINT.
template<typename T > int SaltNoiseDataSet< T >::putPattern (int index, const T * pat) virtual
Put the given vector pat at pattern index. The function returns the patternSize().
Implements DataSet< T >.
References ERROR_PRINT.
template<typename T > int SaltPepperNoiseDataSet< T >::putPattern (int index, const T * pat) virtual
Put the given vector pat at pattern index. The function returns the patternSize().
Implements DataSet< T >.
References ERROR_PRINT.
template<typename T > int CacheDataSet< T >::putPattern (int index, const T * pat) virtual
Put the given vector pat at pattern index. The function returns the patternSize().
Implements DataSet< T >.
References ERROR_PRINT.
template<typename T > int DerivDataSet< T >::putPattern (int index, const T * pat) virtual
Put the given vector pat at pattern index. The function returns the patternSize().
Implements DataSet< T >.
References ERROR_PRINT.
template<typename T > SaltNoiseDataSet< T >::SaltNoiseDataSet (DataSet< T > * ds, MTRand * random, double vd, T zero)
References IncRef, DataSet< T >::patternSize(), and SaltNoiseDataSet< T >::zero_positions.
template<typename T > SaltPepperNoiseDataSet< T >::SaltPepperNoiseDataSet (DataSet< T > * ds, MTRand * random, double vd, T zero, T one)
References IncRef, DataSet< T >::patternSize(), and SaltPepperNoiseDataSet< T >::perturbed_positions.
template<typename T > void MatrixDataSet< T >::setNumSteps (int * v)
Setter for numSteps attribute.
template<typename T > void MatrixDataSet< T >::setSubMatrixSize (int * v)
Setter for submatrixsize attribute.
template<typename T > void MatrixDataSet< T >::setValue (int * dest, int * orig) private
Referenced by MatrixDataSet< T >::setCircular(), MatrixDataSet< T >::setOffset(), MatrixDataSet< T >::setOrderStep(), and MatrixDataSet< T >::setStep().
template<typename T > void MatrixDataSet< T >::setValue (bool * dest, bool * orig) private
template<typename T > ShortListDataSet< T >::ShortListDataSet (DataSet< T > * ds, int short_list_size, int unk_word)
References IncRef, ShortListDataSet< T >::patsize, and DataSet< T >::patternSize().
template<typename T > SparseDataset< T >::SparseDataset (Matrix< T > * m, int nump, int patsize)
References ERROR_EXIT, ERROR_EXIT2, ERROR_PRINT2, Matrix< T >::getRawDataAccess(), IncRef, Matrix< T >::isSimple(), SparseDataset< T >::matrix_indexes, SparseDataset< T >::patternsize, and Matrix< T >::size().
template<typename T > SplitDataSet< T >::SplitDataSet (int ini, int fin, DataSet< T > * ds)
References IncRef, and DataSet< T >::patternSize().
template<typename T > SubDataSet< T >::SubDataSet (int ini, int fin, DataSet< T > * ds)
References IncRef.
template<typename T > UnionDataSet< T >::UnionDataSet (int n, DataSet< T > ** v)
References IncRef, DataSet< T >::numPatterns(), and DataSet< T >::patternSize().
template<typename T > AccumulateDataSet< T >::~AccumulateDataSet () virtual
template<typename T > BitDataSet< T >::~BitDataSet () virtual
template<typename T > ByteDataSet< T >::~ByteDataSet () virtual
template<typename T > CacheDataSet< T >::~CacheDataSet () virtual
References DecRef.
template<typename T > ContextualizerDataSet< T >::~ContextualizerDataSet () virtual
References DecRef.
template<typename T > DerivDataSet< T >::~DerivDataSet () virtual
References DecRef.
template<typename T > IdentityDataSet< T >::~IdentityDataSet () virtual
template<typename T > IndexDataSet< T >::~IndexDataSet () virtual
References DecRef.
template<typename T > IndexFilterDataSet< T >::~IndexFilterDataSet () virtual
References DecRef.
template<typename T > JoinDataSet< T >::~JoinDataSet () virtual
References DecRef.
template<typename T > LinearCombDataSet< T >::~LinearCombDataSet () virtual
References DecRef.
template<typename T > MatrixDataSet< T >::~MatrixDataSet () virtual
References DecRef.
template<typename T > PerturbationDataSet< T >::~PerturbationDataSet () virtual
References DecRef.
template<typename T > SaltNoiseDataSet< T >::~SaltNoiseDataSet () virtual
References DecRef.
template<typename T > SaltPepperNoiseDataSet< T >::~SaltPepperNoiseDataSet () virtual
References DecRef.
template<typename T > ShortListDataSet< T >::~ShortListDataSet () virtual
References DecRef.
template<typename T > SparseDataset< T >::~SparseDataset () virtual
References DecRef.
template<typename T > SplitDataSet< T >::~SplitDataSet () virtual
References DecRef.
template<typename T > SubDataSet< T >::~SubDataSet () virtual
References DecRef.
template<typename T > UnionDataSet< T >::~UnionDataSet () virtual
References DecRef.