april-ann
Hmm_trainer
Classes
struct list_top_order
struct list_output
struct hmm_trainer_cls_transition
struct hmm_trainer_cls_state
struct hmm_trainer_transition
struct hmm_aux_transition
class hmm_trainer
class hmm_trainer_model
Functions
hmm_trainer::hmm_trainer ()
hmm_trainer::~hmm_trainer ()
void hmm_trainer::check_cls_state (int st)
int hmm_trainer::new_cls_state ()
void hmm_trainer::check_cls_transition (int tr)
int hmm_trainer::new_cls_transition (int c_st)
void hmm_trainer::check_cls_emission (int emis)
void hmm_trainer::begin_expectation ()
void hmm_trainer::end_expectation (bool update_trans_prob=true, bool update_a_priori_emission=true)
void hmm_trainer::print () const
hmm_trainer_model::hmm_trainer_model (hmm_trainer *trainer)
int hmm_trainer_model::new_state ()
void hmm_trainer_model::new_transition (int from, int to, int emission, int cls_transition, log_float prob, const char *output)
bool hmm_trainer_model::prepare_model ()
hmm_trainer_model::~hmm_trainer_model ()
log_float hmm_trainer_model::transition_prob (int tr)
int hmm_trainer_model::transition_emission (int tr)
void hmm_trainer_model::print () const
void hmm_trainer_model::print_dot () const
log_float hmm_trainer_model::viterbi (const MatrixFloat *emission, bool emission_in_log_base, bool do_expectation, MatrixFloat *reest_emission, MatrixFloat *seq_reest_emission, MatrixFloat *state_probabilities, char **output_str, float count_value)
void hmm_trainer_model::forward (MatrixFloat *emission, log_float *alpha)
void hmm_trainer_model::backward (MatrixFloat *input_emission, MatrixFloat *output_emission, log_float *alpha, bool do_expectation)
void hmm_trainer_model::forward_backward (MatrixFloat *input_emission, MatrixFloat *output_emission, bool do_expectation=true)
Detailed Description
Function Documentation
void hmm_trainer_model::backward (MatrixFloat * input_emission, MatrixFloat * output_emission, log_float * alpha, bool do_expectation) private
References acum_apriori_cls_emission(), acum_tran_prob(), apriori_cls_emission, hmm_trainer_transition::cls_transition, hmm_trainer_model::final_state, hmm_trainer_transition::from, log_float::from_float(), Matrix< T >::getDimSize(), GPUMirroredMemoryBlock< T >::getPPALForReadAndWrite(), Matrix< T >::getRawDataAccess(), hmm_trainer_model::num_states, hmm_trainer_model::num_transitions, log_float::one(), april_utils::swap(), hmm_trainer_transition::to, log_float::to_float(), hmm_trainer_model::trainer, hmm_trainer_model::transition, hmm_trainer_model::transition_emission(), hmm_trainer_model::transition_prob(), and log_float::zero().
Referenced by hmm_trainer_model::forward_backward().
void hmm_trainer::begin_expectation ()
References acum_cls_emission, cls_transition, num_cls_emissions, num_cls_transitions, and log_double::zero().
void hmm_trainer::check_cls_emission (int emis)
References acum_cls_emission, apriori_cls_emission, num_cls_emissions, log_float::one(), and vsz_cls_emissions.
Referenced by hmm_trainer_model::new_transition().
void hmm_trainer::check_cls_state (int st)
References cls_state, num_cls_states, and vsz_cls_states.
Referenced by new_cls_state().
void hmm_trainer::check_cls_transition (int tr)
References cls_transition, num_cls_transitions, and vsz_cls_transitions.
Referenced by new_cls_transition().
void hmm_trainer::end_expectation (bool update_trans_prob = true, bool update_a_priori_emission = true)
References hmm_trainer_cls_transition::acum, acum_cls_emission, apriori_cls_emission, cls_state, hmm_trainer_cls_state::cls_tr_list, cls_transition, log_float::from_float(), log_double::log(), hmm_trainer_cls_transition::next, num_cls_emissions, num_cls_states, log_float::one(), hmm_trainer_cls_transition::prob, and log_float::zero().
void hmm_trainer_model::forward (MatrixFloat * emission, log_float * alpha) private
References apriori_cls_emission, hmm_trainer_transition::from, log_float::from_float(), Matrix< T >::getDimSize(), GPUMirroredMemoryBlock< T >::getPPALForReadAndWrite(), Matrix< T >::getRawDataAccess(), hmm_trainer_model::initial_state, hmm_trainer_model::num_states, hmm_trainer_model::num_transitions, log_float::one(), hmm_trainer_transition::to, hmm_trainer_model::trainer, hmm_trainer_model::transition, hmm_trainer_model::transition_emission(), and hmm_trainer_model::transition_prob().
Referenced by hmm_trainer_model::forward_backward().
void hmm_trainer_model::forward_backward (MatrixFloat * input_emission, MatrixFloat * output_emission, bool do_expectation = true)
References hmm_trainer_model::backward(), hmm_trainer_model::forward(), Matrix< T >::getDimSize(), hmm_trainer_model::num_states, and log_float::zero().
hmm_trainer::hmm_trainer ()
References acum_cls_emission, apriori_cls_emission, cls_state, cls_transition, num_cls_emissions, num_cls_states, num_cls_transitions, log_float::one(), vsz_cls_emissions, vsz_cls_states, and vsz_cls_transitions.
hmm_trainer_model::hmm_trainer_model (hmm_trainer * trainer)
References hmm_trainer_model::created, hmm_trainer_model::final_state, IncRef, hmm_trainer_model::initial_state, hmm_trainer_model::list_transitions, hmm_trainer_model::num_states, hmm_trainer_model::num_transitions, hmm_trainer_model::trainer, and hmm_trainer_model::transition.
int hmm_trainer::new_cls_state ()
References check_cls_state(), cls_state, hmm_trainer_cls_state::cls_tr_list, and num_cls_states.
int hmm_trainer::new_cls_transition (int c_st)
References check_cls_transition(), cls_state, hmm_trainer_cls_state::cls_tr_list, cls_transition, hmm_trainer_cls_transition::emission, hmm_trainer_cls_transition::next, num_cls_transitions, hmm_trainer_cls_transition::prob, and log_float::zero().
int hmm_trainer_model::new_state ()
References hmm_trainer_model::num_states.
void hmm_trainer_model::new_transition (int from, int to, int emission, int cls_transition, log_float prob, const char * output)
References check_cls_emission(), hmm_aux_transition::emission, hmm_aux_transition::from, hmm_aux_transition::id, hmm_trainer_model::list_transitions, hmm_aux_transition::next, hmm_trainer_model::num_transitions, hmm_aux_transition::output, hmm_aux_transition::prob, hmm_aux_transition::to, and hmm_trainer_model::trainer.
bool hmm_trainer_model::prepare_model ()
References hmm_trainer_transition::cls_transition, hmm_trainer_model::created, hmm_aux_transition::emission, ERROR_PRINT2, ERROR_PRINT3, hmm_trainer_model::final_state, hmm_trainer_transition::from, hmm_aux_transition::from, hmm_aux_transition::id, hmm_trainer_model::initial_state, hmm_trainer_model::list_transitions, hmm_aux_transition::next, list_top_order::next, hmm_trainer_model::num_states, hmm_trainer_model::num_transitions, hmm_trainer_transition::output, hmm_aux_transition::output, set_cls_transition_emission(), set_cls_transition_prob(), list_top_order::state, hmm_trainer_transition::to, hmm_aux_transition::to, hmm_trainer_model::trainer, and hmm_trainer_model::transition.
void hmm_trainer::print () const
void hmm_trainer_model::print () const
References hmm_trainer_transition::cls_transition, hmm_trainer_model::created, hmm_trainer_model::final_state, get_cls_transition_emission(), get_cls_transition_prob(), hmm_trainer_model::initial_state, hmm_trainer_model::list_transitions, hmm_aux_transition::next, hmm_trainer_model::num_states, hmm_trainer_model::num_transitions, log_float::to_float(), hmm_trainer_model::trainer, and hmm_trainer_model::transition.
void hmm_trainer_model::print_dot () const
References hmm_trainer_transition::cls_transition, hmm_trainer_model::created, get_cls_transition_emission(), get_cls_transition_prob(), hmm_trainer_model::num_states, hmm_trainer_model::num_transitions, hmm_trainer_transition::output, log_float::to_float(), hmm_trainer_model::trainer, and hmm_trainer_model::transition.
int hmm_trainer_model::transition_emission (int tr) inline private
References hmm_trainer_transition::cls_transition, get_cls_transition_emission(), hmm_trainer_model::trainer, and hmm_trainer_model::transition.
Referenced by hmm_trainer_model::backward(), hmm_trainer_model::forward(), and hmm_trainer_model::viterbi().
log_float hmm_trainer_model::transition_prob (int tr) inline private
References hmm_trainer_transition::cls_transition, get_cls_transition_prob(), hmm_trainer_model::trainer, and hmm_trainer_model::transition.
Referenced by hmm_trainer_model::backward(), hmm_trainer_model::forward(), and hmm_trainer_model::viterbi().
log_float hmm_trainer_model::viterbi (const MatrixFloat * emission, bool emission_in_log_base, bool do_expectation, MatrixFloat * reest_emission, MatrixFloat * seq_reest_emission, MatrixFloat * state_probabilities, char ** output_str, float count_value)
References acum_cls_emission, acum_tran_prob(), apriori_cls_emission, Matrix< T >::begin(), hmm_trainer_transition::cls_transition, hmm_trainer_model::final_state, hmm_trainer_transition::from, log_double::from_double(), log_float::from_float(), Matrix< T >::getDimSize(), Matrix< T >::getNumDim(), hmm_trainer_model::initial_state, list_output::next, hmm_trainer_model::num_states, hmm_trainer_model::num_transitions, log_float::one(), hmm_trainer_transition::output, list_output::output, april_utils::swap(), hmm_trainer_transition::to, hmm_trainer_model::trainer, hmm_trainer_model::transition, hmm_trainer_model::transition_emission(), hmm_trainer_model::transition_prob(), log_float::zero(), and Matrix< T >::zeros().
hmm_trainer::~hmm_trainer ()
References acum_cls_emission, apriori_cls_emission, cls_state, and cls_transition.
hmm_trainer_model::~hmm_trainer_model ()
References DecRef, hmm_trainer_model::num_transitions, hmm_trainer_transition::output, hmm_trainer_model::trainer, and hmm_trainer_model::transition.