april-ann
Image
Imaging
Namespaces
namespace april_utils
Classes
struct FloatRGB
class Image< T >
Macros
#define _IMAGE_CC_
Typedefs
typedef Image< float > ImageFloat
typedef Image< FloatRGB > ImageFloatRGB
Functions
FloatRGB operator+ (FloatRGB x, FloatRGB y)
FloatRGB operator- (FloatRGB x, FloatRGB y)
FloatRGB operator* (FloatRGB x, FloatRGB y)
FloatRGB operator/ (FloatRGB x, FloatRGB y)
FloatRGB operator+ (FloatRGB x, float y)
FloatRGB operator- (FloatRGB x, float y)
FloatRGB operator* (FloatRGB x, float y)
FloatRGB operator/ (FloatRGB x, float y)
FloatRGB operator+ (float x, FloatRGB y)
FloatRGB operator- (float x, FloatRGB y)
FloatRGB operator* (float x, FloatRGB y)
FloatRGB operator/ (float x, FloatRGB y)
FloatRGB operator+= (FloatRGB x, FloatRGB y)
FloatRGB operator-= (FloatRGB x, FloatRGB y)
FloatRGB operator*= (FloatRGB x, FloatRGB y)
FloatRGB operator/= (FloatRGB x, FloatRGB y)
FloatRGB operator+= (FloatRGB x, float y)
FloatRGB operator-= (FloatRGB x, float y)
FloatRGB operator*= (FloatRGB x, float y)
FloatRGB operator/= (FloatRGB x, float y)
ImageFloat * RGB_to_grayscale (ImageFloatRGB *src)
ImageFloatRGB * grayscale_to_RGB (ImageFloat *src)
Image< T >::Image (Matrix< T > *mat)
Image< T >::Image (Matrix< T > *mat, int width, int height, int offset_w, int offset_h)
Image< T >::Image (Image &other)
Image< T >::Image (int width, int height, T value=T())
virtual Image< T >::~Image ()
Image< T > * Image< T >::crop (int width, int height, int offset_w, int offset_h) const
Image< T > * Image< T >::clone_subimage (int width, int height, int offset_w, int offset_h, T default_color) const
Image< T > * Image< T >::crop_with_padding (int width, int height, int offset_w, int offset_h, T default_color) const
Image< T > * Image< T >::clone () const
void Image< T >::projection_v (T *v) const
void Image< T >::projection_v (Matrix< T > **m) const
void Image< T >::projection_h (T *v) const
void Image< T >::projection_h (Matrix< T > **m) const
Image< T > * Image< T >::shear_h (double radians, T default_color) const
void Image< T >::shear_h_inplace (double radians, T default_color)
void Image< T >::min_bounding_box (float threshold, int *w, int *h, int *x, int *y) const
void Image< T >::copy (const Image< T > *src, int dst_x, int dst_y)
Image< T > * Image< T >::rotate90_cw () const
Image< T > * Image< T >::rotate90_ccw () const
Image< T > * Image< T >::invert_colors () const
Image< T > * Image< T >::remove_blank_columns () const
Image< T > * Image< T >::convolution5x5 (float *k, T default_color=T()) const
Image< T > * Image< T >::resize (int dst_width, int dst_height) const
void Image< T >::invert_affine_matrix (float c[6], float dest[6]) const
Image< T > * Image< T >::affine_transform (AffineTransform2D *trans, T default_value, int *offset_x=0, int *offset_y=0) const
Detailed Description
Macro Definition Documentation
#define _IMAGE_CC_
Typedef Documentation
typedef Image<float> ImageFloat
typedef Image<FloatRGB> ImageFloatRGB
Function Documentation
template<typename T > Image< T > * Image< T >::affine_transform (AffineTransform2D * trans, T default_value, int * offset_x = 0, int * offset_y = 0) const
Applies an affine transform given by the matrix
| c[0] c[1] c[2] | | c[3] c[4] c[5] | | 0 0 1 |
References Matrix< T >::data, april_utils::max(), and april_utils::min().
template<typename T > Image< T > * Image< T >::clone () const
References Matrix< T >::data.
template<typename T > Image< T > * Image< T >::clone_subimage (int width, int height, int offset_w, int offset_h, T default_color) const
template<typename T > Image< T > * Image< T >::convolution5x5 (float * k, T default_color = T()) const
Aplica un kernel de convolucion de 5x5 a la imagen. Devuelve el resultado en una imagen nueva. El kernel se organiza por filas:
             0  1  2  3  4
             5  6  7  8  9
            10 11 12 13 14
            15 16 17 18 19
            20 21 22 23 24
template<typename T > void Image< T >::copy (const Image< T > * src, int dst_x, int dst_y)
References Image< T >::height, and Image< T >::width.
template<typename T > Image< T > * Image< T >::crop (int width, int height, int offset_w, int offset_h) const
template<typename T > Image< T > * Image< T >::crop_with_padding (int width, int height, int offset_w, int offset_h, T default_color) const
ImageFloatRGB * grayscale_to_RGB (ImageFloat * src)
References Image< T >::height, and Image< T >::width.
template<typename T > Image< T >::Image (Matrix< T > * mat)
References IncRef.
template<typename T > Image< T >::Image (Matrix< T > * mat, int width, int height, int offset_w, int offset_h)
References IncRef.
template<typename T > Image< T >::Image (int width, int height, T value = T())
References Image< T >::height, IncRef, Image< T >::matrix, Image< T >::offset, and Image< T >::width.
template<typename T > Image< T >::Image (Image< T > & other)
References Image< T >::height, IncRef, Image< T >::matrix, Image< T >::offset, and Image< T >::width.
template<typename T> void Image< T >::invert_affine_matrix (float c[6], float dest[6]) const private
template<typename T > Image< T > * Image< T >::invert_colors () const
template<typename T > void Image< T >::min_bounding_box (float threshold, int * w, int * h, int * x, int * y) const
FloatRGB operator* (FloatRGB x, FloatRGB y)
References FloatRGB::b, FloatRGB::g, and FloatRGB::r.
FloatRGB operator* (FloatRGB x, float y)
FloatRGB operator* (float x, FloatRGB y)
FloatRGB operator*= (FloatRGB x, FloatRGB y)
FloatRGB operator*= (FloatRGB x, float y)
FloatRGB operator+ (FloatRGB x, FloatRGB y)
References FloatRGB::b, FloatRGB::g, and FloatRGB::r.
FloatRGB operator+ (FloatRGB x, float y)
FloatRGB operator+ (float x, FloatRGB y)
FloatRGB operator+= (FloatRGB x, FloatRGB y)
FloatRGB operator+= (FloatRGB x, float y)
FloatRGB operator- (FloatRGB x, FloatRGB y)
References FloatRGB::b, FloatRGB::g, and FloatRGB::r.
FloatRGB operator- (FloatRGB x, float y)
FloatRGB operator- (float x, FloatRGB y)
FloatRGB operator-= (FloatRGB x, FloatRGB y)
FloatRGB operator-= (FloatRGB x, float y)
FloatRGB operator/ (FloatRGB x, FloatRGB y)
References FloatRGB::b, FloatRGB::g, and FloatRGB::r.
FloatRGB operator/ (FloatRGB x, float y)
FloatRGB operator/ (float x, FloatRGB y)
FloatRGB operator/= (FloatRGB x, FloatRGB y)
FloatRGB operator/= (FloatRGB x, float y)
template<typename T > void Image< T >::projection_h (T * v) const
template<typename T > void Image< T >::projection_h (Matrix< T > ** m) const
template<typename T > void Image< T >::projection_v (T * v) const
template<typename T > void Image< T >::projection_v (Matrix< T > ** m) const
template<typename T > Image< T > * Image< T >::remove_blank_columns () const
template<typename T > Image< T > * Image< T >::resize (int dst_width, int dst_height) const
ImageFloat * RGB_to_grayscale (ImageFloatRGB * src)
References Image< T >::height, FloatRGB::to_grayscale(), and Image< T >::width.
template<typename T > Image< T > * Image< T >::rotate90_ccw () const
template<typename T > Image< T > * Image< T >::rotate90_cw () const
template<typename T > Image< T > * Image< T >::shear_h (double angle, T default_value) const
angle va en radianes
default_value es el color de los pixels nuevos que aparecen en las esquinas
    +-------+  +-------+
    |       |  |\       \
    |  OLD  |  | \  NEW  \
    |       |  |an\       \
    +-------+  |gle+-------+
References Matrix< T >::data.
template<typename T > void Image< T >::shear_h_inplace (double radians, T default_color)
template<typename T > Image< T >::~Image () virtual
References DecRef.