april-ann
Gzio
Misc
Macros
#define LUA_GZIOLIBNAME "gzio"
#define LUA_GZFILEHANDLE "gzFile"
#define IO_INPUT 1
#define IO_OUTPUT 2
#define topfile(L) ((gzFile *)luaL_checkudata(L, 1, LUA_GZFILEHANDLE))
#define GZIO_API LUA_API
#define LUA_GZIOLIBNAME "gzio"
Functions
static int pushresult (lua_State *L, int i, const char *filename)
static int pushgzresult (lua_State *L, gzFile f, int i, const char *filename)
static void fileerror (lua_State *L, int arg, const char *filename)
static int io_type (lua_State *L)
static gzFile tofile (lua_State *L)
static gzFile * newfile (lua_State *L)
static int io_pclose (lua_State *L)
static int io_fclose (lua_State *L)
static int aux_close (lua_State *L)
static int io_close (lua_State *L)
static int io_gc (lua_State *L)
static int io_tostring (lua_State *L)
static int io_open (lua_State *L)
static int io_popen (lua_State *L)
static int io_tmpfile (lua_State *L)
static gzFile getiofile (lua_State *L, int findex)
static int g_iofile (lua_State *L, int f, const char *mode)
static int io_input (lua_State *L)
static int io_output (lua_State *L)
static int io_readline (lua_State *L)
static void aux_lines (lua_State *L, int idx, int toclose)
static int f_lines (lua_State *L)
static int io_lines (lua_State *L)
static int read_number (lua_State *L, gzFile f)
static int test_eof (lua_State *L, gzFile f)
static int read_line (lua_State *L, gzFile f)
static int read_chars (lua_State *L, gzFile f, size_t n)
static int g_read (lua_State *L, gzFile f, int first)
static int io_read (lua_State *L)
static int f_read (lua_State *L)
static int g_write (lua_State *L, gzFile f, int arg)
static int io_write (lua_State *L)
static int f_write (lua_State *L)
static int f_seek (lua_State *L)
static int f_setvbuf (lua_State *L)
static int io_flush (lua_State *L)
static int f_flush (lua_State *L)
static void createmeta (lua_State *L)
static void createstdfile (lua_State *L, gzFile f, int k, const char *fname)
GZIO_API int luaopen_gzio (lua_State *L)
Variables
static const char *const fnames [] = {"input", "output"}
static const luaL_Reg iolib []
static const luaL_Reg flib []
Detailed Description
Macro Definition Documentation
#define GZIO_API LUA_API
#define IO_INPUT 1
Referenced by io_input(), io_lines(), io_read(), and luaopen_gzio().
#define IO_OUTPUT 2
Referenced by io_close(), io_flush(), io_output(), io_write(), and luaopen_gzio().
#define LUA_GZFILEHANDLE "gzFile"
Referenced by createmeta(), io_type(), and newfile().
#define LUA_GZIOLIBNAME "gzio"
#define LUA_GZIOLIBNAME "gzio"
Referenced by luaopen_gzio().
#define topfile (L) ((gzFile *)luaL_checkudata(L, 1, LUA_GZFILEHANDLE))
Referenced by io_fclose(), io_gc(), io_pclose(), io_tostring(), and tofile().
Function Documentation
static int aux_close (lua_State * L) static
Referenced by io_close(), io_gc(), and io_readline().
static void aux_lines (lua_State * L, int idx, int toclose) static
References io_readline().
Referenced by f_lines(), and io_lines().
static void createmeta (lua_State * L) static
References flib, and LUA_GZFILEHANDLE.
Referenced by luaopen_gzio().
static void createstdfile (lua_State * L, gzFile f, int k, const char * fname) static
References newfile().
Referenced by luaopen_gzio().
static int f_flush (lua_State * L) static
References pushresult(), and tofile().
static int f_lines (lua_State * L) static
References aux_lines(), and tofile().
Referenced by io_lines().
static int f_read (lua_State * L) static
References g_read(), and tofile().
static int f_seek (lua_State * L) static
References pushgzresult(), and tofile().
static int f_setvbuf (lua_State * L) static
References pushresult(), and tofile().
static int f_write (lua_State * L) static
References g_write(), and tofile().
static void fileerror (lua_State * L, int arg, const char * filename) static
Referenced by g_iofile(), and io_lines().
static int g_iofile (lua_State * L, int f, const char * mode) static
References fileerror(), newfile(), and tofile().
Referenced by io_input(), and io_output().
static int g_read (lua_State * L, gzFile f, int first) static
References pushresult(), read_chars(), read_line(), read_number(), and test_eof().
Referenced by f_read(), and io_read().
static int g_write (lua_State * L, gzFile f, int arg) static
References pushresult().
Referenced by f_write(), and io_write().
static gzFile getiofile (lua_State * L, int findex) static
References fnames.
Referenced by io_flush(), io_read(), and io_write().
static int io_close (lua_State * L) static
References aux_close(), IO_OUTPUT, and tofile().
static int io_fclose (lua_State * L) static
References pushresult(), and topfile.
Referenced by luaopen_gzio().
static int io_flush (lua_State * L) static
References getiofile(), IO_OUTPUT, and pushresult().
static int io_gc (lua_State * L) static
References aux_close(), and topfile.
static int io_input (lua_State * L) static
References g_iofile(), and IO_INPUT.
static int io_lines (lua_State * L) static
References aux_lines(), f_lines(), fileerror(), IO_INPUT, and newfile().
static int io_open (lua_State * L) static
References newfile(), and pushresult().
static int io_output (lua_State * L) static
References g_iofile(), and IO_OUTPUT.
static int io_pclose (lua_State * L) static
References pushresult(), and topfile.
Referenced by luaopen_gzio().
static int io_popen (lua_State * L) static
References newfile(), and pushresult().
static int io_read (lua_State * L) static
References g_read(), getiofile(), and IO_INPUT.
static int io_readline (lua_State * L) static
References aux_close(), and read_line().
Referenced by aux_lines().
static int io_tmpfile (lua_State * L) static
References newfile(), and pushresult().
static int io_tostring (lua_State * L) static
References topfile.
static int io_type (lua_State * L) static
References LUA_GZFILEHANDLE.
static int io_write (lua_State * L) static
References g_write(), getiofile(), and IO_OUTPUT.
GZIO_API int luaopen_gzio (lua_State * L)
References createmeta(), createstdfile(), io_fclose(), IO_INPUT, IO_OUTPUT, io_pclose(), iolib, and LUA_GZIOLIBNAME.
static gzFile* newfile (lua_State * L) static
References LUA_GZFILEHANDLE.
Referenced by createstdfile(), g_iofile(), io_lines(), io_open(), io_popen(), and io_tmpfile().
static int pushgzresult (lua_State * L, gzFile f, int i, const char * filename) static
Referenced by f_seek().
static int pushresult (lua_State * L, int i, const char * filename) static
Referenced by f_flush(), f_setvbuf(), g_read(), g_write(), io_fclose(), io_flush(), io_open(), io_pclose(), io_popen(), and io_tmpfile().
static int read_chars (lua_State * L, gzFile f, size_t n) static
Referenced by g_read().
static int read_line (lua_State * L, gzFile f) static
Referenced by g_read(), and io_readline().
static int read_number (lua_State * L, gzFile f) static
Referenced by g_read().
static int test_eof (lua_State * L, gzFile f) static
Referenced by g_read().
static gzFile tofile (lua_State * L) static
References topfile.
Referenced by f_flush(), f_lines(), f_read(), f_seek(), f_setvbuf(), f_write(), g_iofile(), and io_close().
Variable Documentation
const luaL_Reg flib[] static
Initial value:
= {
  {"close", io_close},
  {"flush", f_flush},
  {"lines", f_lines},
  {"read", f_read},
  {"seek", f_seek},
  {"setvbuf", f_setvbuf},
  {"write", f_write},
  {"__gc", io_gc},
  {"__tostring", io_tostring},
  {NULL, NULL}
}
Referenced by createmeta().
const char* const fnames[] = {"input", "output"} static
Referenced by getiofile().
const luaL_Reg iolib[] static
Initial value:
= {
  {"close", io_close},
  {"flush", io_flush},
  {"input", io_input},
  {"lines", io_lines},
  {"open", io_open},
  {"output", io_output},
  {"popen", io_popen},
  {"read", io_read},
  {"tmpfile", io_tmpfile},
  {"type", io_type},
  {"write", io_write},
  {NULL, NULL}
}
Referenced by luaopen_gzio().