april-ann
Math
Basics
Classes
class GPUMirroredMemoryBlock< T >
Macros
#define VECTOR_SSET(n, value, vec, step) catlas_sset((n), (value), (vec), (step))
#define VECTOR_DSET(n, value, vec, step) catlas_dset((n), (value), (vec), (step))
#define NEGATE_CBLAS_TRANSPOSE(trans) ((trans) == CblasNoTrans)?CblasTrans:CblasNoTrans
#define NEAR_ZERO 1e-6f
#define DERIVATIVE_SATURATION 17.0f
#define sigmoid(numerator, value) (numerator) / (expf(-(value))+1.0f)
#define logsigmoid(value) -log1pf(expf(-(value)))
#define getMatrixFlatIndex(x, lda, y) ((x)+(y)*(lda))
#define getMatrixIndex(x, lda, y) ((x)*(lda)+(y))
Typedefs
typedef GPUMirroredMemoryBlock
< float > FloatGPUMirroredMemoryBlock
typedef GPUMirroredMemoryBlock
< int > IntGPUMirroredMemoryBlock
Functions
void applyMask (FloatGPUMirroredMemoryBlock *units, FloatGPUMirroredMemoryBlock *mask, float mask_value, unsigned int size, unsigned int bunch_size, bool use_gpu)
void doApplyLogisticActivation (FloatGPUMirroredMemoryBlock *input_units, FloatGPUMirroredMemoryBlock *output_units, unsigned int size, unsigned int bunch_size, bool use_gpu)
void doMultiplyLogisticDerivatives (FloatGPUMirroredMemoryBlock *output_units, FloatGPUMirroredMemoryBlock *input_errors, FloatGPUMirroredMemoryBlock *output_errors, unsigned int size, unsigned int bunch_size, bool use_gpu)
void doApplyLogLogisticActivation (FloatGPUMirroredMemoryBlock *input_units, FloatGPUMirroredMemoryBlock *output_units, unsigned int size, unsigned int bunch_size, bool use_gpu)
void doMultiplyLogLogisticDerivatives (FloatGPUMirroredMemoryBlock *output_units, FloatGPUMirroredMemoryBlock *input_errors, FloatGPUMirroredMemoryBlock *output_errors, unsigned int size, unsigned int bunch_size, bool use_gpu)
void doApplyTanhActivation (FloatGPUMirroredMemoryBlock *input_units, FloatGPUMirroredMemoryBlock *output_units, unsigned int size, unsigned int bunch_size, bool use_gpu)
void doMultiplyTanhDerivatives (FloatGPUMirroredMemoryBlock *output_units, FloatGPUMirroredMemoryBlock *input_errors, FloatGPUMirroredMemoryBlock *output_errors, unsigned int size, unsigned int bunch_size, bool use_gpu)
void doApplySoftsignActivation (FloatGPUMirroredMemoryBlock *input_units, FloatGPUMirroredMemoryBlock *output_units, unsigned int size, unsigned int bunch_size, bool use_gpu)
void doMultiplySoftsignDerivatives (FloatGPUMirroredMemoryBlock *output_units, FloatGPUMirroredMemoryBlock *input_errors, FloatGPUMirroredMemoryBlock *output_errors, unsigned int size, unsigned int bunch_size, bool use_gpu)
void doApplySoftplusActivation (FloatGPUMirroredMemoryBlock *input_units, FloatGPUMirroredMemoryBlock *output_units, unsigned int size, unsigned int bunch_size, bool use_gpu)
void doMultiplySoftplusDerivatives (FloatGPUMirroredMemoryBlock *input_units, FloatGPUMirroredMemoryBlock *input_errors, FloatGPUMirroredMemoryBlock *output_errors, unsigned int size, unsigned int bunch_size, bool use_gpu)
void doApplyHardtanhActivation (FloatGPUMirroredMemoryBlock *input_units, FloatGPUMirroredMemoryBlock *output_units, unsigned int size, unsigned int bunch_size, bool use_gpu)
void doMultiplyHardtanhDerivatives (FloatGPUMirroredMemoryBlock *input_units, FloatGPUMirroredMemoryBlock *input_errors, FloatGPUMirroredMemoryBlock *output_errors, unsigned int size, unsigned int bunch_size, bool use_gpu)
void doApplySinActivation (FloatGPUMirroredMemoryBlock *input_units, FloatGPUMirroredMemoryBlock *output_units, unsigned int size, unsigned int bunch_size, bool use_gpu)
void doMultiplySinDerivatives (FloatGPUMirroredMemoryBlock *input_units, FloatGPUMirroredMemoryBlock *input_errors, FloatGPUMirroredMemoryBlock *output_errors, unsigned int size, unsigned int bunch_size, bool use_gpu)
void doApplySoftmaxActivation (FloatGPUMirroredMemoryBlock *input_units, FloatGPUMirroredMemoryBlock *output_units, FloatGPUMirroredMemoryBlock *minimums, FloatGPUMirroredMemoryBlock *maximums, FloatGPUMirroredMemoryBlock *sums, unsigned int size, unsigned int bunch_size, bool use_gpu)
void doApplyLogSoftmaxActivation (FloatGPUMirroredMemoryBlock *input_units, FloatGPUMirroredMemoryBlock *output_units, FloatGPUMirroredMemoryBlock *minimums, FloatGPUMirroredMemoryBlock *maximums, FloatGPUMirroredMemoryBlock *sums, unsigned int size, unsigned int bunch_size, bool use_gpu)
float doMSELossFunction (FloatGPUMirroredMemoryBlock *input, FloatGPUMirroredMemoryBlock *target, float zero_epsilon_distance, unsigned int size, unsigned int bunch_size, bool use_gpu)
void doComputeMSEGradient (FloatGPUMirroredMemoryBlock *input, FloatGPUMirroredMemoryBlock *target, FloatGPUMirroredMemoryBlock *error_output, float zero_epsilon_distance, unsigned int size, unsigned int bunch_size, bool use_gpu)
float doMAELossFunction (FloatGPUMirroredMemoryBlock *input, FloatGPUMirroredMemoryBlock *target, float zero_epsilon_distance, unsigned int size, unsigned int bunch_size, bool use_gpu)
void doComputeMAEGradient (FloatGPUMirroredMemoryBlock *input, FloatGPUMirroredMemoryBlock *target, FloatGPUMirroredMemoryBlock *error_output, float zero_epsilon_distance, unsigned int size, unsigned int bunch_size, bool use_gpu)
float doCrossEntropyLossFunction (FloatGPUMirroredMemoryBlock *input, FloatGPUMirroredMemoryBlock *target, float epsilon, unsigned int size, unsigned int bunch_size, bool use_gpu)
float doMultiClassCrossEntropyLossFunction (FloatGPUMirroredMemoryBlock *input, FloatGPUMirroredMemoryBlock *target, float epsilon, unsigned int size, unsigned int bunch_size, bool use_gpu)
void doComputeCrossEntropyGradient (FloatGPUMirroredMemoryBlock *input, FloatGPUMirroredMemoryBlock *target, FloatGPUMirroredMemoryBlock *error_output, float epsilon, unsigned int size, unsigned int bunch_size, bool use_gpu)
float doLocalFMeasureLossFunction (FloatGPUMirroredMemoryBlock *input, FloatGPUMirroredMemoryBlock *target, unsigned int size, unsigned int bunch_size, float beta, float &Gab, float &Hab, bool complement_output, bool use_gpu)
void doComputeLocalFMeasureGradient (FloatGPUMirroredMemoryBlock *target, FloatGPUMirroredMemoryBlock *output_error, unsigned int size, unsigned int bunch_size, float beta, float Gab, float Hab, bool complement_output, bool use_gpu)
void doSgemv (CBLAS_ORDER major_type, CBLAS_TRANSPOSE a_transpose, int m, int n, float alpha, FloatGPUMirroredMemoryBlock *a, unsigned int a_inc, FloatGPUMirroredMemoryBlock *x, unsigned int x_inc, float beta, FloatGPUMirroredMemoryBlock *y, unsigned int y_inc, unsigned int a_shift, unsigned int x_shift, unsigned int y_shift, bool use_gpu)
void doScopy (int N, const FloatGPUMirroredMemoryBlock *x, unsigned int x_shift, unsigned int x_inc, FloatGPUMirroredMemoryBlock *y, unsigned int y_shift, unsigned int y_inc, bool use_gpu)
void doScopyLoop (int N, FloatGPUMirroredMemoryBlock *x, unsigned int x_inc, FloatGPUMirroredMemoryBlock *y, unsigned int y_inc, unsigned int times, const unsigned int stride, bool use_gpu)
void doSaxpy (int N, float alpha, const FloatGPUMirroredMemoryBlock *x, unsigned int x_shift, unsigned int x_inc, FloatGPUMirroredMemoryBlock *y, unsigned int y_shift, unsigned int y_inc, bool use_gpu)
void doSaxpyLoop (int N, float alpha, FloatGPUMirroredMemoryBlock *x, unsigned int x_inc, unsigned int x_shift, FloatGPUMirroredMemoryBlock *y, unsigned int y_inc, unsigned int y_shift, unsigned int times, const unsigned int stride_x, const unsigned int stride_y, bool use_gpu)
void doSgemm (CBLAS_ORDER major_type, CBLAS_TRANSPOSE a_transpose, CBLAS_TRANSPOSE b_transpose, int m, int n, int k, float alpha, FloatGPUMirroredMemoryBlock *a, unsigned int a_inc, FloatGPUMirroredMemoryBlock *b, unsigned int b_inc, float beta, FloatGPUMirroredMemoryBlock *c, unsigned int c_inc, unsigned int a_shift, unsigned int b_shift, unsigned int c_shift, bool use_gpu)
void doSscal (unsigned int size, FloatGPUMirroredMemoryBlock *x, unsigned int inc, unsigned int shift, float alpha, bool use_gpu)
void doSger (CBLAS_ORDER major_type, unsigned int m, unsigned int n, float alpha, FloatGPUMirroredMemoryBlock *x, unsigned int x_shift, unsigned int x_inc, FloatGPUMirroredMemoryBlock *y, unsigned int y_shift, unsigned int y_inc, FloatGPUMirroredMemoryBlock *a, unsigned int a_shift, unsigned int a_inc, bool use_gpu)
float doSdot (unsigned int size, const FloatGPUMirroredMemoryBlock *x, unsigned int x_shift, unsigned int x_inc, const FloatGPUMirroredMemoryBlock *y, unsigned int y_shift, unsigned int y_inc, bool use_gpu)
float doSnrm2 (unsigned int n, const FloatGPUMirroredMemoryBlock *x, unsigned int inc, unsigned int shift, bool use_gpu)
void doSsbmv (CBLAS_ORDER major_type, CBLAS_UPLO uplo, int n, int k, float alpha, FloatGPUMirroredMemoryBlock *a, unsigned int a_lda, FloatGPUMirroredMemoryBlock *x, unsigned int x_inc, float beta, FloatGPUMirroredMemoryBlock *y, unsigned int y_inc, unsigned int a_shift, unsigned int x_shift, unsigned int y_shift, bool use_gpu)
void doClamp (unsigned int N, FloatGPUMirroredMemoryBlock *v, unsigned int stride, unsigned int shift, float lower, float upper, bool use_gpu)
void doFill (unsigned int N, FloatGPUMirroredMemoryBlock *v, unsigned int stride, unsigned int shift, float value, bool use_gpu)
float doSum (unsigned int N, const FloatGPUMirroredMemoryBlock *v, unsigned int stride, unsigned int shift, bool use_gpu)
void doScalarAdd (unsigned int N, FloatGPUMirroredMemoryBlock *v, unsigned int stride, unsigned int shift, float value, bool use_gpu)
bool doEquals (unsigned int N, const FloatGPUMirroredMemoryBlock *v1, const FloatGPUMirroredMemoryBlock *v2, unsigned int stride1, unsigned int stride2, unsigned int shift1, unsigned int shift2, float epsilon, bool use_gpu)
void doLog (unsigned int N, FloatGPUMirroredMemoryBlock *v, unsigned int stride, unsigned int shift, bool use_gpu)
void doLog1p (unsigned int N, FloatGPUMirroredMemoryBlock *v, unsigned int stride, unsigned int shift, bool use_gpu)
void doExp (unsigned int N, FloatGPUMirroredMemoryBlock *v, unsigned int stride, unsigned int shift, bool use_gpu)
void doSqrt (unsigned int N, FloatGPUMirroredMemoryBlock *v, unsigned int stride, unsigned int shift, bool use_gpu)
void doTanh (unsigned int N, FloatGPUMirroredMemoryBlock *v, unsigned int stride, unsigned int shift, bool use_gpu)
void doPow (unsigned int N, FloatGPUMirroredMemoryBlock *v, unsigned int stride, unsigned int shift, float value, bool use_gpu)
Variables
static april_utils::hash
< unsigned int,
april_utils::list< T * > > GPUMirroredMemoryBlock< T >::pool_lists
Detailed Description
Macro Definition Documentation
#define DERIVATIVE_SATURATION 17.0f
#define getMatrixFlatIndex (x, lda, y) ((x)+(y)*(lda))
#define getMatrixIndex (x, lda, y) ((x)*(lda)+(y))
#define logsigmoid (value) -log1pf(expf(-(value)))
#define NEAR_ZERO 1e-6f
Referenced by ANN::MultiClassCrossEntropyLossFunction::addLoss(), ANN::CrossEntropyLossFunction::addLoss(), ANN::MAELossFunction::computeGradient(), ANN::MultiClassCrossEntropyLossFunction::computeGradient(), and ANN::CrossEntropyLossFunction::computeGradient().
#define NEGATE_CBLAS_TRANSPOSE (trans) ((trans) == CblasNoTrans)?CblasTrans:CblasNoTrans
Referenced by ANN::DotProductANNComponent::doBackprop(), and ANN::DotProductANNComponent::doForward().
#define sigmoid (numerator, value) (numerator) / (expf(-(value))+1.0f)
#define VECTOR_DSET (n, value, vec, step) catlas_dset((n), (value), (vec), (step))
#define VECTOR_SSET (n, value, vec, step) catlas_sset((n), (value), (vec), (step))
Typedef Documentation
typedef GPUMirroredMemoryBlock<float> FloatGPUMirroredMemoryBlock
typedef GPUMirroredMemoryBlock<int> IntGPUMirroredMemoryBlock
Function Documentation
void applyMask (FloatGPUMirroredMemoryBlock * units, FloatGPUMirroredMemoryBlock * mask, float mask_value, unsigned int size, unsigned int bunch_size, bool use_gpu)
Referenced by ANN::ActivationFunctionANNComponent::doBackprop(), and ANN::ActivationFunctionANNComponent::doForward().
void doApplyHardtanhActivation (FloatGPUMirroredMemoryBlock * input_units, FloatGPUMirroredMemoryBlock * output_units, unsigned int size, unsigned int bunch_size, bool use_gpu)
Referenced by ANN::HardtanhActfANNComponent::applyActivation().
void doApplyLogisticActivation (FloatGPUMirroredMemoryBlock * input_units, FloatGPUMirroredMemoryBlock * output_units, unsigned int size, unsigned int bunch_size, bool use_gpu)
Referenced by ANN::LogisticActfANNComponent::applyActivation().
void doApplyLogLogisticActivation (FloatGPUMirroredMemoryBlock * input_units, FloatGPUMirroredMemoryBlock * output_units, unsigned int size, unsigned int bunch_size, bool use_gpu)
Referenced by ANN::LogLogisticActfANNComponent::applyActivation().
void doApplyLogSoftmaxActivation (FloatGPUMirroredMemoryBlock * input_units, FloatGPUMirroredMemoryBlock * output_units, FloatGPUMirroredMemoryBlock * minimums, FloatGPUMirroredMemoryBlock * maximums, FloatGPUMirroredMemoryBlock * sums, unsigned int size, unsigned int bunch_size, bool use_gpu)
Referenced by ANN::LogSoftmaxActfANNComponent::applyActivation().
void doApplySinActivation (FloatGPUMirroredMemoryBlock * input_units, FloatGPUMirroredMemoryBlock * output_units, unsigned int size, unsigned int bunch_size, bool use_gpu)
Referenced by ANN::SinActfANNComponent::applyActivation().
void doApplySoftmaxActivation (FloatGPUMirroredMemoryBlock * input_units, FloatGPUMirroredMemoryBlock * output_units, FloatGPUMirroredMemoryBlock * minimums, FloatGPUMirroredMemoryBlock * maximums, FloatGPUMirroredMemoryBlock * sums, unsigned int size, unsigned int bunch_size, bool use_gpu)
Referenced by ANN::SoftmaxActfANNComponent::applyActivation().
void doApplySoftplusActivation (FloatGPUMirroredMemoryBlock * input_units, FloatGPUMirroredMemoryBlock * output_units, unsigned int size, unsigned int bunch_size, bool use_gpu)
Referenced by ANN::SoftplusActfANNComponent::applyActivation().
void doApplySoftsignActivation (FloatGPUMirroredMemoryBlock * input_units, FloatGPUMirroredMemoryBlock * output_units, unsigned int size, unsigned int bunch_size, bool use_gpu)
Referenced by ANN::SoftsignActfANNComponent::applyActivation().
void doApplyTanhActivation (FloatGPUMirroredMemoryBlock * input_units, FloatGPUMirroredMemoryBlock * output_units, unsigned int size, unsigned int bunch_size, bool use_gpu)
Referenced by ANN::TanhActfANNComponent::applyActivation().
void doClamp (unsigned int N, FloatGPUMirroredMemoryBlock * v, unsigned int stride, unsigned int shift, float lower, float upper, bool use_gpu)
Referenced by clamp_functor::operator()().
void doComputeCrossEntropyGradient (FloatGPUMirroredMemoryBlock * input, FloatGPUMirroredMemoryBlock * target, FloatGPUMirroredMemoryBlock * error_output, float epsilon, unsigned int size, unsigned int bunch_size, bool use_gpu)
Referenced by ANN::MultiClassCrossEntropyLossFunction::computeGradient(), and ANN::CrossEntropyLossFunction::computeGradient().
void doComputeLocalFMeasureGradient (FloatGPUMirroredMemoryBlock * target, FloatGPUMirroredMemoryBlock * output_error, unsigned int size, unsigned int bunch_size, float beta, float Gab, float Hab, bool complement_output, bool use_gpu)
Referenced by ANN::LocalFMeasureLossFunction::computeGradient().
void doComputeMAEGradient (FloatGPUMirroredMemoryBlock * input, FloatGPUMirroredMemoryBlock * target, FloatGPUMirroredMemoryBlock * error_output, float zero_epsilon_distance, unsigned int size, unsigned int bunch_size, bool use_gpu)
Referenced by ANN::MAELossFunction::computeGradient().
void doComputeMSEGradient (FloatGPUMirroredMemoryBlock * input, FloatGPUMirroredMemoryBlock * target, FloatGPUMirroredMemoryBlock * error_output, float zero_epsilon_distance, unsigned int size, unsigned int bunch_size, bool use_gpu)
Referenced by ANN::MSELossFunction::computeGradient().
float doCrossEntropyLossFunction (FloatGPUMirroredMemoryBlock * input, FloatGPUMirroredMemoryBlock * target, float epsilon, unsigned int size, unsigned int bunch_size, bool use_gpu)
Referenced by ANN::CrossEntropyLossFunction::addLoss().
bool doEquals (unsigned int N, const FloatGPUMirroredMemoryBlock * v1, const FloatGPUMirroredMemoryBlock * v2, unsigned int stride1, unsigned int stride2, unsigned int shift1, unsigned int shift2, float epsilon, bool use_gpu)
Referenced by equals_functor::operator()().
void doExp (unsigned int N, FloatGPUMirroredMemoryBlock * v, unsigned int stride, unsigned int shift, bool use_gpu)
Referenced by Matrix< float >::exp().
void doFill (unsigned int N, FloatGPUMirroredMemoryBlock * v, unsigned int stride, unsigned int shift, float value, bool use_gpu)
Referenced by Matrix< float >::fill(), and TokenMemoryBlock::setToZero().
float doLocalFMeasureLossFunction (FloatGPUMirroredMemoryBlock * input, FloatGPUMirroredMemoryBlock * target, unsigned int size, unsigned int bunch_size, float beta, float & Gab, float & Hab, bool complement_output, bool use_gpu)
Referenced by ANN::LocalFMeasureLossFunction::addLoss().
void doLog (unsigned int N, FloatGPUMirroredMemoryBlock * v, unsigned int stride, unsigned int shift, bool use_gpu)
Referenced by Matrix< float >::log().
void doLog1p (unsigned int N, FloatGPUMirroredMemoryBlock * v, unsigned int stride, unsigned int shift, bool use_gpu)
Referenced by Matrix< float >::log1p().
float doMAELossFunction (FloatGPUMirroredMemoryBlock * input, FloatGPUMirroredMemoryBlock * target, float zero_epsilon_distance, unsigned int size, unsigned int bunch_size, bool use_gpu)
Referenced by ANN::MAELossFunction::addLoss().
float doMSELossFunction (FloatGPUMirroredMemoryBlock * input, FloatGPUMirroredMemoryBlock * target, float zero_epsilon_distance, unsigned int size, unsigned int bunch_size, bool use_gpu)
Referenced by ANN::MSELossFunction::addLoss().
float doMultiClassCrossEntropyLossFunction (FloatGPUMirroredMemoryBlock * input, FloatGPUMirroredMemoryBlock * target, float epsilon, unsigned int size, unsigned int bunch_size, bool use_gpu)
Referenced by ANN::MultiClassCrossEntropyLossFunction::addLoss().
void doMultiplyHardtanhDerivatives (FloatGPUMirroredMemoryBlock * input_units, FloatGPUMirroredMemoryBlock * input_errors, FloatGPUMirroredMemoryBlock * output_errors, unsigned int size, unsigned int bunch_size, bool use_gpu)
Referenced by ANN::HardtanhActfANNComponent::multiplyDerivatives().
void doMultiplyLogisticDerivatives (FloatGPUMirroredMemoryBlock * output_units, FloatGPUMirroredMemoryBlock * input_errors, FloatGPUMirroredMemoryBlock * output_errors, unsigned int size, unsigned int bunch_size, bool use_gpu)
Referenced by ANN::LogisticActfANNComponent::multiplyDerivatives(), and ANN::SoftmaxActfANNComponent::multiplyDerivatives().
void doMultiplyLogLogisticDerivatives (FloatGPUMirroredMemoryBlock * output_units, FloatGPUMirroredMemoryBlock * input_errors, FloatGPUMirroredMemoryBlock * output_errors, unsigned int size, unsigned int bunch_size, bool use_gpu)
void doMultiplySinDerivatives (FloatGPUMirroredMemoryBlock * input_units, FloatGPUMirroredMemoryBlock * input_errors, FloatGPUMirroredMemoryBlock * output_errors, unsigned int size, unsigned int bunch_size, bool use_gpu)
Referenced by ANN::SinActfANNComponent::multiplyDerivatives().
void doMultiplySoftplusDerivatives (FloatGPUMirroredMemoryBlock * input_units, FloatGPUMirroredMemoryBlock * input_errors, FloatGPUMirroredMemoryBlock * output_errors, unsigned int size, unsigned int bunch_size, bool use_gpu)
Referenced by ANN::SoftplusActfANNComponent::multiplyDerivatives().
void doMultiplySoftsignDerivatives (FloatGPUMirroredMemoryBlock * output_units, FloatGPUMirroredMemoryBlock * input_errors, FloatGPUMirroredMemoryBlock * output_errors, unsigned int size, unsigned int bunch_size, bool use_gpu)
Referenced by ANN::SoftsignActfANNComponent::multiplyDerivatives().
void doMultiplyTanhDerivatives (FloatGPUMirroredMemoryBlock * output_units, FloatGPUMirroredMemoryBlock * input_errors, FloatGPUMirroredMemoryBlock * output_errors, unsigned int size, unsigned int bunch_size, bool use_gpu)
Referenced by ANN::TanhActfANNComponent::multiplyDerivatives().
void doPow (unsigned int N, FloatGPUMirroredMemoryBlock * v, unsigned int stride, unsigned int shift, float value, bool use_gpu)
Referenced by Matrix< float >::pow().
void doSaxpy (int N, float alpha, const FloatGPUMirroredMemoryBlock * x, unsigned int x_shift, unsigned int x_inc, FloatGPUMirroredMemoryBlock * y, unsigned int y_shift, unsigned int y_inc, bool use_gpu)
Referenced by axpy_functor::operator()().
void doSaxpyLoop (int N, float alpha, FloatGPUMirroredMemoryBlock * x, unsigned int x_inc, unsigned int x_shift, FloatGPUMirroredMemoryBlock * y, unsigned int y_inc, unsigned int y_shift, unsigned int times, const unsigned int stride_x, const unsigned int stride_y, bool use_gpu)
Referenced by ANN::BiasANNComponent::computeBP(), ANN::ConvolutionBiasANNComponent::computeBP(), and ANN::BiasANNComponent::doForward().
void doScalarAdd (unsigned int N, FloatGPUMirroredMemoryBlock * v, unsigned int stride, unsigned int shift, float value, bool use_gpu)
Referenced by Matrix< float >::scalarAdd().
void doScopy (int N, const FloatGPUMirroredMemoryBlock * x, unsigned int x_shift, unsigned int x_inc, FloatGPUMirroredMemoryBlock * y, unsigned int y_shift, unsigned int y_inc, bool use_gpu)
Referenced by ANN::LinearActfANNComponent::applyActivation(), TokenMemoryBlock::clone(), ANN::LinearActfANNComponent::multiplyDerivatives(), ANN::LogSoftmaxActfANNComponent::multiplyDerivatives(), ANN::LogLogisticActfANNComponent::multiplyDerivatives(), and copy_functor::operator()().
void doScopyLoop (int N, FloatGPUMirroredMemoryBlock * x, unsigned int x_inc, FloatGPUMirroredMemoryBlock * y, unsigned int y_inc, unsigned int times, const unsigned int stride, bool use_gpu)
float doSdot (unsigned int size, const FloatGPUMirroredMemoryBlock * x, unsigned int x_shift, unsigned int x_inc, const FloatGPUMirroredMemoryBlock * y, unsigned int y_shift, unsigned int y_inc, bool use_gpu)
Referenced by Matrix< float >::dot().
void doSgemm (CBLAS_ORDER major_type, CBLAS_TRANSPOSE a_transpose, CBLAS_TRANSPOSE b_transpose, int m, int n, int k, float alpha, FloatGPUMirroredMemoryBlock * a, unsigned int a_inc, FloatGPUMirroredMemoryBlock * b, unsigned int b_inc, float beta, FloatGPUMirroredMemoryBlock * c, unsigned int c_inc, unsigned int a_shift, unsigned int b_shift, unsigned int c_shift, bool use_gpu)
Referenced by Matrix< float >::gemm().
void doSgemv (CBLAS_ORDER major_type, CBLAS_TRANSPOSE a_transpose, int m, int n, float alpha, FloatGPUMirroredMemoryBlock * a, unsigned int a_inc, FloatGPUMirroredMemoryBlock * x, unsigned int x_inc, float beta, FloatGPUMirroredMemoryBlock * y, unsigned int y_inc, unsigned int a_shift, unsigned int x_shift, unsigned int y_shift, bool use_gpu)
Referenced by Matrix< float >::gemv().
void doSger (CBLAS_ORDER major_type, unsigned int m, unsigned int n, float alpha, FloatGPUMirroredMemoryBlock * x, unsigned int x_shift, unsigned int x_inc, FloatGPUMirroredMemoryBlock * y, unsigned int y_shift, unsigned int y_inc, FloatGPUMirroredMemoryBlock * a, unsigned int a_shift, unsigned int a_inc, bool use_gpu)
Referenced by Matrix< float >::ger().
float doSnrm2 (unsigned int n, const FloatGPUMirroredMemoryBlock * x, unsigned int inc, unsigned int shift, bool use_gpu)
Referenced by Matrix< float >::norm2(), and norm2_functor::operator()().
void doSqrt (unsigned int N, FloatGPUMirroredMemoryBlock * v, unsigned int stride, unsigned int shift, bool use_gpu)
Referenced by Matrix< float >::sqrt().
void doSsbmv (CBLAS_ORDER major_type, CBLAS_UPLO uplo, int n, int k, float alpha, FloatGPUMirroredMemoryBlock * a, unsigned int a_lda, FloatGPUMirroredMemoryBlock * x, unsigned int x_inc, float beta, FloatGPUMirroredMemoryBlock * y, unsigned int y_inc, unsigned int a_shift, unsigned int x_shift, unsigned int y_shift, bool use_gpu)
Referenced by Matrix< float >::cmul().
void doSscal (unsigned int size, FloatGPUMirroredMemoryBlock * x, unsigned int inc, unsigned int shift, float alpha, bool use_gpu)
Referenced by Matrix< float >::scal().
float doSum (unsigned int N, const FloatGPUMirroredMemoryBlock * v, unsigned int stride, unsigned int shift, bool use_gpu)
Referenced by sum_functor::operator()().
void doTanh (unsigned int N, FloatGPUMirroredMemoryBlock * v, unsigned int stride, unsigned int shift, bool use_gpu)
Referenced by Matrix< float >::tanh().
Variable Documentation
template<typename T> april_utils::hash< unsigned int, april_utils::list< T * > > GPUMirroredMemoryBlock< T >::pool_lists static private
Referenced by GPUMirroredMemoryBlock< float >::GPUMirroredMemoryBlock(), GPUMirroredMemoryBlock< float >::~GPUMirroredMemoryBlock(), and GPUMirroredMemoryBlock< T >::PoolFreeBeforeExit::~PoolFreeBeforeExit().