april-ann
Matrix
Basics
Namespaces
namespace april_utils
Classes
class Matrix< T >
struct clamp_functor
struct sum_functor
struct equals_functor
struct copy_functor
struct axpy_functor
struct norm2_functor
struct norm2_reductor
class component_wise_functor_0< MATRIX, Func >
class component_wise_functor_1< MATRIX, Func >
Macros
#define DEFAULT_N_TH 100
#define DEFAULT_SIZE_TH 100
#define DEFAULT_CONTIGUOUS_TH 200
Typedefs
typedef Matrix< float > MatrixFloat
Functions
template<typename Func >
component_wise_functor_0
< MatrixFloat, Func > make_cwise_functor_0 (Func f)
This make class is needed to do type inference in template classes.
template<typename Func >
component_wise_functor_0
< const MatrixFloat, Func > make_const_cwise_functor_0 (Func f)
template<typename Func >
component_wise_functor_1
< MatrixFloat, Func > make_cwise_functor_1 (float v, Func f)
This make class is needed to do type inference in template classes.
template<typename Func >
component_wise_functor_1
< const MatrixFloat, Func > make_const_cwise_functor_1 (float v, Func f)
template<typename FUNC , typename MATRIX >
void applyFunctionWithSpanIterator (MATRIX *m, const FUNC &functor, const int N_th=DEFAULT_N_TH, const unsigned int SIZE_th=DEFAULT_SIZE_TH, const unsigned int CONTIGUOUS_th=DEFAULT_CONTIGUOUS_TH)
template<typename FUNC , typename MATRIX1 , typename MATRIX2 >
void applyBinaryFunctionWithSpanIterator (MATRIX1 *m1, MATRIX2 *m2, const FUNC &functor, const int N_th=DEFAULT_N_TH, const unsigned int SIZE_th=DEFAULT_SIZE_TH, const unsigned int CONTIGUOUS_th=DEFAULT_CONTIGUOUS_TH)
template<typename FUNC , typename MATRIX >
float applySumReductionWithSpanIterator (MATRIX *m, const FUNC &functor, const int N_th=DEFAULT_N_TH, const unsigned int SIZE_th=DEFAULT_SIZE_TH, const unsigned int CONTIGUOUS_th=DEFAULT_CONTIGUOUS_TH)
template<typename FUNC , typename MATRIX1 , typename MATRIX2 >
bool applyBinaryAndReductionWithSpanIterator (MATRIX1 *m1, MATRIX2 *m2, const FUNC &functor, const int N_th=DEFAULT_N_TH, const unsigned int SIZE_th=DEFAULT_SIZE_TH, const unsigned int CONTIGUOUS_th=DEFAULT_CONTIGUOUS_TH)
template<typename T , typename MATRIX , typename FUNC1 , typename FUNC2 >
T applyReductionWithSpanIteratorNOPARALLEL (MATRIX *m, FUNC1 &functor, FUNC2 &reductor, const T initial_value)
template<typename FUNC , typename MATRIX >
void applyFunctionWithSpanIteratorNOPARALLEL (MATRIX *m, const FUNC &functor)
template<typename FUNC , typename MATRIX1 , typename MATRIX2 >
void applyBinaryFunctionWithSpanIteratorNOPARALLEL (MATRIX1 *m1, MATRIX2 *m2, const FUNC &functor)
template<typename T >
MatrixFloat * readMatrixFloatFromStream (T &stream)
void saveMatrixFloatToFile (MatrixFloat *mat, FILE *f, bool is_ascii)
int saveMatrixFloatToString (MatrixFloat *mat, char **buffer, bool is_ascii)
int hexdigit (char c)
MatrixFloat * readMatrixFloatHEX (int width, int height, constString cs)
MatrixFloat * readMatrixFloatPNM (constString cs, bool forcecolor, bool forcegray)
int saveMatrixFloatPNM (MatrixFloat *mat, char **buffer)
int saveMatrixFloatHEX (MatrixFloat *mat, char **buffer, int *width, int *height)
template MatrixFloat * readMatrixFloatFromStream< constString > (constString &stream)
template MatrixFloat * readMatrixFloatFromStream< ReadFileStream > (ReadFileStream &stream)
Matrix< T >::iterator::iterator (Matrix< T > *m)
Matrix< T >::iterator::iterator (Matrix< T > *m, int raw_pos)
Matrix< T >::iterator::iterator (Matrix< T > *m, int raw_pos, int *coords)
Matrix< T >::iterator::iterator ()
Matrix< T >::iterator::iterator (const iterator &other)
Matrix< T >::iterator::~iterator ()
iterator & Matrix< T >::iterator::operator= (const iterator &other)
bool Matrix< T >::iterator::operator== (const iterator &other) const
bool Matrix< T >::iterator::operator!= (const iterator &other) const
iterator & Matrix< T >::iterator::operator++ ()
T & Matrix< T >::iterator::operator* ()
int Matrix< T >::iterator::getRawPos () const
Matrix< T >::col_major_iterator::col_major_iterator (Matrix< T > *m)
Matrix< T >::col_major_iterator::col_major_iterator (Matrix< T > *m, int raw_pos)
Matrix< T >::col_major_iterator::col_major_iterator (Matrix< T > *m, int raw_pos, int *coords)
Matrix< T >::col_major_iterator::col_major_iterator ()
Matrix< T >::col_major_iterator::col_major_iterator (const col_major_iterator &other)
Matrix< T >::col_major_iterator::col_major_iterator (const iterator &other)
Matrix< T >::col_major_iterator::~col_major_iterator ()
col_major_iterator & Matrix< T >::col_major_iterator::operator++ ()
T & Matrix< T >::col_major_iterator::operator* ()
int Matrix< T >::col_major_iterator::getRawPos () const
Matrix< T >::const_iterator::const_iterator (const Matrix< T > *m)
Matrix< T >::const_iterator::const_iterator (const Matrix< T > *m, int raw_pos)
Matrix< T >::const_iterator::const_iterator (const Matrix< T > *m, int raw_pos, int *coords)
Matrix< T >::const_iterator::const_iterator ()
Matrix< T >::const_iterator::~const_iterator ()
const_iterator & Matrix< T >::const_iterator::operator++ ()
const T & Matrix< T >::const_iterator::operator* () const
int Matrix< T >::const_iterator::getRawPos () const
Matrix< T >::const_col_major_iterator::const_col_major_iterator (const Matrix< T > *m)
Matrix< T >::const_col_major_iterator::const_col_major_iterator (const Matrix< T > *m, int raw_pos)
Matrix< T >::const_col_major_iterator::const_col_major_iterator (const Matrix< T > *m, int raw_pos, int *coords)
Matrix< T >::const_col_major_iterator::const_col_major_iterator ()
Matrix< T >::const_col_major_iterator::~const_col_major_iterator ()
const_col_major_iterator & Matrix< T >::const_col_major_iterator::operator++ ()
const T & Matrix< T >::const_col_major_iterator::operator* () const
int Matrix< T >::const_col_major_iterator::getRawPos () const
Matrix< T >::best_span_iterator::best_span_iterator (const Matrix< T > *m, int raw_pos)
Matrix< T >::best_span_iterator::best_span_iterator (const Matrix< T > *m)
Matrix< T >::best_span_iterator::best_span_iterator (const best_span_iterator &other)
Matrix< T >::best_span_iterator::best_span_iterator ()
Matrix< T >::best_span_iterator::~best_span_iterator ()
int Matrix< T >::best_span_iterator::getOffset () const
int Matrix< T >::best_span_iterator::getStride () const
int Matrix< T >::best_span_iterator::getSize () const
best_span_iterator & Matrix< T >::best_span_iterator::operator= (const best_span_iterator &other)
bool Matrix< T >::best_span_iterator::operator== (const best_span_iterator &other) const
bool Matrix< T >::best_span_iterator::operator!= (const best_span_iterator &other) const
best_span_iterator & Matrix< T >::best_span_iterator::operator++ ()
int Matrix< T >::best_span_iterator::numberOfIterations () const
void Matrix< T >::best_span_iterator::setAtIteration (int idx)
Matrix< T >::sliding_window::sliding_window ()
Matrix< T >::sliding_window::sliding_window (Matrix< T > *m, const int *sub_matrix_size=0, const int *offset=0, const int *step=0, const int *num_steps=0, const int *order_step=0)
Matrix< T >::sliding_window::sliding_window (const sliding_window &other)
Matrix< T >::sliding_window::~sliding_window ()
sliding_window & Matrix< T >::sliding_window::operator= (const sliding_window &other)
sliding_window * Matrix< T >::sliding_window::next ()
Matrix< T > * Matrix< T >::sliding_window::getMatrix (bool clone=false)
int Matrix< T >::sliding_window::numWindows () const
void Matrix< T >::sliding_window::setAtWindow (int windex)
const int * Matrix< T >::sliding_window::getCoords () const
int Matrix< T >::sliding_window::getNumDim () const
void Matrix< T >::fill (T value)
void Matrix< T >::clamp (T lower, T upper)
void Matrix< T >::zeros ()
void Matrix< T >::ones ()
void Matrix< T >::diag (T value)
Matrix< T > * Matrix< T >::addition (const Matrix< T > *other)
Matrix< T > * Matrix< T >::substraction (const Matrix< T > *other)
Matrix< T > * Matrix< T >::multiply (const Matrix< T > *other) const
T Matrix< T >::sum () const
void Matrix< T >::scalarAdd (T s)
bool Matrix< T >::equals (const Matrix< T > *other, T epsilon) const
void Matrix< T >::log ()
void Matrix< T >::log1p ()
void Matrix< T >::exp ()
void Matrix< T >::sqrt ()
void Matrix< T >::pow (T value)
void Matrix< T >::tanh ()
Matrix< T > * Matrix< T >::cmul (const Matrix< T > *other)
void Matrix< T >::copy (const Matrix< T > *other)
void Matrix< T >::axpy (T alpha, const Matrix< T > *other)
void Matrix< T >::gemm (CBLAS_TRANSPOSE trans_A, CBLAS_TRANSPOSE trans_B, T alpha, const Matrix< T > *otherA, const Matrix< T > *otherB, T beta)
void Matrix< T >::gemv (CBLAS_TRANSPOSE trans_A, T alpha, const Matrix< T > *otherA, const Matrix< T > *otherX, T beta)
void Matrix< T >::ger (T alpha, const Matrix< T > *otherX, const Matrix< T > *otherY)
T Matrix< T >::dot (const Matrix< T > *other) const
void Matrix< T >::scal (T value)
T Matrix< T >::norm2 () const
T Matrix< T >::min (int &arg_min, int &arg_min_raw_pos) const
T Matrix< T >::max (int &arg_max, int &arg_max_raw_pos) const
void Matrix< T >::minAndMax (T &min, T &max) const
Matrix< T > * Matrix< T >::maxSelDim (const int dim, IntGPUMirroredMemoryBlock *raw_positions=0, int shift=0) const
void Matrix< T >::adjustRange (T rmin, T rmax)
void Matrix< T >::initialize (const int *dim)
void Matrix< T >::allocate_memory (int size)
Allocation of memory for data pointer. It is Referenced for sharing.
void Matrix< T >::release_memory ()
Release of the memory allocated for data pointer.
Matrix< T >::Matrix (int numDim, const int *stride, const int offset, const int *matrixSize, const int total_size, const int last_raw_pos, GPUMirroredMemoryBlock< T > *data, const CBLAS_ORDER major_order, const bool use_cuda)
Null constructor.
Matrix< T >::Matrix (int numDim, const int *dim, CBLAS_ORDER major_order=CblasRowMajor, GPUMirroredMemoryBlock< T > *data=0, int offset=0)
Full constructor given numDim, dim, and major_order.
Matrix< T >::Matrix (Matrix< T > *other, const int *coords, const int *sizes, bool clone=true)
Sub-matrix constructor.
Matrix< T >::Matrix (int numDim, int d1,...)
Constructor with T() values and CblasRowMajor order.
Matrix< T >::Matrix (Matrix< T > *other, bool clone=true)
Constructor for copy or clone other given matrix.
virtual Matrix< T >::~Matrix ()
Destructor.
Matrix< T > * Matrix< T >::rewrap (const int *new_dims, int len)
Modify sizes of matrix.
Matrix< T > * Matrix< T >::transpose () const
Transposition.
Matrix< T > * Matrix< T >::cloneOnlyDims () const
Copy only sizes, but not data.
Matrix< T > * Matrix< T >::clone (CBLAS_ORDER major_order)
Deep copy with different major_order.
Matrix< T > * Matrix< T >::clone ()
Deep copy.
Matrix< T > * Matrix< T >::shallow_copy ()
Shallow copy.
T & Matrix< T >::operator[] (int i)
Raw access operator [].
const T & Matrix< T >::operator[] (int i) const
T & Matrix< T >::operator() (int i)
T & Matrix< T >::operator() (int row, int col)
T & Matrix< T >::operator() (int coord0, int coord1, int coord2,...)
T & Matrix< T >::operator() (int *coords, int sz)
const T & Matrix< T >::operator() (int i) const
const T & Matrix< T >::operator() (int row, int col) const
const T & Matrix< T >::operator() (int coord0, int coord1, int coord2,...) const
const T & Matrix< T >::operator() (int *coords, int sz) const
bool Matrix< T >::getCol (int col, T *vec, int vecsize)
bool Matrix< T >::putCol (int col, T *vec, int vecsize)
bool Matrix< T >::putSubCol (int col, int first_row, T *vec, int vecsize)
bool Matrix< T >::sameDim (const Matrix< T > *other) const
Matrix< T > * Matrix< T >::select (int dim, int index)
bool Matrix< T >::nextCoordVectorRowOrder (int *coords, int &raw_pos) const
Updates with the following coordinates vector.
bool Matrix< T >::nextCoordVectorColOrder (int *coords, int &raw_pos) const
static bool Matrix< T >::nextCoordVectorRowOrder (int *coords, int &raw_pos, const int *sizes, const int *strides, const int numDim, const int last_raw_pos)
static bool Matrix< T >::nextCoordVectorColOrder (int *coords, int &raw_pos, const int *sizes, const int *strides, const int numDim, const int last_raw_pos)
bool Matrix< T >::nextCoordVectorRowOrder (int *coords) const
bool Matrix< T >::nextCoordVectorColOrder (int *coords) const
static bool Matrix< T >::nextCoordVectorRowOrder (int *coords, const int *sizes, const int numDim)
static bool Matrix< T >::nextCoordVectorColOrder (int *coords, const int *sizes, const int numDim)
int Matrix< T >::computeRawPos (const int *coords) const
Computes the position at data array given it coordinates.
void Matrix< T >::computeCoords (const int raw_pos, int *coords) const
Computes the coordinates given the raw data position.
bool Matrix< T >::getIsContiguous () const
Indicates if it is a contiguous matrix.
void Matrix< float >::fill (floatvalue)
void Matrix< float >::clamp (floatlower, floatupper)
void Matrix< float >::zeros ()
void Matrix< float >::ones ()
void Matrix< float >::diag (floatvalue)
Matrix< float > * Matrix< float >::addition (const Matrix< float > *other)
Matrix< float > * Matrix< float >::substraction (const Matrix< float > *other)
Matrix< float > * Matrix< float >::multiply (const Matrix< float > *other) const
float Matrix< float >::sum () const
void Matrix< float >::scalarAdd (floats)
bool Matrix< float >::equals (const Matrix< float > *other, floatepsilon) const
void Matrix< float >::log ()
void Matrix< float >::log1p ()
void Matrix< float >::exp ()
void Matrix< float >::sqrt ()
void Matrix< float >::pow (floatvalue)
void Matrix< float >::tanh ()
Matrix< float > * Matrix< float >::cmul (const Matrix< float > *other)
void Matrix< float >::copy (const Matrix< float > *other)
void Matrix< float >::axpy (floatalpha, const Matrix< float > *other)
void Matrix< float >::gemm (CBLAS_TRANSPOSE trans_A, CBLAS_TRANSPOSE trans_B, floatalpha, const Matrix< float > *otherA, const Matrix< float > *otherB, floatbeta)
void Matrix< float >::gemv (CBLAS_TRANSPOSE trans_A, floatalpha, const Matrix< float > *otherA, const Matrix< float > *otherX, floatbeta)
void Matrix< float >::ger (floatalpha, const Matrix< float > *otherX, const Matrix< float > *otherY)
float Matrix< float >::dot (const Matrix< float > *other) const
void Matrix< float >::scal (floatvalue)
float Matrix< float >::norm2 () const
float Matrix< float >::min (int &arg_min, int &arg_min_raw_pos) const
float Matrix< float >::max (int &arg_max, int &arg_max_raw_pos) const
void Matrix< float >::minAndMax (float &min, float &max) const
Matrix< float > * Matrix< float >::maxSelDim (const int dim, IntGPUMirroredMemoryBlock *raw_positions=0, int shift=0) const
void Matrix< float >::adjustRange (floatrmin, floatrmax)
Variables
const float CTENEGRO = 1.0f
const float CTEBLANCO = 0.0f
Detailed Description
Macro Definition Documentation
#define DEFAULT_CONTIGUOUS_TH 200
#define DEFAULT_N_TH 100
#define DEFAULT_SIZE_TH 100
Typedef Documentation
typedef Matrix<float> MatrixFloat
Function Documentation
template<typename T> Matrix< T > * Matrix< T >::addition (const Matrix< T > * other)
References ERROR_EXIT.
Matrix< float > * Matrix< float >::addition (const Matrix< float > * other)
References Matrix< T >::axpy(), and Matrix< T >::clone().
void Matrix< float >::adjustRange (floatrmin , floatrmax)
References Matrix< T >::fill(), Matrix< T >::minAndMax(), Matrix< T >::scal(), and Matrix< T >::scalarAdd().
template<typename T> void Matrix< T >::adjustRange (T rmin, T rmax)
References ERROR_EXIT.
template<typename T > void Matrix< T >::allocate_memory (int size) private
Allocation of memory for data pointer. It is Referenced for sharing.
References IncRef.
Referenced by Matrix< T >::Matrix().
template<typename FUNC , typename MATRIX1 , typename MATRIX2 > bool applyBinaryAndReductionWithSpanIterator (MATRIX1 * m1, MATRIX2 * m2, const FUNC & functor, const int N_th = DEFAULT_N_TH, const unsigned int SIZE_th = DEFAULT_SIZE_TH, const unsigned int CONTIGUOUS_th = DEFAULT_CONTIGUOUS_TH)
References omp_utils::get_num_threads().
Referenced by Matrix< float >::equals().
template<typename FUNC , typename MATRIX1 , typename MATRIX2 > void applyBinaryFunctionWithSpanIterator (MATRIX1 * m1, MATRIX2 * m2, const FUNC & functor, const int N_th = DEFAULT_N_TH, const unsigned int SIZE_th = DEFAULT_SIZE_TH, const unsigned int CONTIGUOUS_th = DEFAULT_CONTIGUOUS_TH)
References omp_utils::get_num_threads().
Referenced by Matrix< float >::axpy(), and Matrix< float >::copy().
template<typename FUNC , typename MATRIX1 , typename MATRIX2 > void applyBinaryFunctionWithSpanIteratorNOPARALLEL (MATRIX1 * m1, MATRIX2 * m2, const FUNC & functor)
Referenced by Matrix< float >::axpy().
template<typename FUNC , typename MATRIX > void applyFunctionWithSpanIterator (MATRIX * m, const FUNC & functor, const int N_th = DEFAULT_N_TH, const unsigned int SIZE_th = DEFAULT_SIZE_TH, const unsigned int CONTIGUOUS_th = DEFAULT_CONTIGUOUS_TH)
References omp_utils::get_num_threads().
Referenced by Matrix< float >::clamp(), Matrix< float >::exp(), Matrix< float >::fill(), Matrix< float >::log(), Matrix< float >::log1p(), Matrix< float >::pow(), Matrix< float >::scal(), Matrix< float >::scalarAdd(), Matrix< float >::sqrt(), and Matrix< float >::tanh().
template<typename FUNC , typename MATRIX > void applyFunctionWithSpanIteratorNOPARALLEL (MATRIX * m, const FUNC & functor)
Referenced by Matrix< float >::scal().
template<typename T , typename MATRIX , typename FUNC1 , typename FUNC2 > T applyReductionWithSpanIteratorNOPARALLEL (MATRIX * m, FUNC1 & functor, FUNC2 & reductor, const T initial_value)
Referenced by Matrix< float >::norm2().
template<typename FUNC , typename MATRIX > float applySumReductionWithSpanIterator (MATRIX * m, const FUNC & functor, const int N_th = DEFAULT_N_TH, const unsigned int SIZE_th = DEFAULT_SIZE_TH, const unsigned int CONTIGUOUS_th = DEFAULT_CONTIGUOUS_TH)
References omp_utils::get_num_threads().
Referenced by Matrix< float >::sum().
void Matrix< float >::axpy (floatalpha , const Matrix< float > * other)
References applyBinaryFunctionWithSpanIterator(), applyBinaryFunctionWithSpanIteratorNOPARALLEL(), ERROR_EXIT, ERROR_EXIT2, Matrix< T >::major_order, and Matrix< T >::size().
template<typename T> void Matrix< T >::axpy (T alpha, const Matrix< T > * other)
References ERROR_EXIT.
Referenced by Matrix< float >::addition(), ANN::BiasANNComponent::computeBP(), ANN::DotProductANNComponent::computeBP(), ANN::Connections::computeMomentumOnPrevVector(), ANN::Connections::computeWeightDecayOnPrevVector(), ANN::CopyANNComponent::doBackprop(), ANN::GaussianNoiseANNComponent::doForward(), ANN::BiasANNComponent::doForward(), ANN::DotProductANNComponent::doForward(), ANN::ConvolutionBiasANNComponent::doForward(), and Matrix< float >::substraction().
template<typename T> Matrix< T >::best_span_iterator::best_span_iterator (const Matrix< T > * m, int raw_pos) private
References Matrix< T >::computeCoords(), Matrix< T >::best_span_iterator::coords, Matrix< T >::major_order, Matrix< T >::matrixSize, Matrix< T >::best_span_iterator::num_iterations, Matrix< T >::numDim, Matrix< T >::best_span_iterator::order, and april_utils::Sort().
template<typename T> Matrix< T >::best_span_iterator::best_span_iterator (const Matrix< T > * m)
References Matrix< T >::best_span_iterator::coords, Matrix< T >::major_order, Matrix< T >::matrixSize, Matrix< T >::best_span_iterator::num_iterations, Matrix< T >::numDim, Matrix< T >::best_span_iterator::order, and april_utils::Sort().
template<typename T> Matrix< T >::best_span_iterator::best_span_iterator ()
template<typename T> Matrix< T >::best_span_iterator::best_span_iterator (const best_span_iterator & other)
References Matrix< T >::best_span_iterator::coords, Matrix< T >::best_span_iterator::m, and Matrix< T >::best_span_iterator::order.
void Matrix< float >::clamp (floatlower , floatupper)
References applyFunctionWithSpanIterator().
template<typename T> void Matrix< T >::clamp (T lower, T upper)
References april_utils::clamp(), Matrix< T >::best_span_iterator::getOffset(), Matrix< T >::best_span_iterator::getSize(), and Matrix< T >::best_span_iterator::getStride().
template<typename T > Matrix< T > * Matrix< T >::clone ()
Deep copy.
Referenced by Matrix< float >::addition(), ANN::FlattenANNComponent::doBackprop(), ANN::RewrapANNComponent::doBackprop(), ANN::ActivationFunctionANNComponent::doBackprop(), ANN::DotProductANNComponent::doBackprop(), ANN::RewrapANNComponent::doForward(), ANN::SelectANNComponent::doForward(), ANN::FlattenANNComponent::doForward(), ANN::BiasANNComponent::doForward(), ANN::ActivationFunctionANNComponent::doForward(), ANN::ConvolutionBiasANNComponent::doForward(), ANN::MaxPoolingANNComponent::doForward(), ANN::MaxPoolingANNComponent::getRewrappedMatrix(), ANN::ConvolutionANNComponent::getRewrappedMatrix(), and Matrix< float >::substraction().
template<typename T > Matrix< T > * Matrix< T >::clone (CBLAS_ORDER major_order)
Deep copy with different major_order.
References Matrix< T >::begin(), Matrix< T >::end(), and Matrix< T >::setUseCuda().
template<typename T > Matrix< T > * Matrix< T >::cloneOnlyDims () const
Copy only sizes, but not data.
References Matrix< T >::setUseCuda().
Referenced by ANN::MAELossFunction::computeGradient(), ANN::MSELossFunction::computeGradient(), ANN::MultiClassCrossEntropyLossFunction::computeGradient(), ANN::CrossEntropyLossFunction::computeGradient(), ANN::LocalFMeasureLossFunction::computeGradient(), ANN::BiasANNComponent::computeGradients(), ANN::DotProductANNComponent::computeGradients(), ANN::ConvolutionBiasANNComponent::computeGradients(), ANN::ConvolutionANNComponent::computeGradients(), ANN::ActivationFunctionANNComponent::doBackprop(), ANN::GaussianNoiseANNComponent::doForward(), ANN::ActivationFunctionANNComponent::doForward(), and ANN::ConvolutionANNComponent::getRewrappedMatrix().
Matrix< float > * Matrix< float >::cmul (const Matrix< float > * other)
References Matrix< T >::data, doSsbmv(), ERROR_EXIT, ERROR_EXIT2, Matrix< T >::getIsContiguous(), Matrix< T >::major_order, Matrix< T >::Matrix(), Matrix< T >::offset, Matrix< T >::sameDim(), Matrix< T >::setUseCuda(), Matrix< T >::size(), Matrix< T >::total_size, and Matrix< T >::use_cuda.
template<typename T> Matrix< T > * Matrix< T >::cmul (const Matrix< T > * other)
References ERROR_EXIT.
template<typename T> Matrix< T >::col_major_iterator::col_major_iterator (Matrix< T > * m) private
References Matrix< T >::col_major_iterator::coords, Matrix< T >::col_major_iterator::data, Matrix< T >::getData(), Matrix< T >::getIsContiguous(), Matrix< T >::getMajorOrder(), Matrix< T >::getNumDim(), Matrix< T >::getOffset(), and Matrix< T >::col_major_iterator::raw_pos.
template<typename T> Matrix< T >::col_major_iterator::col_major_iterator (Matrix< T > * m, int raw_pos) private
References Matrix< T >::computeCoords(), Matrix< T >::col_major_iterator::coords, Matrix< T >::col_major_iterator::data, Matrix< T >::getData(), Matrix< T >::getIsContiguous(), Matrix< T >::getMajorOrder(), and Matrix< T >::getNumDim().
template<typename T> Matrix< T >::col_major_iterator::col_major_iterator (Matrix< T > * m, int raw_pos, int * coords) private
References Matrix< T >::col_major_iterator::data, Matrix< T >::getData(), Matrix< T >::getIsContiguous(), Matrix< T >::getMajorOrder(), and Matrix< T >::getNumDim().
template<typename T> Matrix< T >::col_major_iterator::col_major_iterator ()
template<typename T> Matrix< T >::col_major_iterator::col_major_iterator (const col_major_iterator & other)
References Matrix< T >::col_major_iterator::coords, Matrix< T >::col_major_iterator::data, and Matrix< T >::col_major_iterator::m.
template<typename T> Matrix< T >::col_major_iterator::col_major_iterator (const iterator & other)
References Matrix< T >::iterator::coords, Matrix< T >::col_major_iterator::coords, Matrix< T >::col_major_iterator::data, Matrix< T >::col_major_iterator::m, and Matrix< T >::col_major_iterator::raw_pos.
template<typename T > void Matrix< T >::computeCoords (const int raw_pos, int * coords) const
Computes the coordinates given the raw data position.
Referenced by Matrix< T >::best_span_iterator::best_span_iterator(), Matrix< T >::col_major_iterator::col_major_iterator(), Matrix< T >::const_col_major_iterator::const_col_major_iterator(), Matrix< T >::const_iterator::const_iterator(), and Matrix< T >::iterator::iterator().
template<typename T > int Matrix< T >::computeRawPos (const int * coords) const
Computes the position at data array given it coordinates.
Referenced by Matrix< float >::diag(), Matrix< float >::iteratorAt(), and Matrix< T >::Matrix().
template<typename T> Matrix< T >::const_col_major_iterator::const_col_major_iterator (const Matrix< T > * m) private
References Matrix< T >::const_col_major_iterator::coords, Matrix< T >::const_col_major_iterator::data, Matrix< T >::getData(), Matrix< T >::getIsContiguous(), Matrix< T >::getMajorOrder(), Matrix< T >::getNumDim(), Matrix< T >::getOffset(), and Matrix< T >::const_col_major_iterator::raw_pos.
template<typename T> Matrix< T >::const_col_major_iterator::const_col_major_iterator (const Matrix< T > * m, int raw_pos) private
References Matrix< T >::computeCoords(), Matrix< T >::const_col_major_iterator::coords, Matrix< T >::const_col_major_iterator::data, Matrix< T >::getData(), Matrix< T >::getIsContiguous(), Matrix< T >::getMajorOrder(), and Matrix< T >::getNumDim().
template<typename T> Matrix< T >::const_col_major_iterator::const_col_major_iterator (const Matrix< T > * m, int raw_pos, int * coords) private
References Matrix< T >::const_col_major_iterator::data, Matrix< T >::getData(), Matrix< T >::getIsContiguous(), Matrix< T >::getMajorOrder(), and Matrix< T >::getNumDim().
template<typename T> Matrix< T >::const_col_major_iterator::const_col_major_iterator ()
template<typename T> Matrix< T >::const_iterator::const_iterator (const Matrix< T > * m) private
References Matrix< T >::const_iterator::coords, Matrix< T >::const_iterator::data, Matrix< T >::getData(), Matrix< T >::getIsContiguous(), Matrix< T >::getMajorOrder(), Matrix< T >::getNumDim(), Matrix< T >::getOffset(), and Matrix< T >::const_iterator::raw_pos.
template<typename T> Matrix< T >::const_iterator::const_iterator (const Matrix< T > * m, int raw_pos) private
References Matrix< T >::computeCoords(), Matrix< T >::const_iterator::coords, Matrix< T >::const_iterator::data, Matrix< T >::getData(), Matrix< T >::getIsContiguous(), Matrix< T >::getMajorOrder(), and Matrix< T >::getNumDim().
template<typename T> Matrix< T >::const_iterator::const_iterator (const Matrix< T > * m, int raw_pos, int * coords) private
References Matrix< T >::const_iterator::data, Matrix< T >::getData(), Matrix< T >::getIsContiguous(), Matrix< T >::getMajorOrder(), and Matrix< T >::getNumDim().
template<typename T> Matrix< T >::const_iterator::const_iterator ()
void Matrix< float >::copy (const Matrix< float > * other)
References applyBinaryFunctionWithSpanIterator(), ERROR_EXIT, ERROR_EXIT2, Matrix< T >::major_order, Matrix< T >::sameDim(), Matrix< T >::size(), and Matrix< T >::use_cuda.
template<typename T> void Matrix< T >::copy (const Matrix< T > * other)
References ERROR_EXIT.
Referenced by ANN::JoinANNComponent::buildMatrixFloatToken(), Image< T >::clone_subimage(), ANN::Connections::Connections(), ANN::Connections::copyToPrevVector(), ANN::SelectANNComponent::doBackprop(), ANN::CopyANNComponent::doBackprop(), ANN::ConvolutionANNComponent::doBackprop(), ANN::MaxPoolingANNComponent::doForward(), ANN::ConvolutionANNComponent::doForward(), DataSetToken::getPatternBunch(), DataSetFloat2TokenWrapper::getPatternBunch(), Matrix< T >::Matrix(), ANN::ConvolutionBiasANNComponent::prepareBiasBunch(), and DataSetFloat2TokenWrapper::putPatternBunch().
void Matrix< float >::diag (floatvalue)
References Matrix< T >::computeRawPos(), Matrix< T >::data, ERROR_EXIT, Matrix< T >::matrixSize, Matrix< T >::numDim, and Matrix< T >::use_cuda.
template<typename T> void Matrix< T >::diag (T value)
References ERROR_EXIT.
float Matrix< float >::dot (const Matrix< float > * other) const
References Matrix< T >::data, doSdot(), ERROR_EXIT, ERROR_EXIT2, Matrix< T >::getVectorSize(), Matrix< T >::getVectorStride(), Matrix< T >::isVector(), Matrix< T >::major_order, Matrix< T >::offset, and Matrix< T >::use_cuda.
template<typename T> T Matrix< T >::dot (const Matrix< T > * other) const
References ERROR_EXIT.
Referenced by Matrix< float >::multiply().
bool Matrix< float >::equals (const Matrix< float > * other, floatepsilon) const
References applyBinaryAndReductionWithSpanIterator(), and Matrix< T >::sameDim().
template<typename T> bool Matrix< T >::equals (const Matrix< T > * other, T epsilon) const
References ERROR_EXIT.
void Matrix< float >::exp ()
References applyFunctionWithSpanIterator(), doExp(), and make_cwise_functor_0().
template<typename T > void Matrix< T >::exp ()
References ERROR_EXIT.
void Matrix< float >::fill (floatvalue)
References applyFunctionWithSpanIterator(), doFill(), and make_cwise_functor_1().
template<typename T> void Matrix< T >::fill (T value)
Referenced by Matrix< float >::adjustRange(), Matrix< float >::ones(), LibPNG::readPNG(), and Matrix< float >::zeros().
void Matrix< float >::gemm (CBLAS_TRANSPOSE trans_A, CBLAS_TRANSPOSE trans_B, floatalpha , const Matrix< float > * otherA, const Matrix< float > * otherB, floatbeta)
References Matrix< T >::data, doSgemm(), ERROR_EXIT, ERROR_EXIT6, Matrix< T >::major_order, Matrix< T >::matrixSize, Matrix< T >::numDim, Matrix< T >::offset, Matrix< T >::stride, april_utils::swap(), and Matrix< T >::use_cuda.
template<typename T> void Matrix< T >::gemm (CBLAS_TRANSPOSE trans_A, CBLAS_TRANSPOSE trans_B, T alpha, const Matrix< T > * otherA, const Matrix< T > * otherB, T beta)
References ERROR_EXIT.
Referenced by ANN::DotProductANNComponent::computeBP(), ANN::ConvolutionANNComponent::computeBP(), ANN::DotProductANNComponent::doBackprop(), ANN::ConvolutionANNComponent::doBackprop(), ANN::DotProductANNComponent::doForward(), ANN::ConvolutionANNComponent::doForward(), and Matrix< float >::multiply().
void Matrix< float >::gemv (CBLAS_TRANSPOSE trans_A, floatalpha , const Matrix< float > * otherA, const Matrix< float > * otherX, floatbeta)
References Matrix< T >::data, doSgemv(), ERROR_EXIT, ERROR_EXIT4, Matrix< T >::getVectorSize(), Matrix< T >::getVectorStride(), Matrix< T >::isVector(), Matrix< T >::major_order, Matrix< T >::matrixSize, Matrix< T >::numDim, Matrix< T >::offset, Matrix< T >::stride, april_utils::swap(), and Matrix< T >::use_cuda.
template<typename T> void Matrix< T >::gemv (CBLAS_TRANSPOSE trans_A, T alpha, const Matrix< T > * otherA, const Matrix< T > * otherX, T beta)
References ERROR_EXIT.
Referenced by ANN::DotProductANNComponent::doBackprop(), ANN::DotProductANNComponent::doForward(), and Matrix< float >::multiply().
void Matrix< float >::ger (floatalpha , const Matrix< float > * otherX, const Matrix< float > * otherY)
References Matrix< T >::data, doSger(), ERROR_EXIT, ERROR_EXIT4, Matrix< T >::getVectorSize(), Matrix< T >::getVectorStride(), Matrix< T >::isVector(), Matrix< T >::major_order, Matrix< T >::matrixSize, Matrix< T >::numDim, Matrix< T >::offset, Matrix< T >::stride, and Matrix< T >::use_cuda.
template<typename T> void Matrix< T >::ger (T alpha, const Matrix< T > * otherX, const Matrix< T > * otherY)
References ERROR_EXIT.
Referenced by ANN::DotProductANNComponent::computeBP(), and Matrix< float >::multiply().
template<typename T> bool Matrix< T >::getCol (int col, T * vec, int vecsize)
template<typename T > const int * Matrix< T >::sliding_window::getCoords () const
template<typename T > bool Matrix< T >::getIsContiguous () const
Indicates if it is a contiguous matrix.
Referenced by Matrix< float >::cmul(), Matrix< T >::col_major_iterator::col_major_iterator(), Matrix< T >::const_col_major_iterator::const_col_major_iterator(), Matrix< T >::const_iterator::const_iterator(), ANN::RewrapANNComponent::doBackprop(), ANN::FlattenANNComponent::doBackprop(), ANN::ActivationFunctionANNComponent::doBackprop(), ANN::RewrapANNComponent::doForward(), ANN::FlattenANNComponent::doForward(), ANN::ActivationFunctionANNComponent::doForward(), ANN::MaxPoolingANNComponent::doForward(), ANN::MaxPoolingANNComponent::getRewrappedMatrix(), ANN::ConvolutionANNComponent::getRewrappedMatrix(), Matrix< float >::isSimple(), Matrix< T >::iterator::iterator(), Matrix< float >::norm2(), and ANN::LossFunction::throwErrorAndGetMatrixFromTokens().
template<typename T > Matrix< T > * Matrix< T >::sliding_window::getMatrix (bool clone = false)
References ERROR_EXIT, Matrix< T >::last_raw_pos, and Matrix< T >::total_size.
template<typename T > int Matrix< T >::sliding_window::getNumDim () const
template<typename T > int Matrix< T >::best_span_iterator::getOffset () const
Referenced by Matrix< T >::clamp().
template<typename T > int Matrix< T >::iterator::getRawPos () const
template<typename T > int Matrix< T >::col_major_iterator::getRawPos () const
template<typename T > int Matrix< T >::const_iterator::getRawPos () const
template<typename T > int Matrix< T >::const_col_major_iterator::getRawPos () const
template<typename T > int Matrix< T >::best_span_iterator::getSize () const
Referenced by Matrix< T >::clamp().
template<typename T > int Matrix< T >::best_span_iterator::getStride () const
Referenced by Matrix< T >::clamp().
int hexdigit (char c) inline
Referenced by readMatrixFloatHEX().
template<typename T > void Matrix< T >::initialize (const int * dim) private
References ERROR_EXIT.
Referenced by Matrix< T >::Matrix().
template<typename T> Matrix< T >::iterator::iterator (Matrix< T > * m) private
References Matrix< T >::iterator::coords, Matrix< T >::iterator::data, Matrix< T >::getData(), Matrix< T >::getIsContiguous(), Matrix< T >::getMajorOrder(), Matrix< T >::getNumDim(), Matrix< T >::getOffset(), and Matrix< T >::iterator::raw_pos.
template<typename T> Matrix< T >::iterator::iterator (Matrix< T > * m, int raw_pos) private
References Matrix< T >::computeCoords(), Matrix< T >::iterator::coords, Matrix< T >::iterator::data, Matrix< T >::getData(), Matrix< T >::getIsContiguous(), Matrix< T >::getMajorOrder(), and Matrix< T >::getNumDim().
template<typename T> Matrix< T >::iterator::iterator (Matrix< T > * m, int raw_pos, int * coords) private
References Matrix< T >::iterator::data, Matrix< T >::getData(), Matrix< T >::getIsContiguous(), Matrix< T >::getMajorOrder(), and Matrix< T >::getNumDim().
template<typename T> Matrix< T >::iterator::iterator ()
template<typename T> Matrix< T >::iterator::iterator (const iterator & other)
References Matrix< T >::iterator::coords, Matrix< T >::iterator::data, and Matrix< T >::iterator::m.
void Matrix< float >::log ()
References applyFunctionWithSpanIterator(), doLog(), and make_cwise_functor_0().
template<typename T > void Matrix< T >::log ()
References ERROR_EXIT.
void Matrix< float >::log1p ()
References applyFunctionWithSpanIterator(), doLog1p(), and make_cwise_functor_0().
template<typename T > void Matrix< T >::log1p ()
References ERROR_EXIT.
template<typename Func > component_wise_functor_0<const MatrixFloat,Func> make_const_cwise_functor_0 (Func f)
template<typename Func > component_wise_functor_1<const MatrixFloat,Func> make_const_cwise_functor_1 (float v, Func f)
template<typename Func > component_wise_functor_0<MatrixFloat,Func> make_cwise_functor_0 (Func f)
This make class is needed to do type inference in template classes.
Referenced by Matrix< float >::exp(), Matrix< float >::log(), Matrix< float >::log1p(), Matrix< float >::sqrt(), and Matrix< float >::tanh().
template<typename Func > component_wise_functor_1<MatrixFloat,Func> make_cwise_functor_1 (float v, Func f)
This make class is needed to do type inference in template classes.
Referenced by Matrix< float >::fill(), Matrix< float >::pow(), Matrix< float >::scal(), and Matrix< float >::scalarAdd().
template<typename T> Matrix< T >::Matrix (int numDim, const int * stride, const int offset, const int * matrixSize, const int total_size, const int last_raw_pos, GPUMirroredMemoryBlock< T > * data, const CBLAS_ORDER major_order, const bool use_cuda) private
Null constructor.
References IncRef, and Matrix< T >::numDim.
template<typename T> Matrix< T >::Matrix (int numDim, const int * dim, CBLAS_ORDER major_order = CblasRowMajor, GPUMirroredMemoryBlock< T > * data = 0, int offset = 0)
Full constructor given numDim, dim, and major_order.
Default constructor.
References Matrix< T >::allocate_memory(), Matrix< T >::data, ERROR_EXIT2, GPUMirroredMemoryBlock< T >::getSize(), IncRef, Matrix< T >::initialize(), Matrix< T >::matrixSize, Matrix< T >::numDim, Matrix< T >::size(), Matrix< T >::stride, and Matrix< T >::total_size.
template<typename T> Matrix< T >::Matrix (int numDim, int d1, ...)
Constructor with T() values and CblasRowMajor order.
Constructor with variable arguments.
References Matrix< T >::allocate_memory(), Matrix< T >::initialize(), Matrix< T >::matrixSize, Matrix< T >::numDim, Matrix< T >::stride, and Matrix< T >::total_size.
template<typename T> Matrix< T >::Matrix (Matrix< T > * other, bool clone = true)
Constructor for copy or clone other given matrix.
Constructor given other matrix, it does a shallow or deep copy (clone). By default is a deep copy, some code pieces expect this behavior, don't change it.
References Matrix< T >::allocate_memory(), Matrix< T >::CONTIGUOUS, Matrix< T >::copy(), Matrix< T >::data, IncRef, Matrix< T >::initialize(), Matrix< T >::is_contiguous, Matrix< T >::last_raw_pos, Matrix< T >::matrixSize, Matrix< T >::numDim, Matrix< T >::offset, Matrix< T >::stride, and Matrix< T >::total_size.
template<typename T> Matrix< T >::Matrix (Matrix< T > * other, const int * coords, const int * sizes, bool clone = true)
Sub-matrix constructor.
Constructor for sub-matrix building.
References Matrix< T >::allocate_memory(), Matrix< T >::begin(), Matrix< T >::computeRawPos(), Matrix< T >::CONTIGUOUS, Matrix< T >::data, Matrix< T >::end(), ERROR_EXIT3, IncRef, Matrix< T >::initialize(), Matrix< T >::is_contiguous, Matrix< T >::last_raw_pos, Matrix< T >::major_order, Matrix< T >::matrixSize, Matrix< T >::nextCoordVectorColOrder(), Matrix< T >::nextCoordVectorRowOrder(), Matrix< T >::numDim, Matrix< T >::offset, Matrix< T >::stride, and Matrix< T >::total_size.
float Matrix< float >::max (int & arg_max, int & arg_max_raw_pos) const
References april_utils::argmax(), Matrix< T >::begin(), and Matrix< T >::end().
template<typename T > T Matrix< T >::max (int & arg_max, int & arg_max_raw_pos) const
References ERROR_EXIT.
Referenced by Matrix< float >::maxSelDim().
Matrix< float > * Matrix< float >::maxSelDim (const int dim, IntGPUMirroredMemoryBlock * raw_positions = 0, int shift = 0) const
References april_utils::argmax(), Matrix< T >::data, ERROR_EXIT, ERROR_EXIT2, GPUMirroredMemoryBlock< T >::getPPALForWrite(), Matrix< T >::getRawDataAccess(), Matrix< T >::major_order, Matrix< T >::matrixSize, Matrix< T >::max(), Matrix< T >::numDim, Matrix< T >::offset, Matrix< T >::select(), Matrix< T >::setUseCuda(), Matrix< T >::stride, april_utils::swap(), and Matrix< T >::use_cuda.
template<typename T > Matrix< T > * Matrix< T >::maxSelDim (const int dim, IntGPUMirroredMemoryBlock * raw_positions = 0, int shift = 0) const
References ERROR_EXIT.
Referenced by ANN::MaxPoolingANNComponent::doForward().
float Matrix< float >::min (int & arg_min, int & arg_min_raw_pos) const
References april_utils::argmin(), Matrix< T >::begin(), and Matrix< T >::end().
template<typename T > T Matrix< T >::min (int & arg_min, int & arg_min_raw_pos) const
References ERROR_EXIT.
template<typename T> void Matrix< T >::minAndMax (T & min, T & max) const
References ERROR_EXIT.
Referenced by Matrix< float >::adjustRange().
void Matrix< float >::minAndMax (float & min, float & max) const
References Matrix< T >::begin(), Matrix< T >::end(), and Matrix< T >::major_order.
Matrix< float > * Matrix< float >::multiply (const Matrix< float > * other) const
References Matrix< T >::dot(), Matrix< T >::gemm(), Matrix< T >::gemv(), Matrix< T >::ger(), Matrix< T >::getVectorSize(), Matrix< T >::isColVector(), Matrix< T >::isVector(), Matrix< T >::major_order, Matrix< T >::matrixSize, Matrix< T >::numDim, Matrix< T >::setUseCuda(), Matrix< T >::use_cuda, and Matrix< T >::zeros().
template<typename T> Matrix< T > * Matrix< T >::multiply (const Matrix< T > * other) const
References ERROR_EXIT.
Referenced by AffineTransform2D::accumulate().
template<typename T > Matrix< T >::sliding_window::sliding_window * Matrix< T >::sliding_window::next ()
References Matrix< T >::numDim, and Matrix< T >::offset.
template<typename T > bool Matrix< T >::nextCoordVectorColOrder (int * coords, int & raw_pos) const
Referenced by Matrix< T >::Matrix().
template<typename T > bool Matrix< T >::nextCoordVectorColOrder (int * coords) const
template<typename T > bool Matrix< T >::nextCoordVectorColOrder (int * coords, const int * sizes, const int numDim) static
template<typename T > bool Matrix< T >::nextCoordVectorColOrder (int * coords, int & raw_pos, const int * sizes, const int * strides, const int numDim, const int last_raw_pos) static
template<typename T > bool Matrix< T >::nextCoordVectorRowOrder (int * coords, int & raw_pos) const
Updates with the following coordinates vector.
Referenced by Matrix< T >::Matrix().
template<typename T > bool Matrix< T >::nextCoordVectorRowOrder (int * coords) const
template<typename T > bool Matrix< T >::nextCoordVectorRowOrder (int * coords, const int * sizes, const int numDim) static
template<typename T > bool Matrix< T >::nextCoordVectorRowOrder (int * coords, int & raw_pos, const int * sizes, const int * strides, const int numDim, const int last_raw_pos) static
float Matrix< float >::norm2 () const
References applyReductionWithSpanIteratorNOPARALLEL(), Matrix< T >::data, doSnrm2(), Matrix< T >::getIsContiguous(), Matrix< T >::numDim, Matrix< T >::offset, Matrix< T >::stride, Matrix< T >::total_size, and Matrix< T >::use_cuda.
template<typename T > T Matrix< T >::norm2 () const
References ERROR_EXIT.
Referenced by ANN::Connections::applyMaxNormPenalty().
template<typename T > int Matrix< T >::best_span_iterator::numberOfIterations () const
template<typename T > int Matrix< T >::sliding_window::numWindows () const
void Matrix< float >::ones ()
References Matrix< T >::fill().
template<typename T > void Matrix< T >::ones ()
References ERROR_EXIT.
template<typename T> bool Matrix< T >::iterator::operator!= (const iterator & other) const
template<typename T> bool Matrix< T >::best_span_iterator::operator!= (const best_span_iterator & other) const
template<typename T > T & Matrix< T >::operator() (int i)
template<typename T > T & Matrix< T >::operator() (int row, int col)
template<typename T > T & Matrix< T >::operator() (int coord0, int coord1, int coord2, ...)
template<typename T > T & Matrix< T >::operator() (int * coords, int sz)
template<typename T > const T & Matrix< T >::operator() (int i) const
template<typename T > const T & Matrix< T >::operator() (int row, int col) const
template<typename T > const T & Matrix< T >::operator() (int coord0, int coord1, int coord2, ...) const
template<typename T > const T & Matrix< T >::operator() (int * coords, int sz) const
template<typename T > T & Matrix< T >::iterator::operator* ()
References Matrix< T >::data.
template<typename T > T & Matrix< T >::col_major_iterator::operator* ()
References Matrix< T >::data.
template<typename T > const T & Matrix< T >::const_iterator::operator* () const
References Matrix< T >::data.
template<typename T > const T & Matrix< T >::const_col_major_iterator::operator* () const
References Matrix< T >::data.
template<typename T > Matrix< T >::iterator & Matrix< T >::iterator::operator++ ()
template<typename T > Matrix< T >::col_major_iterator & Matrix< T >::col_major_iterator::operator++ ()
template<typename T > Matrix< T >::const_iterator & Matrix< T >::const_iterator::operator++ ()
template<typename T > Matrix< T >::const_col_major_iterator & Matrix< T >::const_col_major_iterator::operator++ ()
template<typename T > Matrix< T >::best_span_iterator & Matrix< T >::best_span_iterator::operator++ ()
References Matrix< T >::numDim.
template<typename T> Matrix< T >::iterator & Matrix< T >::iterator::operator= (const iterator & other)
References Matrix< T >::iterator::coords, Matrix< T >::data, Matrix< T >::iterator::idx, Matrix< T >::iterator::m, and Matrix< T >::iterator::raw_pos.
template<typename T > Matrix< T >::sliding_window::sliding_window & Matrix< T >::sliding_window::operator= (const sliding_window & other)
References Matrix< T >::sliding_window::coords, DecRef, Matrix< T >::sliding_window::finished, IncRef, Matrix< T >::last_raw_pos, Matrix< T >::sliding_window::last_raw_pos, Matrix< T >::sliding_window::m, Matrix< T >::sliding_window::num_step_by_step, Matrix< T >::sliding_window::num_steps, Matrix< T >::sliding_window::num_windows, Matrix< T >::offset, Matrix< T >::sliding_window::offset, Matrix< T >::sliding_window::order_step, Matrix< T >::sliding_window::raw_pos, Matrix< T >::sliding_window::step, Matrix< T >::sliding_window::sub_matrix_size, Matrix< T >::total_size, and Matrix< T >::sliding_window::total_size.
template<typename T> Matrix< T >::best_span_iterator & Matrix< T >::best_span_iterator::operator= (const best_span_iterator & other)
References Matrix< T >::best_span_iterator::coords, Matrix< T >::best_span_iterator::m, Matrix< T >::best_span_iterator::num_iterations, Matrix< T >::best_span_iterator::order, and Matrix< T >::best_span_iterator::raw_pos.
template<typename T> bool Matrix< T >::iterator::operator== (const iterator & other) const
References Matrix< T >::iterator::m, and Matrix< T >::iterator::raw_pos.
template<typename T> bool Matrix< T >::best_span_iterator::operator== (const best_span_iterator & other) const
References Matrix< T >::best_span_iterator::m, and Matrix< T >::best_span_iterator::raw_pos.
template<typename T > T & Matrix< T >::operator[] (int i)
Raw access operator [].
template<typename T > const T & Matrix< T >::operator[] (int i) const
template<typename T> void Matrix< T >::pow (T value)
References ERROR_EXIT.
void Matrix< float >::pow (floatvalue)
References applyFunctionWithSpanIterator(), doPow(), and make_cwise_functor_1().
template<typename T> bool Matrix< T >::putCol (int col, T * vec, int vecsize)
template<typename T> bool Matrix< T >::putSubCol (int col, int first_row, T * vec, int vecsize)
template<typename T > MatrixFloat * readMatrixFloatFromStream (T & stream)
References Matrix< T >::begin(), Matrix< T >::end(), constString::extract_float(), constString::extract_float_binary(), constString::extract_int(), constString::extract_token(), and constString::extract_u_line().
template MatrixFloat* readMatrixFloatFromStream< constString > (constString & stream)
template MatrixFloat* readMatrixFloatFromStream< ReadFileStream > (ReadFileStream & stream)
MatrixFloat * readMatrixFloatHEX (int width, int height, constString cs)
References Matrix< T >::begin(), april_utils::clamp(), CTEBLANCO, CTENEGRO, and hexdigit().
MatrixFloat * readMatrixFloatPNM (constString cs, bool forcecolor, bool forcegray)
References Matrix< T >::begin(), april_utils::clamp(), CTEBLANCO, CTENEGRO, constString::extract_int(), constString::extract_token(), constString::extract_u_line(), constString::len(), and constString::skip().
template<typename T > void Matrix< T >::release_memory () private
Release of the memory allocated for data pointer.
References DecRef.
template<typename T > Matrix< T > * Matrix< T >::rewrap (const int * new_dims, int len)
Modify sizes of matrix.
References ERROR_EXIT, ERROR_EXIT2, and Matrix< T >::setUseCuda().
Referenced by ANN::FlattenANNComponent::doBackprop(), ANN::RewrapANNComponent::doBackprop(), ANN::ActivationFunctionANNComponent::doBackprop(), ANN::ConvolutionANNComponent::doBackprop(), ANN::RewrapANNComponent::doForward(), ANN::FlattenANNComponent::doForward(), ANN::ActivationFunctionANNComponent::doForward(), ANN::MaxPoolingANNComponent::doForward(), ANN::ConvolutionANNComponent::doForward(), ANN::MaxPoolingANNComponent::getRewrappedMatrix(), ANN::ConvolutionANNComponent::getRewrappedMatrix(), and ANN::ConvolutionBiasANNComponent::prepareBiasBunch().
template<typename T> bool Matrix< T >::sameDim (const Matrix< T > * other) const
References Matrix< T >::matrixSize, and Matrix< T >::numDim.
Referenced by Matrix< float >::cmul(), ANN::BiasANNComponent::computeGradients(), ANN::DotProductANNComponent::computeGradients(), Matrix< float >::copy(), ANN::DotProductANNComponent::doBackprop(), ANN::ActivationFunctionANNComponent::doBackprop(), Matrix< float >::equals(), and ANN::LossFunction::throwErrorAndGetMatrixFromTokens().
int saveMatrixFloatHEX (MatrixFloat * mat, char ** buffer, int * width, int * height)
References Matrix< T >::begin(), april_utils::clamp(), CTEBLANCO, CTENEGRO, Matrix< T >::getDimSize(), and Matrix< T >::getNumDim().
int saveMatrixFloatPNM (MatrixFloat * mat, char ** buffer)
References Matrix< T >::begin(), april_utils::clamp(), CTEBLANCO, CTENEGRO, Matrix< T >::getDimSize(), and Matrix< T >::getNumDim().
void saveMatrixFloatToFile (MatrixFloat * mat, FILE * f, bool is_ascii)
References Matrix< T >::begin(), binarizer::code_float(), Matrix< T >::end(), Matrix< T >::getDimSize(), Matrix< T >::getMajorOrder(), and Matrix< T >::getNumDim().
int saveMatrixFloatToString (MatrixFloat * mat, char ** buffer, bool is_ascii)
References Matrix< T >::begin(), binarizer::buffer_size_32(), Matrix< T >::end(), Matrix< T >::getDimSize(), Matrix< T >::getMajorOrder(), Matrix< T >::getNumDim(), and Matrix< T >::size().
Referenced by ANN::Connections::toLuaString().
void Matrix< float >::scal (floatvalue)
References applyFunctionWithSpanIterator(), applyFunctionWithSpanIteratorNOPARALLEL(), doSscal(), and make_cwise_functor_1().
template<typename T> void Matrix< T >::scal (T value)
References ERROR_EXIT.
Referenced by Matrix< float >::adjustRange(), ANN::Connections::applyMaxNormPenalty(), ANN::DotProductANNComponent::computeBP(), ANN::Connections::computeMomentumOnPrevVector(), and ANN::ActivationFunctionANNComponent::doForward().
template<typename T> void Matrix< T >::scalarAdd (T s)
Referenced by Matrix< float >::adjustRange().
void Matrix< float >::scalarAdd (floats)
References applyFunctionWithSpanIterator(), doScalarAdd(), and make_cwise_functor_1().
template<typename T > Matrix< T > * Matrix< T >::select (int dim, int index)
References Matrix< T >::data, ERROR_EXIT, IncRef, Matrix< T >::last_raw_pos, Matrix< T >::major_order, Matrix< T >::matrixSize, Matrix< T >::numDim, Matrix< T >::offset, Matrix< T >::stride, Matrix< T >::total_size, and Matrix< T >::use_cuda.
Referenced by ANN::DotProductANNComponent::computeBP(), ANN::SelectANNComponent::doBackprop(), ANN::SelectANNComponent::doForward(), ANN::DotProductANNComponent::doForward(), Matrix< float >::maxSelDim(), and ANN::ConvolutionBiasANNComponent::prepareBiasBunch().
template<typename T > void Matrix< T >::best_span_iterator::setAtIteration (int idx)
template<typename T > void Matrix< T >::sliding_window::setAtWindow (int windex)
References Matrix< T >::offset.
template<typename T > Matrix< T > * Matrix< T >::shallow_copy ()
Shallow copy.
template<typename T > Matrix< T >::sliding_window::sliding_window ()
template<typename T> Matrix< T >::sliding_window::sliding_window (Matrix< T > * m, const int * sub_matrix_size = 0, const int * offset = 0, const int * step = 0, const int * num_steps = 0, const int * order_step = 0)
References Matrix< T >::sliding_window::coords, ERROR_EXIT1, ERROR_EXIT2, IncRef, Matrix< T >::sliding_window::last_raw_pos, Matrix< T >::matrixSize, Matrix< T >::sliding_window::num_step_by_step, Matrix< T >::sliding_window::num_windows, Matrix< T >::numDim, Matrix< T >::sliding_window::raw_pos, Matrix< T >::stride, and Matrix< T >::sliding_window::total_size.
template<typename T> Matrix< T >::sliding_window::sliding_window (const sliding_window & other)
References Matrix< T >::sliding_window::coords, IncRef, Matrix< T >::sliding_window::m, Matrix< T >::sliding_window::num_step_by_step, Matrix< T >::sliding_window::num_steps, Matrix< T >::sliding_window::offset, Matrix< T >::sliding_window::order_step, Matrix< T >::sliding_window::step, and Matrix< T >::sliding_window::sub_matrix_size.
void Matrix< float >::sqrt ()
References applyFunctionWithSpanIterator(), doSqrt(), and make_cwise_functor_0().
template<typename T > void Matrix< T >::sqrt ()
References ERROR_EXIT.
template<typename T> Matrix< T > * Matrix< T >::substraction (const Matrix< T > * other)
References ERROR_EXIT.
Matrix< float > * Matrix< float >::substraction (const Matrix< float > * other)
References Matrix< T >::axpy(), and Matrix< T >::clone().
float Matrix< float >::sum () const
References applySumReductionWithSpanIterator().
template<typename T > T Matrix< T >::sum () const
void Matrix< float >::tanh ()
References applyFunctionWithSpanIterator(), doTanh(), and make_cwise_functor_0().
template<typename T > void Matrix< T >::tanh ()
References ERROR_EXIT.
template<typename T > Matrix< T > * Matrix< T >::transpose () const
Transposition.
References Matrix< T >::begin(), Matrix< T >::end(), and Matrix< T >::setUseCuda().
void Matrix< float >::zeros ()
References Matrix< T >::fill().
Referenced by AffineTransform2D::AffineTransform2D().
template<typename T > void Matrix< T >::zeros ()
References ERROR_EXIT.
Referenced by ANN::BiasANNComponent::computeGradients(), ANN::DotProductANNComponent::computeGradients(), ANN::ConvolutionBiasANNComponent::computeGradients(), ANN::ConvolutionANNComponent::computeGradients(), ANN::SelectANNComponent::doBackprop(), ANN::MaxPoolingANNComponent::doBackprop(), ANN::ConvolutionANNComponent::doBackprop(), ImageHistogram::generateWindowHistogram(), ImageHistogram::getHistogram(), ImageHistogram::getWindowHistogram(), Matrix< float >::multiply(), and hmm_trainer_model::viterbi().
template<typename T > Matrix< T >::best_span_iterator::~best_span_iterator ()
template<typename T > Matrix< T >::col_major_iterator::~col_major_iterator ()
template<typename T > Matrix< T >::const_col_major_iterator::~const_col_major_iterator ()
template<typename T > Matrix< T >::const_iterator::~const_iterator ()
template<typename T > Matrix< T >::iterator::~iterator ()
template<typename T > Matrix< T >::~Matrix () virtual
Destructor.
template<typename T > Matrix< T >::sliding_window::~sliding_window ()
References DecRef, and Matrix< T >::offset.
Variable Documentation
const float CTEBLANCO = 0.0f
Referenced by readMatrixFloatHEX(), readMatrixFloatPNM(), saveMatrixFloatHEX(), and saveMatrixFloatPNM().
const float CTENEGRO = 1.0f
Referenced by readMatrixFloatHEX(), readMatrixFloatPNM(), saveMatrixFloatHEX(), and saveMatrixFloatPNM().