april-ann
omp_utils Namespace Reference
Util
Functions
int get_num_threads ()
Function Documentation
int omp_utils::get_num_threads ()
Referenced by applyBinaryAndReductionWithSpanIterator(), applyBinaryFunctionWithSpanIterator(), applyFunctionWithSpanIterator(), and applySumReductionWithSpanIterator().