april-ann
InterestPoints Namespace Reference
Interest_points
Classes
struct xy
Typedefs
typedef april_utils::pair
< float, float > Point2D
Functions
void process_stroke_max (max_finder< xy > &finder, vector< xy > *strokep)
void process_stroke_min (min_finder< xy > &finder, vector< xy > *strokep)
void process_neighborns (vector< Point2D > &v, int line_ini[], int line_end[], int y)
void remove_neighborns (vector< Point2D > &v, int dup_int, int h)
bool is_white (float value, float threshold, bool reverse=false)
bool is_black (float value, float threshold, bool reverse=false)
april_utils::vector< Point2D > * extract_points_from_image_old (ImageFloat *pimg, float threshold_white=0.6, float threshold_black=0.4, int local_context=6, int duplicate_interval=5)
Given an Image returns a vector with the local maxima and local minima of the given image.
void extract_points_from_image (ImageFloat *pimg, april_utils::vector< Point2D > *local_minima, april_utils::vector< Point2D > *local_maxima, float threshold_white=0.4, float threshold_black=0.6, int local_context=6, int duplicate_interval=3)
Given an Image returns a vector with the local maxima and local minima of the given image.
Typedef Documentation
typedef april_utils::pair<float, float> InterestPoints::Point2D
Function Documentation
void InterestPoints::extract_points_from_image (ImageFloat * pimg, april_utils::vector< Point2D > * local_minima, april_utils::vector< Point2D > * local_maxima, float threshold_white = 0.4, float threshold_black = 0.6, int local_context = 6, int duplicate_interval = 3)
Given an Image returns a vector with the local maxima and local minima of the given image.
Parameters
[in] pimg Pointer to the image
[out] local_minima Return the points of the local minima contour
[out] local_maxima Return the points of the local maxima contour
[in] threshold_white More than this value is considered black
[in] threshold_black Less than this value is set to white
[in] local_context The number of pixels in stroke that is used to compute the local maxima/minima
[in] duplicate_interval The minimum distance of locals within the same stroke
return result_Point2D;
return result_Point2D;
References Image< T >::height, is_black(), is_white(), process_stroke_max(), process_stroke_min(), april_utils::vector< T >::push_back(), remove_neighborns(), april_utils::vector< T >::size(), april_utils::swap(), and Image< T >::width.
april_utils::vector< Point2D > * InterestPoints::extract_points_from_image_old (ImageFloat * pimg, float threshold_white = 0.6, float threshold_black = 0.4, int local_context = 6, int duplicate_interval = 5)
Given an Image returns a vector with the local maxima and local minima of the given image.
Parameters
[in] pimg Pointer to the image
[in] threshold_white More than this value is considered black
[in] threshold_black Less than this value is set to white
[in] local_context The number of pixels in stroke that is used to compute the local maxima/minima
[in] duplicate_interval The minimum distance of locals within the same stroke
References Image< T >::height, is_black(), is_white(), process_stroke_max(), process_stroke_min(), april_utils::vector< T >::push_back(), remove_neighborns(), april_utils::vector< T >::size(), april_utils::swap(), and Image< T >::width.
bool InterestPoints::is_black (float value, float threshold, bool reverse = false) inline
Referenced by extract_points_from_image(), and extract_points_from_image_old().
bool InterestPoints::is_white (float value, float threshold, bool reverse = false) inline
Referenced by extract_points_from_image(), and extract_points_from_image_old().
void InterestPoints::process_neighborns (vector< Point2D > & v, int line_ini[], int line_end[], int y) inline
References april_utils::vector< T >::push_back().
Referenced by remove_neighborns().
void InterestPoints::process_stroke_max (max_finder< xy > & finder, vector< xy > * strokep) inline
References april_utils::vector< T >::clear(), april_utils::max_finder< T >::end_sequence(), april_utils::max_finder< T >::put(), and april_utils::vector< T >::size().
Referenced by extract_points_from_image(), and extract_points_from_image_old().
void InterestPoints::process_stroke_min (min_finder< xy > & finder, vector< xy > * strokep) inline
References april_utils::vector< T >::clear(), april_utils::min_finder< T >::end_sequence(), april_utils::min_finder< T >::put(), and april_utils::vector< T >::size().
Referenced by extract_points_from_image(), and extract_points_from_image_old().
void InterestPoints::remove_neighborns (vector< Point2D > & v, int dup_int, int h) inline
References process_neighborns(), april_utils::vector< T >::size(), and april_utils::vector< T >::swap().
Referenced by extract_points_from_image(), and extract_points_from_image_old().