april-ann
april_utils Namespace Reference
LexClass | Matrix | Util | Image
Namespaces
namespace list_aux_templates
Classes
struct LexClass
class ReferencedVector
struct default_hash_function
struct default_equality_comparison_function
struct default_hash_function< int >
struct default_hash_function< unsigned int >
struct default_hash_function< int_pair >
struct default_hash_function< uint_pair >
struct default_hash_function< int16_pair >
struct default_hash_function< constString >
struct default_hash_function< T * >
struct default_equality_comparison_function< char * >
struct default_hash_function< char * >
struct hash_restricted_vector
class cache_open_addr_hash
class ComparablePtr
class context
struct vec_wrapper
class context_of_vectors
struct fifo_node
class fifo
class fifo_block
class hash
class list
class max_min_finder
class max_finder
class min_finder
class maxiphobic_minheap
class RunningStat
class MFSet
struct CmpLessDefault
class min_heap
class string
struct default_hash_function< string >
class NullType
class NullContainer
class open_addr_hash
class open_addr_hash_timestamp
class open_addr_hash_fast_it
struct pair
struct pair< T1, NullType >
class PartQ
class slist
class stopwatch
class Trie
class Trie4lua
class TrieOpenAddr
class TrieVector
class tuple
class vector
class WordsTable
Typedefs
typedef ReferencedVector< float > ReferencedVectorFloat
typedef ReferencedVector
< uint32_t > ReferencedVectorUint
typedef april_utils::pair< int,
int > int_pair
typedef april_utils::pair
< unsigned int, unsigned int > uint_pair
typedef april_utils::pair
< int16_t, int16_t > int16_pair
Functions
template<typename T , typename K >
int binary_search (const T *vec, int sz, const K &value)
template<typename T , typename K >
const T * binary_search_first (const T *vec, int sz, const K &value)
unsigned int ceilingPowerOfTwo (unsigned int value)
bool check_floats (float *v, unsigned int sz)
template<typename T >
T clamp (T val, T lower, T upper)
void derivative1 (float *v, float *v_dest, int n)
void derivative2 (float *v, float *v_dest, int n)
template<typename T >
void swap_bytes_in_place (T &data)
template<typename T >
T swap_bytes (T data)
template<typename T >
T max (T a, T b)
template<typename T >
T min (T a, T b)
template<typename T >
int argmax (const T *v, int size)
template<typename T >
int argmin (const T *v, int size)
template<typename T >
T max (const T *v, int size)
template<typename T >
T min (const T *v, int size)
template<typename Iterator >
Iterator argmax (Iterator begin, Iterator end)
template<typename Iterator >
Iterator argmin (Iterator begin, Iterator end)
template<typename T >
T::iterator argmax (T &container)
template<typename T >
T::iterator argmin (T &container)
template<typename T >
T::value_type max (T &container)
template<typename T >
T::value_type min (T &container)
template<typename T >
void mean_deviation (T v[], int sz, double *mean, double *dev)
int mod (int x, int y)
template<typename T1 , typename T2 >
bool operator== (const pair< T1, T2 > &x, const pair< T1, T2 > &y)
template<typename T1 , typename T2 >
bool operator< (const pair< T1, T2 > &x, const pair< T1, T2 > &y)
template<typename T1 >
bool operator== (const pair< T1, NullType > &x, const pair< T1, NullType > &y)
template<typename T1 >
bool operator< (const pair< T1, NullType > &x, const pair< T1, NullType > &y)
template<typename first , typename second >
pair< first, second > make_pair (const first &_X, const second &_Y)
template<typename T >
void InsertionSort (T v[], int low, int high)
template<typename T , typename Compare >
void InsertionSort (T v[], int low, int high, Compare compare)
template<typename T >
T med3 (T v[], int low, int high)
template<typename T , typename Compare >
T med3 (T v[], int low, int high, Compare compare)
template<typename T >
int partition (T v[], int low, int high)
template<typename T , typename Compare >
int partition (T v[], int low, int high, Compare compare)
template<typename T >
void Sort (T v[], int low, int high)
template<typename T , typename Compare >
void Sort (T v[], int low, int high, Compare compare)
template<typename T >
void Sort (T v[], int sze)
template<typename T , typename Compare >
void Sort (T v[], int sze, Compare compare)
template<typename T >
T Selection (T v[], int sze, int k)
template<typename T , typename Compare >
T Selection (T v[], int sze, int k, Compare cmp)
template<typename T >
void swap (T &a, T &b)
template<>
FloatRGB clamp< FloatRGB > (FloatRGB val, FloatRGB lower, FloatRGB upper)
Detailed Description
esto es una prueba
Typedef Documentation
typedef april_utils::pair<int16_t,int16_t> april_utils::int16_pair
typedef april_utils::pair<int,int> april_utils::int_pair
typedef ReferencedVector<float> april_utils::ReferencedVectorFloat
typedef ReferencedVector<uint32_t> april_utils::ReferencedVectorUint
typedef april_utils::pair<unsigned int,unsigned int> april_utils::uint_pair
Function Documentation
template<typename T > int april_utils::argmax (const T * v, int size)
Referenced by argmax(), max(), Matrix< float >::max(), and Matrix< float >::maxSelDim().
template<typename Iterator > Iterator april_utils::argmax (Iterator begin, Iterator end)
template<typename T > T::iterator april_utils::argmax (T & container)
References argmax().
template<typename T > int april_utils::argmin (const T * v, int size)
Referenced by argmin(), min(), and Matrix< float >::min().
template<typename Iterator > Iterator april_utils::argmin (Iterator begin, Iterator end)
template<typename T > T::iterator april_utils::argmin (T & container)
References argmin().
template<typename T , typename K > int april_utils::binary_search (const T * vec, int sz, const K & value) inline
template<typename T , typename K > const T* april_utils::binary_search_first (const T * vec, int sz, const K & value) inline
unsigned int april_utils::ceilingPowerOfTwo (unsigned int value)
Referenced by ANN::LogSoftmaxActfANNComponent::applyActivation(), and ANN::SoftmaxActfANNComponent::applyActivation().
bool april_utils::check_floats (float * v, unsigned int sz)
References ERROR_PRINT2.
Referenced by ANN::Connections::pruneSubnormalAndCheckNormal().
template<typename T > T april_utils::clamp (T val, T lower, T upper)
Referenced by Matrix< T >::clamp(), clamp< FloatRGB >(), derivative1(), derivative2(), DerivDataSet< T >::getPattern(), ByteDataSet< T >::putPattern(), readMatrixFloatHEX(), readMatrixFloatPNM(), saveMatrixFloatHEX(), saveMatrixFloatPNM(), Image< T >::substract_image(), and LibPNG::writePNG().
template<> FloatRGB april_utils::clamp< FloatRGB > (FloatRGB val, FloatRGB lower, FloatRGB upper)
References clamp().
void april_utils::derivative1 (float * v, float * v_dest, int n)
References clamp().
void april_utils::derivative2 (float * v, float * v_dest, int n)
References clamp().
template<typename T > void april_utils::InsertionSort (T v[], int low, int high) inline
Referenced by april_utils::PartQ< T >::increase_lastSorted(), Selection(), and Sort().
template<typename T , typename Compare > void april_utils::InsertionSort (T v[], int low, int high, Compare compare) inline
template<typename first , typename second > pair<first, second> april_utils::make_pair (const first & _X, const second & _Y) inline
Referenced by april_utils::Trie4lua::find().
template<typename T > T april_utils::max (T a, T b)
Referenced by Image< T >::affine_transform(), ANN::Connections::copyWeightsTo(), ImageHistogram::generateWindowHistogram(), Matrix< float >::getVectorSize(), ANN::Connections::loadWeights(), and april_utils::MFSet::merge().
template<typename T > T april_utils::max (const T * v, int size)
References argmax().
template<typename T > T::value_type april_utils::max (T & container)
References argmax().
template<typename T > void april_utils::mean_deviation (T v[], int sz, double * mean, double * dev)
template<typename T > T april_utils::med3 (T v[], int low, int high) inline
References swap().
Referenced by partition().
template<typename T , typename Compare > T april_utils::med3 (T v[], int low, int high, Compare compare) inline
References swap().
template<typename T > T april_utils::min (T a, T b)
Referenced by Image< T >::affine_transform(), ImageHistogram::generateWindowHistogram(), april_utils::maxiphobic_minheap< T >::merge(), constString::operator<(), constString::operator<=(), constString::operator>(), constString::operator>=(), and StringQueue::putBuffer().
template<typename T > T april_utils::min (const T * v, int size)
References argmin().
template<typename T > T::value_type april_utils::min (T & container)
References argmin().
int april_utils::mod (int x, int y) inline
Referenced by MatrixDataSet< T >::auxGetPattern(), and MatrixDataSet< T >::auxPutPattern().
template<typename T1 , typename T2 > bool april_utils::operator< (const pair< T1, T2 > & x, const pair< T1, T2 > & y)
template<typename T1 > bool april_utils::operator< (const pair< T1, NullType > & x, const pair< T1, NullType > & y)
template<typename T1 , typename T2 > bool april_utils::operator== (const pair< T1, T2 > & x, const pair< T1, T2 > & y)
References april_utils::pair< T1, T2 >::first, and april_utils::pair< T1, T2 >::second.
template<typename T1 > bool april_utils::operator== (const pair< T1, NullType > & x, const pair< T1, NullType > & y)
References april_utils::pair< T1, NullType >::first.
template<typename T > int april_utils::partition (T v[], int low, int high) inline
References med3(), and swap().
Referenced by april_utils::PartQ< T >::increase_lastSorted(), Selection(), and Sort().
template<typename T , typename Compare > int april_utils::partition (T v[], int low, int high, Compare compare) inline
References med3(), and swap().
template<typename T > T april_utils::Selection (T v[], int sze, int k)
References InsertionSort(), and partition().
template<typename T , typename Compare > T april_utils::Selection (T v[], int sze, int k, Compare cmp)
References InsertionSort(), and partition().
template<typename T > void april_utils::Sort (T v[], int low, int high)
References InsertionSort(), and partition().
Referenced by Matrix< T >::best_span_iterator::best_span_iterator(), and Sort().
template<typename T , typename Compare > void april_utils::Sort (T v[], int low, int high, Compare compare)
References InsertionSort(), partition(), and Sort().
template<typename T > void april_utils::Sort (T v[], int sze)
Template del algoritmo quicksort en la version que realiza una sola llamada recursiva (para evitar que en el caso peor la pila crezca de forma lineal con la talla del vector. En un caso base inferior a MINSIZE (ahora es constante, TODO: se puede meter como un valor en el template y dar valor por defecto) se utiliza InsertionSort.
REQUIERE QUE EL TIPO T TENGA DEFINIDA LA OPERACION DE COPIA Y LA COMPARACION MENOR ESTRICTO "<".
Se utiliza basicamente asi:
T v[n];
Sort(v,n); // ordenamos el vector
References Sort().
template<typename T , typename Compare > void april_utils::Sort (T v[], int sze, Compare compare)
References Sort().
template<typename T > void april_utils::swap (T & a, T & b) inline
Referenced by hmm_trainer_model::backward(), ANN::DotProductANNComponent::build(), ANN::Connections::endUpdate(), InterestPoints::extract_points_from_image(), InterestPoints::extract_points_from_image_old(), Matrix< float >::gemm(), Matrix< float >::gemv(), april_utils::TrieVector::getSequence(), Matrix< float >::maxSelDim(), med3(), april_utils::maxiphobic_minheap< T >::merge(), partition(), MTRand::shuffle(), april_utils::vector< Token * >::swap(), april_utils::slist< T * >::swap(), april_utils::fifo_block< T, fifo_block_size >::swap(), april_utils::list< T >::swap(), swap_bytes(), swap_bytes_in_place(), and hmm_trainer_model::viterbi().
template<typename T > T april_utils::swap_bytes (T data)
References swap().
template<typename T > void april_utils::swap_bytes_in_place (T & data)
References swap().