april-ann
april_utils::list< T >::const_iterator Struct Reference
Const iterator used to iterate through a list.
Public Types
typedef T value_type
typedef const T * pointer
typedef const T & reference
typedef const T & const_reference
typedef ptrdiff_t difference_type
Public Member Functions
const_iterator (const node *p)
const_iterator (const iterator &i)
const_iterator (iterator &i)
const_iterator & operator++ ()
const_iterator operator++ (int)
const_iterator & operator-- ()
const_iterator operator-- (int)
reference operator* () const
pointer operator-> () const
bool operator== (const const_iterator &i) const
bool operator!= (const const_iterator &i) const
Public Attributes
const node * ptr
Friends
class list< T >
Detailed Description
template<class T>
struct april_utils::list< T >::const_iterator
Const iterator used to iterate through a list.
Member Typedef Documentation
template<class T> typedef const T& april_utils::list< T >::const_iterator::const_reference
template<class T> typedef ptrdiff_t april_utils::list< T >::const_iterator::difference_type
template<class T> typedef const T* april_utils::list< T >::const_iterator::pointer
template<class T> typedef const T& april_utils::list< T >::const_iterator::reference
template<class T> typedef T april_utils::list< T >::const_iterator::value_type
Constructor & Destructor Documentation
template<class T> april_utils::list< T >::const_iterator::const_iterator (const node * p) inline
Referenced by april_utils::list< T >::const_iterator::operator++(), and april_utils::list< T >::const_iterator::operator--().
template<class T> april_utils::list< T >::const_iterator::const_iterator (const iterator & i) inline
template<class T> april_utils::list< T >::const_iterator::const_iterator (iterator & i) inline
Member Function Documentation
template<class T> bool april_utils::list< T >::const_iterator::operator!= (const const_iterator & i) const inline
References april_utils::list< T >::const_iterator::ptr.
template<class T> reference april_utils::list< T >::const_iterator::operator* () const inline
References april_utils::list< T >::node::data, and april_utils::list< T >::const_iterator::ptr.
template<class T> const_iterator& april_utils::list< T >::const_iterator::operator++ () inline
References april_utils::list< T >::node::next, and april_utils::list< T >::const_iterator::ptr.
template<class T> const_iterator april_utils::list< T >::const_iterator::operator++ (int) inline
References april_utils::list< T >::const_iterator::const_iterator(), april_utils::list< T >::node::next, and april_utils::list< T >::const_iterator::ptr.
template<class T> const_iterator& april_utils::list< T >::const_iterator::operator-- () inline
References april_utils::list< T >::node::prev, and april_utils::list< T >::const_iterator::ptr.
template<class T> const_iterator april_utils::list< T >::const_iterator::operator-- (int) inline
References april_utils::list< T >::const_iterator::const_iterator(), april_utils::list< T >::node::prev, and april_utils::list< T >::const_iterator::ptr.
template<class T> pointer april_utils::list< T >::const_iterator::operator-> () const inline
References april_utils::list< T >::node::data, and april_utils::list< T >::const_iterator::ptr.
template<class T> bool april_utils::list< T >::const_iterator::operator== (const const_iterator & i) const inline
References april_utils::list< T >::const_iterator::ptr.
Friends And Related Function Documentation
template<class T> friend class list< T > friend
Member Data Documentation
template<class T> const node* april_utils::list< T >::const_iterator::ptr
Referenced by april_utils::list< T >::const_iterator::operator!=(), april_utils::list< T >::const_iterator::operator*(), april_utils::list< T >::const_iterator::operator++(), april_utils::list< T >::const_iterator::operator--(), april_utils::list< T >::const_iterator::operator->(), and april_utils::list< T >::const_iterator::operator==().