april-ann
axpy_functor Struct Reference
Matrix
Public Member Functions
axpy_functor (float alpha)
void operator() (MatrixFloat *one, const MatrixFloat *other, unsigned int size, unsigned int stride_one, unsigned int stride_other, unsigned int offset_one, unsigned int offset_other) const
Public Attributes
float alpha
Constructor & Destructor Documentation
axpy_functor::axpy_functor (float alpha) inline
Member Function Documentation
void axpy_functor::operator() (MatrixFloat * one, const MatrixFloat * other, unsigned int size, unsigned int stride_one, unsigned int stride_other, unsigned int offset_one, unsigned int offset_other) const inline
References alpha, doSaxpy(), Matrix< T >::getCudaFlag(), and Matrix< T >::getRawDataAccess().
Member Data Documentation
float axpy_functor::alpha
Referenced by operator()().