april-ann
april_utils::LexClass Struct Reference
Classes
struct data_t
Public Member Functions
LexClass ()
~LexClass ()
uint32_t addPair (char *word, char *outsym, log_float prob)
unsigned int size ()
const char * getWordFromWordId (uint32_t wid)
const char * getWordFromPairId (uint32_t pairid)
const char * getOutSymFromOutSymId (uint32_t oid)
const char * getOutSymFromPairId (uint32_t pairid)
bool getWordId (const char *word, uint32_t &wid)
bool getOutSymId (const char *outsym, uint32_t &oid)
data_t getPairData (uint32_t pair_id)
unsigned int wordTblSize ()
unsigned int outsymTblSize ()
Public Member Functions inherited from Referenced
Referenced ()
virtual ~Referenced ()
virtual void incRef ()
virtual bool decRef ()
Public Attributes
vector< data_t > data
vector< char * > strings
vector< int_pair > string2wid_oid
vector< uint32_t > wid2string
vector< uint32_t > oid2string
hash< char *, uint32_t > string2id
Additional Inherited Members
Protected Attributes inherited from Referenced
int refs
Constructor & Destructor Documentation
april_utils::LexClass::LexClass () inline
References addPair(), and log_float::one().
april_utils::LexClass::~LexClass () inline
References april_utils::vector< T >::size(), and strings.
Member Function Documentation
uint32_t april_utils::LexClass::addPair (char * word, char * outsym, log_float prob) inline
References data, oid2string, april_utils::LexClass::data_t::outsym, april_utils::LexClass::data_t::prob, april_utils::vector< T >::push_back(), april_utils::vector< T >::size(), string2id, string2wid_oid, strings, wid2string, and april_utils::LexClass::data_t::word.
Referenced by LexClass().
const char* april_utils::LexClass::getOutSymFromOutSymId (uint32_t oid) inline
References oid2string, and strings.
Referenced by getOutSymFromPairId().
const char* april_utils::LexClass::getOutSymFromPairId (uint32_t pairid) inline
References data, and getOutSymFromOutSymId().
bool april_utils::LexClass::getOutSymId (const char * outsym, uint32_t & oid) inline
References april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::find(), string2id, and string2wid_oid.
data_t april_utils::LexClass::getPairData (uint32_t pair_id) inline
References data.
const char* april_utils::LexClass::getWordFromPairId (uint32_t pairid) inline
References data, and getWordFromWordId().
const char* april_utils::LexClass::getWordFromWordId (uint32_t wid) inline
References strings, and wid2string.
Referenced by getWordFromPairId().
bool april_utils::LexClass::getWordId (const char * word, uint32_t & wid) inline
References april_utils::hash< KeyType, DataType, HashFcn, EqualKey >::find(), string2id, and string2wid_oid.
unsigned int april_utils::LexClass::outsymTblSize () inline
References oid2string, and april_utils::vector< T >::size().
unsigned int april_utils::LexClass::size () inline
References data.
unsigned int april_utils::LexClass::wordTblSize () inline
References april_utils::vector< T >::size(), and wid2string.
Member Data Documentation
vector<data_t> april_utils::LexClass::data
Referenced by addPair(), getOutSymFromPairId(), getPairData(), getWordFromPairId(), and size().
vector<uint32_t> april_utils::LexClass::oid2string
Referenced by addPair(), getOutSymFromOutSymId(), and outsymTblSize().
hash<char *,uint32_t> april_utils::LexClass::string2id
Referenced by addPair(), getOutSymId(), and getWordId().
vector<int_pair> april_utils::LexClass::string2wid_oid
Referenced by addPair(), getOutSymId(), and getWordId().
vector<char *> april_utils::LexClass::strings
Referenced by addPair(), getOutSymFromOutSymId(), getWordFromWordId(), and ~LexClass().
vector<uint32_t> april_utils::LexClass::wid2string
Referenced by addPair(), getWordFromWordId(), and wordTblSize().