april-ann
equals_functor Struct Reference
Matrix
Public Member Functions
equals_functor (float epsilon)
bool operator() (const MatrixFloat *m1, const MatrixFloat *m2, unsigned int size, unsigned int stride1, unsigned int stride2, unsigned int offset1, unsigned int offset2) const
Public Attributes
float epsilon
Constructor & Destructor Documentation
equals_functor::equals_functor (float epsilon) inline
Member Function Documentation
bool equals_functor::operator() (const MatrixFloat * m1, const MatrixFloat * m2, unsigned int size, unsigned int stride1, unsigned int stride2, unsigned int offset1, unsigned int offset2) const inline
References doEquals(), epsilon, Matrix< T >::getCudaFlag(), and Matrix< T >::getRawDataAccess().
Member Data Documentation
float equals_functor::epsilon
Referenced by operator()().