april-ann
clamp_functor Struct Reference
Matrix
Public Member Functions
clamp_functor (float lower, float upper)
void operator() (MatrixFloat *m, unsigned int size, unsigned int stride, unsigned int offset) const
Public Attributes
float lower
float upper
Constructor & Destructor Documentation
clamp_functor::clamp_functor (float lower, float upper) inline
Member Function Documentation
void clamp_functor::operator() (MatrixFloat * m, unsigned int size, unsigned int stride, unsigned int offset) const inline
References doClamp(), Matrix< T >::getCudaFlag(), Matrix< T >::getRawDataAccess(), lower, and upper.
Member Data Documentation
float clamp_functor::lower
Referenced by operator()().
float clamp_functor::upper
Referenced by operator()().