april-ann
copy_functor Struct Reference
Matrix
Public Member Functions
void operator() (MatrixFloat *dest, const MatrixFloat *orig, unsigned int size, unsigned int stride_dest, unsigned int stride_orig, unsigned int offset_dest, unsigned int offset_orig) const
Member Function Documentation
void copy_functor::operator() (MatrixFloat * dest, const MatrixFloat * orig, unsigned int size, unsigned int stride_dest, unsigned int stride_orig, unsigned int offset_dest, unsigned int offset_orig) const inline
References doScopy(), Matrix< T >::getCudaFlag(), and Matrix< T >::getRawDataAccess().