april-ann
april_utils::list< T >::const_reverse_iterator Struct Reference
Iterator used to iterate backwards through a list.
Public Types
typedef T value_type
typedef const T * pointer
typedef const T & reference
typedef const T & const_reference
typedef ptrdiff_t difference_type
Public Member Functions
const_reverse_iterator (const const_iterator &ci)
private constructor. we don't want reverse iterators created from iterators :)
const_reverse_iterator (const const_reverse_iterator &other)
const_reverse_iterator & operator++ ()
const_reverse_iterator operator++ (int)
const_reverse_iterator & operator-- ()
const_reverse_iterator operator-- (int)
reference operator* () const
pointer operator-> () const
iterator base ()
bool operator== (const reverse_iterator &other) const
bool operator!= (const reverse_iterator &other) const
Public Attributes
const_iterator current
Friends
class list< T >
Detailed Description
template<class T>
struct april_utils::list< T >::const_reverse_iterator
Iterator used to iterate backwards through a list.
Member Typedef Documentation
template<class T> typedef const T& april_utils::list< T >::const_reverse_iterator::const_reference
template<class T> typedef ptrdiff_t april_utils::list< T >::const_reverse_iterator::difference_type
template<class T> typedef const T* april_utils::list< T >::const_reverse_iterator::pointer
template<class T> typedef const T& april_utils::list< T >::const_reverse_iterator::reference
template<class T> typedef T april_utils::list< T >::const_reverse_iterator::value_type
Constructor & Destructor Documentation
template<class T> april_utils::list< T >::const_reverse_iterator::const_reverse_iterator (const const_iterator & ci) inline
private constructor. we don't want reverse iterators created from iterators :)
Referenced by april_utils::list< T >::const_reverse_iterator::operator++(), and april_utils::list< T >::const_reverse_iterator::operator--().
template<class T> april_utils::list< T >::const_reverse_iterator::const_reverse_iterator (const const_reverse_iterator & other) inline
Member Function Documentation
template<class T> iterator april_utils::list< T >::const_reverse_iterator::base () inline
References april_utils::list< T >::const_reverse_iterator::current.
template<class T> bool april_utils::list< T >::const_reverse_iterator::operator!= (const reverse_iterator & other) const inline
References april_utils::list< T >::reverse_iterator::current, and april_utils::list< T >::const_reverse_iterator::current.
template<class T> reference april_utils::list< T >::const_reverse_iterator::operator* () const inline
References april_utils::list< T >::const_reverse_iterator::current.
Referenced by april_utils::list< T >::const_reverse_iterator::operator->().
template<class T> const_reverse_iterator& april_utils::list< T >::const_reverse_iterator::operator++ () inline
References april_utils::list< T >::const_reverse_iterator::current.
template<class T> const_reverse_iterator april_utils::list< T >::const_reverse_iterator::operator++ (int) inline
References april_utils::list< T >::const_reverse_iterator::const_reverse_iterator(), and april_utils::list< T >::const_reverse_iterator::current.
template<class T> const_reverse_iterator& april_utils::list< T >::const_reverse_iterator::operator-- () inline
References april_utils::list< T >::const_reverse_iterator::current.
template<class T> const_reverse_iterator april_utils::list< T >::const_reverse_iterator::operator-- (int) inline
References april_utils::list< T >::const_reverse_iterator::const_reverse_iterator(), and april_utils::list< T >::const_reverse_iterator::current.
template<class T> pointer april_utils::list< T >::const_reverse_iterator::operator-> () const inline
References april_utils::list< T >::const_reverse_iterator::operator*().
template<class T> bool april_utils::list< T >::const_reverse_iterator::operator== (const reverse_iterator & other) const inline
References april_utils::list< T >::reverse_iterator::current, and april_utils::list< T >::const_reverse_iterator::current.
Friends And Related Function Documentation
template<class T> friend class list< T > friend
Member Data Documentation
template<class T> const_iterator april_utils::list< T >::const_reverse_iterator::current
Referenced by april_utils::list< T >::const_reverse_iterator::base(), april_utils::list< T >::const_reverse_iterator::operator!=(), april_utils::list< T >::const_reverse_iterator::operator*(), april_utils::list< T >::const_reverse_iterator::operator++(), april_utils::list< T >::const_reverse_iterator::operator--(), and april_utils::list< T >::const_reverse_iterator::operator==().